### ISSUE TITLE
Provide a way to manually confirm new users

### ISSUE THREAD

**Issue by Chaz6** [openSUSE/osem#1061]
When some mail hosts block messages at smtp-time (Hotmail, Google, etc), it should be possible for an admin to manually confirm a new user's email address.

**Comment by shlok007** [comment]
I see a closed PR. If someone isn't working already. I would like to work on it :).

**Comment by shlok007** [comment]
As @nishanthvijayan pointed out, @hennevogel  Should we allow the admin to cancel confirmation of a user as well?

**Comment by Chaz6** [comment]
@shlok007 I think so yes, and there should also be an audit trail (i.e. which admin did it).

**Comment by differentreality** [comment]
The audit trail is beyond the scope of this issue at this time, as we are (re) implementing a full changelog. @nishanthvijayan we will merge this change soon, so please make sure we add this in #1019

**Comment by differentreality** [comment]
@shlok007 it would make sense to adapt the view in users#show and users#edit too.
