### ISSUE TITLE
Adding Add buttons at the top

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1062]
Currently the _Add_  button in the rooms page in the backend is at the end:

![image](https://cloud.githubusercontent.com/assets/16052290/16415091/bfb3041e-3d3b-11e6-9d2a-371e03eff80b.png)

So if there are many rooms to have to scroll a lot to create a new room. We should also add a new button at the top:

![good_solution](https://cloud.githubusercontent.com/assets/16052290/16415584/4d691008-3d3e-11e6-9fb0-5d859cf4e005.png)

That should be done for rooms, tracks, events types, ... and in short in everywhere to be consistent.

**Comment by shyukri** [comment]
What should be the reasonable limit to display 2 btns? 5 or more items?

**Comment by differentreality** [comment]
What do you mean?

**Comment by shlok007** [comment]
Hi! Is this issue still open? If that's an issue, I suggest instead of adding two buttons, we could just have a single button at the top.

**Comment by Ana06** [comment]
I think that it is not open, because @shyukri implemented it in #1066. :no_mouth:

**Comment by shlok007** [comment]
I saw a closed PR. Sorry :).

**Comment by hennevogel** [comment]
I don't like it. Too many buttons are way more confusing than learning to press END on your keyboard.
