### ISSUE TITLE
conference_registrations#new prefilled times

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1086]
I don't like that we prefill arrival and departute date for people, specially when we don't give them the option to mark them as nil and not share that information with us.

But still I would like people to complete their actual data there, not just hit register with the prefilled information.

**Comment by charliequinn** [comment]
Reason I added specs on #1138 is that I was interested in picking this one up :smile: 

Anyway, I've put together a mockup form that the user will see on initial entry:

![date-form](https://cloud.githubusercontent.com/assets/140386/17620919/b7b9a212-6087-11e6-81ec-2f75982440cb.PNG)

I've also drafted a few acceptance criteria based on my assumptions about the issue. Can you have a look and let me know what you think...?

**A**
Given a user has not entered an arrival time
When they go to the conference_registrations#new form
Then the arrival time field will be blank

**B**
Given a user has not entered an arrival time
And a user has not selected they are unsure about their arrival time
When they click on submit
Then they will get an error message saying "You must provide an arrival date/time. If you are unsure about your expected arrival or would rather not share this information then just check 'Not sure'."

**C**
Given a user has not entered an arrival time
When they go to the conference_registrations#new form
And click on the arrival time field
Then the datepicker will be displayed  with a default value of the conference start datetime

**D**
Given a user has entered an arrival time
When they select 'Not sure' for their arrival datetime
Then the arrival time field will be nulled

**E**
Given a user has selected 'Not sure' for their arrival time
When they click on the arrival time field
Then the datetime picker field will be displayed
And the 'Not sure' field will be unchecked
