### ISSUE TITLE
Update to Rails 5

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#1087]
[Rails 5 is out](http://weblog.rubyonrails.org/2016/7/2/this-week-in-rails-rails-5-is-out-with-new-guides-and-more/) so we should consider to update Rails in the next future.

**Comment by kirantpatil** [comment]
[Turbolinks 5](https://github.com/turbolinks/turbolinks) will help OSEM a true hybrid application.

**Comment by suprgyabhushan** [comment]
There is no error in upgrading to Rails 5 but is it not better to look up this matter at a later stage as many of the existing gems required for solving other bugs may not be compatible with Rails 5.

**Comment by differentreality** [comment]
That's precisely the goal of this issue

**Comment by AEtherC0r3** [comment]
I'm going​ to work on this

**Comment by AEtherC0r3** [comment]
Rails 5 needs at least Ruby 2.2.2, the vagrant installation has 2.1 by default. A way to overcome this is to install rvm or rbenv and use that to install the required ruby version. Is there a simpler method available?

**Comment by hennevogel** [comment]
@AEtherC0r3 sure. distro packages :-)

https://build.opensuse.org/project/show/devel:languages:ruby has everything you need

**Comment by stephlocke** [comment]
Hi peeps,
I'm currently evaluating some conference management systems for use by some R conferences and my ruby guy pointed out the lack of Rails >=5 for osem right now. 

We're hoping to do a deployment of a prototype second week of July - do you think this issue is likely to get fixed and closed at least in the git repo (not necessarily a release) within the next 3-4 weeks?

Cheers for developing & maintaining this software!
Steph

**Comment by differentreality** [comment]
Hi @stephlocke, we haven't done much progress with Rails 5 lately, as we are currently running 4 projects on GSoC, and we are focusing on those features. @AEtherC0r3 who started working on it is also a GSoC student. 
We also have the GSoC evaulations that are coming up, so we are quite busy on that end.

That said, the Rails 5 update is definitely something we want to implement - and we will - however I cannot say with certainty when. We are happily accepting contributions if you think you can help speed things up towards that direction. 

In the meantime feel free to try out our demo http://demo.osem.io/ and keep an eye out on this thread about any progress regarding Rails 5.

Thanks,
Stella
