### ISSUE TITLE
Add Markdown for User Entered Text Formatting

### ISSUE THREAD

**Issue by altsalt** [openSUSE/osem#1090]
Sooo, why can't we format our biographies?

How about being able to add some flavor to talk descriptions?

Sure, this is a new feature, but one that is pretty required.

Tips on where to implement if one of the core team would like someone else to give a shot?

**Comment by Ana06** [comment]
I can do it. I think it can be useful in event descriptions. I am not sure about biographies.
@hennevogel @ChrisBr @differentreality do we want to do that?

**Comment by hennevogel** [comment]
Makes sense yes
