### ISSUE TITLE
Creating multiple choice questions is broken

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#1091]
When creating a new question of type 'multiple choice', providing some answers, adding the question will be denied:

```
Oops, couldn't save Question. Must have answers.
```

Somehow the answers created in the dialog don't make it to the question model.

**Comment by jospoortvliet** [comment]
Can confirm this in Version 1.0.

**Comment by differentreality** [comment]
Questions will be totally replaced by Surveys #1100 
We are working on it... Thanks for the patience :)

**Comment by bear454** [comment]
I can't reproduce this issue on master branch. Feel free to reopen if necessary.
