### ISSUE TITLE
Heroku config variables not matching documented values in install.md

### ISSUE THREAD

**Issue by stephlocke** [openSUSE/osem#1095]
I'm trying to perform a Heroku deployment. I'm encountering some difficulties where the config values requested by Heroku don't match those in install.md

All the values in the Heroku deployment are mandatory, so maybe the missing ones aren't considered important for deployment? Perhaps they should be non-mandatory in the Heroku deployment?

The `OSEM_DEVISE_SECRET_KEY` and `DATABASE_URL` variables are missing from the guidance below. `DATABASE_URL` seems fairly self-explanatory but `OSEM_DEVISE_SECRET_KEY` could do with some guidance.

| Install.md variable 			| Heroku variable | 
|----------			|---------			|
| OSEM_NAME   			| OSEM_NAME   			|
| OSEM_HOSTNAME 		| OSEM_HOSTNAME 		|
| OSEM_EMAIL_ADDRESS 		|  OSEM_EMAIL_ADDRESS 		| 
| OSEM_ICHAIN_ENABLED 		| *missing* |
| OSEM_TRANSIFEX_APIKEY 	|  *missing* |
| OSEM_ERRBIT_HOST 		|  *missing* |
| OSEM_ERRBIT_APIKEY 		|  *missing* |
| OSEM_FACTORY_LINT		|  *missing* |
| OSEM_GOOGLE_KEY/OSEM_GOOGLE_SECRET | *missing* |
| OSEM_FACEBOOK_KEY/OSEM_FACEBOOK_SECRET |  *missing* |
| OSEM_GITHUB_KEY/OSEM_GITHUB_SECRET | *missing* |
| OSEM_SMTP_ADDRESS		|  OSEM_SMTP_ADDRESS		| 
| OSEM_SMTP_PORT		|  OSEM_SMTP_PORT		| 
| OSEM_SMTP_USERNAME		|  OSEM_SMTP_PORT		| 
| OSEM_SMTP_PASSWORD		| OSEM_SMTP_PASSWORD		|
| OSEM_SMTP_AUTHENTICATION	| OSEM_SMTP_AUTHENTICATION	
| OSEM_SMTP_DOMAIN		| OSEM_SMTP_DOMAIN		|
| CLOUDINARY_URL		| CLOUDINARY_URL		|
|  *missing* |  OSEM_DEVISE_SECRET_KEY |
|  *missing* |  DATABASE_URL|

PS Apologies if this is a dumb question - I'm a Ruby n00b and whilst I did check the wiki and for prev. issues I may have missed something

**Comment by hennevogel** [comment]
Thanks for the report @stephlocke, sorry for the late answer.

Indeed most of them are not required for the deployment. 'DATABASE_URL' is strictly speaking nothing OSEM specific and OSEM_DEVISE_SECRET_KEY isn't needed anymore. I'll fix this soonish.

**Comment by hennevogel** [comment]
Let us know if you need anything else :-)
