### ISSUE TITLE
Navbar does not collapse when clicked outside the navbar

### ISSUE THREAD

**Issue by arun1595** [openSUSE/osem#1096]
After clicking on the `.navbar-toggle` button, the navbar expands showing the links. When a user clicks oustide the navbar, the button's background changes but the navbar doesn't collapse.

[Watch here](https://vid.me/VLqZ)

**Comment by itaditya** [comment]
I would like to take on this bug , is anyone on this one already . Please tell so that otherwise I can contribute ;)

**Comment by bear454** [comment]
See https://github.com/openSUSE/osem/pull/1957#issuecomment-373197255
