### ISSUE TITLE
Layout of sign in page for with ICHAIN

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1098]
When ICHAIN is enabled the view for in `/users/ichain_sign_in` is not styled properly.

![screenshot-osem - chromium](https://cloud.githubusercontent.com/assets/4322737/16731539/5d689404-4781-11e6-831b-ab3849d8c17c.png)

**Comment by ChrisBr** [comment]
IIRC, this is only the testmode! In production you will redirected to the openSUSE page...

**Comment by differentreality** [comment]
https://events.opensuse.org/users/ichain_sign_in

**Comment by ChrisBr** [comment]
Hm, ok!
