### ISSUE TITLE
Linkable events in conference/events

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1121]
When showing all of the unscheduled events in conference/events, some of the events are clickable and some others have the word `more` at the end, and only the word more links to proposal#show

There should be 1 common way for this. I would personally prefer the clickable box, and the word more can stay where it applies.

**Comment by AEtherC0r3** [comment]
I tried to reproduce this but failed
Is it still relevant?

**Comment by differentreality** [comment]
Fixed in #1132
