### ISSUE TITLE
view comments in event list

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#1135]
You can't see which events have comments in the event list and they are necessary for scheduling.

**Comment by sherrimitchell** [comment]
Henne,

I am going to work on this issue. My understanding of what is needed for the issue is as follows:

- In the Admin Events Index view for a conference, add a Comments Column
- If Comments for an Event exist, display an indication that comments exist ( 'Comments(2) )

**Comment by hennevogel** [comment]
sounds like a plan @sherrimitchell :-)

**Comment by sherrimitchell** [comment]
@hennevogel I have added the column and link to the page, and when the user clicks the link the show page for the event will display with the comments link at the bottom of the page, which is the default behavior for clicking on an event. Currently, the user must click the comments link to see the add comments form and any comments previously added. I had a couple of additional questions regarding this feature:

- Currently, on the event show page the total number of comments is displayed with a link to view/add a new comment. So when a user clicks the comments link on the events index page, they will have to click the comments link on the event show page to actually view the comments. This seems like an unnecessary step and not the best user experience. Do you want to keep this functionality the way it is, or allow the user to click the comments link from the events index page and go directly to the comments view?
- If I add the ability for the user to view the comments directly from this link, do you want them to be able to view the comments count and a limited number of comments or characters with an ellipses and then click a 'more' link?
- Currently on the event show page the comments link is displayed with the total (0 - ...). There is no explicit indicator for the user to leave a comment. Should there be some sort of link/indicator included to leave a comment?
- If this is changed, do you also want the default behavior for the event show page to be changed to reflect this change for consistency?

Thanks!
