### ISSUE TITLE
See commercials in admin/events#show

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1146]
While it's possible to see the available commercials in proposals#show, it is not possible to see them from the admin panel.

**Comment by arun1595** [comment]
I'll do this.

**Comment by redimido** [comment]
I do not know how the commercials show. I hace tried to see the ones I created for the event but nothing shows when I am not logged and when I log, commercials are not shown either.

where are the commercials supposed to show? should there be a carrousel or some rotating video embebbed?

thanks
Gabriel

**Comment by differentreality** [comment]
Check this out
http://demo.osem.io/conference/osemdemo/program/proposal/14/

Create a proposal -> Edit the proposal -> Go to Commercials Tab

It mentions there:

> 
You can add commercials for your proposal. These commercials will be displayed on the public proposal page. If you don't add a commercial, the conference commercial will be displayed!

If you have further problems, please find us on IRC or open a new issue so that we can keep the comments of this issue on subject.

**Comment by differentreality** [comment]
Closed in https://github.com/openSUSE/osem/pull/1322
