### ISSUE TITLE
Remove versions for EventAttachment

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1147]
Even though the model EventAttachment no longer exists, there can be version records about it. 
Shouldn't we remove them with a rake task?  @hennevogel

**Comment by hennevogel** [comment]
sure

**Comment by redasus** [comment]
What exactly are version records ?

**Comment by differentreality** [comment]
The records in the `versions` table in the DB.

**Comment by redasus** [comment]
what's the item_type for an event_attachment ?
Shouldn't these be in an enum ?

**Comment by differentreality** [comment]
@redasus please point to a line of code or explain where you see what, so that we can better understand and help
