### ISSUE TITLE
Feature Request - print ticket and ..!

### ISSUE THREAD

**Issue by ZEROF** [openSUSE/osem#1153]
Hi,

I don't know if some payment system can be used with OSEM; but it will be nice (for now) if user can print ticket and that ticket can have few information in conf logo/conf name/ticket type/date/user name/ and qr code (ticket can be scanned) and in the end admin can set date when user(s) can download ticket(s), this option is good if user will send bank transfer or something like that, that give them week or two to do that, and orga team to check if payment is made. Setting ticket download date can be made as global option, for all users, not user by user. I say this, because if you have 1000 people on your event, it will be real mess for admin to keep trace.

I used this options with other ticket system (c4sh, not public anymore), and for orga team is very good to have this feature(s).

Thanks for GJ!

**Comment by ChrisBr** [comment]
Hi @ZEROF, 

we're working on this feature as part of this year Google Summer of Code
https://github.com/openSUSE/mentoring/issues/24

Also see these PR:
https://github.com/openSUSE/osem/pull/1108
https://github.com/openSUSE/osem/pull/1116
https://github.com/openSUSE/osem/pull/1118

which we plan to merge the next few days.

For more information, you should contact @rishabhs95 (our GSoC student) or @lagartoflojo (mentor). 

Stay tuned :)

**Comment by ChrisBr** [comment]
@lagartoflojo @rishabhs95 did we cover sth of this in your GSoC project? If yes please update and close!

**Comment by lagartoflojo** [comment]
@ChrisBr no, we didn't do anything about printing tickets. That's definitely something we can improve upon. Right now, you pay for a ticket and you still get the same email message we always had.

**Comment by rishabhs95** [comment]
Yes, so you can pay for the tickets via stripe and after a successful payment, Stripe will send you an email confirming the received payment.

**Comment by differentreality** [comment]
This is now implemented in OSEM as part of @siddhantbajaj GSoC 2017 project https://github.com/openSUSE/osem/pull/1600
