### ISSUE TITLE
Organizer Reports

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#1155]
The admin interface should have a report section with things like:
- Events that have no commercial
- Missing speakers, people who have not checked in but have a talk
- All Events with a Event.description (things speakers need)

So basically information that helps the organizers doing their thing.

**Comment by differentreality** [comment]
https://github.com/openSUSE/osem/pull/1114 introduces some of those things.

**Comment by hennevogel** [comment]
Ah cool. Just cleaning out my notes :-) Shall we close this?

**Comment by differentreality** [comment]
No, of course not. Number 2 is not being implemented yet. And perhaps we come up with more ideas. I just wanted to make sure the PR was mentioned in this issue 😊
