### ISSUE TITLE
"More" links in program are all broken

### ISSUE THREAD

**Issue by LukasReschke** [openSUSE/osem#1170]
The links at https://conf.nextcloud.com/conference/NextcloudConference2016/schedule saying "… more" are all broken and go to "Cloud Federation beyond simple file sharing" instead of the right program entry.

This is on 1.0

cc @jospoortvliet

**Comment by differentreality** [comment]
Indeed :(

In https://github.com/openSUSE/osem/blob/one/app/views/conference/_all_events.html.erb#L16
The line should read:
 <%= link_to 'more', conference_program_proposal_path(@conference.short_title, event.id) if event.abstract.length > 400 %>
