### ISSUE TITLE
Add Open Graph Meta Data to Event#show

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#1177]
There should be sensible [open graph](http://ogp.me/) metadata embeeded in the Event#show page. Like 
- og:title with the title
- og:image with the conference logo
- og:url with the url
- og:description with the abstrace
- og:site_name with OSEM_NAME

and possibly more.

**Comment by sherrimitchell** [comment]
Henne, I am working on #1178 and since this issue is so similar, I would like to work it also. -- Sherri

**Comment by ChrisBr** [comment]
done in https://github.com/openSUSE/osem/pull/1231
