### ISSUE TITLE
Add Open Graph Meta Data to Conference#show

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#1178]
There should be sensible [open graph](http://ogp.me/) metadata embeeded in the Conference#show page. Like 
- og:title with the title
- og:image with the conference logo
- og:url with the url
- og:description with the description
- og:site_name with OSEM_NAME

and possibly more.

**Comment by sherrimitchell** [comment]
Hi Henne. I am going to work on this issue. Sherri

**Comment by ChrisBr** [comment]
done in https://github.com/openSUSE/osem/pull/1231
