### ISSUE TITLE
admin/tickets#show

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1190]
The paid column shows true even if not all of the tickets are paid (some paid, some not). That's misleading and a problem when it comes to the financial side of the tickets.

If a user purchased 2 tickets in 2 different occasions, and only 1 ticket is paid, an organizer should know how many tickets are paid, and how many are not.

**Comment by richiethomas** [comment]
@differentreality I can take this.  So should we replace the 'Paid' column with a column showing how many tickets out of the total quantity are paid?  This would imply that the remainder are unpaid.

Alternately, we could make each scenario (paid vs unpaid) explicit, and show each number.

**Comment by richiethomas** [comment]
@differentreality what's your opinion on my proposed implementation above?  Related question- would you prefer to see a total quantity of paid and unpaid tickets, or a single column with % paid / unpaid?  Let me know and I'll start work on the issue.

**Comment by shlok007** [comment]
@richiethomas ping!

**Comment by richiethomas** [comment]
@shlok007 my apologies, I must have lost track of this issue.  I'm happy to give it up for someone else to work on.
