### ISSUE TITLE
Add meta tags for Facebook and other sites

### ISSUE THREAD

**Issue by redimido** [openSUSE/osem#1192]
Hi, when trying to share our OSEM setup on Facebook, one of our followers noted that Facebook did not allow him to reference us cleanly.

when done so in Facebook, it adds:

> OSEM requires JavaScript to be enabled to function. Please turn on JavaScript in your browser's settings and reload the page to continue

I looked for it, and found this Facebook URL:
[https://developers.facebook.com/docs/sharing/webmasters](https://developers.facebook.com
/docs/sharing/webmasters)

**Comment by ChrisBr** [comment]
Implemented Open Graph Metadata in https://github.com/openSUSE/osem/pull/1231
