### ISSUE TITLE
OSEM our conference is not free. it has a pretty small fee, and we need support for it

### ISSUE THREAD

**Issue by redimido** [openSUSE/osem#1194]
Hi,
We request a fee of about 30usd to attend that help us to pay for the venue rooms.

I did not find where I can fix that.

The introductory text for registering says "going to the conference is free of charge", but we do not have a company behind us and we need some help to pay for venue costs.

can this be added?

**Comment by differentreality** [comment]
We already support tickets, which can be introduced from the admin panel if you navigate to 'Tickets' from the left menu. You can also accept payments online, after our most recent changes during GSoC.

If your conference has tickets, this message won't appear.

**Comment by differentreality** [comment]
@redimido is it clear how you can do what you need? Can we close this or is there something else related to this issue that we haven't addressed yet?

**Comment by differentreality** [comment]
I will close this as there is no response, and the issue does not seem to exist anymore.
If there is anything else you need @redimido feel free to open a new issue or find us on IRC irc://freenode.net/osem

**Comment by redimido** [comment]
Thank you.

I worked around with your suggestions

Regards,
Gabriel


El 5 dic. 2016 8:57, "Stella Rouzi" <notifications@github.com> escribió:

I will close this as there is no response, and the issue does not seem to
exist anymore.
If there is anything else you need @redimido <https://github.com/redimido>
feel free to open a new issue or find us on IRC irc://freenode.net/osem

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openSUSE/osem/issues/1194#issuecomment-264874860>, or mute
the thread
