### ISSUE TITLE
function intersecting_events no longer returns a collect of events

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1205]
https://github.com/openSUSE/osem/blame/master/app/models/event_schedule.rb#L28

Returns event_schedules instead of events

**Comment by Ana06** [comment]
Why do we want to change that and why is it a bug? We could change the name of the method and the comment to make clear that it returns `event_schedules`.

**Comment by differentreality** [comment]
@Ana06 I marked it as a bug because I saw it somewhere being used expecting to return events. I will have to look more to find where - there is a small possibility it was not on master but on an open PR.
