### ISSUE TITLE
Add db seed

### ISSUE THREAD

**Issue by alexdor** [openSUSE/osem#1211]
Include a db seed in order to minimize testing time.

**Comment by lagartoflojo** [comment]
I always use https://github.com/openSUSE/osem/blob/master/lib/tasks/data_demo.rake
Do we need anything else?

**Comment by hennevogel** [comment]
@alexdor please explain what you are looking for...

**Comment by alexdor** [comment]
@lagartoflojo  The [data_demo.rake](https://github.com/openSUSE/osem/blob/master/lib/tasks/data_demo.rake) is a start but I think it's incomplete. For example, it should include, a conference with open proposals, some rejected and some accepted proposals, some speakers, a few venues etc. 

@hennevogel I was looking for a seed.rb that would populate the database with test data, by running  `rake db:seed`, which is built-in to rails.

**Comment by differentreality** [comment]
I would also like an automated way to add some more information, both for my dev env as well as for the review apps. We only create a conference and most of the times we also need some events to exist to actually review a PR. And that's just a single example. 
Perhaps it makes sense to keep the data in the rake task, instead of seeds.rb

**Comment by lagartoflojo** [comment]
@alexdor is this something you'd like to tackle? I agree with @differentreality that it would be quite useful.

**Comment by differentreality** [comment]
Some of the cases that would be interesting to have as demo data:

- [ ] Full conference happening in the future (with open cfp, venue/rooms, submitted talks by multiple speakers, partly confirmed talks)
- [ ] Full conference in the past (with closed cfp, venue/rooms, submitted talks by multiple speakers, rejected talks, confirmed talks, multiple scheduled talks in various rooms)
- [ ] Conference without venue/rooms, with submitted talks

In each case a full range of events is desired:
* New Event
* Accepted Event
* Rejected Event
* Confirmed Event
* Scheduled Event
