### ISSUE TITLE
Replace vagrant with docker 

### ISSUE THREAD

**Issue by alexdor** [openSUSE/osem#1213]
Docker is overall lighter than vagrant. Its benefits include, but are not limited to :
- Better resource management 
- Smaller images 
- Fewer and lighter dependencies 
- Less bandwidth required per image download

**Comment by differentreality** [comment]
@alexdor @lagartoflojo can help you with docker

**Comment by lagartoflojo** [comment]
Hi @alexdor, have you had a look at https://github.com/openSUSE/osem/pull/933? Is something like that what you're proposing?

**Comment by lagartoflojo** [comment]
While that PR was closed, we could re-open the discussion about either keeping Vagrant or moving development to Docker/docker-compose.

**Comment by alexdor** [comment]
Hi @lagartoflojo, my proposal is similar but not the same. For example, I would move the DB to separate container cause it's closer to docker's philosophy that way. Yeah we should reopen the discussion, should we do it before creating a pull request?

**Comment by lagartoflojo** [comment]
I agree with respect to the DB. Ideally, we would run mysql/mariadb even in dev machines, to be as close to a production env as possible.

But we should definitely agree on the direction we want to take before writing code. There's already a prototype in #933, and I think it's enough to have a fruitful discussion.

Personally, I prefer the Docker / docker-compose solution. I tried using Vagrant locally but it did not work for me, so I also used Docker for osem in the end.

Docker can be used as a [provider for Vagrant](https://www.vagrantup.com/docs/docker/), but I don't think we need it. Using is just more complexity for very little gain. It would mean maintaining both a Vagrantfile and a Dockerfile, as well as requiring contributors to have both tools installed.

Right now, Docker is very easy to install, even on [Windows](https://docs.docker.com/docker-for-windows/) and on [macOS](https://docs.docker.com/docker-for-mac/), so it should be quite easy for any future contributor to get started. Also, building osem on Docker is quite easy: `docker-compose build`. All dependencies are automatically downloaded, no need for additional plug-ins like in Vagrant.

@hennevogel @differentreality @ChrisBr @kalabiyau thoughts?

**Comment by hennevogel** [comment]
Introducing docker as vagrant backend is pretty easy. I have a branch in the [hackweek tool](https://github.com/SUSE/hackweek/compare/vagrant-docker-backend?expand=1) that does this. But anyway, using docker for development brings two major PITAs:

1. 'Folder syncing' with the correct file/folder permissions only works with horrible hacks (like the IMAGE_USERID hack in hackweek) that are not really portable across OSes.
2. There is no real way to run one-off commands inside the container. Which is what you really do a lot while developing. 

That's what makes me stay away from docker for development right now. Feel free to prove me wrong for both :-)

BTW a docker image in the hub for OSEM production, or a docker-compose file for this, is some completely different story!

**Comment by Ana06** [comment]
@hennevogel what is the state of this? it seems docker is already being used and documented. Should we get rid of vagrant?

**Comment by hennevogel** [comment]
for me this would be okay
