### ISSUE TITLE
Obligatory Questions?

### ISSUE THREAD

**Issue by mmarkus1** [openSUSE/osem#1217]
Will it be possible (in future versions) to choose obligatory or non-oblitatory for a question, so that the user must fill out the field or leave it empty to register for the event?

**Comment by differentreality** [comment]
Yes, that's the concept already in https://github.com/openSUSE/osem/pull/1100 (https://github.com/openSUSE/osem/pull/1100/files#diff-1a428cc0dc9bd983d4680fd977647262R10)
