### ISSUE TITLE
Feature request: More granular time slots

### ISSUE THREAD

**Issue by kormoc** [openSUSE/osem#1220]
Currently the time slots are limited to 15 minute chunks. We would prefer 5 minute chunks, as generally our talks are ~50 minutes and then there's a 10 minute break to setup the room for the next talk. Currently we're forced to set the talks as 45 minutes or 1 hour.

**Comment by differentreality** [comment]
This is done, however I think this should be an option conference-wise not app-wise. @Ana06 @eug3nix  this is not currently happening, right? Meaning we cannot have 5-minute slots for schedule of conf A, and 15-minute slots for conf B?

**Comment by eug3nix** [comment]
@differentreality yes, that's correct, the schedule grid density is currently configured in the .dotenv files, but this can be adjusted of course

**Comment by differentreality** [comment]
This will also be extremely useful and flexible for when we implement the hosted version of OSEM.

**Comment by kormoc** [comment]
Thank you very much @Ana06, @differentreality, @eug3nix, and @JewelSam ! This will make things a lot easier for us to manage for our next conference 🎉
