### ISSUE TITLE
presentation proposal for 2 people not possible any more

### ISSUE THREAD

**Issue by skriesch** [openSUSE/osem#1225]
3 years ago it was possible to write a proposal for 2 speakers (I did that). This year I heared by B1 Systems that it isn't possible any more. They wanted to give a presentation ( 2 speakers) and Stan was able to enter only one name. Can you fix this bug / activate the old feature again, please?

We want to give a talk with 2 speakers at the next oSC. :-)

**Comment by differentreality** [comment]
I don't think it was ever possible to show publicly more than one speaker per talk.

This is already requested and tracked in https://github.com/openSUSE/osem/issues/749

**Comment by skriesch** [comment]
I created a proposal for 2 people for the oSC14. I believe that was one of the first conferences with OSEM. But you can mark it as a duplicate, if you have got a issue for that. Last weekend we spoke about that in our meeting at SUSE (whether Bug or Feature Request).

**Comment by ChrisBr** [comment]
As said, covered in #749
