### ISSUE TITLE
Making comment counter more efficient

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#1230]
By introducing a counter cache.
See my comment from #1186 

But we can improve your changes with some advanced Rails techniques :) With your changes, every time I access events#index we make several COUNT calls. Instead hitting the database all the time we could instead cache it. Rails already implements this :smile:

From the rails documentation:

belongs_to :author, dependent: :destroy, counter_cache: true

http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to

Of course you would need a migration to add the column for storing the hash. However, I think it's worth the effort. These adaptions don't make the code more complicated and improve the performance A LOT!

**Comment by mwgalloway** [comment]
@ChrisBr if this is up for grabs, I'd like to take a crack at it!

**Comment by shaan15** [comment]
Hi, is someone still working on this or is it up for grabs?
