### ISSUE TITLE
Broken revision count

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1236]
I don't understand the intended behavior of  [revision_observer.rb](https://github.com/openSUSE/osem/blob/master/app/models/revision_observer.rb) .

It seems like it should increment `revision` column on every change of `room` , `track` , `event` and `conference` itself. If that's the case then then the count increments for the changes in `conference` model only and needs to be fixed.

**Comment by differentreality** [comment]
Thanks for the issue @shlok007 
Also Event, Room, Track do not have a relationship with Conference any more, they do with Program.
https://github.com/openSUSE/osem/blob/master/app/models/revision_observer.rb#L19

**Comment by shlok007** [comment]
I was thinking maybe we could drop observers. It was removed from core in Rails 4.0 . There hasn't been a version release since 2013 and hence, no support for rails 5 yet. See: https://github.com/rails/rails-observers/pull/39

We could probably use `Concerns` instead
https://signalvnoise.com/posts/3372-put-chubby-models-on-a-diet-with-concerns
