### ISSUE TITLE
Allow to upload a picture directly or from other opensuse.org sides for commercials

### ISSUE THREAD

**Issue by lrupp** [openSUSE/osem#1248]
I tried to update my proposal here:
 https://events.opensuse.org/conference/oSC17/program/proposal/1242/edit#commercials-content

But I'm unable to upload or link our team logo from:
https://en.opensuse.org/images/7/70/Heroes_logo.png

Why do I need to create an account on external pages first, that have nothing to do with openSUSE as such?

So please allow to upload media or at least include opensuse.org in the list of allowed domains.

**Comment by hennevogel** [comment]
Because we don't want to take care of hosting your data and all that comes with it (backup etc.) forever. Please make use of what is possible with OSEM...

**Comment by lrupp** [comment]
I understand that you do not want to allow uploading - and I already suggested that you allow to include other URLs like ones from opensuse.org. 

At the moment, the tools just tells me:
"Just paste the url of your video/photo provider. Currently supported: YouTube, Vimeo, SpeakerDeck, SlideShare, Instagram, Flickr." 

Why is openSUSE not in this list?

**Comment by ChrisBr** [comment]
@lrupp because we use OEmbed to realize it (http://oembed.com/). If openSUSE does support this I'd be happy to include it :)

**Comment by lrupp** [comment]
Thanks for the information: https://progress.opensuse.org/issues/15906 opened for our openSUSE Wiki admins...
