### ISSUE TITLE
Change homepage to next conference#show

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#1259]
We use osem as annual conference organizer, currently osem show a list of next conferences as homepage but should be great if it could go to the next conference#show if there are only one conference configured.

We have done a hack to do this in http://www.opensouthcode.org but if there are any interest I could try to implement it.

**Comment by lagartoflojo** [comment]
I very much like this idea. @Ana06 @differentreality @ChrisBr thoughts?

**Comment by differentreality** [comment]
I'd go for it too.

**Comment by lagartoflojo** [comment]
@davidsf would you like to implement this?

**Comment by ChrisBr** [comment]
@lagartoflojo http://www.pgconf.us/conferences/2017 did the same! So yes, I also think it makes sense

**Comment by Ana06** [comment]
I like it too

**Comment by divyanshumehta** [comment]
Can I try it out @Ana06 , please. Doesn't it need only the routes file to be changed?

**Comment by ChrisBr** [comment]
@divyanshumehta go ahead, you don't need to ask if you want to work on an issue!

**Comment by Rupal-IIITD** [comment]
@davidsf 
I didn't quite understand as to what you mean by "go to the next conference#show if there are only one conference configured"?
Can I request you to elaborate a bit more?

**Comment by davidsf** [comment]
@Rupal-IIITD 
We use osem for an annual conference, for us is better to go to the conference#show of the next conference, instead of listing the conferences.

**Comment by davidsf** [comment]
What is the state of this? I see some implementation by @divyanshumehta. It is completed ?

**Comment by differentreality** [comment]
No, unfortunately not @davidsf but it is in my plans to have this done soon.

**Comment by bear454** [comment]
@davidsf please consider closing this PR, and supporting the more flexible change in #1994 .

**Comment by differentreality** [comment]
It seems we should let people choose what they want:
1. always redirect to conferences#show (if there is an upcoming conference), this will make it impossible to access conferences#index, and thus see a list of past conferences.
2. no change - you get to see conferences#index (which btw has buttons for different options for each conference listed there!)
3. we have been also discussing redirecting to conferences#show only if there is only 1 conference in the OSEM installation - I see this being helpful and relevant only for one-time-only conferences (unlikely they will install OSEM just to host 1 single conference and nothing more, ever)

https://github.com/openSUSE/osem/pull/1867

**Comment by bear454** [comment]
All of these scenarios are handled by #1994.
