### ISSUE TITLE
Update proposal page: Requirements field should not be collapsed if non-empty

### ISSUE THREAD

**Issue by afaerber** [openSUSE/osem#1260]
When initially editing a talk proposal, the Requirements field is collapsed, which makes perfect sense.

However, once it has been expanded and filled, the next time one edits the proposal it is collapsed again, hiding the previously entered contents. If clicking on "Do you require something special?" the field is shown with the previously entered contents, so it is just a display issue.

Expected behavior would be to have the field collapsed if empty but shown if non-empty.

**Comment by BelieveC** [comment]
@afaerber, Pull request #1276 for fixing above issue.

**Comment by differentreality** [comment]
I agree with this approach, when there is content, it makes sense to be visible.
