### ISSUE TITLE
Don't ask for arrival and departure when registering

### ISSUE THREAD

**Issue by lagartoflojo** [openSUSE/osem#1263]
Most people leave this field with the defaults, and conference organizers don't really need it.
If a particular conference wants to have this info from every attendee, then they can add it as a question to the registration itself.
It does not make sense to have it as default.

This task would still involve somehow migrating old answers for previous conferences.

![screenshot from 2017-02-01 17-49-02](https://cloud.githubusercontent.com/assets/2944/22517669/3dc29ee0-e8aa-11e6-8c0b-cbc5b70e6506.png)

**Comment by shlok007** [comment]
Travel info can be migrated into surveys which is introduced in https://github.com/openSUSE/osem/pull/1100 . We could probably add a rake task to migrate the travel info  for previous conferences to survey answers once that PR gets merged.

**Comment by lagartoflojo** [comment]
I don't know if it makes sense to wait for that PR. AFAIK the surveys are not related to the registration, are they?
In any case, we can just keep it simple. We're talking about migrating the arrival/departure times for old conferences, so I don't think it's really very important information. What's important is that we don't lose it.

**Comment by differentreality** [comment]
Surveys are **not** directly related to registration. But we might have surveys implemented by the end of the month.
I would like to keep the information. Where would you migrate it to? Questions?

**Comment by lagartoflojo** [comment]
Yes, I would migrate them to Questions. Do you think that would work?

**Comment by differentreality** [comment]
We had some bugs with questions so I am not 100% sure. Perhaps worth trying if you wanna close this soon and if it doesn't work, we can wait a bit for surveys.

**Comment by lagartoflojo** [comment]
Gotcha, then we just have to try it out :)

**Comment by shlok007** [comment]
There could be questions titled `Arrival` and `Departure` in which the travel info of the users can be migrated. This would result in something like this:

:arrow_down: *questions#show* for question tittled `Arrival` (same goes for departure)
![arrival](https://cloud.githubusercontent.com/assets/14155445/22555390/9116a0fc-e989-11e6-85f6-0439891a97ce.png)

>We had some bugs with questions so I am not 100% sure. 

But again, it seems like the ability to disable a question which is not *global* is currently broken. 
Therefore, it would ask the `Arrival` question every time a user registers ( with arrival time of other users as options ). I suggest we fix that first then we can proceed to add a task to migrate the data. :slightly_smiling_face:

**Comment by Ana06** [comment]
Closing this as there is further discussion in the duplicated issue #2333
