### ISSUE TITLE
Crowded ApplicationHelper [ Refactoring ]

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1264]
Currently [ApplicationHelper](https://github.com/openSUSE/osem/blob/master/app/helpers/application_helper.rb) has 58 methods with 500+ lines of code. 
These methods can be divided into separate helper classes for separate views.

**Comment by gunkiratk** [comment]
Hey,
I want to work on this issue

**Comment by Ana06** [comment]
@gunkiratk go ahead! :wink:

**Comment by gunkiratk** [comment]
@Ana06 thanks!
My Rgsoc partner @shaan15 would be working on it!

**Comment by agrim123** [comment]
@shlok007 i m interested in working on this issue

**Comment by shlok007** [comment]
@agrim123 Feel free to send a PR with your changes . :slightly_smiling_face:
