### ISSUE TITLE
"Remember me" label is not clickable

### ISSUE THREAD

**Issue by lagartoflojo** [openSUSE/osem#1271]
When logging in, in the login box drop-down, clicking on "remember me" does not check/uncheck the checkbox, as expected.

![screenshot from 2017-02-06 18-58-40](https://cloud.githubusercontent.com/assets/2944/22659548/4bfd195c-ec9e-11e6-824a-c16afb7ea05a.png)

**Acceptance criteria**

- In the top menu bar, click on "Sign In"
- Click on "Remember me".
- Show that the checkbox gets checked.

**Comment by BelieveC** [comment]
@lagartoflojo, clicking on "remember me" is working as expected. Are you talking about any specific page?

**Comment by lagartoflojo** [comment]
Does not work for me. I tried the master branch on Chromium 52 and Firefox 50.
The "Remember me" label does not check the checkbox in any page.

**Comment by BelieveC** [comment]
Works fine for me on firefox 50.1. 
![signin](https://cloud.githubusercontent.com/assets/14261624/22660373/45426990-ecc7-11e6-8c10-fda12444130b.png)

**Comment by lagartoflojo** [comment]
I don't really understand how it works for you. Looking [at the code](https://github.com/openSUSE/osem/blob/master/app/views/layouts/_navigation.html.haml#L71-L74), there's no `<label>` for the "Remember me" text.

**Comment by lagartoflojo** [comment]
Please note I'm talking about clicking on the "remember me" **text**. I'm NOT talking about clicking on the checkbox itself.
