### ISSUE TITLE
Superfluous "Sign in" link

### ISSUE THREAD

**Issue by lagartoflojo** [openSUSE/osem#1272]
When logging in, in the login box drop-down there is a "Sign In" link that is not really useful. We can remove it.
This link is [only shown in non-desktop devices](https://github.com/openSUSE/osem/blob/master/app/views/layouts/_navigation.html.haml#L87-L88) for some reason.

![screenshot from 2017-02-06 18-56-27](https://cloud.githubusercontent.com/assets/2944/22659475/0759b990-ec9e-11e6-8ef6-6c7ffd080964.png)

**Acceptance criteria**

- In the top menu bar, click on "Sign In"
- Show that there's no "Sign In" link within the drop-down.

**Comment by lagartoflojo** [comment]
Ok, not sure how I saw this, but it seems to be fixed 😝

**Comment by sheamunion** [comment]
@lagartoflojo I'm happy to take care of this!
