### ISSUE TITLE
Better "short title" UI

### ISSUE THREAD

**Issue by lagartoflojo** [openSUSE/osem#1273]
When creating a new conference, it's not very clear what the "short title" field is for. Without reading the gray help text underneath, it's not possible to realize that it's for the URLs.
The UI can help with this. For example, something like:

![screenshot from 2017-02-01 17-48-27](https://cloud.githubusercontent.com/assets/2944/22659926/de5c3b92-ec9f-11e6-9c6e-54cf419fd0b7.png)

We can also disallow users from typing prohibited characters (symbols, spaces, upper case letters, etc.). Another option would be to rename the field to something more obvious (technically, the short title is a "slug", but that's probably jargon).

**Acceptance criteria**

- Go to the "New conference" form.
- Explain how the new interface for the "short title" field is easier to understand.

**Comment by sheamunion** [comment]
I'd like to take this on!

**Comment by lagartoflojo** [comment]
@sheamunion hi Shea, great! What do you have in mind to try to fix this?

**Comment by sheamunion** [comment]
According the formtastic-bootstrap documentation, one can prepend a `<span>` element to a form input using the [`:prepend`](https://github.com/mjbellantoni/formtastic-bootstrap#prepended-text) option. I suggest we leverage that option to achieve what you've documented in your image above.

Furthermore, we can add a [`pattern`](http://www.w3schools.com/tags/att_input_pattern.asp) attribute to the `input` to restrict user input. We can also use the `title` attribute to provide specific feedback about what characters are allowed in this field.

We _could_ rename the field to something like "Custom URL" to avoid jargon but I think that may be over-doing it. I suspect that the visual queues of the prepended URL, the input restrictions, and the hint text will suffice.

**Comment by sheamunion** [comment]
See #1281!

**Comment by lagartoflojo** [comment]
Thanks! I added some comments to your PR :)
