### ISSUE TITLE
Program.any_events_for_this_date? is possibly broken

### ISSUE THREAD

**Issue by eug3nix** [openSUSE/osem#1298]
Hi everyone, please take a look at this
https://github.com/openSUSE/osem/blob/master/app/models/program.rb#L153
this method rely on the events.start_time column which seems to be obsolete
as a result, the return value for this method is always FALSE
resulting in all dates on the public schedule events tab dropdown being greyed-out
I played with the code in IRB and it seems that this may be the correct code for the method:
`EventSchedule.where(schedule_id: selected_schedule.id).where(start_time: parsed_date..(parsed_date + 1)).any?`
Please advise

P.S. here is the screen which shows the issue from the user perspective(note the greyed-out dropdown items vs the event date)
![screenshot at 2017-02-22 16 13 44](https://cloud.githubusercontent.com/assets/4243476/23215406/efa37348-f91a-11e6-8a1e-d0b654980c52.png)

Thanks,
Eugene/CommandPrompt Inc.

**Comment by differentreality** [comment]
https://github.com/openSUSE/osem/issues/1154
https://github.com/openSUSE/osem/blob/master/app/models/event.rb#L246

**Comment by Ana06** [comment]
This is already solved: #1309
