### ISSUE TITLE
Issue with Confirmed events scheduled chart on event index page

### ISSUE THREAD

**Issue by siddhantbajaj** [openSUSE/osem#1302]
Right now to check if the event is scheduled or not we check if its start time attribute is set or not. I think instead of this we should check if there is an entry for that respective confirmed event in EventSchedule table.

**Comment by differentreality** [comment]
@siddhantbajaj Could you please give some more details? What's the issue with the way things are now and where in the code does the issue occur?

**Comment by siddhantbajaj** [comment]
Consider an Event { id: 1, start_time: nil}

When we schedule this event an entry is created in Event Schedule table something like this:
{ id: 7, event_id: 1, schedule_id: 1, room_id: 1, start_time: "2017-02-18 10:00:00" } but the start time of that event still remains nil.

So to determine if the event is scheduled or not we should check if there is entry in the Event Schedule table where event_id = 1 (in this case).

Right now the code to determine if the event is scheduled is something like this:
https://github.com/openSUSE/osem/blob/master/app/models/conference.rb#L333

**Comment by Ana06** [comment]
@siddhantbajaj yes `start_time` attribute in event is an unused attribute at the moment, so it should be used :+1:
