### ISSUE TITLE
Duplicate methods in application_controller and conference.rb

### ISSUE THREAD

**Issue by nikhilgupta1211** [openSUSE/osem#1310]
method date_string in application_controller and method date_range_string in conference.rb produce the same result so we can keep one of them and remove the other .

**Comment by shaan15** [comment]
Hi, is this issue still open?

**Comment by jbkimble** [comment]
@nikhilgupta1211 I'm going to take a crack at this issue!

**Comment by jbkimble** [comment]
@nikhilgupta1211 I'm going to look into this!

**Comment by nikhilgupta1211** [comment]
@jbkimble actually this has already been resolved in #1311
