### ISSUE TITLE
2016 index page is broken

### ISSUE THREAD

**Issue by seanlinsley** [openSUSE/osem#1313]
Clicking "View Conference" on [this page](http://www.pgconf.us/conferences/) for PGConf US 2016 results in an [internal server error](http://www.pgconf.us/conferences/2016).

Context: I was linked to [this page](http://www.pgconf.us/conferences/2016/program/proposals/147/), watched the video, then tried shortening the URL (e.g. removing `/proposals/`) until I got to a page that existed, so I could find more videos.

**Comment by differentreality** [comment]
Indeed conferences#show for 2016 isn't working. We would need to see some logs to help more though.

**Comment by differentreality** [comment]
@seanlinsley can you provide us with more information in order to debug this?

**Comment by seanlinsley** [comment]
I'm not sure what you're asking for; this page still reproduces the server error: http://www.pgconf.us/conferences/2016

**Comment by differentreality** [comment]
I am asking for the rails server logs

**Comment by seanlinsley** [comment]
How would I have access to those? I'm just a random person on the internet.

**Comment by differentreality** [comment]
Oh alright, I assumed you were involved with PGConf US and that was why you opened an issue with OSEM about this, instead of contacting the organizers of the conference.

Any conference using OSEM can modify it in any way they like. There is no way for us to reproduce the error, I am afraid.  @eug3nix perhaps you can help us?

**Comment by eug3nix** [comment]
Hey, @seanlinsley I am the one who is working on the current implementation of the pgconf.us website, which is running OSEM with quite a lot of modifications done to it. The legacy conference data(e.g 2016) was migrated from the previous PGConf application but still needs some manual tweaking here and there to make OSEM work, we are actively working on the PGConf 2017 at the moment and will spend some more time on fixing the legacy data later.
The issue you reported has nothing to do with the OSEM code itself, but I would like to thank you for this report.
You can use the official pgconf.us organizers email to contact the conference staff directly: organizers@pgconf.us

Thank you!
Eugene/CommandPrompt Inc.

**Comment by seanlinsley** [comment]
Ah I see. I'd clicked the only relevant link in the footer on [this page](www.pgconf.us/confearences/2016/program/proposals/147):

<img width="1001" alt="screen shot 2017-03-16 at 11 16 27 am" src="https://cloud.githubusercontent.com/assets/688886/24006531/1925f86e-0a3a-11e7-96e1-3d262c1d6156.png">

But the [2017 index page](http://www.pgconf.us/conferences/2017) correctly has a mailto link for organizers@pgconf.us:

<img width="1323" alt="screen shot 2017-03-16 at 11 16 46 am" src="https://cloud.githubusercontent.com/assets/688886/24006532/192a2d4e-0a3a-11e7-812d-732e62dd12c8.png">
