### ISSUE TITLE
Document openid implementation better

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1315]
While there is some mention about implementing openid in our installation instructions, this is mainly intended for production.

It is very unclear to new contributors as to what needs to be done in order to implement openid in development - or that this is even possible!

**Comment by AEtherC0r3** [comment]
Hello @differentreality, can you assign this issue to me?

**Comment by differentreality** [comment]
@AEtherC0r3 go ahead!

**Comment by AEtherC0r3** [comment]
This should have been closed when #1366 was merged
