### ISSUE TITLE
Change styling on views

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1326]
Views should use the new ruby syntax and comply with rubocop styling.

**Comment by divyanshumehta** [comment]
@differentreality I am on it

**Comment by divyanshumehta** [comment]
I saw usage of `:class =>"btn btn-default"` this can be changed to `class: "btn btn-default"`. Are we looking for these for these types of changes?

**Comment by differentreality** [comment]
Yes, and also for this example single quotes (unless there is string interpolation)

**Comment by gargi-gupta** [comment]
Me and my teammate @Rupal-IIITD used rubocop but it showed styling issues in only .rb files.
For .html.haml we had to use haml-lint instead.

**Comment by divyanshumehta** [comment]
@differentreality is there any way to keep the test to keep the test running on the go, I mean something like guard which checks the as we save a file. Because a lot of files need to be changed and runnnig the test after each file change involves a lot of time.

**Comment by Ana06** [comment]
@differentreality what about adding https://github.com/brigade/haml-lint to the project?

**Comment by differentreality** [comment]
@Ana06 I haven't tried it yet, but sounds good!

**Comment by divyanshumehta** [comment]
I too think a linter would be needed to maintain the views with uniformity.

**Comment by differentreality** [comment]
@divyanshumehta so added it to your PR!

**Comment by lagartoflojo** [comment]
@differentreality @Ana06 We recently introduced haml-lint to our project at work. It works fine, alright. But unlike Rubocop, it's not able to auto-correct :(

**Comment by differentreality** [comment]
@lagartoflojo sounds like we should use it too

**Comment by lagartoflojo** [comment]
I agree, we should!
Should it be part of https://github.com/openSUSE/osem/pull/1358 ?

**Comment by differentreality** [comment]
I don't mind opening a new PR for it. I had initially suggested we do styling changes in #1358 https://github.com/openSUSE/osem/pull/1358#issuecomment-285965198 but now that we will introduce a different tool, we can merge #1358 and then do the rest in a new PR.

**Comment by lagartoflojo** [comment]
Sounds good.

**Comment by lagartoflojo** [comment]
I think it makes sense to just enable haml-lint in one PR, and then start enabling the rules in different PRs. Some rules will need a lot of fixes, while others not so many.

**Comment by divyanshumehta** [comment]
Yeah good idea the RP #1358 has the changes for thr Ruby syntax and someluntibg correction. I will correct the linting in a new PRs, as there are lots of changed
