### ISSUE TITLE
Make Splashpage components selected by default

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1340]
When creating the Splashpage it ask you what components you want to include on it. I wold say that more likely you will select all or most of them, so I would show all of them already selected. Like this:

![image](https://cloud.githubusercontent.com/assets/16052290/23695603/595610a0-03e0-11e7-9288-a0ffad337da9.png)

**Comment by nikhilgupta1211** [comment]
@Ana06 I am on it :)
