### ISSUE TITLE
the schedule is broken for some browsers

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1342]
The schedule is not rendered properly in some browsers, I tried it in firefox:

![image](https://cloud.githubusercontent.com/assets/16052290/23699508/ae2f114e-03ef-11e7-9453-db31c405e167.png)

However in chromium It is properly rendered:

![image](https://cloud.githubusercontent.com/assets/16052290/23699575/f1f36dd0-03ef-11e7-878e-77c4e46ff012.png)

**Comment by siaw23** [comment]
how do i reproduce this? want to check it out.

**Comment by Ana06** [comment]
@siaw23 Open the schedule in Firefox for example :wink:

**Comment by Ronaq13** [comment]
I want to work on this.

**Comment by Ana06** [comment]
@Ronaq13 not sure if it is a good idea to work on more than one issue at the same time. Anyway, go ahead!

**Comment by Ronaq13** [comment]
@Ana06 I am not able to get this error. I checked on Chrome, Chromium, and also on Firefox. It renders perfectly on all the platforms. Recently firefox got updated, maybe that resolved this issue. 

![firefox_osem](https://user-images.githubusercontent.com/16839496/33702533-126a0812-db4a-11e7-8cb5-c68370c91089.png)

**Comment by Ronaq13** [comment]
@Ana06 : Any update on this? Is this still an issue. Just want a confirmation from your side.

**Comment by bear454** [comment]
@Ana06: can you please update, based on `master` branch & current browsers; I think this can be closed.
