### ISSUE TITLE
Log in is needed to see the schedule

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1343]
It is not allowed to see the schedule without log in.

**Comment by BelieveC** [comment]
I'm on it :+1:

**Comment by Ana06** [comment]
This is still not fixed, check for example https://events.opensuse.org/conferences/oSC17/schedule without login

**Comment by hennevogel** [comment]
are you working on this?

**Comment by BelieveC** [comment]
@hennevogel, No I'm not currently working on this.

**Comment by hennevogel** [comment]
tracked in #2365 now...
