### ISSUE TITLE
Issue with error message

### ISSUE THREAD

**Issue by siddhantbajaj** [openSUSE/osem#1345]
If you try to update conference and set start_date greater than end_date, then you get error message like this:
![screenshot from 2017-03-09 00 59 12](https://cloud.githubusercontent.com/assets/17237680/23720280/46c79b46-0464-11e7-819c-1af9cf0d080e.png)

I think it should be like this:
> Updating conference failed.Start date is greater than End date.

You can see this validation here:
https://github.com/openSUSE/osem/blob/master/app/models/conference.rb#L659

**Comment by agrim123** [comment]
This occurs because rails prepends name of the field to error message, so it is not required to include the field name manually.  
http://api.rubyonrails.org/classes/ActiveModel/Errors.html

**Comment by siddhantbajaj** [comment]
@agrim123 Yes you are right. I have seen this at few other places as well. Would you like to work on this?

**Comment by chashmeetsingh** [comment]
@siddhantbajaj can I?

**Comment by siddhantbajaj** [comment]
@chashmeetsingh go ahead. :+1:
