### ISSUE TITLE
Issue with registration limit

### ISSUE THREAD

**Issue by siddhantbajaj** [openSUSE/osem#1347]
When we create a conference its registration limit is by default set as 0 (which means no registration limit).
Now suppose 2 users register for the conference so no of registrations for the conference becomes 2. If we now try to update the registration limit of the conference to 1, conference will get successfully updated which I think should not happen.

**Comment by differentreality** [comment]
I am worried this might be introducing more limitations for the organizer rather than helping the organizer. Perhaps it would make more sense if there was more functionality around the registration limit, but there isn't any.

**Comment by siddhantbajaj** [comment]
Yes you are right,I was a bit worried about that too. But I think we should show some warning kind of a message so that at least the organiser knows about this because i don't think someone would want to set registration limit less than the number of registrations already present.
We would allow the conference to be updated but with a warning message. What do you think? @differentreality

**Comment by differentreality** [comment]
I would totally go for informing the organizer. I would not want to show a warning message when the update has been successfully completed, it's confusing. 
We could show the total number of registrations underneath the input box for registration limit. 'You already have X registrations.'

**Comment by siddhantbajaj** [comment]
Okay @differentreality ,I will make the changes in the PR. :+1:
