### ISSUE TITLE
[Question] Re-send confirmation instructions

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1350]
When a user signs up in OSEM, he receives a confirmation mail to confirm his account before he can log in. In my opinion there should be a way to resend the confirmation mail in case it wasn't received by the user.

Feel free to close this issue if something like this isn't yet needed. :slightly_smiling_face: .

**Comment by differentreality** [comment]
Why isn't that happening already? Did you try resending the confirmation email or were you unable to find where to do that from?

**Comment by shlok007** [comment]
Sorry. I failed to notice the `Need help?` button down below.
