### ISSUE TITLE
Formatting date

### ISSUE THREAD

**Issue by chashmeetsingh** [openSUSE/osem#1357]
We can format dates so that they look more human readable.
For example:
<img width="243" alt="screen shot 2017-03-11 at 9 46 19 pm" src="https://cloud.githubusercontent.com/assets/8962264/23824837/379caa98-06a4-11e7-8399-dabf685da958.png">

I would like to do this!

**Comment by Ana06** [comment]
Why do you want to render the start and the emd date in a different format? :thinking:

Could you please add a screenshot of how is this currently done so it is clear what the problem is? :wink:

**Comment by chashmeetsingh** [comment]
End date shows how it is currently displayed and start date shows how we should display it.

**Comment by differentreality** [comment]
Date format is clearly a personal preference (or country convention)
This is a duplicate of #666
