### ISSUE TITLE
Error in signin sign out options in responsive mode

### ISSUE THREAD

**Issue by manishyadavv** [openSUSE/osem#1380]
There is error while opening in responsive mode ,the sign out, Edit account ,Edit profile remains hidden when we click on it and drop down list doesn't show anything.@differentreality
@Ana06 
I had checked it for both Firefox and Chrome Browsers.
here are screenshots.
before clicking
![beforeclickadmin](https://cloud.githubusercontent.com/assets/23294174/24005284/9668e972-0a8e-11e7-904d-533dee9dd51a.png)
after clicking
![afterclickadmin](https://cloud.githubusercontent.com/assets/23294174/24005301/a58f9c0c-0a8e-11e7-9364-53a2b00a3466.png)

**Comment by nikhilgupta1211** [comment]
@manishyadavv this is being solved in #1320

**Comment by manishyadavv** [comment]
#1320  I had seen this but while operating in browser it shows options like this
![upld](https://cloud.githubusercontent.com/assets/23294174/24010295/7527edda-0a9d-11e7-833a-3121e1c73133.png)
when the cursor is moved on the option it shows and disappears when we remove from it.
