### ISSUE TITLE
Issue in conference dashboard

### ISSUE THREAD

**Issue by manishyadavv** [openSUSE/osem#1381]
Graph showing Submissions over time misbehaves when the boxes are checked and unchecked multiple times , graph merges under the other one and looses it's design.

before unchecking Submitted/Confirmed/Unconfirmed boxes
![beforeuncheckingbox](https://cloud.githubusercontent.com/assets/23294174/24008963/6bba5dd6-0a99-11e7-8200-ff99dead989b.png)

after unchecking Submitted/Confirmed/Unconfirmed boxes
![afterboxunchecking](https://cloud.githubusercontent.com/assets/23294174/24009013/8fd70da4-0a99-11e7-849e-7a737b55c1f3.png)

**Comment by manishyadavv** [comment]
Also it works when screen size in default in chrome(zoom=100%) but misbehaves when zoom=90% or less.

**Comment by differentreality** [comment]
Duplicate https://github.com/openSUSE/osem/issues/579
