### ISSUE TITLE
Missing Controller, Model tests for Venue

### ISSUE THREAD

**Issue by BelieveC** [openSUSE/osem#1382]
Following files and tests for Venue are missing:

- `spec/controllers/admin/venues_controller_spec.rb`
- `spec/models/venue_spec.rb`

**Comment by Ana06** [comment]
There some files that are not tested yet, but we don't need an issue for any of them. Otherwise we will have many issue for increase rspec coverage.

You can work on this, but please don't open issues for that. :slightly_smiling_face:
