### ISSUE TITLE
Order .rubocop.yml

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1385]
Order the cops in .rubocop.yml by sections (Style, Rails, etc.) and also alphabetically inside every section. It should look similar to: https://github.com/bbatsov/rubocop/blob/master/config/default.yml (only the order, the cops enabled should remain the same)

Add a *short* description (one sentence) of the cop in a comment in the line before it. Some cops already have it, but there are many without it.

**Comment by siaw23** [comment]
on it... ;)
