### ISSUE TITLE
Create resource with empty used/total_quantity throws an exception

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1394]
**Issue**: Creating/Updating resource with empty `quantity` or `used` returns the following.

![error](https://cloud.githubusercontent.com/assets/14155445/24133851/41cc4378-0e26-11e7-897d-249b45864cc8.png)

**Possible Solution**: Add a validation for presence of `used` and `quantity` while creating/updating resource.

**Comment by agrim123** [comment]
@shlok007 I think we need to add check apart from adding validations for `used` and `quantity`. Something like this can be done
```
def used_less_than_quantity
  if !used.nil? && !quantity.nil?
    errors.add(:used, 'can not be higher than total quantity') unless used <= quantity
  end
end
```

**Comment by Ana06** [comment]
@shlok007 
> Possible Solution: Add a validation for presence of used and quantity while creating/updating resource.

and what if you don't know the total resources you have? I wouldn't make this compulsory.

@agrim123 I like your idea, feel free to open a PR. Although you can use `present?` instead of `! nil?` which is more readable and have `used <= quantity` in the same condition.

**Comment by agrim123** [comment]
@Ana06 I think the `quantity` input field should have a default value of 0 as `used` has. It is causing problems while rendering index page for resources, giving error 
`undefined method '-' for nil:NilClass`
because `quantity` is being assigned a nil value !

**Comment by shlok007** [comment]
Adding a default value wouldn't solve the problem of resources whose quantity are not yet know. Maybe we we could rewrite the helper function and in the views render something else ( like a  dash(`-`) ) when the `quantity` is not yet known? This could be a temporary solution until we come up with https://github.com/openSUSE/osem/issues/1284

Something in terms of:
![resource_index](https://cloud.githubusercontent.com/assets/14155445/24146021/d18010ca-0e59-11e7-8284-28587f7475fd.png)

**Comment by differentreality** [comment]
Maybe we should not be adding resources without a total number

**Comment by agrim123** [comment]
But `quantity_left_of` helper function is performing a arithmetic calculation so we need to give it an integer value.

**Comment by agrim123** [comment]
Maybe we can do something like this 
```
def used_less_than_quantity
  return (errors.add(:used, 'can not be higher than total quantity') unless used <= quantity) if used.present? && quantity.present?
end
```
@shlok007 @differentreality what say?

**Comment by Ana06** [comment]
@differentreality 

> Maybe we should not be adding resources without a total number

But you could want to register how many you used although you don't know/don't want to track the total amount. Why limiting it? :confused: 

@agrim123 
> Maybe we can do something like this

why `unless` and `if`? just use only one condition!

**Comment by agrim123** [comment]
@Ana06 I updated my comment. 
But still if a user submits an empty field then following error is raised 
`nil can't be coerced into Fixnum`
Need suggestions on that.
