### ISSUE TITLE
Add haml-lint

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1395]
Add https://github.com/brigade/haml-lint to the project

We should enable haml-lint in one PR, and then start enabling the rules in different PRs.

Related to: https://github.com/openSUSE/osem/issues/1326

**Comment by agrim123** [comment]
@Ana06 I am interested on working on this.

**Comment by Ana06** [comment]
Go ahead!

**Comment by agrim123** [comment]
We need to add .haml-lint.yml? I just ran a haml-lint and got warnings including LongLine(how much length should be kept for the same ).

**Comment by Ana06** [comment]
you should add haml-lint, disabled the errors and make haml-lint to run in travis. So basically make everything ready so we can progressively enable the rules and everything is already set up. :wink:

**Comment by Ana06** [comment]
This is block until https://github.com/openSUSE/osem/issues/1450 get merged, as haml-lint depends on Rubocop 0.48 and our current version is too old. Changing everything in one single PR is too much.

**Comment by differentreality** [comment]
@Ana06 can we close this?

**Comment by Ana06** [comment]
Sure! It was done in https://github.com/openSUSE/osem/pull/1469 :wink:
