### ISSUE TITLE
Missing Label and Unnecessary Fields in Edit Account Page

### ISSUE THREAD

**Issue by msdundar** [openSUSE/osem#1409]
Firstly, in the 'edit account' page (/accounts/edit), label for the 'email_public' field is missing. The default behavior of Rails brings 'Email public' string to the view, however this is not a clear explanation for users.

Secondly, OpenID instructions are rendered in the edit account page, even though there is no openid associated with the account.

**Comment by neilhalligan** [comment]
Ok if I take this on?

**Comment by neilhalligan** [comment]
Will do thanks
