### ISSUE TITLE
Name, Nickname and Username Are Confusing

### ISSUE THREAD

**Issue by msdundar** [openSUSE/osem#1410]
When registering to OSEM, the form consists a 'name' field, but there is no further explanation. What do we mean with name? First name, last name or full name?

Also it is very confusing to have two similar but separate fields named as 'username' and 'nickname'.  The username is located in the 'edit account' page and the nickname is located in 'edit profile' page. What is the difference between them? Why users need to generate three different names for their accounts?

**Comment by differentreality** [comment]
Name is the name of the person, we don't want to assume that everybody has a first name and last name, and that they want to give both to us. So there is a single field for people to fill out as they see fit.

Nickname is your identifier online, eg IRC. It is not the username for logging in to OSEM.

Does that make sense?
We can of course provide clarifications (hints) on the edit fields.

**Comment by msdundar** [comment]
Yes, probably it is better to provide hints for the fields.

**Comment by alator21** [comment]
Can i work on it?

**Comment by differentreality** [comment]
Go ahead @alator21 !

**Comment by alator21** [comment]
@differentreality Are the messages okay?Is the view okay?Show i create a hint button near each field instead? 
![screenshot from 2017-03-28 14-51-19](https://cloud.githubusercontent.com/assets/24437129/24403705/cc226a48-13c6-11e7-9b3d-df52f3482c28.png)

**Comment by alator21** [comment]
#1419

**Comment by AEtherC0r3** [comment]
This issue should be closed

**Comment by differentreality** [comment]
Fixed in #1419
