### ISSUE TITLE
No method error in Admin::Events#index

### ISSUE THREAD

**Issue by BelieveC** [openSUSE/osem#1411]
When you try to download XLS file from Admin::Events#index you get error as follows: 
Error: `undefined method 'reopen' for "streamed":String`

![screenshot from 2017-03-27 00-05-23](https://cloud.githubusercontent.com/assets/14261624/24335078/63c78862-1294-11e7-91be-456d20a28f45.png)

Ref: [Link](https://github.com/straydogstudio/axlsx_rails/issues/18#issuecomment-132234648)

**Comment by BelieveC** [comment]
On it!

**Comment by AEtherC0r3** [comment]
This seems to have been fixed in master

**Comment by differentreality** [comment]
Fixed in https://github.com/openSUSE/osem/commit/ebe1ca374da3366e29efe1e63a65d618cdfe9fe5
