### ISSUE TITLE
Enable Style/NegatedIf Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1415]
Enable Style/NegatedIf Rubocop cop: https://rubocop.readthedocs.io/en/latest/cops_style/#stylenegatedif

**Comment by BelieveC** [comment]
On it!

**Comment by differentreality** [comment]
@BelieveC you currently have 5 pending open PRs with OSEM. I would rather you focus on them and how you can enhance those things you are already working on, work on them more, and leave the new junior jobs open for other people that want to get to know OSEM.

**Comment by BelieveC** [comment]
@differentreality Alright! :+1:

**Comment by BelieveC** [comment]
Anyone who is interested can work on this!

**Comment by sunny-b** [comment]
Can I take a stab at this one? Haven't contributed before and this seems simple enough.

**Comment by lagartoflojo** [comment]
@sunny-b go ahead :)
