### ISSUE TITLE
Enable Style/ZeroLengthPredicate Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1416]
Enable Style/ZeroLengthPredicate Rubocop cop: https://rubocop.readthedocs.io/en/latest/cops_style/#stylezerolengthpredicate

**Comment by BelieveC** [comment]
On it!

**Comment by differentreality** [comment]
@BelieveC you currently have 5 pending open PRs with OSEM. I would rather you focus on them and how you can enhance those things you are already working on, work on them more, and leave the new junior jobs open for other people that want to get to know OSEM.

**Comment by BelieveC** [comment]
@differentreality, Sorry, I opened a PR before I read your comment. I focus them too, sometimes it takes time to get my PR reviewed therefore working on different PR parallelly. Won't work on more than 5 PR concurrently. :+1:
