### ISSUE TITLE
Enable Style/Tab Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1428]
Enable Style/Tab Rubocop cop:
https://rubocop.readthedocs.io/en/latest/cops_style/#styletab :bowtie:

**Comment by neilhalligan** [comment]
I would like to take this on. Is it available?

**Comment by codyborders** [comment]
@neilhalligan I am working on it -- sorry I didn't post a comment claiming it!

**Comment by Ana06** [comment]
@neilhalligan what about issue https://github.com/openSUSE/osem/issues/1437?? It is quite similar to this one. :slightly_smiling_face: 

If so please add a comment in the issue so everybody is aware you are working on it :wink:
