### ISSUE TITLE
Enable Style/DotPosition Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1431]
Enable Style/DotPosition Rubocop cop:
https://rubocop.readthedocs.io/en/latest/cops_style/#styledotposition

**Comment by sunny-b** [comment]
I can do this one

**Comment by sunny-b** [comment]
So I've enabled the cop and ran autocorrect. There is one small bump. Line 65 in app/models/cfp.rb is now 209 characters long -- 1 character longer than your specified max length.

Should I leave it like that and complete the PR or change the maxlength cop to 209?

**Comment by Ana06** [comment]
@sunny-b You should fix the offense but without changing the maxlength. You can write the line in several lines instead or something like that.

**Comment by sunny-b** [comment]
Oh yeah, duh haha. Will do
