### ISSUE TITLE
Permission to access admin/schedules by cfp

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1432]
Currently only users with `organizer` role can manage admin/schedules as specified in https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L160 .

Users with role `cfp` handles the events in a conference so giving them access to schedules as well is something that could be considered .

**Comment by Ana06** [comment]
I would say that user with `cfp` role don't need to access the schedule. :thinking: 

@differentreality what do you think?

**Comment by differentreality** [comment]
CfP team is exactly who should be handling the schedule. They handle the call for papers, that is not just setting the dates for the cfp, it's taking care of the conference's program, that includes assigning tracks/difficulty levels, accepting/rejecting proposals, and coming up with the conference's schedule.

**Comment by nasia-sam** [comment]
I could work on it :)

**Comment by differentreality** [comment]
@nasia-sam you can go ahead, I don't think anything else before you do, @Ana06 ?

**Comment by Ana06** [comment]
yes, go ahead! :wink:
