### ISSUE TITLE
Missing description field in schedule xml 

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#1435]
The app giggity complains about the xml returned by our osem installation. 

The problem is that the xml doesn't have a description field.

**Comment by Ana06** [comment]
But we have never pretend OSEM to work with [Gigity](https://play.google.com/store/apps/details?id=net.gaast.giggity), have we? There may be more things that doesn't work with it. Do we want to have the field abstract and description in the `xml` with both the abstract? :thinking: 

There is a related issue here: https://github.com/openSUSE/osem/issues/1049

@hennevogel, @differentreality, @ChrisBr, @eug3nix opinions?

**Comment by differentreality** [comment]
We didn't shout it out loud, but when we implemented the XML export, we did it with the structure that was useful (useful to apps like Gigity, and to the video team). So I would say that we should provide a valid XML export to be used in android apps and to make the life of video people easier.

I am indeed wondering myself why we need to have abstract shown twice. @davidsf can you help us understand why the description is necessary and why it should hold the same information as abstract field?

**Comment by Ana06** [comment]
@differentreality 

> I am indeed wondering myself why we need to have abstract shown twice. @davidsf can you help us understand why the description is necessary and why it should hold the same information as abstract field?

I guess that the abstract field is called description in Gigity. So I would say that for Gigity it would be fine if we remove abstract and add description. The problem is that this may not work for other apps.

**Comment by differentreality** [comment]
If that's the case now (wasn't last year) we should just add the field description with the abstract content.

**Comment by differentreality** [comment]
@davidsf ping

**Comment by davidsf** [comment]
Sorry for the delay,

With the patch, gigity works great for us. So, just adding the abstract content as another description field it's ok.

**Comment by differentreality** [comment]
@davidsf what I was asking is do we need both fields? Or just description? Do you know if this is a new requirement of gigity?

**Comment by davidsf** [comment]
A quick test show me that with only the description field gigity workf s ok. I don't know if this is a new requirement, In giggity readme it says that supports  xcal/Pentabarf/frab/wafer formats. What is the format of osem xml ?

**Comment by differentreality** [comment]
It's frab format https://github.com/openSUSE/osem/issues/733

**Comment by sleep-walker** [comment]
I can confirm that giggity can't parse exported schedules.
