### ISSUE TITLE
Enable Lint/DuplicatedKey Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1437]
Enable Lint/DuplicatedKey Rubocop cop:
https://rubocop.readthedocs.io/en/latest/cops_lint/#lintduplicatedkey

**Comment by Ana06** [comment]
@neilhalligan do you want to do this? :slightly_smiling_face:

**Comment by neilhalligan** [comment]
Hi Ana06, Ill take this thanks!
