### ISSUE TITLE
Splashpage show and edit pages should look similar

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1439]
We should make the Splashpage show and edit pages to look similar. Order the items that can be in the Splashpage the same. And also there are two items missed in the show page.

Splashpage edit page:

![image](https://cloud.githubusercontent.com/assets/16052290/24703555/f1841f1e-1a03-11e7-9009-2d5547db8bf5.png)

Splashpage show page:

![image](https://cloud.githubusercontent.com/assets/16052290/24703595/213b692e-1a04-11e7-93cf-f5f3501fe64b.png)

**Comment by nasia-sam** [comment]
Hello, could I work on it ?

**Comment by nasia-sam** [comment]
@Ana06 Actually, I've done some work. Should I make a pull request ? 

![screenshot from 2017-04-05 19-04-37hg](https://cloud.githubusercontent.com/assets/24506693/24715834/9ba428d2-1a35-11e7-8a03-3515e028515e.png)

**Comment by Ana06** [comment]
@nasia-sam sorry I didn't read it until now. The PR is already merged, so I'll close this :wink:
