### ISSUE TITLE
Schedule shows first speaker image twice

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1454]
After introducing multiple speakers per talk #1278, the schedule shows the image of the first speaker twice. This is happening even if the speaker is not the submitter of the proposal.

![screenshot from 2017-04-14 12-10-26](https://cloud.githubusercontent.com/assets/4322737/25041794/5428f3a6-211b-11e7-9d79-b702c286e907.png)

**Comment by nikhilgupta1211** [comment]
I am on it :)
