### ISSUE TITLE
Make each Lodging Card in the Splashpage of equal height w.r.t to its row

### ISSUE THREAD

**Issue by BelieveC** [openSUSE/osem#1456]
Lodging Cards in the Splashpage have different height according to its content.

![screenshot from 2017-04-14 19-14-26](https://cloud.githubusercontent.com/assets/14261624/25045399/c09abb04-2149-11e7-8f6c-cff31c0886c6.png)

We can improve user experience by making Height of each card in the single row of the same height as anyway we are starting next lodging card on next row.

This can be easily done using Flexbox. Ref: [Link](https://clearleft.com/posts/270).

**Comment by divyanshumehta** [comment]
I would like to work on it
