### ISSUE TITLE
Add Link to Lodging(Where to stay part of Splashpage) in the Navbar of Splashpage's Navbar 

### ISSUE THREAD

**Issue by BelieveC** [openSUSE/osem#1458]
We don't have link to `Lodging(Where to stay part of Splashpage)` in `splashpage` navbar

- Splashpage Navbar: 

![navbar](https://cloud.githubusercontent.com/assets/14261624/25045798/9dcff506-214b-11e7-9721-01dc2fbab8b9.png)

- Splashpage Lodging part:

![screenshot from 2017-04-14 19-24-49](https://cloud.githubusercontent.com/assets/14261624/25045812/b1a5f77e-214b-11e7-9eb9-906f085d2d38.png)

I think we should add a link to Lodging in the Navbar!

**Comment by divyanshumehta** [comment]
I would like to work on this issue.
