### ISSUE TITLE
The field "Name" in the sign up form is required

### ISSUE THREAD

**Issue by AEtherC0r3** [openSUSE/osem#1466]
In the User model the presence of :name is not validated, and in the signup form there is no asterisk indicating that the "Name" field is required. Yet, in  https://github.com/openSUSE/osem/blob/master/app/views/devise/registrations/new.html.haml#L12 we can see that the attribute "required" is set to true, which results in a message nagging anyone who wants to leave that field empty.
![2017-04-23 11-42-57](https://cloud.githubusercontent.com/assets/3638310/25312217/403db176-281c-11e7-9cdb-974b004e3ab7.png)

If this is confirmed as a bug I will fix it.

**Comment by differentreality** [comment]
Good catch! Isn't this a duplicate of #1406 though?

**Comment by AEtherC0r3** [comment]
Closed as duplicate of #1406
