### ISSUE TITLE
.rubocop_todo.yml should exclude the application helper

### ISSUE THREAD

**Issue by AEtherC0r3** [openSUSE/osem#1470]
In #1451 the line that excludes the application helper was removed (https://github.com/openSUSE/osem/pull/1451/files#diff-74423563ec7c74f4cb7f74689b49e7c1L45)

This change causes rubocop on travis to fail with `app/helpers/application_helper.rb:1:1: C: Metrics/ModuleLength: Module has too many lines. [478/472]`

**Comment by Ana06** [comment]
Rubocop in master is working, see the last build: https://travis-ci.org/openSUSE/osem/builds/225553409

In #1451 the `todo` file was generated again after update Rubocop. Application helper got removed but the number of lines increased.

**Comment by AEtherC0r3** [comment]
The number 472 was deliberately chosen in order for the rule to cop without the application_helper excluded. This implies that if someone adds even a single line of code then the cop will fail. As far as I know the purpose of rubocop is to enforce best coding practices. Therefore, I don't think that changing the rules to fit our case is the "proper" thing to do. So I think we should leave the exclusion of application helper file in rubocop_todo.yml and revert the maximum module length to 256.

**Comment by differentreality** [comment]
#1335 will solve this. Indeed the file should have stayed excluded in rubocop.
