### ISSUE TITLE
frab XML view: dates not sorted

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#1474]
The current export is: ```<day date="2017-05-27" index="1">, <day date="2017-05-26" index="2">, <day date="2017-05-28" index="3">```

This is obviously wrong. My guess is that
https://github.com/openSUSE/osem/blob/master/app/views/schedules/show.xml.haml#L12
is the culprit and that sorting the keys would fix it.

**Comment by differentreality** [comment]
This is specific to events.opensuse.org and not the current branch of OSEM.

**Comment by danimo** [comment]
If it's fixed it would be nice to learn which commit fixes the issue so we can backport it.
