### ISSUE TITLE
An admin shouldn't be able to submit a proposal when the submission period is closed

### ISSUE THREAD

**Issue by AEtherC0r3** [openSUSE/osem#1475]
If the cfp for a conference exists then an admin can submit a proposal for that conference, even when the submission period isn't open

Steps to reproduce:
1. Sign in with an admin account
2. Select a conference
3. Create cfp with dates in the future
4. Go to root_path
5. Press the 'Submit Proposal' button
6. Create a proposal

The same happens if the cfp dates are in the past

**Comment by differentreality** [comment]
An admin can do everything, and should be able to bypass things other users cannot access.
An admin, or an organizer, can (and should be able to) submit events like lunch breaks, or a last minute competition session, or extra open slots for BoFs.
These things do not fall into the rules of CfP, ie don't need voting or approval, and are not tightly related to the job the CfP team.
