### ISSUE TITLE
Show proposals to all speakers, not just submitter

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1482]
Users are able to see their submissions, but that only works if the user is the submitter. It should be showing the proposals where the user is just the speaker as well.

**Comment by divyanshumehta** [comment]
ok on it

**Comment by divyanshumehta** [comment]
So in the index view of the conferences when the user clicks `Submit Proposals` the user must see all the existing proposals also?

**Comment by divyanshumehta** [comment]
ping @differentreality

**Comment by namangupta01** [comment]
Is anybody working on it?

**Comment by differentreality** [comment]
Doesn't look like it

**Comment by namangupta01** [comment]
@differentreality Does speaker only able to see the proposals or they can even modify it ?

**Comment by differentreality** [comment]
I'd say that all speakers of the event should be able to see the event (index and show actions), as well as edit it, and add commercials for it, so that:

- Each speaker might want to add a piece of text in the event abstract
- Each speaker should upload slides, and add a commercial for them

**Comment by namangupta01** [comment]
@differentreality All the things listed by you is already taken care in pr #1809. Please have a look.
