### ISSUE TITLE
/accounts/sign_out - page doesn't exist

### ISSUE THREAD

**Issue by kallewa** [openSUSE/osem#1485]
clicking "Sign out" link 
launches 
... /accounts/sign_out

and an error message 
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

**Comment by kallewa** [comment]
from /var/log/apache2/error.log
App 27845 stdout: Started GET "/accounts/sign_out" at 2017-05-11 04:36:36 +0000
App 27845 stdout: ActionController::RoutingError (No route matches [GET] "/accounts/sign_out"):

**Comment by BelieveC** [comment]
> App 27845 stdout: ActionController::RoutingError (No route matches [GET] "/accounts/sign_out"):

@kallewa, I think above log from `/var/log/apache2/error.log` is itself a reason for message that you are getting error message as when you do `/accounts/sign_out` as per Rails conventions we use `DELETE` http verb instead of `GET`. It is trivial no route will match for `/accounts/sign_out` using `GET`. I don't think this is an problem. :wink:

**Comment by kallewa** [comment]
`/accounts/sign_out` is an operation called by OSEM. OSEM is wanting to `GET` something from the server, not `DELETE`anything. I didn't change any OSEM code; this is baked in.

**Comment by kallewa** [comment]
You're correct; `DELETE` it is.

Page Source
```
<ul class="dropdown-menu">
<snip>
<ul class="dropdown-menu">
<snip>
<li>
<a rel="nofollow" data-method="delete" href="/accounts/sign_out">
<span class="fa fa-minus"></span>
Sign out
</a>
</li>
```

**Comment by differentreality** [comment]
@kallewa is it possible you tried to open the sign_out link in a new tab? That can cause the action to ge GET instead of DELETE

**Comment by kallewa** [comment]
PEBKAC. Since posting this issue, I've already learned a lot, such as there's still more to learn. 
The INSTALL instructions suggest looking on the web for how to deploy rails apps. It's clear that more looking and learning is in order. I'm closing this issue in favor of following the INSTALL instructions.
