### ISSUE TITLE
Have more than one speaker per talk

### ISSUE THREAD

**Issue by TheRealBro** [openSUSE/osem#1496]
at the moment OSEM generates the following file: 
https://events.opensuse.org/conference/oSC17/schedule.xml
which is used for the exports to media.ccc.de and youtube after processing the videos.
Also the metadata are automatically added from this schedule file.

Unfortunately - atm - OSEM has only the speaker who requested the talk as "speaker" in the schedule and in the system - examples see here:
https://events.opensuse.org/conference/oSC17/program/proposal/1350 - Abhishek is missing
https://events.opensuse.org/conference/oSC17/program/proposal/1336 - Nirmoy is missing

So please allow more than one speaker to be added to a talk - otherwise the generation of correct metadata for video files and all other references to schedule will fail.

**Comment by differentreality** [comment]
This has already been implemented in OSEM (it is not deployed to events.opensuse.org though)
https://github.com/openSUSE/osem/pull/1278
