### ISSUE TITLE
Enable Style/SpaceInsideBrackets Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1497]
Enable Style/SpaceInsideBrackets Rubocop cop
https://rubocop.readthedocs.io/en/latest/cops_style/#stylespaceinsidebrackets

:bowtie:

**Comment by divyanshumehta** [comment]
on it :+1:

**Comment by divyanshumehta** [comment]
@Ana06 shouldn't this issue be closed.

**Comment by Ana06** [comment]
@divyanshumehta yes! :wink:

BTW, do u know u can mention the issue u are working on in your commit and then the issue is closed automatically when merging? https://help.github.com/articles/closing-issues-using-keywords/
