### ISSUE TITLE
Comment Notifications

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#15]
We have comments on events but no notifications for new comments.

**Comment by raluka** [comment]
What do you mean by notification? Should we send e-mails, post to social media, or display messages for logged in users?

**Comment by hennevogel** [comment]
Email notifications would be what we are looking for. Whenever a **Comment** is created, send an email to all **User** that have the **Role** *organizer* or *cfp* for the **Conference** the **Event** is for. The email should  contain the text of the **Comment** and the link to the **Event**.

Additionally if you find the time there also should be a indication inside the app which events have comments with created_at newer then User.last_sign_in_at.

**Comment by differentreality** [comment]
Done? :)

**Comment by raluka** [comment]
I think so, we have a merged pull request 
https://github.com/raluka/osem/pull/3

**Comment by differentreality** [comment]
https://github.com/openSUSE/osem/pull/699
