### ISSUE TITLE
Provide API to submit oembed commercials

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#1508]
Out video releasing pipeline can automatically submit the YouTube URL of a talk at release time. It knows the ID of the event as well as the URL YouTube is going to publish the video under.

What is needed is an (authenticated) API that the video publisher can call. It should accept the talk ID and the URL of the video. Authentication could happen via a simple token.

**Comment by thomic** [comment]
@danimo this relates #1492 ... either close or merge issue to this one here

**Comment by danimo** [comment]
Duplicate of #1492
