### ISSUE TITLE
Add event button does not appear in Events section

### ISSUE THREAD

**Issue by Andrew908** [openSUSE/osem#1511]
![error](https://cloud.githubusercontent.com/assets/5663144/26643972/76f4885e-4633-11e7-9df2-d59d0d09f5c5.JPG)

As you can see from the print screen I can't see the button to add an event. the version for ruby i tried 3.4.1 2.3.4 and 2.2.7 same result. I also tried with rails 5 and 4. No change. 

Can you please tell me how I can make the button appear. 
I am using Linux Centos 7 with Apache. 

Regards,

**Comment by differentreality** [comment]
Hi @Andrew908, your ruby and rails versions are not relevant to this.

In order for proposals/events to show up on the table, users must first submit them, eg. http://demo.osem.io/conferences/osemdemo/program/proposals supposing cfp is open. 

Alternatively an organizer can add an event from the admin panel (from where you are showing on your screenshot), but you probably need to pull the latest changes of our master to enable this feature. It was introduced in https://github.com/openSUSE/osem/commit/c31fea71a8d65ce406dc0898ffde07516b868e83

What's the latest commit you see on your `git log`?

**Comment by differentreality** [comment]
@Andrew908 I will close this as it does not appear to be a bug with OSEM itself. Feel free to reach out again, if you are still unable to figure things out. 
You can also find us on IRC (Freenode server #osem).
