### ISSUE TITLE
Introduce new role 'organization admin' to manage organizations

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1514]
Related PR: #1538
The dotted/dashed line represents the permission for specific organization/conference the user belongs to whereas solid lines represents permission to create/manage all.
 
![organization_admin_role](https://cloud.githubusercontent.com/assets/14155445/26739308/ec942bca-47ee-11e7-8db3-a06b003388b7.png)

**Comment by shlok007** [comment]
Since, `organization admin` will be presiding over all the conferences and `organizers` are restricted to their conference only, it makes sense __not__ to give permission to `organizers` to create new conference anymore. 

A conference then, can __only__ be created by the site admin and the organization admin in the hosted version.

**Comment by lagartoflojo** [comment]
I think, at least for now, there should only be an arrow from Site Admin -> Create organization, since that's the only thing we're allowing, right?

**Comment by lagartoflojo** [comment]
As for disallowing `organizers` from creating conferences, that probably makes sense.
So does the `organization admin` choose who the `organizer`s for each conference are?

**Comment by lagartoflojo** [comment]
Can you please explain what the different lines (solid, dashed, dotted) mean?

**Comment by shlok007** [comment]
Since, we have made a few changes now, I'll update the diagram. The dotted/dashed line represents the permission for specific organization/conference the user belongs to whereas solid lines represents permission to create/manage all. 

> So does the organization admin choose who the organizers for each conference are?

`organization admin` behave as just as organizers do for all it's conferences. So, yes.

There can be two possibilities here:

- Give permission to `organization admins` to manage all conferences that belongs to his/her organization so when a new conference is created, all the `organization admins` will be able to manage all parts of that conference exactly as a `organizer` can. They can add an organizer( or any other role ) to its conference from the Roles section in the admin sidebar for a conference.

- As soon as an `organization admin` creates a new conference, all the `organization admins` of that organization will be assigned the  `organizer` role of that conference. In this way we wouldn't have to explicitly define permissions for `organization admin` to manage parts of the conferences since, we already have that set up for `organizers`.

No matter what we decide on, the permissions* for the rest of the roles won't be affected so they will behave as it is. So, yes `organizers` will be able to add more `organizers` just like they do now. 

*The only change will be that organizers will not be able to create conferences now!

**Comment by lagartoflojo** [comment]
I think option 1. is better - organization admins have full control of everything under their organization.
In case 2, if at some point, you want to "kick out" an organization admin from the organization, it will be much more work, since you'll have to remove them from every conference separately. I think there's more code (hence, increased possibilities of bugs) in this second scenario as well.

**Comment by shlok007** [comment]
Closed via: #1538
