### ISSUE TITLE
Ability to select organizations while creating a conference

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1524]
Reference #1637

**Comment by lagartoflojo** [comment]
Please link the corresponding PR :)

**Comment by lagartoflojo** [comment]
Ah, I see it's not "In Review" anymore.
When should we do this? It sounds like it should be done before the domain name stuff.

**Comment by shlok007** [comment]
Yeah we did revert the change in the first merged PR https://github.com/openSUSE/osem/pull/1517/commits/cce3ff7aea589d18d4da96acda3341afbaf024a3#diff-168f74a68f9e23df7672afdf50ff0da9R10 . I'll add this again.
