### ISSUE TITLE
E-mail not sent when user registered for a conference

### ISSUE THREAD

**Issue by Andrew908** [openSUSE/osem#1525]
Good afternoon, 

First, Thank you for your answer. I was able to resolve the issue of the previous ticket. 
Second. I check the box: Send an email when the user registers for the conference? but the user still doesn't receive an e-mail when he is registering to a conference. The users receives e-mails when he signs up, but not when he registers for the conference. 

Third. Would it be possible to implement an option to send emails of confirmation after a participant registers for an event ? 

Fourth. Would it be possible to add the hour from which to which the event will take place ( Now it only shows the date in the full schedule view)? 

Thank you very much for your answer and time. 

Regards,

**Comment by differentreality** [comment]
Hey @Andrew908, have you setup the email_settings of the conference? 
You need to check the box, as shown in the screenshot, and add data for subject & body of the email.

![screenshot from 2017-06-06 19-10-39](https://user-images.githubusercontent.com/4322737/26839501-dfde301a-4aeb-11e7-8944-475a6ad2e95c.png)

Also keep in mind
https://github.com/openSUSE/osem/blob/master/INSTALL.m

**Comment by Andrew908** [comment]
As you can see from the print screen I have done this. And the e-mail is setup correctly otherwise I would not receive the confirmation e-mail. 

Regards, 
![error](https://user-images.githubusercontent.com/5663144/26842237-628c85c0-4aec-11e7-867a-a427d7a2b023.JPG)

**Comment by differentreality** [comment]
The link I pasted was broken in the previous comment, are you running `bundle exec rake jobs:work`?

**Comment by Andrew908** [comment]
I get the following error message when I run that command: 

rake aborted!
NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration:0x007f822a42a820>
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/railtie/configuration.rb:95:in `method_missing'
/var/www/html/osem/config/environments/development.rb:5:in `block in <top (required)>'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:182:in `configure'
/var/www/html/osem/config/environments/development.rb:1:in `<top (required)>'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `each'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/var/www/html/osem/config/environment.rb:25:in `<top (required)>'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/var/www/html/osem/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/root/.rbenv/versions/2.2.7/bin/bundle:23:in `load'
/root/.rbenv/versions/2.2.7/bin/bundle:23:in `<main>'
Tasks: TOP => jobs:work => jobs:environment_options => environment
(See full trace by running task with --trace)

Regards,

**Comment by differentreality** [comment]
What's the exact command you are running? Is this your production environment? Perhaps you need to specify RAILS_ENV=production bundle exec ... 

Why don't you join our IRC channel #osem on freenode?
Also keep in mind that by the end of the summer we will have implemented a new feature where you can use our hosted OSEM to create your conference. 

Regarding your other questions for registering to events, they make sense and I would personally like to see them implemented. However, I doubt we will find time to work on them in the next months.

**Comment by Andrew908** [comment]
Thank you for your answer and your time again. Indeed I was missing the production enviroment. But now I get a strange error that I don't understand why:

2017-06-07T07:35:34+0200: [Worker(host:v-host pid:11809)] Starting job worker
[Worker(host:v-inea-osem01 pid:11809)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=1) RUNNING
2017-06-07T07:35:34+0200: [Worker(host:v-host pid:11809)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=1) RUNNING
[ActiveJob] [ActionMailer::DeliveryJob] [72c6266a-cead-4bc1-8983-9535bb8d0ac5] Performing ActionMailer::DeliveryJob from DelayedJob(mailers) with arguments: "Mailbot", "registration_mail", "deliver_now", gid://osem/Conference/1, gid://osm/User/6
[ActiveJob] [ActionMailer::DeliveryJob] [72c6266a-cead-4bc1-8983-9535bb8d0ac5] Performed ActionMailer::DeliveryJob from DelayedJob(mailers) in 1631.13ms
[Worker(host:v-host pid:11809)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=1) FAILED (0 prior attempts) with ArgumentError: An SMTP From address is required to send a message. Set the message smtp_envelope_fro, return_path, sender, or from address.

But the from address is already set in the .env.production file and it works for confirmation e-mails. Is there any other place in which I need to specify the from address. 

Unfortunately, I can't use the hosted version as I work for an institution and the information is not for the public but for internal use only. 

Thank you and have a nice day.

**Comment by differentreality** [comment]
It would be extremely helpful if you were also posting the actual command you run. 

Can you confirm you have the following lines?
https://github.com/openSUSE/osem/blob/master/config/environments/production.rb#L70-L82

**Comment by Andrew908** [comment]
this is the command: bundle exec rake jobs:work RAILS_ENV=production.

Yes I can confirm that some of them are enabled, others I have commented as they are not relevant for my mail server. 

REgards,

**Comment by differentreality** [comment]
@Andrew908 re-reading your error it seems that jobs start just fine, and then you try to send an email which raises the error ` An SMTP From address is required to send a message. `

So perhaps you haven't set the email it requires?
https://github.com/openSUSE/osem/blob/master/app/mailers/mailbot.rb#L4

Which gets set from the contact information of your conference
http://demo.osem.io/admin/conferences/osemdemo/contact/edit

**Comment by differentreality** [comment]
Due to the inactivity of the thread, I am assuming this was solved and it was not a bug in OSEM.
