### ISSUE TITLE
Refactor ticket purchases

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1527]
1. The ticket_purchases controller is not authorizing TicketPurchase
https://github.com/openSUSE/osem/blob/master/app/controllers/ticket_purchases_controller.rb

2. Theoretically, a ticked_purchase can occur at any time (after the conference, after registration period is over, etc), as there is no ability limiting it

3. Ticket graphs over time, in admin/conferences#index and admin/conferences#show, show float numbers for the number of tickets sold, obviously we can't have sold 2.5 tickets. 

![screenshot from 2017-06-06 18-16-10](https://user-images.githubusercontent.com/4322737/26836733-4f401f34-4ae4-11e7-83b6-fabb516392f3.png)

4. At the ticket turnover distribution graph in admin/tickets#index, the amount of the turnover could be formatted into a more humanly readable way

![screenshot from 2017-06-06 19-07-03](https://user-images.githubusercontent.com/4322737/26839331-68040a9c-4aeb-11e7-9ea6-347d107166ee.png)

**Comment by Ana06** [comment]
@siddhantbajaj we are changing things here as part of your GSoC project. You also plan to improve the statistics, so I would say you would like to take a look at this issue. :wink:

**Comment by siddhantbajaj** [comment]
Yes definitely. 👍

**Comment by svbeon** [comment]
Stats are horrible on mobile, they resize and grow extremely large when scrolling, the other day I got a diagram with the y labels 0.0001, 0.0002, 0.0003, 0.0004... All the way through 17.0000

**Comment by differentreality** [comment]
Hi @svbeon, the issue on mobile devices is being tracked in issue https://github.com/openSUSE/osem/issues/579 and worked on in PR https://github.com/openSUSE/osem/pull/1269
