### ISSUE TITLE
Separate test suit

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1529]
Run the test suites separately.

Run linters (Rubocop and haml-lint) and RSpec in different jobs in Travis.

**Comment by harpojaeger** [comment]
I'd be happy to take this on.  Here's what I see in .travis.yml now:
```
script:
  - 'bundle exec rubocop -Dc .rubocop.yml'
  - 'bundle exec haml-lint app/views'
  - 'bundle exec rspec --color --format documentation'
```

Am I right that what's needed here is to refactor .travis.yml roughly according to [these specs](https://docs.travis-ci.com/user/speeding-up-the-build/)?

**Comment by Ana06** [comment]
@harpojaeger great! :+1: 

Travis should run rubocop and haml-lint (linter cop) together and rspec separately. so basically two `env`:

```
TEST_SUITE=rspec
TEST_SUITE=linters
```

**Comment by harpojaeger** [comment]
Okay, looks good.  However, I forked the repo and Travis is failing right off the bat:
```
...
Fetching carrierwave-bombshelter 0.1.1.6
Installing acts_as_list 0.4.0
Installing carrierwave-bombshelter 0.1.1.6
Downloading axlsx-2.0.1 revealed dependencies not in the API or the lockfile
(rubyzip (~> 1.0.0)).
Either installing with `--full-index` or running `bundle update axlsx` should
fix the problem.
The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed 3 times.
The command "bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}" failed and exited with 34 during .
Your build has been stopped.
```

I want to make sure Travis is working *before* I start messing with the settings so I don't compound things further.

**Comment by mdeniz** [comment]
@harpojaeger I already was working on that before  @Ana06 created this issue... BTW I already fixed that failure of the dependencies for axlsx. 😄

**Comment by Ana06** [comment]
@harpojaeger sorry for the misunderstanding :confounded:

**Comment by harpojaeger** [comment]
NP!
