### ISSUE TITLE
Worklow to assign organization admins to organizations

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1532]
Being resolved in #1571 
Since, only site admins have the ability to create organizations for now. Site admins should be able to assign organization admins of an organization. 

I propose the following workflow:

A new button in organization#index to manage organization admin of a particular organization.
![screenshot_20170608_043224](https://user-images.githubusercontent.com/14155445/26905327-6e8f5a28-4c04-11e7-9457-ae004ae82eac.png)

The role views for each organization to assign organization admin just like roles for conferences.
![screenshot_20170608_043556](https://user-images.githubusercontent.com/14155445/26905332-74551b82-4c04-11e7-8103-cc8ff1ec242c.png)

**Comment by shlok007** [comment]
@lagartoflojo please do let me know if this looks good..

**Comment by lagartoflojo** [comment]
Do we need to display the `id` field in the users table?

**Comment by shlok007** [comment]
Sorry, I just realized this. I'll try to figure out why we why we have that in `admin/conference/roles` . If there is no particular reason, we can get rid of it!

**Comment by differentreality** [comment]
No direct reason, just so we know who is who, in case something goes wrong / we need sth, we have a user id to refer to (which is easier than an email or a name, etc).

**Comment by lagartoflojo** [comment]
Ok, I think I would just get rid of the ID column, since it doesn't really provide anything too useful.
Also, what's the first column with the yes/not toggle?

**Comment by shlok007** [comment]
Toggling it to 'No' removes the assigned role.

**Comment by lagartoflojo** [comment]
Is this list supposed to show ONLY organization admins?

**Comment by shlok007** [comment]
Yes, because the rest of the roles are conference specific and belongs to a particular conference only, they can be viewed/altered in `admin/conferences/#{short_title}/roles` ( just like they are being now. )

**Comment by lagartoflojo** [comment]
But then, by using the switch, as soon as it goes to "OFF", the user should disappear from the list, since this list is only for org admins...
Therefore it doesn't seem to me that the switch is the correct UI element to use here.

**Comment by shlok007** [comment]
Okay! That's definitely not something we want.

What about something like this instead?
![screenshot_20170626_183307](https://user-images.githubusercontent.com/14155445/27540800-08d03e10-5a9f-11e7-8603-e4ad064675b5.png)

**Comment by lagartoflojo** [comment]
That looks much better.
I don't think the "view profile" button is needed. Wouldn't just clicking on the user's name take you to their profile?
And I'd label the button "Remove from organization admins" so it's more explicit

**Comment by lagartoflojo** [comment]
Does the "edit" button on the top right corner do anything?

**Comment by shlok007** [comment]
>I don't think the "view profile" button is needed. Wouldn't just clicking on the user's name take you to their profile?
And I'd label the button "Remove from organization admins" so it's more explicit

Sure!
>Does the "edit" button on the top right corner do anything?

I used the existing view for conference/roles to create this mockup. They have the 'edit' button to edit the _description_ of the roles. I suggest we keep it for `organization admins` as well. This will do no harm and only increase the level of customization we have.

**Comment by lagartoflojo** [comment]
hehe, when someone says "more customization", I hear "more complexity" 😛
I leave it up to you, I just didn't know what it was there for :)

**Comment by shlok007** [comment]
I gave it some thought again and it doesn't make sense to allow editing `Organization Admin` role name for somebody because that's exactly what the role is doing for every organization. Which might not be the case for roles like `info desk` or `volunteers coordinator` in conferences.
