### ISSUE TITLE
Enable Rails/FindEach Rubocop cop

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1535]
Enable Rails/FindEach Rubocop cop
https://rubocop.readthedocs.io/en/latest/cops_rails/#railsfindeach

**Comment by dPliakos** [comment]
Hello! May I give a try to this?

**Comment by Ana06** [comment]
Sure! :+1: 
You should also remove it from the `.rubocop-todo.yml` file as this one overwrite what is inside the `.rubocop.yml`. :wink:
