### ISSUE TITLE
Define separate abilities for controllers in admin namespace

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1552]
Since, we are using separate controllers for administrators and non- administrators, there comes a situation when we want to allow access to actions in the controller without namespace and restrict access to the same actions present in the admin namespace. 

For example: Allow access to `edit` action in the `UsersController` but restrict access to `edit` action in the `Admin::UsersController`

It makes sense to have a separate model to handle abilities for the controllers present inside the admin namespace.

The documentation in cancancan covering the above situation:
https://github.com/ryanb/cancan/wiki/Admin-Namespace

**Comment by differentreality** [comment]
We could do that, I'd work with you on this. However is this something you want to implement for/during your GSoC project?

**Comment by shlok007** [comment]
Yes, I'll be happy to take this as well, thank you! :v:
