### ISSUE TITLE
Duplicate label attribute in admin/targets/_form

### ISSUE THREAD

**Issue by AEtherC0r3** [openSUSE/osem#1555]
One of the labels should be removed https://github.com/openSUSE/osem/blob/master/app/views/admin/targets/_form.html.haml#L13

**Comment by LiamElliott** [comment]
Can I complete this? Good for a first contribution.

**Comment by differentreality** [comment]
Hi @LiamElliott, absolutely give it a go!

**Comment by differentreality** [comment]
Hey @LiamElliott, have you started working on this already?

**Comment by differentreality** [comment]
Closed in https://github.com/openSUSE/osem/pull/1567
