### ISSUE TITLE
[production][subscriptions#create] ActiveRecord::RecordInvalid: Validation failed: User has already been taken, User already subscri...

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1589]
subscriptions#create threw this 0 times
<pre>
ActiveRecord::RecordInvalid: Validation failed: User has already been taken, User already subscribed!
</pre>
[https://events.opensuse.org/conference/oS3DW/subscriptions](https://events.opensuse.org/conference/oS3DW/subscriptions)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/596487efa8d5e5000cfd37a6)

**Comment by differentreality** [comment]
User is subscribed to a conference. User tries to subscribe to the same conference. An exception is thrown, what should happen is that we just see a message saying that the user is already subscribed.

**Comment by dPliakos** [comment]
Hello!!
May I give a try on this ?

**Comment by differentreality** [comment]
Go ahead @dPliakos :D

**Comment by dPliakos** [comment]
The same could happen when the user tries to unsubscribe from a conference, but in that case osem produces a `NoMethodError`. 
This must happens because the there is no conference with the requested id at the user subscriptions.
What should be done in such a case?

**Comment by differentreality** [comment]
Good catch @dPliakos :) 
What do _you_ think the workflow should be like in this case?

**Comment by dPliakos** [comment]
I think it should test if there is such a subscription before the try to destroy it and then provide a message in case of absence.
But the error message are under subscription using `@subscription.errors.full_messages.to_sentence`, so do we need to have something like that for the user instead ?

**Comment by differentreality** [comment]
And where would you redirect the user?

**Comment by dPliakos** [comment]
We want the user to be on the same page, but with an error shown.
Now is redirected to root_path. I do not know what actually is, but I guess it the main/base url. And error is set to `@subscription.errors.full_messages.to_sentence`.

We want to redirect root_path and set `error: ` to another message ?

**Comment by differentreality** [comment]
Nice, so we want to redirect to root_path, with an error message, if there is no subscription for the user. Right? You can put that in one line code before `@subscription.destroy` happens.
