### ISSUE TITLE
fix warning in Rspec

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1598]
`WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<ActiveRecord::RecordInvalid: Validation failed: User already Registered!, Registration limit exceeded>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /home/travis/build/openSUSE/osem/spec/models/registration_spec.rb:23:in `block (4 levels) in <top (required)>'.`

See https://travis-ci.org/openSUSE/osem/jobs/254192394

**Comment by rahul2240** [comment]
want to try.

**Comment by Ana06** [comment]
@rahul2240 go ahead! :wink:

**Comment by rahul2240** [comment]
![image](https://user-images.githubusercontent.com/25618739/28681804-63e33438-7318-11e7-94be-46684994d9e0.jpg)

**Comment by rahul2240** [comment]
@Ana06   i used "rescue ActiveRecord::RecordInvalid" in the example in registration_spec.rb  to remove this warning.If you approve this then i can send the PR.

**Comment by Ana06** [comment]
@rahul2240 

> @Ana06 i used "rescue ActiveRecord::RecordInvalid" in the example in registration_spec.rb to remove this warning.If you approve this then i can send the PR.

That remove the error, but you are not testing it then. You don't need to do that. The error is complaining about the lack of message in https://github.com/openSUSE/osem/blob/master/spec/models/registration_spec.rb#L23. And you have the error here: `<ActiveRecord::RecordInvalid: Validation failed: User already Registered!, Registration limit exceeded>` So you can just add the error message as a param in the `raise_error`. :wink:

**Comment by rahul2240** [comment]
I tried adding the message as a param in the raise_error a month ago,and i tried it again today but i dont understand why i am getting this error.

Failures:

  1) Registration validation registration_limit_not_exceed is not valid when limit exceeded
     Failure/Error: expect { create(:registration, conference: conference, user: user) }.to raise_error('User already Registered')
     
       expected Exception with "User already Registered", got #<ActiveRecord::RecordInvalid: Validation failed: User already Registered!, Registration limit exceeded> with backtrace:
         # ./spec/models/registration_spec.rb:23:in `block (5 levels) in <top (required)>'
         # ./spec/models/registration_spec.rb:23:in `block (4 levels) in <top (required)>'
     # ./spec/models/registration_spec.rb:23:in `block (4 levels) in <top (required)>'

**Comment by rahul2240** [comment]
@Ana06 Thanks for the help.I got the mistake,it was with error message which i was writing wrong from last 1 month :disappointed_relieved:
