### ISSUE TITLE
Only ask speakers to register, if registrations are possible for the conference

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1609]
https://github.com/openSUSE/osem/blob/master/app/views/proposals/index.html.haml#L54 

Only show the relevant text, if there is a registration period set for the conference, otherwise it will be confusing.

Same for the tooltip link that encourages speakers to register for the conference, this only makes sense if the conference has a registration_period set.

**Comment by namangupta01** [comment]
i am working on this issue

**Comment by namangupta01** [comment]
Fixed in #1621 
Please close this issue!
