### ISSUE TITLE
Add valid email regex for user registration

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1614]
A user can sign up with email like a@a , so i think validation on the email is required.

**Comment by Ana06** [comment]
I am not completely sure if we want to change this validation.

 We are using [devise gem](https://github.com/plataformatec/devise) for authentication. So the email validation come from the gem and this is made on purpose on the gem:

> Email regex used to validate email formats. It simply asserts that one (and only one) `@` exists in the given string. This is mainly to give user feedback and not to assert the e-mail validity.

@differentreality @hennevogel @ChrisBr @lagartoflojo what do you think? do we want to be stricter here?

**Comment by lagartoflojo** [comment]
I agree, we don't really need anything more complex than what comes out of the box from Devise. The better way of confirming your email by clicking a secret link on an email sent to you.

**Comment by rahul2240** [comment]
Thanks!
i will ask the same from devise developers.

**Comment by Ana06** [comment]
@rahul2240 there are many related issues in the devise gem regarding this. The reason they give is the one I already posted: 

> Email regex used to validate email formats. It simply asserts that one (and only one) @ exists in the given string. This is mainly to give user feedback and not to assert the e-mail validity.


So, I'll close this then :wink:

**Comment by rahul2240** [comment]
yes thanks.
