### ISSUE TITLE
Rename "size" field to "capacity" in Room

### ISSUE THREAD

**Issue by afranke** [openSUSE/osem#1625]
Venue rooms have a size field which seems to be the number of attendees it can accommodate. This should be named capacity as size is an ambiguous term and probably not the first one would think of for that.

**Comment by namangupta01** [comment]
Want to work on it

**Comment by Ana06** [comment]
@afranke you mean changing the name of this field that the user see or do you mean also the code?

**Comment by afranke** [comment]
I have no clue about the code. I am a user, I organize conferences and I am evaluating OSEM as such. I won’t delve into the code. ☺

**Comment by Ana06** [comment]
@afranke ok, I think we can change this :+1: thanks for the suggestion :wink:

**Comment by rahul2240** [comment]
can i try?
