### ISSUE TITLE
Cross-Site Scripting Warnings in app/views/conferences

### ISSUE THREAD

**Issue by shlok007** [openSUSE/osem#1645]
[Security issue from Hakiri](https://hakiri.io/projects/d1eb39a7696349/stacks/70eaa9009f1f2b/builds/51071bafacecd2/warnings/4a3a8cf37c2073): Unsafe model attribute in link_to href in app/views/conferences/_venue.html.haml
[Security issue from Hakiri](https://hakiri.io/projects/d1eb39a7696349/stacks/70eaa9009f1f2b/builds/51071bafacecd2/warnings/8f60bfccfeba77): Unescaped model attribute in app/views/conferences/_venue_map.html.haml
[Security issue from Hakiri](https://hakiri.io/projects/d1eb39a7696349/stacks/70eaa9009f1f2b/builds/51071bafacecd2/warnings/40b203cbad7d32): Unescaped model attribute in app/views/conferences/show.html.haml
[Security issue from Hakiri](https://hakiri.io/projects/d1eb39a7696349/stacks/70eaa9009f1f2b/builds/51071bafacecd2/warnings/d7fd272c6e91dc): Unescaped model attribute in app/views/conferences/_venue_map.html.haml
[Security issue from Hakiri](https://hakiri.io/projects/d1eb39a7696349/stacks/70eaa9009f1f2b/builds/51071bafacecd2/warnings/30e0dd86a728f7): Unescaped model attribute in app/views/conferences/_venue_map.html.haml

For further details: https://github.com/openSUSE/osem/pull/1610#issuecomment-323535723

**Comment by differentreality** [comment]
Fixed in https://github.com/openSUSE/osem/pull/1755
