### ISSUE TITLE
Add description field for cfps

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1650]
So that organizers can customize the text that appears in proposals#index, tracks#index, booths#index and encourage/inform submitters about what they should focus on, and what they should know about their submissions.

**Comment by ViditChitkara** [comment]
Can I take up this issue?

**Comment by differentreality** [comment]
go ahead @ViditChitkara :)

**Comment by ViditChitkara** [comment]
Could you please explain what is exactly meant by "customize" here. What I am thinking is just to add a field in cfp model and show it in cfp#index.

**Comment by differentreality** [comment]
Yes, that's what I meant @ViditChitkara 

Customize, as in a conference organizer can choose what text to show. So yes, that means a field with the information.
