### ISSUE TITLE
Browsing is confusing with organization name on the top left navbar

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1651]
When I am anywhere (eg proposals#index) I see the organization name on the top left corner of the navigation bar. That takes me to organizations#index. 

Usually on the top left we find the link to homepage. 

Also there is nothing I want to do in organizations#index (99% of the time at least).

The organization name could be the same as the app name (for the non hosted version of OSEM), as such I see the exact same thing, which is directing me to a totally different place every time. And that's confusing.

**Comment by bear454** [comment]
I think what we're missing is some logic for when there's only one organization. In that case, I agree, it makes no sense to deal with the organizational level.
