### ISSUE TITLE
Export tracks and booths

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1652]
It would be useful to have similar export options like we do for proposals.

**Comment by namangupta01** [comment]
@differentreality What are the fields of tracks and booths should be included while exporting?

**Comment by differentreality** [comment]
@namangupta01 **designing** the feature is part of working on the issue to implement this feature, so if you want to work on this, as with any project, smaller or bigger, you should come up with a plan. 

For this particular issue your plan is to understand who will use this, when/why an organizer will need this. What is an organizer getting out of this export? That way you come up with your workflow, and the information that is useful to show, ie which fields, with which order.
That way you will have figured out **exactly** what it is that you want to implement, so that you can start coding.

Please come up with a suggestion and post a comment with it, so that we can discuss it.

**Comment by namangupta01** [comment]
@differentreality Okay, thanks! Working on it!

**Comment by namangupta01** [comment]
@differentreality For tracks we can have a fields : 
ID 
Name
Description
Events ( as a Track has many events)
Rooms
Start Date
End Date
Included in Cfp
Submitter's Name
But my doubt is that, as Track has many events, but we can only set one room for a track. What if there are two events of a particular Track are taking place in parallel in different rooms but a track can only have one room.
Please correct me if i am wrong!

**Comment by differentreality** [comment]
It's not possible to schedule an event with trackA in a room different than trackA's room (however I just realized the opposite is true, you can double check and open an issue for it, if you want to).

However, when we export tracks into a pdf or spreadsheet, how do you plan to show the events? Like a big list? Isn't that going to occupy a lot of room? I am not sure if we should do that.

**Comment by namangupta01** [comment]
As of now track can only have one room, but track can have many rooms. So should i open the issue for "track has many rooms"?
For exporting the track we can make multiple tables in a pdf, each table corresponding to particular track or we can also ask user to which track he wants to export. What you say?

**Comment by differentreality** [comment]
I am confused with both of your points.

The feature is about adding a button in admin/tracks#index which will export our tracks list into a pdf, and XLS file. And that's needed, for example, for organizers to get a list of all track proposals, or all confirmed tracks of their conference. 

Why would they need to export 1 track?

**Comment by namangupta01** [comment]
As i was thinking to include all the events and rooms that belongs to a particular track into the export which will make a row in a table big thats why i was saying to import one track but which is now i think is  wrong.
And as the events will make it a big list we can exclude **events** and **room** field from beign exported in track.
So, the fields should be :
ID
Name
Description
Start Date
End Date
Included in Cfp
Submitter's Name
But including room field in export will make it easy for the organisers to manage the events at venue but including this field in track export can sometimes make a big list when the number of rooms are more.
That's why i was thinking wheather to include this field or not?
So what do u think of this?

**Comment by differentreality** [comment]
@namangupta01 I don't understand why you are saying that 1 track will be in multiple rooms. 
Each track is happening in 1 room. Where did you see things written differently?

**Comment by namangupta01** [comment]
@differentreality I am saying about one track will be in multiple rooms because:
track has many events and events can occur in different rooms so indirectly track has many rooms.
I have a doubt regarding this, please clear it.

**Comment by kormoc** [comment]
Side note, I would like to request that any exports also be available via json/jsonp for embedding in external websites and/or native mobile applications.

Thanks!

**Comment by differentreality** [comment]
@kormoc like these ones? https://github.com/openSUSE/osem/blob/master/app/controllers/api/v1/events_controller.rb

**Comment by differentreality** [comment]
@namangupta01 yes, that's not the intended behavior exactly.

But this is independent of what we want to do here. We want to export the list of tracks (not their events), and we want to show room in which the track is assigned (if the room exists).

**Comment by kormoc** [comment]
Yes indeed @differentreality!

**Comment by namangupta01** [comment]
@differentreality  working on it 👍
