### ISSUE TITLE
Getting error message even after visiting some other page

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1656]
I edit my booth request and removed everything from the field and after submitting that i got this error "An error prohibited the Booth for Title can't be blank. Description can't be blank. Reasoning can't be blank. Responsibles can't be blank. Website url can't be blank. Submitter relationship can't be blank. "
When i go to some other page, the error was still there on the top.

**Comment by differentreality** [comment]
I can reproduce this, I believe it was also mentioned in another issue. We should fix that in all occurences. First I would focus on reproducing locally this error. Then investigating as to why it appears. Try to apply a solution. If the solution works for this particular case, then apply it in other places of the app where this can occur.

Thanks for reporting this @rahul2240 :+1:

**Comment by rahul2240** [comment]
@differentreality Thanks,I got the solution.

Flash[:notice]‘s message will persist to the next action and should be used when redirecting to another action via the ‘redirect_to’ method.
Flash.now[:notice]‘s message will be displayed in the view your are rendering via the ‘render’ method.

Reference: https://gist.github.com/awesome/4356500

**Comment by differentreality** [comment]
👍 nice, let's fix this in all places where it is needed!

**Comment by rahul2240** [comment]
@differentreality  ok :smile:
