### ISSUE TITLE
Openid needs to require email

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1658]
* Openid model needs to validate for email existence, because user model requires it, and if it is not there, there is no point in creating the openid record without the user record.

That already means we should put all that into a transaction in the users/omniauth controller.

* We need to explicitly request access to user's email when authorizing with openid. If a user does **not** have a public email (I stumbled upon that with github), then things go bad. 
Also when that happens, we need to catch this and redirect to our home page with a relevant message (right now it redirects to github and the user has no idea what's going on)

**Comment by ViditChitkara** [comment]
Can I start working on this @differentreality ?

**Comment by differentreality** [comment]
Sure @ViditChitkara
