### ISSUE TITLE
proposals#edit form show text in track field

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1659]
The field for track selection should show some text, like difficulty level does.

**Comment by namangupta01** [comment]
@differentreality want to work on it!

**Comment by differentreality** [comment]
@namangupta01 thanks :) Go ahead!

**Comment by namangupta01** [comment]
@differentreality Here, how it look likes :
![screenshot from 2017-09-07 23-42-41](https://user-images.githubusercontent.com/20709985/30178509-cba2c0b4-9426-11e7-813a-284787946e8d.png)

**Comment by differentreality** [comment]
@namangupta01 please add the screenshots of your changes in your PR instead :)
