### ISSUE TITLE
config/environments/production.rb should be in .example file

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1666]
production.rb should be renamed to production.rb.example, and production.rb should be added in gitignore.

**Comment by tobru** [comment]
This would make deploying the application with Docker much more complicated as we would have to somehow generate the file or create it with a template.

**Comment by differentreality** [comment]
So this would not be enough?
`cp config/environments/production.rb.example config/environments/production.rb`

**Comment by tobru** [comment]
Yeah, would be a solution if the example file is ready to be used.
