### ISSUE TITLE
There should be submitter name when admin creates a track

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1672]
There is a bug when admin creates a new track. There is no name in the submitter i.e submitter field is empty. As shown in the screenshot.
![screenshot from 2017-09-01 16-11-53](https://user-images.githubusercontent.com/20709985/29966623-5ce05092-8f30-11e7-9dc0-1bcd0fd7d452.png)

**Comment by differentreality** [comment]
That's by design. 
We care about the submitter only when a user submits a track proposal. The existence of the submitter defines whether or not this is a self organized track. 
Changing this behavior would require defining self organized tracks in a different way.

**Comment by namangupta01** [comment]
@differentreality Track with Track ID 1 is also a self organised track, yet it is showing the submitter name which is weird.
This track was created by the drop down menu present on the top-right of the web page.
I think this should not happen if we are not showing name for self organised track.

**Comment by differentreality** [comment]
@namangupta01 self organized tracks show submitter name.
