### ISSUE TITLE
Database config examples for all supported databases

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1676]
https://github.com/openSUSE/osem/blob/master/config/database.yml.example only shows the config for sqlite3.

Since we support mysql and postresql, I would add comments with the configuration for each of those databases as well.

**Comment by akshitahluwalia** [comment]
I would like to work on this issue please assign it to me.
 :smile:

**Comment by akshitahluwalia** [comment]
@differentreality I have created the PR for the same please have a look at it.

**Comment by rishabh92** [comment]
@differentreality Looks like a good amount of work was done on this issue but it was closed due to some reason. I can probably take this up if you don't mind? :innocent:

**Comment by differentreality** [comment]
@rishabh92 if you check the contents of the PR you will see that the code is no longer there. As such it was not possible to merge the PR. The contributor hasn't been responsive for a while, so there was no point in having this PR open any more. 

Feel free to work on it :+1:
