### ISSUE TITLE
admin/cfps#show does not show the type

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1679]
When in the show page of a cfp, you are not able to tell which cfp type this is. Type should also be visible.

**Comment by namangupta01** [comment]
Can i work on it?

**Comment by differentreality** [comment]
@namangupta01 you already have 6 open PRs pending review and/or changes, so I would strongly suggest to focus on improving them instead of taking up a new issue.

**Comment by namangupta01** [comment]
Sure :)

**Comment by ViditChitkara** [comment]
Can I work on it!!

**Comment by differentreality** [comment]
@ViditChitkara how about we first merge your open PR and then you get started with this? 
I have some time today to further review your PR, but there are some more comments you still haven't replied to.

**Comment by ViditChitkara** [comment]
OK,I'll work on it later!

**Comment by rahul2240** [comment]
If no one is working on this issue,then please allow me to work on it.

**Comment by Ana06** [comment]
@ViditChitkara there are many other issues you can work on when you finish your current PR :wink: so we can allow @rahul2240 to work on this now. @rahul2240 go ahead! :smile:
