### ISSUE TITLE
error in generating pdf for ticket when venue is not set

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1683]
physicalticketcontroller#show should contain condition on @venue.name that if it exist then only pdf will be generated otherwise venue is nil and app will show error

**Comment by differentreality** [comment]
> undefined method `name' for nil:NilClass

` draw_text @conference.venue.name.to_s, at: [@mid_horizontal + 30, cursor - 70]`

app/pdfs/ticket_pdf.rb:54:in `draw_second_square'

**Comment by rahul2240** [comment]
can i take this?

**Comment by differentreality** [comment]
Go ahead @rahul2240, thanks for reporting and taking up on it :)
