### ISSUE TITLE
Inform in advance about eventschedule deletion upon change of conference dates

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1687]
From @kormoc in #1640 

I would like to request that a click though okay/cancel is given that displays the number of events this change will delete before deleting them. It was non-obvious that we had to expand, move, and then contract to change hour windows.

Thanks!

**Comment by rahul2240** [comment]
can i take this?

**Comment by differentreality** [comment]
@rahul2240 you can, if you want to :)

**Comment by rahul2240** [comment]
@differentreality  I have to show the events that are going to delete when the conference dates are changed.Nothing else right? Please correct me if i am wrong.

**Comment by differentreality** [comment]
Showing all events is an overkill (and can be a lot of data to show on a pop up). 

We should show something along those lines:
'Are you sure you want to make to change conference hours? You have already scheduled content, which will be unscheduled if you proceed. Do you wish to proceed?'

**Comment by rahul2240** [comment]
Thanks 😄 I will do it.
