### ISSUE TITLE
Email in ticket shows beyond the square outline

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1691]
![screenshot from 2017-09-12 09-52-35](https://user-images.githubusercontent.com/4322737/30311942-2a5717fa-97a0-11e7-8587-93eb7cc1fe4f.png)

**Comment by ViditChitkara** [comment]
@differentreality Can I work on it?🙂🙂

**Comment by siddhantbajaj** [comment]
@ViditChitkara sure go ahead. One possible fix could be using a `bounding_box` instead of `stroke_rectangle`. Check Prawn pdf [documentation](http://prawnpdf.org/manual.pdf) for more.
