### ISSUE TITLE
Cross-Site Scripting Warning in app/views/conferences/_venue.html.haml

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1692]
[Security issue from Hakiri](https://hakiri.io/projects/d1eb39a7696349/stacks/70eaa9009f1f2b/builds/f5a462c5036e62/warnings/b63c0b1464fa55): Unsafe model attribute in link_to href in app/views/conferences/_venue.html.haml

**Comment by akshitahluwalia** [comment]
@differentreality I would like to work on this issue please assign it to me.

**Comment by differentreality** [comment]
Closing this as duplicate of https://github.com/openSUSE/osem/issues/1696

@akshitahluwalia May I suggest we first finalize and merge your open PR before you start working on something entirely different?
