### ISSUE TITLE
Fix Hakiri security warnings

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1696]
There are 5 security warnings reported by Haikiri as you can see for example here (or in any other PR open as it is faillling in all of them): https://hakiri.io/github/openSUSE/osem/master/cceb11c73a6007fb6b538eefabacf6dcd667dedc/warnings?name=Cross-Site+Scripting

**Comment by akshitahluwalia** [comment]
@Ana06 I would like to work on it please assign it to me
Thanks :+1:

**Comment by akshitahluwalia** [comment]
@differentreality I have already started working on this and the other PR is pending for review with updated changes as proposed.

**Comment by rahul2240** [comment]
@akshitahluwalia are you working on this issue?

**Comment by akshitahluwalia** [comment]
Yes @rahul2240 I am working on this.
