### ISSUE TITLE
Total amount is not showing cents

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1702]
if the price of the ticket is 1.53 then in total only 1 is visible
![total](https://user-images.githubusercontent.com/25618739/30512650-d401441e-9b11-11e7-9fee-9d6b4e844c25.png)

**Comment by differentreality** [comment]
Yeap, for total we are only adding the integer part of the number.

**Comment by rahul2240** [comment]
@differentreality thanks.Will send the PR asap.
