### ISSUE TITLE
Payments grooming

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1703]
1. Do not go to payments#new, if amount is 0
Currently you can:
* go to payments#new path directly, which will show that you can pay 0 euro, 
* it will ask for your credit card information (the button will even go green, as if the transaction was successful)
* and then you will be told that 
> Invalid positive integer Please try again with correct credentials.

Relevant screenshots:

![screenshot from 2017-09-17 13-25-59](https://user-images.githubusercontent.com/4322737/30519955-18228e9c-9bac-11e7-9385-169f52e691fe.png)
![screenshot from 2017-09-17 13-26-12](https://user-images.githubusercontent.com/4322737/30519956-18270b16-9bac-11e7-8bf0-3dc108819058.png)
![screenshot from 2017-09-17 13-26-40](https://user-images.githubusercontent.com/4322737/30519957-182dcc4e-9bac-11e7-8f30-3c8c35328c85.png)
![screenshot from 2017-09-17 13-26-26](https://user-images.githubusercontent.com/4322737/30519961-1e1444b2-9bac-11e7-8ed4-d6d759187130.png)

2. physical_tickets#index url is conference/abc/physical_ticket (according to our routes https://github.com/openSUSE/osem/blob/master/config/routes.rb#L125) but it would make sense to be physical_tickets (in plural)

**Comment by rishabhptr** [comment]
Can I work on this issue?

**Comment by differentreality** [comment]
@rishabhptr absolutely, go ahead! Thanks for picking it up :)

**Comment by rishabhptr** [comment]
@differentreality Actually, the page is physical_ticket#index instead of physical_tickets#index, therefore I cant directly change in routes.rb because then the controller would need to be changed too,so do you think `resources :physical_ticket, path:"physical_tickets", only: [:index]`  would suffice?
