### ISSUE TITLE
Link to ticket missing

### ISSUE THREAD

**Issue by tobru** [openSUSE/osem#1705]
After buying a ticket the page `/conferences/myconf/physical_ticket/ID` is displayed where the ticket can be viewed or downloaded as PDF. When closing this page I cannot find a link to it afterwards. I would expect to find a link under `/conferences/myconf/register`. Where can a participant see his tickets?

**Comment by differentreality** [comment]
One place to find your tickets is from the home page, there is a button 'Tickets'.

It makes sense to make this visible in conference_registrations#show as well.

**Comment by tobru** [comment]
Oh yeah, I see... This wasn't obvious. Thanks for pointing there!

**Comment by differentreality** [comment]
Our current master is under active development for the past months. This is a new feature coming from our GSoC, and there is even a related PR still open, so it is very possible that there is still room for improvement. Feel free to report your findings :)

**Comment by tobru** [comment]
Thanks, I'll do. I see that master is living, which is great. I love software like this who sees great activity, this also makes me confident that my testing and reporting helps to make OSEM great.

**Comment by Ana06** [comment]
@siddhantbajaj what is the state of that?

**Comment by differentreality** [comment]
This seems to have been resolved in #1788
