### ISSUE TITLE
Fix Haikiri offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1707]
Due to Cross-Site Scripting offenses found in our code by Haikiri, it is failing in all PR. For example: https://hakiri.io/github/openSUSE/osem/master/8b9933968ce346f1e555fde03db7cc058e32119e

**Comment by ViditChitkara** [comment]
@Ana06 Isn't #1696 also for hakiri warnings?

**Comment by namangupta01** [comment]
Can i work on this issue?

**Comment by Ana06** [comment]
@ViditChitkara you right, I open the same issue twice :rofl:

**Comment by Ana06** [comment]
@namangupta01, @akshitahluwalia is already working on it.
