### ISSUE TITLE
More than one options of Multiple choice while creating a new question

### ISSUE THREAD

**Issue by ViditChitkara** [openSUSE/osem#1718]
![bug1](https://user-images.githubusercontent.com/22616017/31028636-4866cde2-a56c-11e7-940f-061b348c3f54.png)
Not sure why there are multiple options in question type Drop down for "multiple choice" question

**Comment by namangupta01** [comment]
@ViditChitkara I didn't get this. Mine is showing only one time
![screen shot 2017-09-30 at 12 10 20 pm](https://user-images.githubusercontent.com/20709985/31043422-e05a111a-a5d8-11e7-9123-683a14cf5140.png)
I think some line of code gets repeated in your code check it out!

**Comment by differentreality** [comment]
@ViditChitkara it's because the question type has been added multiple times in your DB. 

We are refactoring questions entirely in #1100, so fixing this is not a priority.

**Comment by ViditChitkara** [comment]
Yes,there are multiple records of multiple choice type question😅😅. Should I close this issue?

**Comment by differentreality** [comment]
Yes, please.
