### ISSUE TITLE
wrong argument passing while calling link_to_organization method 

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1725]
Argument given while calling the **link_to_organization**  method in file https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml is not correct as it is passing the conference_id as shown in lines:
https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml#L8
https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml#L227

**Comment by differentreality** [comment]
I no longer see that for https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml#L8 but it's true for https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml#L22 :+1:

**Comment by namangupta01** [comment]
@differentreality I didn't get why it is not true for https://github.com/openSUSE/osem/blob/master/app/views/admin/versions/_object_desc_and_link.html.haml#L8 
as here version.item_id is not a organization id.

**Comment by differentreality** [comment]
@namangupta01 why not? What is it?

**Comment by namangupta01** [comment]
@differentreality yes, you are correct when the item_type is organization then item_id gives the id of the organization.
Should i close this issue?

**Comment by differentreality** [comment]
Yes, let's work on #1722
