### ISSUE TITLE
Unable to create rooms when venue is not set

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1729]
Create room is redirecting to home page with a flash message that says "You are not authorized to access this page."
When i am facing this situation-
Create a conference(venue is not set), go to schedules then go to track schedules.
Click on  add track schedules button, then create schedule, now go to create rooms.

I think if venue is not set then instead of create rooms link , add venue link should be there.

**Comment by differentreality** [comment]
Yes the admin/schedules#index and admin/schedules#show should show the same messages regarding creating a venue and rooms.
