### ISSUE TITLE
Conference dates

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1731]
In conference#edit conference date is set to read-only but still it can be changed to other date. 
Input field for dates is confusing for users as it looks like it is locked

**Comment by differentreality** [comment]
Are we talking about this screen?

![screenshot from 2017-10-04 14-14-54](https://user-images.githubusercontent.com/4322737/31172981-6dd52f4c-a90e-11e7-94b3-e81fae72480b.png)

And are you saying that you can actually type on the input box?

**Comment by rahul2240** [comment]
Yes, i am talking about this screen and No i cannot type in input box but using that calendar i can change the date.

**Comment by differentreality** [comment]
The input field is read-only so that people cannot type in it, and the data comes only from the selection on the calendar.

**Comment by rahul2240** [comment]
Yes but don't you think it is confusing for users because it looked like the dates cannot be changed

**Comment by differentreality** [comment]
Feel free to propose an alternative.

**Comment by rahul2240** [comment]
Add white background colour to this input field?

**Comment by differentreality** [comment]
Closing as there isn't much happening here - we probably should not change the visuals users already know.
