### ISSUE TITLE
Opening of Blank Page when SplashPage is not created .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [openSUSE/osem#1732]
When SplashPage is not created by organiser and we click this link , then a blank page is opened .
<img width="1438" alt="screen shot 2017-10-02 at 6 35 01 pm" src="https://user-images.githubusercontent.com/14952645/31079264-a6ab84dc-a7a2-11e7-857c-e239cb81d29d.png">

It should be opening page splashpage#new if splashpage is not created
else it should open the spashpage .

**Comment by differentreality** [comment]
This link is to show what a splashpage is, and where it is found / how it is accessed. It takes you to conferences#show (outside of admin).

If you want to create a splashpage, there is a create button right underneath!

**Comment by sagarpreet-chadha** [comment]
Okay mam...sorry about that ! Thanks !
