### ISSUE TITLE
Error opening link to difficulty level in Revision history

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1741]
When the link to particular difficulty level in Revision history is click, then it shows the error!

![screen shot 2017-10-08 at 12 56 21 am](https://user-images.githubusercontent.com/20709985/31311144-af277cf4-abc3-11e7-970b-ba9c50568069.png)

**Comment by namangupta01** [comment]
@differentreality As there is nothing much to display in difficulty level should it link towards the difficulty_level page?

**Comment by differentreality** [comment]
There is no show page.
So we should either manually redirect to the index page, or add a show page for difficulty_levels.

While a difficulty level does not have any information to show, except for its name and description, we can still present useful information, such as a list of the conference events that have this particular difficulty level.

@namangupta01 can you please check if the same error exists with links to event_types?

**Comment by namangupta01** [comment]
sure! 👍

**Comment by namangupta01** [comment]
@differentreality for event_types this error doesn't exist as it is redirecting to event_types page.

**Comment by differentreality** [comment]
OK then we can do the same thing for difficulty levels.

@namangupta01 you currently have a couple of things you are working on in peding PRs. We can leave this for a new contributor, shall we?

**Comment by namangupta01** [comment]
I have already completed the work for this! Only thing is left is just to make pr! But if you want we can leave this for new contributor. Let me know!

**Comment by differentreality** [comment]
Oh, I see. Why didn't you open a PR already?
If you have already done the work, then there is no point to no not send a PR.

But I strongly suggest you should focus on improving your open PRs, even while you are awaiting review, you can always go back and see your code - do your own review, check if there is something you can write better, rebase and update your PR.

**Comment by namangupta01** [comment]
I didn't make pr. Because as you said you have already five pr open so don't open new pr. That's why! :)

**Comment by differentreality** [comment]
@namangupta01 but that is not at all my point :)

My point is that if you have multiple pending PRs, you have other things to focus on, and work on. It is not the count of the PR that matters, is where your focus and energy is. Not opening a PR means, not working on more things, so that you can focus on the work that is not yet finished.
I hope it is now more clear what I meant. 

The point is not to open many PRs, the point is to be able to write your code, collaborate, so that your code can be merged.
