### ISSUE TITLE
Include speaker email in "Events" admin CSV/XLS export

### ISSUE THREAD

**Issue by meonkeys** [openSUSE/osem#1743]
This would make the export useful for emailing groups of speakers, e.g. those with Confirmed events.

Here's my workaround (no I did not write this on my own):

```sql
SELECT e.id
       ,e.title
       ,e.state
       ,u.email
  FROM events AS e
  JOIN event_users eu ON eu.event_id = e.id
  JOIN users u        ON u.id = eu.user_id
  JOIN programs p     ON p.id = e.program_id
  JOIN conferences c  ON c.id = p.conference_id
   AND c.short_title = 'seagl2017'
   AND e.state       = 'confirmed'
```

**Comment by namangupta01** [comment]
@differentreality  Can i take this issue?

**Comment by namangupta01** [comment]
As there can be multiple speakers to the event so should there be email id of all the speakers. Isn't it?

**Comment by namangupta01** [comment]
we can also have multiple speakers belongs to a particular event because event can have many speakers and also there can be many emails of them so we should have name of all the speakers and all the emails of them.
