### ISSUE TITLE
Set a more meaningful openid username

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1747]
When creating a new account with openid, the username depends on whether or not the service is returning a username field (auth.info.username), if not the username becomes like 1234@facebook (uuid@provider), which does not mean anything to users reading it, and conveys no information whatsoever regarding who this user is. 

We should setup the username during user creation in a more meaningful way, such as: 
If the email is user_stella@gmail.com, the username should become user_stella@facebook.

**Comment by ViditChitkara** [comment]
@differentreality can I give it a try?

**Comment by differentreality** [comment]
@ViditChitkara go ahead :+1:

**Comment by ViditChitkara** [comment]
@differentreality I guess #1658 is a prerequisite for this issue, I guess we need to validate email presence so that it can be used to give a nice username. What do you think?

**Comment by differentreality** [comment]
It is not necessarily a prerequisite, since there can be no user record without email. 
You can start developing this issue first and go step-by-step. 

So assuming there is an email, make sure the user record gets a nice username.
