### ISSUE TITLE
Conference News Feed

### ISSUE THREAD

**Issue by kormoc** [openSUSE/osem#1751]
This is less a discrete task and more just a conversation starter.

One of the reasons why SeaGL keeps a second website is that we don't have a way to publish news (aka blog posts) in OSEM. Is this something that the OSEM team would be interested in having integrated into the codebase?

**Comment by hennevogel** [comment]
Nope sorry. What keeps you from integrating OSEM and your blog?

**Comment by kormoc** [comment]
We've been attempting to keep compatibility with upstream (openSUSE/osem), as sharing features is a good thing, however I understand that there are limits. I'll go ahead and fork ours off and break compatibility.

Thanks for all the code and the hard work over the years!
