### ISSUE TITLE
Error viewing all_comments in notifications dropdown

### ISSUE THREAD

**Issue by ViditChitkara** [openSUSE/osem#1782]
![comments-bug](https://user-images.githubusercontent.com/22616017/32418287-f4abc7be-c28c-11e7-93a1-f4ef8529441d.png)
This occurs when a user is deleted and the associated comments are not destroyed.
https://github.com/openSUSE/osem/blob/be1992a03af2766aef4d39276e34fb3814f882da/app/views/admin/comments/_all_comments.html.haml#L11
The error is occuring in above line when user associated with a comment is not found.
Either we should add dependent destroy to users or show something like "Posted by: Anonymous" when user is nil.
@differentreality What do you think?

**Comment by differentreality** [comment]
@ViditChitkara OSEM does not support user deletion at the moment. Did you manually delete the user to trigger this error?

**Comment by ViditChitkara** [comment]
Yes I manually deleted a user not specifically for this but for testing out openid. Just randomly I noticed that this was happening due to user deletion. This should not happen if someone programmatically removes a user. What do you think??@differentreality

**Comment by differentreality** [comment]
I think this is relevant to https://github.com/openSUSE/osem/issues/330 and we should consider this in regards with that issue.
For what it's worth, I think comments should persist as they play a viable role in event selection. Perhaps users with comments cannot be deleted? Or their name is maintained? Or neither, and we just copy their name with 'deleted user'.

It's a good catch, but I think there is more thinking to be put into it. So I'd rather we close this until we fully address the bigger issue(#330).

**Comment by ViditChitkara** [comment]
Sure! No issues
