### ISSUE TITLE
what's happening events not reflacting current time

### ISSUE THREAD

**Issue by omiday** [openSUSE/osem#1795]
See the screenshot below, with clock configured to display the current time in Seattle.
![screenshot_2017-11-14_09-00-32](https://user-images.githubusercontent.com/3902548/32793517-01706d94-c91b-11e7-98c7-faae68ea9b79.png)

**Comment by differentreality** [comment]
@omiday from your description I don't understand what you were expecting to see as time of the talk, instead of the 16:40

**Comment by omiday** [comment]
At 9:40am when I viewed the page I expected to see nothing. See the schedule for Nov14 at https://www.pgconf.us/conferences/Seattle2017/schedule/events#2017-11-14.
At 9:40am Seattle time (the "now") there was no event going on. The first event started at 10am. OTOH the events in the screenshot were going to happen on that day but later on in the afternoon.

**Comment by differentreality** [comment]
@omiday I am assuming you refer to the part that says 'What's happening now' and the fact that the events listed below that are not happening **now**?

Sorry it hasn't been very clear to me from the comments so far  (if that's indeed what you are referring to). 

This part was introduced/altered by pgconf, and not OSEM team. 

If the intended behavior was indeed different, and this is not just a bad choice of words, feel free to point me to the repo hosting the OSEM instance of PGConf.us and I will happily take a look at the code.

**Comment by adrianovieira** [comment]
I took a look on that pgconf website.

Nice that behaviour they've done for selecting ***tracks*** in schedule.

They've proposed a PR for osem/upstream?

**Comment by bear454** [comment]
The "What's happening now" content has not been upstreamed here.
