### ISSUE TITLE
Conference name repeated in revision_history on adding commercial.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1804]
When adding/updating commercial for a conference, the conf. name is repeated two times where first one links to commercial page for that conf.
I think it would be better that in case of 'commercial in conference' the link is included in commercial text as conference name is already added in the end.
![screenshot from 2017-11-19 23-53-40](https://user-images.githubusercontent.com/26951824/32993927-92ea83ae-cd85-11e7-9e56-c6f5303dcc91.png)

**Comment by differentreality** [comment]
I do not understand what you are suggesting as a solution, but I do agree we need to remove the repetition. I will make this a junior issue so that a new contributor can pick it up.

**Comment by rishabhptr** [comment]
@differentreality My solution was to get rid of the first repetition and add hyperlink of commercial#index in commercial text. Anyways this can be fixed in various ways.

**Comment by esquith** [comment]
I would like to take this. This would be my first open-source thing. Let me know if this is possible and I'll start.

**Comment by differentreality** [comment]
Hi @esquith, welcome! Thank you for taking this, looking forward to your PR.

**Comment by esquith** [comment]
Im having trouble with getting the 'vagrant up' command to work. It never completes the download. Having trouble reaching anyone on the IRC channel as well. Is there any alternative to vagrant that I can use?

**Comment by Harry30897** [comment]
Can I solve this issue @differentreality ?

**Comment by rishabhptr** [comment]
I believe this was solved in #1818 .
