### ISSUE TITLE
Fix splashpage lodgings section

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1811]
![lodgingview](https://user-images.githubusercontent.com/25618739/33164435-ce8dbcc0-d058-11e7-840c-25feaf30e18c.png)
![pi](https://user-images.githubusercontent.com/25618739/33207457-c7e152fc-d133-11e7-8b43-e6082b4060f5.png)

**Comment by rahul2240** [comment]
After adding lodgings for  a conference, i found this at the bottom of the splashpage(lodgings section).columns are not properly divided this can be  fixed either by giving thumnail class 100% width.

**Comment by differentreality** [comment]
Is this relevant after all the recent changes in conferences#show?
