### ISSUE TITLE
splashpage's submit request for track should redirect to track#new

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1813]
On Splashpage submit request for track is redirecting user to program/tracks which is a empty page initially with new track request button, therefore the button on splashpage should redirect user to track#new

**Comment by differentreality** [comment]
@rahul2240 by splashpage do you perhaps mean the conferences#index (splashpage is the conferences#show) ?

In conferences#index the button does direct to **new** action. 

Perhaps a screenshot of where the button is would help.

**Comment by rahul2240** [comment]
@differentreality Yes, In conferences#show 
![splashpage](https://user-images.githubusercontent.com/25618739/33316559-5a5fbfbe-d45a-11e7-9599-5057c62b456f.png)

submit your request for track should redirect user to tracks#new but right now it is redirecting to tracks#index.

**Comment by differentreality** [comment]
Same is true for event proposals (the button redirects to index)

**Comment by differentreality** [comment]
It seems a couple of people have tried to work on this, but I don't think we should make this change. 

If we redirect people directly to the form (new action) it is possible that the CfP period is closed, and they cannot access the new action at all, so they will be redirected to root_path with an error message. 

I think the links should be left as they are. 

@Ana06 ?

**Comment by bear454** [comment]
The section is only shown on the splashpage if the appropos call is open, so that's really only a corner issue of stale browser window/cache expiration.

**Comment by bear454** [comment]
@differentreality do you agree or disagree?

**Comment by differentreality** [comment]
OK sure makes sense :+1:
