### ISSUE TITLE
Fix Bundler/OrderedGems offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1816]
Fix Bundler/OrderedGems Rubocop cop offenses and remove the exclusion from the todo file. :bowtie: 

This cop ensure that gems are alphabetically sorted within groups. It support autocorrection.

https://rubocop.readthedocs.io/en/latest/cops_bundler/#bundlerorderedgems

**Comment by rishabh92** [comment]
Hi @Ana06,
Can i take this one?

**Comment by Ana06** [comment]
@rishabh92 sure! 😉
