### ISSUE TITLE
'vagrant up' doesn't finish downloading when creating the development environment

### ISSUE THREAD

**Issue by esquith** [openSUSE/osem#1819]
When trying to execute 'vagrant up' in the directory, the download never finishes. I think the most I've ever gotten to is 12%.

<img width="978" alt="screen shot 2017-11-28 at 4 33 16 am" src="https://user-images.githubusercontent.com/18001622/33312185-1eaf4d3c-d3f5-11e7-8439-2b2d6c528ad9.png">

Anyone willing to help me get setup?

**Comment by Ana06** [comment]
@esquith It works for me. It could be a problem with your internet connection 🤔

**Comment by esquith** [comment]
Heres a thread where like 30 different people have the same issue.

https://github.com/hashicorp/vagrant/issues/5319

**Comment by adrianovieira** [comment]
The OpenSuse box is very big (1GB+).

So, if I can give you a sample tip:

Before you run the box (via `vagrant up`) you could (or try to) download it first.

This can be done by simply execute `vagrant box add opensuse/openSUSE-42.2-x86_64` - it'll be a long time to be finished as this box is too big (if nothing happens, e.g: timeout, connection loosing etc).

---

PS: I've created my own box to workaround this issue.

**Comment by esquith** [comment]
That doesn't work either. If nobody else is having this problem then I guess its cool, but if other people are having it then you guys should direct people to download it manually in the installation instructions. I've tried different connections too

**Comment by TimOgilvy** [comment]
I'm slowly building a sprinkler for my lawn and peeling all the stickers off the galvinised pipes while I wait for it to download. This is attempt three on laravel/homestead.

at least reading all the stories of people with the same problem is comforting.
