### ISSUE TITLE
No link to organizations menu in admin page

### ISSUE THREAD

**Issue by olea** [openSUSE/osem#1822]
At /admin there is no link to the list of current organizations in database. After some examination I've found it exists a /admin/organizations page which work as expected. 

Another expected way to add a new organization could be when creating a new conference, but in that page you just can choose organizations in the database but can't create a new one.

Using master branch at 8442eb813f87cf2377690a1705873c499da5a920

**Comment by Ana06** [comment]
> At /admin there is no link to the list of current organizations in database. After some examination I've found it exists a /admin/organizations page which work as expected.

A link seems reasonable 👍 

> Another expected way to add a new organization could be when creating a new conference, but in that page you just can choose organizations in the database but can't create a new one.

But you can create the organisation first and afterwards create the conference, right? I am not sure if it we want to add this to the creation of the conference, as it would complicate the process. 🤔  This would be a separate issue anyway (just to avoid mixing things up).

**Comment by olea** [comment]
> I am not sure if it we want to add this to the creation of the conference, as it would complicate the process. :thinking: This would be a separate issue anyway (just to avoid mixing things up).

Well, this could be just a matter of UX refinement. You should consider if the effort pays enough. 

In any case seems clear an entry menu is needed somewhere.

Thanks!

**Comment by olea** [comment]
Related to #1524.
