### ISSUE TITLE
Fix Style/UnneededInterpolation offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1823]
Fix Style/UnneededInterpolation Rubocop cop offenses and remove the exclusion from the todo file. :bowtie: 

This cop checks for strings that are just an interpolated expression. It support autocorrection.

https://rubocop.readthedocs.io/en/latest/cops_style/#styleunneededinterpolation

**Comment by SidharthBansal** [comment]
May I take this issue and make a pull request?

**Comment by Ana06** [comment]
@SidharthBansal sure! 👍
