### ISSUE TITLE
Fix Performance/HashEachMethods offenses

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1825]
Fix Performance/HashEachMethods Rubocop cop offenses and remove the exclusion from the todo file. :bowtie: 

This cop enforces using `keys.each` and `values.each` instead of `each_key` and `each_value`. It support autocorrection, but it is important to review what is autocorrected.

https://rubocop.readthedocs.io/en/latest/cops_performance/#performancehasheachmethods

**Comment by SidharthBansal** [comment]
I would like to work on this.

**Comment by Ana06** [comment]
@SidharthBansal it may be a good idea not to work on many issues at the same time. You are already working on 2 issues. Please finish the other two first. Maybe someone else work to on this as well. 😉

**Comment by SidharthBansal** [comment]
I have solved the other two issues. May I work on this?

**Comment by Ana06** [comment]
@SidharthBansal this is just exactly the same as the other 2 issues you did. what about trying something different (maybe more difficult as well) now and allow someone else to work on this? 😉

**Comment by SidharthBansal** [comment]
Ok

**Comment by Ronaq13** [comment]
I want to take this issue.

**Comment by Ana06** [comment]
@Ronaq13 go ahead! 👍

**Comment by Ronaq13** [comment]
I started working on it.

**Comment by Ronaq13** [comment]
@Ana06 Can you specify some file name where Rubocop finds this offense.  I checked by Rubocop it inspected 556 files and found no offenses. And the project doesn't have any methods like :
```
each_key
each_value
```

Already `keys.each` and `values.each` have been used.

`values.each` has been used in files:

1. app/module/conference.rb
2. spec/factories/event_users.rb
3. coverage/index.html
4. models/email_settings.rb

`keys.each` has been used in files:

1. admin/conference_controller.rb
2. coverage/index.html
3. views/schedules/show.xml.haml

**Comment by Ana06** [comment]
The offenses are excluded in the [`.rubocop_todo.yml` file](https://github.com/openSUSE/osem/blob/master/.rubocop_todo.yml#L382). You have to remove the related offenses from there and after that Rubocop will complain about them. In this case you can use Rubocop autocorrection to solve them.

You may want to read [Rubocop documentation](http://rubocop.readthedocs.io/en/latest/configuration/#automatically-generated-configuration).

**Comment by Ronaq13** [comment]
#1869 Please review the pull request

**Comment by Ronaq13** [comment]
@Ana06 : PR for this issue has merged into master. Please close it.
