### ISSUE TITLE
Speaker proposals allow registration outside registration period

### ISSUE THREAD

**Issue by bear454** [openSUSE/osem#1827]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
After submitting a proposal (Event), a number of steps are presented to the user, to finish their proposal. One of those steps is event registration, regardless of whether the registration period is open for the conference.

**Expected behavior:**
No registration link is presented outside of registration period; authorization blocks registration outside of registration period for non-admin users.

**Steps to reproduce:**

1. Create a conference; do not set a registration period.
2. Create a Call for Papers, type: events.
3. Submit a proposal.
4. Perform the "Registration" task.

**Related code:**

**Other information:**

**Comment by Ana06** [comment]
@bear454 take into account that if the talk is accepted, this is intended. Speakers will be there anyway, so we want to allow them to register even if the registration period is closed already. See https://github.com/openSUSE/osem/issues/829

**Comment by bear454** [comment]
Our problem goes the other way - we have not opened registration yet, and our call for sessions ends about a month before we plan to open registration:

We don't have  a payment gateway in place for tickets; we haven't designed our registration questions yet; we haven't written our email templates yet; and we're still deciding how we want to format the physical tickets... so having registration open is creating a whole slew of problems.

**Comment by bear454** [comment]
A workaround for the other side (late registering speakers) is to leave registration open but artificially set the registration limit.

**Comment by Ana06** [comment]
@bear454 I think a solution for both problems would be to allow the speaker to register if there is o there was a registration open. So, if there is no registration, the speaker is not allowed to register, but if there was one, even if it is closed, then we allow the speaker to register, as he will be there anyway. 

This would take both cases into consideration, right?

**Comment by bear454** [comment]
I'm good with that; I'll update the PR to reflect it.

**Comment by differentreality** [comment]
Can we close this?

**Comment by bear454** [comment]
https://github.com/openSUSE/osem/pull/1629 resolves it.
