### ISSUE TITLE
Error trying  data:demo rake task

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1832]
## Description

Error trying to have demo data in a fresh database installation

```bash
$ bundle exec rake data:demo
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Picture Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `mogrify -resize 100x100 /tmp/mini_magick20171130-18863-1datoxa.png` failed with error:
mogrify: Expected 8192 bytes; found 5236 bytes `/tmp/mini_magick20171130-18863-1datoxa.png' @ warning/png.c/MagickPNGWarningHandler/1777.
mogrify: Read Exception `/tmp/mini_magick20171130-18863-1datoxa.png' @ error/png.c/MagickPNGErrorHandler/1751.
mogrify: corrupt image `/tmp/mini_magick20171130-18863-1datoxa.png' @ error/png.c/ReadPNGImage/3789.
/vagrant/spec/factories/sponsors.rb:15:in `block (3 levels) in <top (required)>'
/vagrant/spec/factories/conferences.rb:43:in `block (4 levels) in <top (required)>'
/vagrant/lib/tasks/data_demo.rake:6:in `block (2 levels) in <top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => data:demo
(See full trace by running task with --trace)
```

### Steps to Reproduce

1. `rm db/development.sqlite3`
2. `bundle exec rake db:setup`
3. `bundle exec rake data:demo`

**Expected behavior:** database with data for demonstration, including an **admin** user to sigin in into the app

**Reproduces how often:** I reproduced it every time I've tried.

**Version:** I've tried against master branch

**Comment by differentreality** [comment]
And you still got this same image?
https://github.com/openSUSE/osem/blob/master/spec/support/logos/OSEM.jpg

Are the relevant packages installed on your system?
That's the imagemagick and imagemagick-devel packages.

On a slightly different note, the first user that registers, will also become an admin.

**Comment by adrianovieira** [comment]
I was only giving a trial in that rake task - I'm not doing that to have an admin user.

It had no image after running data:demo. 

I believe imagemagick-devel is not a requirement, but Yes! It has those packages (imagemagick and imagemagick-devel) installed.

**Comment by differentreality** [comment]
What I was asking was if you have made any changes to the task script, and if this image (https://github.com/openSUSE/osem/blob/master/spec/support/logos/OSEM.jpg) exists in your instance.

**Comment by adrianovieira** [comment]
No! I haven't made any changes to the script.

Yes! That image exists in the my working copy.

**Comment by bear454** [comment]
`rails data:demo` works for me, on master (using SQLite for development). Feel free to repoen if you can still reproduce the issue.
