### ISSUE TITLE
Fix bootstrap script for dbsetup user

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1837]
When starting up the box the `bootstrop.sh`:

- it needs to change to `/vagrant` directory for centos box to "create" database config
- it should install gems as `vagrant` user.

**Comment by Ana06** [comment]
@adrianovieira please do not open issues without description. 🙈 

A short title and a detailed description (including how to reproduce the problem for example) helps to understand what the problem is about. 😉
