### ISSUE TITLE
Text overlap on public proposal page

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1838]
Speaker details either gets overlapped or gets hidden in case event has its own commercial.

![screenshot from 2017-12-01 17-19-43](https://user-images.githubusercontent.com/26951824/33481874-6af7b502-d6bc-11e7-85e0-4cba1a180a76.png)
![screenshot from 2017-12-01 17-20-58](https://user-images.githubusercontent.com/26951824/33481876-6c096f08-d6bc-11e7-8947-eb68a60f0c7b.png)

**Comment by Ronaq13** [comment]
I want to take this issue.

**Comment by rishabhptr** [comment]
@Ronaq13 Actually, this is just a small bug due to email text size which I had already fixed locally.

**Comment by Ana06** [comment]
@rishabhptr please when you work on an issue, write a comment to avoid someone else work on it as well.

@Ronaq13 please choose another issue 😉

**Comment by rishabhptr** [comment]
@Ana06 Sorry, I would make sure from next time.
