### ISSUE TITLE
datetimepicker navigation isn't resets if manually clean up conference start/end date fields 

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1842]
## Description

When you are registering a new conference and you manually erase the start or end fields the calendar showed after that aren't allow you to navigate in other months (for that erased direction)

### Steps to Reproduce

1. register a new conference
2. select a start or end date from the calendar showed
3. manually erase one of them
4. try to navigate to another month ahead (or behind) from that erased one 

**Expected behavior:** allow to navigate ahead (or behind) from that erased one

**Reproduces how often:** I reproduced it every time I've tried.

**Version:** I've tried against master branch

![Steps to reproduce animated](https://user-images.githubusercontent.com/5561794/33530778-d87045ee-d86b-11e7-9fd6-e9b2112be7d2.gif)

**Comment by Ana06** [comment]
@adrianovieira please do not open issues without description. 🙈 

A short title and a detailed description (including screenshot and how to reproduce the problem for example) helps to understand what the problem is about. 😉
