### ISSUE TITLE
autofill conference end date

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1844]
## Description

For every date you choose for as the begin for a conference, when you go to choose end date it always show the current month.

It could be good that the behaviour for the ending date show at least the same month where the conference begin. 

- **old-behaviour**
![old-behaviour](https://user-images.githubusercontent.com/5561794/33531453-6a8cabea-d874-11e7-88b9-d7a0fea30e76.gif)

### Steps to Reproduce

1. register a new conference
2. select start date from the calendar (any month ahead which isn't the current one)
3. select the end date - it will be showed the current month

**Expected behavior:** after the beginig date was defined, calendar for end date starts showing at least the same one as showed in the start date

**Reproduces how often:** I reproduced it every time I've tried.

**Version:** I've tried against master branch

- **new Expected behaviour**
![new-behaviour](https://user-images.githubusercontent.com/5561794/33531452-6a646590-d874-11e7-968f-8c8d7a38ed39.gif)

**Comment by Ana06** [comment]
where? please add more details. Where is this exactly needed? Maybe a screenshot as well... 🤔

**Comment by Ana06** [comment]
@adrianovieira thanks! now the issue is completely clear and the images are really cool!!! 💘

**Comment by Ronaq13** [comment]
I want to take this issue if no one assigned yet.

**Comment by Ronaq13** [comment]
@Ana06 can I start working on this? Or is anybody  else already working.

**Comment by Ana06** [comment]
@Ronaq13 there is a PR for it that you can see in this issue a little bit up. So there is someone already working on it, sorry. 

Nobody is working in these two issues:

- https://github.com/openSUSE/osem/issues/1825
- https://github.com/openSUSE/osem/issues/1342

Maybe you want to work on one of them 😉 (write a comment there if so).
