### ISSUE TITLE
Description of the CFP should not be rendered as markdown

### ISSUE THREAD

**Issue by olea** [openSUSE/osem#1856]
At the CfP page (example http://localhost:9292/admin/conferences/colo/program/cfps) CfP description __should not__ be rendered as makrdown but as plain text because the text headings probably will broke the page styling. See this text:

![captura de pantalla de 2017-12-05 23-13-37](https://user-images.githubusercontent.com/141267/33633682-f4b73742-da11-11e7-910f-c570215a044a.png)

and it's rendered as:

![captura de pantalla de 2017-12-05 23-09-48](https://user-images.githubusercontent.com/141267/33633546-8c203314-da11-11e7-92ef-ed35fb4c1146.png)

**Comment by adrianovieira** [comment]
Hope it should be a plain text - without `markdown` in https://github.com/openSUSE/osem/blob/master/app/views/admin/cfps/index.html.haml#L30

May I work on this?

**Comment by Ana06** [comment]
@adrianovieira 

> Hope it should be a plain text - without markdown in https://github.com/openSUSE/osem/blob/master/app/views/admin/cfps/index.html.haml#L30

I think so 👍 

> May I work on this?

You already did it, so yes! 🤣
