### ISSUE TITLE
Send invitation to a non-registered user added to a role group

### ISSUE THREAD

**Issue by olea** [openSUSE/osem#1857]
When organizing an event very often you'll want to invite friends, collaborators or colleagues. This is particularly relevant when preparing the CfP and inviting colleagues to join. Asking them to first register, to warn you they have registered and finally adding them to the role group is very inneficient.

Another very relevant cases are when calling for volunteers or inviting press contacts.

The ideal approach would be to send an invitation if the user is not registered, to add it automatically to the invited roles and to notify the person who invited the operation was successful.

**Comment by differentreality** [comment]
I am not against this by default, but I think we need to figure out exactly how this will work. What is currently suggested here sounds more complicated than it has to be. 

Also there is something kind of similar suggested in https://github.com/openSUSE/osem/issues/105 (first bullet point says conference invitations), so I would suggest we continue the conversation there.
