### ISSUE TITLE
Please add me to Transifex reviewers

### ISSUE THREAD

**Issue by olea** [openSUSE/osem#1860]
I would like to fix ES translations at Transifex but seems I need review permissions.

I can't see how to ask permisions at Transifex team. Could you please add me? My user there is [olea](https://www.transifex.com/user/profile/olea/). 

Thanks in advance.

**Comment by differentreality** [comment]
As we are planning on changing Transifex, I am not doing any updates on its end. If you really want to do that at this point, please send a request on transifex. 

Check https://github.com/openSUSE/osem/blob/master/TRANSLATION.md for more.
