### ISSUE TITLE
Contribution.md has broken capybara link

### ISSUE THREAD

**Issue by SidharthBansal** [openSUSE/osem#1862]
In contribution.md https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md under Test Suite, capybara link is broken
![image](https://user-images.githubusercontent.com/20972099/33720672-b203ff96-db8a-11e7-9453-32b57a89faab.png)
By clicking on it, it shows
![image](https://user-images.githubusercontent.com/20972099/33720689-c66bdab2-db8a-11e7-8acd-8fafa52b782a.png)

**Comment by SidharthBansal** [comment]
@Ana06 May I change it to http://www.rubydoc.info/github/jnicklas/capybara ?

**Comment by Ana06** [comment]
@SidharthBansal sure! for small fixes like this one you can directly send the PR. 😉

**Comment by SidharthBansal** [comment]
Ok thanks

**Comment by SidharthBansal** [comment]
Please review Pull Request #1866
