### ISSUE TITLE
How to connect to fresh OSEM docker deployment

### ISSUE THREAD

**Issue by vmisson** [openSUSE/osem#1863]
Hello,

I have deployed OSEM instance with the docker compose file.
I'm able to open the default web page but I was not able to find the admin user / password info to log on the app... 

Sorry if it's a stupid question...
Thanks in advance.

**Comment by differentreality** [comment]
@vmisson have you created a user? You can use the sign up link to do so.

**Comment by vmisson** [comment]
Yes I already try this but I got a "Error 500: Internal Server Error". It seems to be related to SMTP misconfiguration.
Anything special to do with mailhog?

**Comment by vmisson** [comment]
Even if SMTP is not working my account is created on the app and I'm able to login. 
But it's a user account... how can I be admin ?

**Comment by differentreality** [comment]
@vmisson your first user should be an admin, it might be that docker is not running the seeds. We should have a look at that, thanks:)

To add the attribute is_admin to a user manually execute the following command:
rake user:admin ['email_of_existing_user']

**Comment by vmisson** [comment]
Thanks for your feedback @differentreality 

I just try but I get the following error:
osem@2309942c09b3:/osem$  rake user:admin ['vincent.misson@gmail.com']
NOTE: Gem.datadir is deprecated; use spec.datadir instead. It will be removed on or after 2016-10-01.
Gem.datadir called from /usr/local/bundle/gems/rdoc-generator-fivefish-0.3.0/lib/rdoc/generator/fivefish.rb:29.
rake aborted!
NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration:0x00000000052cf600>
Did you mean?  console
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie/configuration.rb:95:in `method_missing'
/osem/config/environments/development.rb:5:in `block in <top (required)>'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:210:in `instance_eval'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:210:in `configure'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:182:in `configure'
/osem/config/environments/development.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:597:in `each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:597:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
/osem/config/environment.rb:25:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => user:admin => environment
(See full trace by running task with --trace)

any idea ?

**Comment by differentreality** [comment]
@vmisson you probably need to prepend bundle install to the command you are running.

**Comment by olea** [comment]
> Anything special to do with mailhog?

If you are using upstream Docker conf it should run fine with an external SMTP server.

Just be sure to write [OSEM_SMTP_DOMAIN="" content between quotes](https://github.com/openSUSE/osem/pull/1826)!!

**Comment by vmisson** [comment]
Thanks for your feedback @olea.

I just redeploy everything from scratch and I still have an issue with mailhog.

>web_1       | ArgumentError (wrong authentication type "**login**"):
web_1       |   /usr/local/lib/ruby/2.3.0/net/smtp.rb:772:in `check_auth_method'
web_1       |   /usr/local/lib/ruby/2.3.0/net/smtp.rb:548:in `do_start'
web_1       |   /usr/local/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
web_1       |   mail (2.6.6) lib/mail/network/delivery_methods/smtp.rb:111:in `deliver!'
web_1       |   mail (2.6.6) lib/mail/message.rb:2149:in `do_delivery'
web_1       |   mail (2.6.6) lib/mail/message.rb:237:in `block in deliver'
web_1       |   actionmailer (4.2.9) lib/action_mailer/base.rb:543:in `block in deliver_mail'
web_1       |   activesupport (4.2.9) lib/active_support/notifications.rb:164:in `block in instrument'
web_1       |   activesupport (4.2.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
web_1       |   activesupport (4.2.9) lib/active_support/notifications.rb:164:in `instrument'
web_1       |   actionmailer (4.2.9) lib/action_mailer/base.rb:541:in `deliver_mail'
web_1       |   mail (2.6.6) lib/mail/message.rb:237:in `deliver'
[...]

I try the following options for OSEM_SMTP_AUTHENTICATION: "plain", "login", "cram_md5" and ""...

Any idea ?

**Comment by olea** [comment]
> I try the following options for OSEM_SMTP_AUTHENTICATION: "plain", "login", "cram_md5" and ""...

AFAIK the expected configuration to use mailhog is the one at docker-compose.env.example. But I've never used it, sorry.

**Comment by vmisson** [comment]
The config on docker-compose.env.example is : 
OSEM_EMAIL_ADDRESS="osem@mailhog"
OSEM_SMTP_AUTHENTICATION="login"
OSEM_SMTP_ADDRESS="mailhog"
OSEM_SMTP_PORT="1025"
OSEM_SMTP_USERNAME="mailhog"
OSEM_SMTP_PASSWORD="mailhog"

but it's not working for me... :(
