### ISSUE TITLE
depending of the email length it overwrites the event data

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1870]
If the user choose to have his email public it sometimes overwrites the event data, e.g:

- actual behaviour

![captura de tela de 2017-12-09 10-22-34](https://user-images.githubusercontent.com/5561794/33795577-4b082a0a-dccb-11e7-852e-9fa2aa380e4a.png)

My proposal is to change this by social media icons, e.g:

- new behaviour

![new-behaviour](https://user-images.githubusercontent.com/5561794/33795604-a62624f0-dccb-11e7-8223-6035e0e3c07a.gif)

So, if you add others social media options it'd looks like, e.g:

- if they have twitter and facebook

![newest-behaviour](https://user-images.githubusercontent.com/5561794/33795750-3b995140-dcce-11e7-9380-1e969a69eca3.gif)

**Comment by rishabhptr** [comment]
Yes #1838 is also for this only.

**Comment by adrianovieira** [comment]
Nice! them my PR will cover that!
