### ISSUE TITLE
Create a Issue template file

### ISSUE THREAD

**Issue by adrianovieira** [openSUSE/osem#1875]
Let me suggest you to create templates. So, anyone that open a Issue or a PR could know what do you'd like to have as minimum information. 

- PR template
- Issue template (e.g as the sample below).

sample issue template:

```texinfo
## Description

*`<add a description explaining what are your intention by opennig this issue and how do everybody could help you>`*

- **actual behaviour**: *`<add an image which show us what is happened>`*

### Steps to reproduce

*`<what are some steps to reproduce that behaviour?>`*

1. `do this`
2. `do that`
3. ...

**Reproduces how often:** `<how frequent is this?>`

**Expected behavior:** 

*`<what's the expected behaviour?>`*

**Version:** `<What was the version you've find this  behaviour>`

```

**Comment by differentreality** [comment]
I personally do not like to make things so strict, as in having specific layouts for opening an issue or a PR.

Sure it makes total sense to properly report a bug, but I don't need to have people submit the exact same layout for their report to be adequate or complete.

New contributors can benefit of such information, so I would not object in including relevant information in the wiki. 
However I would **not** make this mandatory.

**Comment by adrianovieira** [comment]
Yes, I also agree with you! It isn't mandatory. It's a template with some suggestions.

So, in the end it is up to each one knows what is necessary  for a good issue description.

**Comment by adrianovieira** [comment]
Sure you all know, but just for reference:

- "Issue and Pull Request templates " - by github: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by differentreality** [comment]
Duplicate https://github.com/openSUSE/osem/issues/1763
