### ISSUE TITLE
before_filter, after_filter and alias_method_chain is deprecated

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1882]
![screen shot 2017-12-13 at 12 17 36 am](https://user-images.githubusercontent.com/20709985/33902476-19bb1c28-df9b-11e7-8a70-23c6cb5679d2.png)

**Comment by AEtherC0r3** [comment]
I will open separate issues with what needs to be done

**Comment by AEtherC0r3** [comment]
Closing this in favor of #1890 and #1891
