### ISSUE TITLE
Change /admin/conferences to /admin/dashboard

### ISSUE THREAD

**Issue by rishabh92** [openSUSE/osem#1888]
Currently, /admin/conferences takes the user to below admin dashboard:

<img width="1152" alt="screen shot 2017-12-12 at 11 26 06 pm" src="https://user-images.githubusercontent.com/13951936/33922948-dee9044a-df93-11e7-8067-5f122481d7d4.png">

I feel that this route should be /admin/dashboard and /admin/conferences should take the user to a page similar to /admin/organization which would have a table view with conference name, dates and some necessary details.

**Comment by differentreality** [comment]
And what mot is information would /admin/conferences#index provide that is not currently available in conferences#index?

**Comment by differentreality** [comment]
Please don't before we decide if we want to implement this. 
Please choose issues that have labels. If the issues are features we would expect you to leave a comment saying what /how you plan on implementing.

**Comment by Ronaq13** [comment]
@differentreality : Ok I will keep this in mind. Thanks :smile:

**Comment by Ronaq13** [comment]
@rishabh92  @differentreality : So are you going with this?

**Comment by rishabh92** [comment]
@differentreality Nothing really. It will just have less information than this page. At first look, It was just a bit weird to me that conference index page shows number of registered users to the website.

**Comment by differentreality** [comment]
We already have all that information that you mention in conferences#index, we don't need to duplicate it in admin.
