### ISSUE TITLE
How to activate transifex in production?

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#1898]
I have a site configured with the transifex API key and it doesn't show the language selector in the botton right corner: 

https://www.opensouthcode.org/conferences/opensouthcode2018

The API key is ok, I have checked it displaying in a rake task.

In development I see the selector correctly.

**Comment by differentreality** [comment]
Perhaps you didn't setup the API key properly in the ENV variables for your **production**?

**Comment by davidsf** [comment]
Yes, I confirmed in console that the env is setup correctly:

```
# RAILS_ENV=production rails console
> puts ENV['OSEM_TRANSIFEX_APIKEY']
cf866a61277842b39c897c5a0b5ec075
```

**Comment by differentreality** [comment]
Check the js code you have, to make sure nothing has changed.

on your browser, right click -> inspect (or whatever similar you have to see if there are js errors)

**Comment by davidsf** [comment]
In the js console I didn't see any error.

**Comment by davidsf** [comment]
I have done a new deployment and now works.... sorry for the noise :(
