### ISSUE TITLE
Check for rooms in tracks#edit

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1902]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
When we edit a track proposal from a user. If there is no room yet we show a  message with links to add venue and room but the error disappears just after creating a venue even if there are no rooms so we get a blank dropdown.

![2017-12-19-130934_1360x768_scrot](https://user-images.githubusercontent.com/26951824/34146136-cc10a528-e4be-11e7-92f9-a55f5471955f.png)
![2017-12-19-131209_1360x768_scrot](https://user-images.githubusercontent.com/26951824/34146242-36edb03e-e4bf-11e7-948b-9199f37ac098.png)

**Expected correct behavior:**
This message should remain till there is atleast one room to assist in creating a room.
So we should check @conference.venue.try(:rooms).present? instead of @conference.venue.try(:rooms).

**Steps to reproduce:**
Create cfp track and edit a track request to add room.

**Comment by Ronaq13** [comment]
I would like to take this.

**Comment by rishabhptr** [comment]
@Ronaq13 Please wait until someone reviews it.

**Comment by differentreality** [comment]
@AEtherC0r3 ?
