### ISSUE TITLE
Tickets Sold page keeps growing on scrolling for mobile device.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1903]
**I'm submitting a ..**
 - [x] Bug Report

**Current behavior:**
When opening the ticket sold page on mobile device the white space around charts keeps increasing infinitely if I scroll back and forth to a point that it is not possible to reach the end of the page.

Similar issue was encountered in #1195 but I am not sure it its entirely same as chart grow to a extend in this case too.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/26951824/34163530-f660abaa-e4fc-11e7-84ed-8ef0ab6762c1.gif)

**Steps to reproduce:**
Visit tickets sold page for a conference on a mobile site. You can reproduce this even when there is no tickets sold(no chart).

**Other information:**
I have tried it on different devices with latest version chrome.

**Comment by rishabhptr** [comment]
I would like to try this.

**Comment by differentreality** [comment]
I can confirm this. 
Relevant to https://github.com/openSUSE/osem/issues/579
