### ISSUE TITLE
Conferences#show : Error related to sponsors splashpage

### ISSUE THREAD

**Issue by kostino** [openSUSE/osem#1909]
**I'm submitting a ..**
 :heavy_check_mark:  Bug Report
- [ ] Feature Request

**Current behavior:** Error when navigating to the conferences#show page.Error likely related to the recent inclusion of a sponsors tab in said splash-page:
![screen shot 2017-12-21 at 18 50 45](https://user-images.githubusercontent.com/27733299/34266093-b9f21a0c-e680-11e7-94e8-b4a65bdf2265.png)

**Steps to reproduce:** Navigate to conferences#show using any way

**Comment by differentreality** [comment]
I cannot reproduce :/ 

Could it be related to imagemagick? Among other, I have imagemagick-devel installed on my system, could you check if you need to install such package as well?

**Comment by differentreality** [comment]
OK I managed to see the error in splashpage (conferences#show). It seems related to the Rails 5 updated, and it looks like we should be adding a check that get_logo function does not return nil.

**Comment by Ronaq13** [comment]
I would like to do this.
