### ISSUE TITLE
Error on viewing conference#show when registration is open.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1920]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
Conference#show (splashpage) shows error when registration is open.
![screenshot from 2017-12-25 16-30-36](https://user-images.githubusercontent.com/26951824/34338763-7ce70ce4-e991-11e7-805a-753d36d8fada.png)

This is likely due to a small typo at line 32:
` conference_id: @conference_id.short_title   // instead of @conference.short_title` 

**Steps to reproduce:**
View a conference whose registration is open.

**Comment by differentreality** [comment]
@AnkushMalik can you extract just the fix for this issue into a PR please?

**Comment by AnkushMalik** [comment]
#1922 is approved by @bear454 , do i need to make seprate pr for this?

**Comment by differentreality** [comment]
Actually it is not approved yet. As I suggested, I would like a separate PR just for this issue here, so that we can merge it immediately.

**Comment by differentreality** [comment]
Reproduction steps also require that you are including the registration period on the splashpage, otherwise this part of the code is not being calculated at all.
