### ISSUE TITLE
Add links to lodgings in admin/lodgings.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1924]
**I'm submitting a ..**
- [x] Feature Request

**Current behavior:**
In admin/lodgings we show a default image for lodging in case a photo is not added but we cannot click the image to visit that lodging page( which is the behaviour in the splashpage).
![screenshot from 2018-01-03 10-04-14](https://user-images.githubusercontent.com/26951824/34509213-783cb8a0-f06d-11e7-8699-fc4f42d1d1be.png)

**Expected correct behavior:**
We can replicate the behaviour in the splashpage as right now we need to select edit to see the url that is present.

**Comment by Harry30897** [comment]
@differentreality  Can I take this issue?

**Comment by differentreality** [comment]
Go ahead @Harry30897 :+1:

**Comment by sak6e** [comment]
I'm a first-timer. What do I need to know to solve this issue?

**Comment by abhiyan52** [comment]
Please close this .. Its already done
