### ISSUE TITLE
Presence Validation error not working on mass import of commercials.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1926]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
If we try to click add when file is not uploaded it shows a error.
![screenshot from 2018-01-04 00-54-23](https://user-images.githubusercontent.com/26951824/34536641-c8f58cc6-f0eb-11e7-9677-854592d3a863.png)

![screenshot from 2018-01-04 01-01-09](https://user-images.githubusercontent.com/26951824/34536898-aa0a06d8-f0ec-11e7-8f6e-2ba0911c16f2.png)

**Expected correct behavior:**
It would be suitable if instead of showing error it should show error message similar to the validation message on submitting an empty form.

**Comment by membrq** [comment]
Can I claim?

**Comment by rishabhptr** [comment]
Issue was resolved, so closing.
