### ISSUE TITLE
Error downloading CSV

### ISSUE THREAD

**Issue by ViditChitkara** [openSUSE/osem#1927]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

![todaysbug-1](https://user-images.githubusercontent.com/22616017/34539119-50b4b0c0-f0f5-11e7-8a4e-5cee58659e6c.png)
Error when downloading csv (could be list of registrations, booths,etc.)

**Steps to reproduce:**

1) Sign in as admin and visit any conference.
2) Go to the registrations link given in the sidebar.
3) Click on export CSV.

**Comment by ViditChitkara** [comment]
@differentreality Could you reproduce this?

**Comment by differentreality** [comment]
@ViditChitkara FYI you don't have to mention me explicitly, any of the contributors can look into the issue. We also get personal emails for all comments/new issues/new PRs on OSEM ;)

Yes, I can reproduce.

**Comment by ViditChitkara** [comment]
Sure, I'll keep this in mind!
