### ISSUE TITLE
Unexpected undo/redo behavior on text formatting in markdown editor

### ISSUE THREAD

**Issue by AnkushMalik** [openSUSE/osem#1929]
**I'm submitting a ..**
- [x] Bug Report
- [x] Feature Request

**Current behavior:**
Unexpected undo/redo behavior on text formatting in markdown editor
![ezgif-5-273653ccaf](https://user-images.githubusercontent.com/13421233/34567475-7832d7d8-f188-11e7-9387-248fece70b73.gif)

**Expected correct behavior:**
while undo , the editor should first remove last applied changes
vice versa for redo. 

**Steps to reproduce:**
can be reproduced in any markdown editor

**Comment by differentreality** [comment]
I think this is irrelevant to your fullstop, and relevant to the formatting. Can you please double check this scenario?

**Comment by AnkushMalik** [comment]
yes , issue is only with formatting. Editor works fine without any text formatting.

**Comment by bear454** [comment]
This is an upstream issue:

- https://github.com/toopay/bootstrap-markdown/issues/189
- https://github.com/toopay/bootstrap-markdown/issues/49
