### ISSUE TITLE
Distorted open-id links in sign-in section

### ISSUE THREAD

**Issue by ViditChitkara** [openSUSE/osem#1931]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

The open-id links are appearing a distorted way (in the sign in section).
![signin-1](https://user-images.githubusercontent.com/22616017/34578776-36bb3e20-f1ac-11e7-85f0-1517b719eafb.jpg)
The links should appear in the centre when viewed on mobile device rather than on the left.
![signin-mobile-1](https://user-images.githubusercontent.com/22616017/34578781-3c4a6190-f1ac-11e7-9327-3662459618e5.jpg)

**Expected correct behavior:**

1) The links should be wrapped in a single row (when viewed on desktop)
2) The links should be centre aligned rather than left aligned (when viewed on mobile)

**Comment by AnkushMalik** [comment]
can i claim this? :)

**Comment by differentreality** [comment]
Sure, you don't have to ask!

**Comment by ViditChitkara** [comment]
@AnkushMalik sorry for the late reply!! We're happy to help, if you are stuck anywhere!!😄😄
