### ISSUE TITLE
Organization admin cant access conferences dashboard

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1933]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
If we assign a user the role organization admin role then the user gets a administration option in his drop-down( admin/conferences ) but this leads to this error.
![screenshot from 2018-01-05 22-59-46](https://user-images.githubusercontent.com/26951824/34620919-27800a78-f26d-11e7-80af-ab2482cc0d53.png)

The user is still able visit dashboard for specific conferences which falls under the specific org.

![screenshot from 2018-01-05 23-09-51](https://user-images.githubusercontent.com/26951824/34621027-942d01c6-f26d-11e7-9d4b-41cfdadb64d9.png)
**Expected correct behavior:**
The user should be able to access admin dashboard to access all conf. under the organization.

**Steps to reproduce:**
Assign any user admin role through email by clicking on organization option in admin sidebar.

**Comment by differentreality** [comment]
Thanks for reporting this @rishabhptr !

Any chance you have already figured out what's wrong?

**Comment by rishabhptr** [comment]
@differentreality I think I do.
 In Admin  controller(index action) we have `@conferences = @active_conferences + 
 @deactive_conferences`
where ,
`@active_conferences = Conference.get_active_conferences_for_dashboard 
 @deactive_conferences=Conference.get_conferences_without_active_for_dashboard(@active_conferences)` 
 and in conference model
` def self.get_active_conferences_for_dashboard`
   ` result = Conference.where('start_date > ?', Time.now)
        .select('id, short_title, color, start_date')`

In this we are not providing organization_id attribute which cancancan requires to authorize.

I have tried by passing organization_id attribute in these functions and its working for me.

**Comment by differentreality** [comment]
Yes the problem seems to be there. Feel free to open a PR with a fix :+1:
