### ISSUE TITLE
Unable to edit Booth request in booth#show

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1940]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
The edit button in booth#show leads to admin edit page but the user cant access that page even if his booth is accepted.
![screenshot from 2018-01-07 16-17-33](https://user-images.githubusercontent.com/26951824/34648807-630703c0-f3c7-11e7-96fd-76695c0efb4a.png)

**Expected correct behavior:**
Change the path to user booth edit.

**Steps to reproduce:**
Submit a booth request to a conference with a cfp for booths and click on booth title to access booths#show.

**Comment by membrq** [comment]
Can I claim?

**Comment by membrq** [comment]
Should basic users be able to request a new booth? Or is that restricted to higher-level roles? When I click on "Add Booth", I get a "You're not authorized to access this page" message.

**Comment by rishabhptr** [comment]
@membrq You are probably getting that error because you are trying to access booths#index page of a conference who is not accepting booths currently(cfp).

When an admin creates a cfp for booths in a conference , the request booth option comes in dashboard.
![screenshot from 2018-01-08 17-05-46](https://user-images.githubusercontent.com/26951824/34669223-b98e98be-f496-11e7-8982-22a8cb25c0ea.png)

So when the user clicks this option he is able to submit his request, and the issue here is that when the user tries to click on his request title he is not able to click edit because the edit button is using admin edit path helper. :smile:
