### ISSUE TITLE
User with accepted track request can see unregistered speakers of all events.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1942]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
When a user with a accepted track request tries to manage his track he can see the unregistered speakers of all events not those restricted to his track under reports option.
![screenshot from 2018-01-07 20-07-15](https://user-images.githubusercontent.com/26951824/34650382-635999fe-f3e6-11e7-98d8-c6d8cad841fd.png)

**Expected correct behavior:**
For other information about events in the reports page we are initialising instance variable according to the user's ability to access those events so here also user should be shown missing speakers in events under his track.

**Steps to reproduce:**
After track request is accepted, click on manage option, you could see users who are speakers and haven't registered yet.

**Comment by differentreality** [comment]
What is the manage option?

**Comment by rishabhptr** [comment]
@differentreality It is available in track#index when your track request is selected and you confirm it.
![screenshot from 2018-01-07 22-34-12](https://user-images.githubusercontent.com/26951824/34651786-19c86a80-f3fb-11e7-9985-9542ef067a7a.png)

**Comment by membrq** [comment]
Can I claim this?

**Comment by membrq** [comment]
I'm having trouble understanding this issue. What determines whether a speaker is "checked in" vs missing? Is it an attribute that gets set somewhere?

Where's the best place to put this code? `reports/_missing_speakers.html.haml`? My first thought was to add an `if` condition around ln 21-22 and if that's able to work, I'd have to find a way to update ln 6 dynamically. Would appreciate feedback!

**Comment by differentreality** [comment]
People (speakers included) can register to a conference. When they arrive there is the attribute **attended** which can be enabled. That's what "checked in" means.

It is very helpful if you provide links to the files/lines you are referring to so that we are all at the same page. Assuming you refer to https://github.com/openSUSE/osem/blob/master/app/views/admin/reports/_missing_speakers.html.haml#L21 I think it makes sense to change the value of the variable @missing_event_speakers altogether.

**Comment by membrq** [comment]
Ah ok, that helps to know. I thought the `missing` attribute had to do with their registration status.

Also, thanks for your input. That was the file I was referring to and I'll make sure to include links next time!
