### ISSUE TITLE
Unable to view a conference

### ISSUE THREAD

**Issue by ViditChitkara** [openSUSE/osem#1944]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

Conference could not be viewed when browsing the site as non-admin
![mastodon-3](https://user-images.githubusercontent.com/22616017/34687937-62831762-f4d6-11e7-8bb8-494c99948daf.jpg)
![mastodon-4](https://user-images.githubusercontent.com/22616017/34687941-6751d51c-f4d6-11e7-9fdc-050017e2290c.jpg)

**Steps to reproduce:**

View any upcoming or past conference( /conferences/:id )

**Comment by differentreality** [comment]
Any chance you haven't run the migrations?

**Comment by ViditChitkara** [comment]
Yes indeed, I missed running the migration. Noticed this on demo.osem.io perhaps the same problem exists there. Closing this now!
