### ISSUE TITLE
Add Validation to lodgings website.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1948]
**I'm submitting a ..**
- [x] Feature Request

**Current behavior:**
Url validation is missing from lodging website while creating a new lodging.So it will accept any string we give as input.
Maybe we should validate it as a url because the same is visible in the conference splashpage if we showcase lodgings.

**Comment by michaelkl** [comment]
I suggest changing `<input type="text">` to `<input type="url">` for `website_link` control of Lodging edit form and let a browser care of the rest.

**Comment by rishabhptr** [comment]
Closing this issue as this was addressed in #2012
