### ISSUE TITLE
Organization admin can access all revision history

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1949]
**Current behavior:**
Organization admin can see whole conferences revision history

**Expected correct behavior:**
Organization admin should only be able to see  its organization's conference history.

**Steps to reproduce:**
Create a user organization admin.
log in as user
view revision history
![a](https://user-images.githubusercontent.com/25618739/34721942-cb47f648-f56a-11e7-89f0-01e02e1eebc1.png)

**Comment by differentreality** [comment]
That's not actually accurate. The organization admin can only see versions related to the conferences of the organization. However, as your screenshot shows, versions related to users (which is independent of conferences) also show up.
