### ISSUE TITLE
Remove create organization button

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1950]
**Current behavior:**
View for organization admin
![fafafa](https://user-images.githubusercontent.com/25618739/34722063-51c591b2-f56b-11e7-8a51-58e8529a7aba.png)

**Expected correct behavior:**
Only superadmin should be able to see the create organization button.
Organization admin can see  delete,edit  button for his organization only.

**Steps to reproduce:**
Create a user organization admin
sign in as user
view organizations

**Comment by differentreality** [comment]
Is this referring to admin/organizations#index ?

**Comment by rahul2240** [comment]
yes @differentreality

**Comment by membrq** [comment]
Hi all! I'd like to claim this

**Comment by membrq** [comment]
I've looked over these two files and I don't see a `superadmin` role defined. Am I looking in the wrong place?

https://github.com/openSUSE/osem/blob/master/app/models/admin_ability.rb
https://github.com/openSUSE/osem/blob/master/app/models/ability.rb


Am I looking in the wrong place?

**Comment by differentreality** [comment]
@rahul2240 did not mean there is a superadmin role (please amend properly),  he is referring to admin users (there is the is_admin attribute in User model)

**Comment by ankitbhardwaj78** [comment]
@differentreality  can i take this issue if it is avilable
