### ISSUE TITLE
Error persists to next page when we reverse the role of an organizer.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#1951]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
When we add an organizer to the conference and we try to reverse the role(by toggling yes/no in the list),we cant do that because the conf. should have atleast have one organiser but the error for same carries onto the next page.

![screenshot from 2018-01-09 18-19-37](https://user-images.githubusercontent.com/26951824/34722191-cb7f33aa-f56b-11e7-842e-1fb97974929b.png)

![screenshot from 2018-01-09 18-19-21](https://user-images.githubusercontent.com/26951824/34722198-d0af3ad2-f56b-11e7-8370-34e66588ae01.png)

**Expected correct behavior:**
In roles controller for the given condition we are redirecting with a error message but we are redirecting to the same page so message comes when we visit next page.I think a flash message would suffice.

**Steps to reproduce:**
In a conference add organizer role to a user and try to reverse it.

**Comment by ankitbhardwaj78** [comment]
@rishabhptr cna i claim this??

**Comment by rishabhptr** [comment]
@ankitbhardwaj78 Yes please, go ahead!

**Comment by snpd25** [comment]
@rishabhptr , Is this issue fixed? as I can't reproduce the error, It's working fine for me.

**Comment by rishabhptr** [comment]
@snpd25 Yes this issue is quite old now, it seems to be fixed in latest build. :+1:
