### ISSUE TITLE
Failed to upload organisation picture

### ISSUE THREAD

**Issue by namangupta01** [openSUSE/osem#1958]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

Getting error while uploading picture of Organisation while creating organisation.

![screen shot 2018-01-12 at 12 01 36 pm](https://user-images.githubusercontent.com/20709985/34862927-da963194-f792-11e7-8dff-c73093aef315.png)

**Steps to reproduce:**

Try to create new organisation with organisation picture.

**Comment by differentreality** [comment]
@namangupta01 you haven't provided any information on the image you are trying to upload. Please do.

Do you have imagemagick installed on your system?

**Comment by namangupta01** [comment]
Oh! imagemagick was not installed that's why it was causing problem.
