### ISSUE TITLE
Remove submit proposal and booth once the conference is over.

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#1963]
**Current behavior:**
User can not submit the proposal once the conference is over so there is no use of submit proposal button (redirecting to proposal#new form) on the index page, same with add booth button in my booth request.
![proposal](https://user-images.githubusercontent.com/25618739/34905919-b77cd2fc-f888-11e7-8175-70ad726069ad.png)

**Expected correct behavior:**
Add booth button from my booth request and add proposal should not be present once the conference is over.

**Comment by AnkushMalik** [comment]
can i work on your latest 2 issues?

**Comment by differentreality** [comment]
By add button you actually  mean the 'Submit Proposal' button, I assume.

**Comment by rahul2240** [comment]
when we do not have any booth request or proposal then submit proposal and booth should not be there . when we have submitted booth  then going to my booth request,you will find a button for add booth which should also be removed , same for proposal.

**Comment by differentreality** [comment]
The buttons only appear when it is possible to create a new request. You are probably logged in as an admin, and an admin can do everything. I think your point, though, is for non-admin users to be able to see relevant buttons. And this already happens.

Can you please double check and update the issue accordingly?
