### ISSUE TITLE
Installation instructions not based on docker

### ISSUE THREAD

**Issue by jgrocha** [openSUSE/osem#1975]
**I'm submitting a ..**
- [ ] Bug Report
- [X] Feature Request

**Current behavior:**

The current install instructions are based on docker.

**Expected correct behavior:**

Following the docker based install does not works on a cloud server with only 2gb of RAM.

**Steps to reproduce:**

Create a virtual machine with only 2Gb os RAM and install OSEM using the Docker instructions.

**Other information:**

It would be great to have detailed instructions how to run OSEM without docker and using Apache and Passenger, for example.

This are old instructions at [opensuse.org](https://news.opensuse.org/2015/04/23/osem-in-10-simple-steps/)

**Comment by differentreality** [comment]
I think too, that we should make available installation instructions without docker or vagrant. Lately a lot of ppl had issues with vagrant as well, and there was no alternative for them.

**Comment by adrianovieira** [comment]
Hi! I've done some work on this.

My findings on this are bellow as simple sample. ;)

Please, let me know what you think about.  :)

---
# CEntOS-7 Setup

Seting up on a minimal CEntOS-7

# Install ruby
`yum install -q -y https://github.com/feedforce/ruby-rpm/releases/download/2.4.2/ruby-2.4.2-1.el7.centos.x86_64.rpm`

# install bundler
`gem install bundler`

# Install nodejs repository
`curl -sL https://rpm.nodesource.com/setup_9.x | bash -`

# Install nodejs and devel tools
`yum install -q -y git make gcc gcc-c++ libxml2-devel libxslt-devel nodejs screen mariadb mariadb-devel sqlite-devel ImageMagick bzip2`

# install phantomjs
```
curl -L --silent https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -o /tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar jxvf /tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /tmp/  phantomjs-2.1.1-linux-x86_64/bin/phantomjs
mv /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
```
# install apache and apache devel libs
`yum install -y libcurl-devel httpd httpd-devel apr-devel apr-util-devel`

# install SGBD
`yum install -y mariadb-server`

# enable mariadb and apache server serices
```
systemctl enable mariadb
systemctl enable httpd
```
# install passenger
`gem install --no-document passenger --version 5.1.12`

# setup passenger in apache2
`passenger-install-apache2-module --snippet > /etc/httpd/conf.modules.d/passenger_alias.load.conf`

# install passenger apache module
```
passenger-install-apache2-module --auto
if [ ! $? -eq 0 ]; then echo [ ERROR ]; exit 1; fi
```

# checking passenger setup
```
passenger-config validate-install --auto --validate-apache2
if [ $? -eq 0 ]; then echo [ OK ]; else exit 1; fi
```
# setup apache vhost for OSEM
```
cat << EOF > /etc/httpd/conf.d/00-osem.conf
<VirtualHost *:80>
  ServerName default
  ServerAdmin root@localhost
  DocumentRoot /var/www/html/osem/public

  # RailsEnv production (this is the default)
  #SetEnv RAILS_ENV production

  <Directory /var/www/html/osem/public>
    Allow from all
    Options -MultiViews
  </Directory>
</VirtualHost>
EOF
```

# open fw ports as a sample
```
iptables -I INPUT -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -p tcp --dport 443 -j ACCEPT
```

# .env.production setup
- get osem master branch
`git clone https://github.com/openSUSE/osem.git /var/www/html/osem`
**or** `curl -sL https://github.com/openSUSE/osem/archive/master.zip -o /tmp/osem.zip && unzip /tmp/osem.zip -d /tmp && mv /tmp/osem-master /var/www/html/osem`

`pushd /var/www/html/osem`

# setup env vars
```
cp dotenv.example .env.production
export SECRET_KEY_BASE=ef2eb183bd5b1539ee6ee63d9b2376d0b66785d092176a3c83bde1ef49d4092b404348f8a391661542e326bc4151da8b7b293b24deb4090c09152fdaad8ef5bb
export RAILS_ENV=production
export OSEM_NAME="DevOps-DF LEG"
```
```
echo '# .env.production setup
SECRET_KEY_BASE=ef2eb183bd5b1539ee6ee63d9b2376d0b66785d092176a3c83bde1ef49d4092b404348f8a391661542e326bc4151da8b7b293b24deb4090c09152fdaad8ef5bb
RAILS_ENV=production
OSEM_NAME="DevOps-DF LEG"' >> .env.production
```
```
cat << EOF > /var/www/html/osem/config/database.yml
production:
 adapter: mysql2
 encoding: utf8
 database: osem
 username: username
 password: password
EOF
```

# install bundle
```
bundle install --deployment --without test development
bundle exec rake assets:precompile
```

# stmp setup
```
echo '
OSEM_SMTP_ADDRESS="smtp.example.com"
OSEM_SMTP_PORT="587"
OSEM_SMTP_USERNAME="username"
OSEM_SMTP_PASSWORD="secret"
OSEM_SMTP_AUTHENTICATION="true"
OSEM_SMTP_DOMAIN="example.com"
OSEM_SMTP_ENABLE_STARTTLS_AUTO="true"
OSEM_SMTP_OPENSSL_VERIFY_MODE="none"' >> .env.production
```
```
cat << EOF >> /var/www/html/osem/db/seeds.rb
# Create Admin user
"user = User.find_or_initialize_by(email: 'admin@localhost.osem', name: 'Adminstrator',
                                  username: 'admin', is_admin: true,
                                  biography: 'OSEM Adminstrator user.')
user.password = 'password123'
user.skip_confirmation!
user.save!

# Create sample organization
organization = Organization.find_or_initialize_by(name: 'DevOps-DF LEG',
                                                  description: 'DevOps-DF Local Enthusiasts Group')
organization.save!
"
```

# DB setup
- systemctl enable mariadb
- systemctl enable httpd
- mysql_secure_installation
- CREATE USER 'db_osem_username'@'localhost' IDENTIFIED BY 'db_osem_userpass';
- GRANT ALL ON osem.* TO 'db_osem_username'@'localhost';
```
systemctl start mariadb
mysql -e "GRANT ALL PRIVILEGES ON osem.* to 'username'@'localhost' IDENTIFIED BY 'password';"
bundle exec rake db:setup
```

# Filesystem Ownership
- File permissions, recursive
- Dir permissions, recursive
- SELinux serve files off Apache, resursive
- Allow write only to specific dirs
```
mkdir -p /var/www/html/osem/log
mkdir -p /var/www/html/osem/tmp/uploads
chown apache:apache -R /var/www/html/osem
cd /var/www/html/osem/
find . -type f -exec chmod 0644 {} \;
find . -type d -exec chmod 0755 {} \;
chcon -t httpd_sys_content_t /var/www/html/osem -R
chcon -t httpd_sys_rw_content_t /var/www/html/osem/tmp -R
chcon -t httpd_sys_rw_content_t /var/www/html/osem/public -R
chcon -t httpd_sys_rw_content_t /var/www/html/osem/log -R
chcon -t httpd_sys_rw_content_t /var/www/html/osem/tmp/uploads
```

# Start httpd
`systemctl restart httpd`

**Comment by adrianovieira** [comment]
I've just started to develop an Ansible Role to perform automated installation. 
The upstream repository is:
https://gitlab.com/adrianovieira/ansible-role-opensuse.osem.webserver

It is in the beginning, but if you can either help or support it'd be great, too.

**Comment by Ana06** [comment]
@adrianovieira amazing work! :cupid: what about a PR? It would be easier to improve it once we have something as based:wink:

**Comment by hennevogel** [comment]
OSEM is not a desktop app, deploying it can have **serious** consequences for your computer/network and most importantly for the users that sign up.

IMHO teaching people how to deploy a rails app is out of scope for us. As soon as you will add installation instructions to our code base you are (morally) responsible for what happens when people follow them. This will also be outdated faster then you can say 'distribution version'.  

We can make it easy with tools like heroku/docker or maybe collect links to tutorials/books/howtos that give an introduction to this complex topic below a **BIG FAT WARNING**. But please not in our code base.

**Comment by Ana06** [comment]
I am using it for development without docker. Some people have reached me in the last months asking how to set it up, so I think that at least this case may be documented. For production, least the steps linking official documentation may be useful as well. :thinking:

**Comment by adrianovieira** [comment]
Hi, @Ana06 ! 

Thanks by considering to send a PR.

Yes. Everybody iare welcome to send a PR there.

**Comment by aspiers** [comment]
I'm a bit confused by this issue.  Firstly the title is "Installation instructions not based on docker" but `INSTALL.md` *is* based on Docker.  Did you mean it to say "*Need* installation instructions not based on docker"?

Secondly:

> Expected correct behavior:
>
> Following the docker based install does not works on a cloud server with only 2gb of RAM.

which sounds like you are saying you expect the docker-based install to not work.  Did you mean to write:

> Expected correct behavior:
>
> Following the docker based install *does* work on a cloud server with only 2gb of RAM.

?

**Comment by aspiers** [comment]
Not sure why this was closed just now?

[**@hennevogel**](https://github.com/hennevogel) commented on [3 Aug 2018, 09:46 BST](https://github.com/openSUSE/osem/issues/1975#issuecomment-410188367 "2018-08-03T08:46:53Z - Replied by Github Reply Comments"):
> IMHO teaching people how to deploy a rails app is out of scope for us.

Yes, that makes sense.

> As soon as you will add installation instructions to our code base you are (morally) responsible for what happens when people follow them.

I disagree with this, sorry.  It's entirely possible to provide instructions with caveats and disclaimers at the top which clearly set expectations.  The typical response to this is "but some people will ignore those caveats / disclaimers" and that is true - but it is an easily rebutted argument, since anyone who ignores them gets what they deserves, and I don't see why the responsible users who actually read documentation carefully should be punished for the behaviours of the irresponsible ones.

> This will also be outdated faster then you can say 'distribution version'.

Again, this is easily addressed with a clear warning that the instructions are likely to get out of date, and clear setting of expectations around the level of support which can be offered by the community.

> We can make it easy with tools like heroku/docker or maybe collect links to tutorials/books/howtos that give an introduction to this complex topic below a **BIG FAT WARNING**.

Yes, that's the correct approach IMHO.  Otherwise it risks deterring talented and motivated people who could potentially become valuable contributors if they had some minimal docs to get them started in the right direction.

> But please not in our code base.

How about the wiki then?

**Comment by hennevogel** [comment]
>  Otherwise it risks deterring talented and motivated people who could potentially become valuable contributors if they had some minimal docs to get them started in the right direction.

development != production

For developing we have a development environment and documentation. For trying osem we have the demo server.
