### ISSUE TITLE
carrierwave migration fails with NoMethodError: undefined method `read' for nil:NilClass 

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#1976]
**I'm submitting a ..**
- [x] Bug Report

The migration fails to run.
https://github.com/openSUSE/osem/blob/master/db/migrate/20171130172334_rebuild_conference_pictures.rb

Adding the following works.

```
if conference.picutre?
  conference.picture.recreate_versions!
end
```

**Comment by kostino** [comment]
I am also having problems running the specified migration.
<img width="972" alt="screen shot 2018-03-17 at 15 51 38" src="https://user-images.githubusercontent.com/27733299/37556193-3a55c1ea-29fb-11e8-9e5c-b8b613858f7d.png">

**Comment by AndrewKvalheim** [comment]
Upstream: carrierwaveuploader/carrierwave#2186
