### ISSUE TITLE
Installation: docker-compose.yml.example is missing

### ISSUE THREAD

**Issue by etuardu** [openSUSE/osem#1980]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
It is not possible to follow the installation instruction in [`INSTALL.md`](https://github.com/openSUSE/osem/blob/master/INSTALL.md):

> First of all, copy `docker-compose.yml.example` to `docker-compose.yml` [...]

as `docker-compose.yml.example` is not found.

**Expected correct behavior:**
Find the file and have the possibility to follow the subsequent instructions.

**Steps to reproduce:**
* Download and extract the tar-gzipped source code for osem 1.0 from the [release page](https://github.com/openSUSE/osem/releases/tag/v1.0)
* Attempt to copy `docker-compose.yml.example` to `docker-compose.yml`

**Other information:**

**Comment by differentreality** [comment]
Hi @etuardu, osem 1.0 did not have docker yet. Are you sure you are reading the installation instructions for osem 1.0 and not the ones found on github (https://github.com/openSUSE/osem/blob/master/INSTALL.md)?

**Comment by etuardu** [comment]
Hello, I am following the installation procedure that you have linked.

The *Download* section links to the release page for version 1.0:

> You can find the latest OSEM releases on our [release page](https://github.com/openSUSE/osem/releases/latest) [...]

Then, the section *Deploy* states that:

> You can deploy OSEM using Docker and Docker-Compose.

**Comment by differentreality** [comment]
Sorry, version 1.0 does not have the docker files.

The link refers to our current master, not version 1.0. 

The zip for version 1.0 contains another INSTALL.md file which you can refer to.
