### ISSUE TITLE
travel info at the registration page should have a button for local people

### ISSUE THREAD

**Issue by tampakrap** [openSUSE/osem#2011]
When going to the registration page of a conference, I am asked to put my travel info. In case though I live in the place that the conference is taking place, it doesn't make sense to put any info there. So I think it would be a cool feature to have a button that defines that I am local and I don't need to put any travel info.

**Comment by Ana06** [comment]
As mentioned in #2333, it may be better to completely get rid of this information.

**Comment by AndrewKvalheim** [comment]
The travel questions have been [completely removed](https://github.com/openSUSE/osem/pull/2591).
