### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by halsk** [openSUSE/osem#2016]
Hello, I'm Hal from Code for Japan. I am planning to use OSEM for my conference. And I have translated some words into Japanese on the Transifex project site.
Is it possible for you to  review my text?

**Comment by differentreality** [comment]
Hi @halsk, I cannot review your japanese translation, as I do not speak japanese. Ideally there should be a second person who can review the translations to confirm them, before they are published.

**Comment by halsk** [comment]
Hi @differentreality , Thank you for replying. I understand it. I think I can find a second person who can review the changes if it does not require too much knowledge of OSEM itself. Can you assign me or him as a reviewer of the transifex project?

**Comment by halsk** [comment]
Hello @differentreality , I don't want to bother you much, but my issue is not resolved yet, I have translated  599 texts and been waiting for review. But if there is no reviewer who can check Japanese, what should I do? I can check the translation in my local environment. Or I can find my friend who can check the translation as well. Please tell me if you have an idea for moving this forward.
