### ISSUE TITLE
N+1 queries with rolify

### ISSUE THREAD

**Issue by bear454** [openSUSE/osem#2018]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

Every call to `User#has_role?` perfoms a query against `roles`.

**Expected correct behavior:**

Rolify project recommends pre-loading roles and using `has_cached_role?` instead, to avoid N+1 queries. https://github.com/RolifyCommunity/rolify#cached-roles-to-avoid-n1-issue

**Steps to reproduce:**

Observe logs while running `AdminAbility.new(User.last)` - observe 7 instances of `Role Load`

**Other information:**

**Comment by differentreality** [comment]
:+1:  Wanna open a PR for it?

**Comment by bear454** [comment]
I thought I had one ready, but it needs some more ♥.
