### ISSUE TITLE
Error in admin/events#show when voting period is closed

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#2019]
![screenshot from 2018-03-30 17-20-38](https://user-images.githubusercontent.com/4322737/38140930-bd7cd192-343e-11e8-85e3-d03fff65a1cb.png)

**Comment by jdg006** [comment]
I would like to take a crack at this issue. Is there anything else I should know about this bug before I get started?

**Comment by differentreality** [comment]
@jdg006 if there is something you would like to know, ask.

**Comment by snpd25** [comment]
@differentreality , Is the issue fixed, if not can you provide an insight on how to reproduce this?

**Comment by kolja-lucht** [comment]
@differentreality Hey! Just came across this issue and was wondering if you still need help with it? I'd be happy to give it a go. Just let me know :)

**Comment by differentreality** [comment]
@kolja-lucht sure, please go ahead! Thank you :)

**Comment by eel87** [comment]
@kolja-lucht are you working on this?

**Comment by kolja-lucht** [comment]
Hey @eel87 
no, hadn't had a chance to check it out throughly. You can take it, if you want 😊

**Comment by vladyio** [comment]
Hey, @differentreality! 

I wonder if this issue is still relevant and whether anyone is working on it?

**Comment by differentreality** [comment]
Hi @vladyio :wave: 
Sorry for the late reply, looks like this was fixed in https://github.com/openSUSE/osem/commit/9908f885707038b3c5a70900d59b864e8bd192fe
Thanks for pointing it out!

Would you like some suggestions for other issues you can work on?
