### ISSUE TITLE
pg gem enabled 

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#2021]
The gem is currently commented out, which means if you want to use postgresql you have to change your Gemfile/Gemfile.lock

What about we have both postgresql and mysql available by default (not commented out)?

**Comment by bear454** [comment]
I'd rather _not_ load gems that won't be used; the memory footprint for `osem` is already pretty big. Consider adding an environment variable for database, and loading gem conditionally; e.g. https://github.com/rspec/rspec-core/blob/master/Gemfile#L8

**Comment by jakrzus** [comment]
Looks like already fixed: 
`gem 'mysql2'`
`gem 'pg'`
