### ISSUE TITLE
Quick deselection of all checkboxes in admin/splashpages#new

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#2022]
Add a button to uncheck all checkboxes

**Comment by jdg006** [comment]
I would be happy to take on this issue. Are there any other specifics I should know before getting started?

**Comment by differentreality** [comment]
@jdg006 before your comment, you can see that there is an open PR for this issue already by someone else.

Please pick another issue to work on. Thank you!

**Comment by snpd25** [comment]
@differentreality , Is this issue fixed or I can work on it?

**Comment by differentreality** [comment]
@snpd25 sure :+1: go ahead, if you haven't already started working on something else!
