### ISSUE TITLE
(There are not) notifications of revision comments to CFP submiters

### ISSUE THREAD

**Issue by olea** [openSUSE/osem#2024]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

When a revisor add a comment  (say at https://OSEMs/admin/conferences/2018/program/events/1) there is not a mail notification neither for submiters or other revisors (members of CFP role group).  

**Expected correct behavior:**

Each comment or other change should be notified related persons by email too. Users need to be sure feedback is received in time.

**Comment by AndrewKvalheim** [comment]
It’s not clear to me what this is suggesting. Email notifications of comments are [already sent](https://github.com/openSUSE/osem/pull/699) to reviewers, and submitters have no access to read comments.

**Comment by hennevogel** [comment]
indeed
