### ISSUE TITLE
Certificate of attendance

### ISSUE THREAD

**Issue by jpescola** [openSUSE/osem#2042]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature Request

**Current behavior:**
resource not found

**Expected correct behavior:**
System show a link to generate pdf certificate of participation in each event in which it was attended

**Comment by Ana06** [comment]
@jpescola can you provide more information? where is the link you speak about?

**Comment by hennevogel** [comment]
@Ana06 this is a feature request.

If an event wants to hand out certificates it can. nothing OSEM will help you with, sorry.
