### ISSUE TITLE
Clarify the vagrant version needs to be a > 2.0

### ISSUE THREAD

**Issue by esparta** [openSUSE/osem#2043]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
If I run `vagrant up` on the development machine, it got an error not exactly clear..
```
The box 'opensuse/openSUSE-42.2-x86_64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below: 

URL: ["https://atlas.hashicorp.com/opensuse/openSUSE-42.2-x86_64"]
Error: The requested URL returned error: 404 Not Found
```
![osem_vagrant-1 8 6](https://user-images.githubusercontent.com/1037088/39510836-02035a00-4da0-11e8-8b7a-2a6b1199b43c.png)

**Expected correct behavior:**
`vagrant up` should start the normal process (download the box, fire up bootstrap.sh, etc)

**Steps to reproduce:**
Having an old version ( minor than 2.0, not clear),
1.- Execute `vagrant up`
2.- Error appears

**Comment by Ana06** [comment]
As we want to get rid of vagrant, I guess we can close this....
