### ISSUE TITLE
Provide og tags to info about panel/schedule/conference

### ISSUE THREAD

**Issue by hellcp** [openSUSE/osem#2046]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature Request

**Current behavior:**
Currently links appear as generic link to generic website

**Expected correct behavior:**
Twitter/Facebook embeds information about panel/schedule/conference in meta og: tags, like opensuse.org does (bonus points for color theme ;) )

**Steps to reproduce:**
![twitter](https://user-images.githubusercontent.com/30577011/39693956-fa85a95a-51e5-11e8-922e-5a08a5f8127d.png)

![discord](https://user-images.githubusercontent.com/30577011/39693983-0e62b04e-51e6-11e8-8efe-268ca8255af6.png)

**Other information:**
Example of opensuse.org:

![o-o](https://user-images.githubusercontent.com/30577011/39694027-2c26702a-51e6-11e8-9612-6434605f5935.png)

**Comment by robotscissors** [comment]
I am new to contributing to open source projects, can I take this one?

**Comment by hellcp** [comment]
Go ahead, nobody can stop you ;)
