### ISSUE TITLE
Enable Rails Rubocop cops

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2048]
Rails cop are disabled by default in Rubocop as not all Ruby projects are Rails.

**Comment by mgiagante** [comment]
Hello! It's my first time contributing to OSEM. I'd like to take this issue.

**Comment by andlrb** [comment]
Hi @mgiagante, this issue was fixed by @bear454 in #2050, so I think this can be closed.

**Comment by Ana06** [comment]
@mgiagante sorry I didn't answer before... I skipped the comment :see_no_evil: As @andlrb says, it is already fixed :smile:
