### ISSUE TITLE
commercial speakerdeck integration not working

### ISSUE THREAD

**Issue by mbgg** [openSUSE/osem#2061]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
When adding a SpeakerDeck URL as commercial to your talk, but it doesn't show anything on the SpeakerDeck tab (see https://events.opensuse.org/conference/oSC18/program/proposal/1789#1 which actually added the SpeakerDeck URL https://speakerdeck.com/mbgg/kdump-under-the-hood#).

**Expected correct behavior:**
SpeakerDeck integartion should show the slides from the SpeakerDeck.

**Steps to reproduce:**
Go to  https://events.opensuse.org/conference/oSC18/program/proposal/1789#1
Select the SpeakerDeck tab
It should show the content of https://speakerdeck.com/mbgg/kdump-under-the-hood# but does not.

**Comment by mbgg** [comment]
Looking into the HTML created out of OSEM, It seems, we miss "https:" prefix when creating the speakerdeck URL:
<iframe allowfullscreen="true" allowtransparency="true" frameborder="0" height="315" id="talk_frame_445904" mozallowfullscreen="true" src="//speakerdeck.com/player/b74edd61207e4c49a2fe3d36dfafaa9a" style="border:0; padding:0; margin:0; background:transparent;" webkitallowfullscreen="true" width="446"></iframe>

**Comment by Ana06** [comment]
It could be that the error is here: https://github.com/openSUSE/osem/blob/a325eccc775e11cda90017e0eacfaf8232fd4aff/app/views/shared/_media_item.html.haml#L11
