### ISSUE TITLE
Using overcommit and git hooks to ensure code style rules are followed

### ISSUE THREAD

**Issue by andlrb** [openSUSE/osem#2072]
**I'm submitting a ..**
- [x] Feature Request

The [CONTRIBUTING.md](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md) guide mentions the use of rubocop to check code style. Rubocop is a great tool, but it's easy to forget to run it before pushing your PR.

That being said, I think introducing [overcommit](https://github.com/brigade/overcommit) and running rubocop on each commit would ease the flow of development while keeping the same high standards of code quality and not having automated tests fail when a PR is submitted.

**Comment by andlrb** [comment]
One of the downsides of this is that there would be an extra step in installing OSEM, but it wouldn't be one that makes the project unusable if is not completed.

**Comment by bear454** [comment]
Would you consider adding some documentation for implementing the git hooks developer-side? For my part, I'm not fond of explicitly implementing git hooks - there's just too much security risk.

**Comment by andlrb** [comment]
That's reasonable and sure, sounds like a good idea to me. Overcommit generates a YML configuration file which holds what tools need to be run on a git hook (e.g: rubocop on pre-commit), but I don't know if I should include that file as well, so that it doesn't get generated each time a user wants to install it, or add it to gitignore and specify in the documentation what pre-commit tools are preferred to be used.

**Comment by bear454** [comment]
@andlrb : here's an example: the github hook config is included in the project, and documented in the code, but not enabled by any automatic means. https://github.com/suse/azurectl#basics

Maybe my fear is irrational here, but what prevents an overcommit config like:
```
PreCommit:
  LOL:
    enabled: true
    command: ['rm', '-rf', '~']
```

**Comment by andlrb** [comment]
Thanks @bear454, that's what I had in my mind too, but just wanted to make sure that's the way to do it. Although I doubt a commit with that config would pass code review, I can understand why you'd be worried about that kind of scenario. 

I'll submit a PR soon :) 
Thanks for your help so far!
