### ISSUE TITLE
Repeated Sessions

### ISSUE THREAD

**Issue by MysterAitch** [openSUSE/osem#2085]
Is it possible to create an event/session (unsure of correct terminology) and allow it to be scheduled more than once?

Currently it appears only once on the schedule page to drag/drop to a date/time.

**Comment by differentreality** [comment]
No, that doesn't exist. 
This is quite similar to https://github.com/openSUSE/osem/issues/13 so feel free to comment there if you have any other ideas/questions regarding this.

**Comment by MysterAitch** [comment]
While it is similar, I'm not sure it is the same as this query. Here I am asking about a specific talk/event being given in a morning and then repeated in an afternoon session, or a keynote/other session being given twice on two separate days of a schedule. 

While this does apply to e.g. breakfast/lunch/tea breaks, the impression I get is that #13 is focussed more on "global" events that spread across multiple rooms/streams/tracks that admins can add (as opposed to repeated instances of a specific event/session).
