### ISSUE TITLE
Document on how to upgrade an old version of OSEM

### ISSUE THREAD

**Issue by redimido** [openSUSE/osem#2091]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature Request

**Current behavior:**

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by Ana06** [comment]
related to https://github.com/openSUSE/osem/issues/1975

**Comment by redimido** [comment]
Thank you.
Please consider this case:
- I did the set-up for our event on 2016
- for 2017 other team tried their own method without osem. That did not work so well
- for 2018 I am using osem again, but it still has bugs from 2016 that I believe were all fixed
- I am not sure if the new code Will work with the DB layout from 2016, and/or if there are new config entries to set.

I am not even sure where to look for the osem version!

Hope you can comment. I went live with the 2016 version.

**Comment by Ana06** [comment]
@hennevogel now that we also updated an old version, is there some documentation we can write down? :thinking:

**Comment by hennevogel** [comment]
When we do a release all of this will be in the release notes. 

@redimido we have one release here https://github.com/openSUSE/osem/releases
more will follow.
