### ISSUE TITLE
Better User Onboarding

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#215]
People seem to be confused about the two-step way of registering for a conference. They think they are registered for the conference after creating an OSEM account.

Proposal: Registering for your first conference should transparently create an OSEM account (unless you have one, which could be detected through the email address).

**Comment by jospoortvliet** [comment]
I was wondering if there has been any progress on this - seeing one part got merged but I dunno how much that deals with this issue... Before we can use it for 2015, this is kind'a a must-have feature... as the painful onboarding it turns off a lot of people and we want to *attract* people to our event :D

**Comment by ChrisBr** [comment]
@jospoortvliet Thanks for your response!
For events.o.o we now use the opensuse account, so it's not necessary to create an OSEM account explicit! But an explicit registration for the conference is still necessary!
But I don't have a good idea at a first glance how we can improve the onboarding with the detour to the opensuse registration proxy!
@hennevogel @differentreality maybe we should discuss / think about this issue again

**Comment by hennevogel** [comment]
We definately need to think about onbording. Not only limited to the sign up process but in general.

**Comment by jospoortvliet** [comment]
We're considering using OSEM again for the ownCloud conference - but forcing people to sign up twice as it is today is not going to work. If it isn't possible to present a single page where you at once can register for account AND conference, I'll have to use another tool :(

It can't be that hard to add user registration to the registration for a conference, is it? I don't care for a second about email verification - that is an entirely unnecessary step in the process.

I'll be announcing the conference next week so I guess I can forget about this - but I don't understand why this isn't a bigger priority.

@ChrisBr you are saying that you don't allow people to register for the openSUSE conference without having created an openSUSE account? You really don't want people to register for the openSUSE Conference, do you? That is a HUGE barrier for many people, not much better than asking an entree fee!

Heck, I PREFER giving my credit card details and paying 10 bucks over creating another account on another random website... And I know that goes for many, if not most internet users. Making people give their mail account and lots of other details, making them go through a verification step and then ANOTHER registration step just to say "yes, I am coming" - it's no surprise we always had so many people show up who had not registered!

Sorry for the rant, but registration is the first thing users see from a conference system - and in case of OSEM, it is the last many see, too. That just plain sucks.

**Comment by hennevogel** [comment]
Just for you :rabbit: I'll spend an evening on this on Thursday.

:kiss: your Henne

**Comment by jospoortvliet** [comment]
You're too nice. And that's serious :D

You will get beer from me in Den Hague.

**Comment by hennevogel** [comment]
I'm Franconian. Never promise what you can't keep!

**Comment by jospoortvliet** [comment]
@hennevogel not an empty promise. Just remind me there and you'll get your beer.

**Comment by hennevogel** [comment]
@jospoortvliet Käsebier is not Bier :stuck_out_tongue_winking_eye:

**Comment by jospoortvliet** [comment]
@hennevogel I'll get you something Belgian, OK?

**Comment by hennevogel** [comment]
@jospoortvliet no reason to get nasty...

**Comment by jospoortvliet** [comment]
@hennevogel what beer do you want...

**Comment by jospoortvliet** [comment]
Code is merged. @danimo you up for updating osem on conference.owncloud.org so we can open registration?
@hennevogel or is there a good reason not to (yet) get going? Master checkout is the only way, right?

**Comment by ChrisBr** [comment]
@jospoortvliet Unfortunately master checkout is the only way at the moment! We think about a release but I don't think this will happen the next few weeks ...

**Comment by jospoortvliet** [comment]
@ChrisBr ok, thanks. I guess we'll go that way then.

**Comment by ChrisBr** [comment]
@hennevogel @differentreality @jospoortvliet I think we can close this here, can't we?

**Comment by hennevogel** [comment]
Don't think, do :-)

**Comment by jospoortvliet** [comment]
Perfect ;-)

Related issue: #625 - not a huge deal but ppl should be able to reset their password from this dialog, too.
