### ISSUE TITLE
Switch to headless chromium

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#2150]
We currently use the phantomjs headless browser in capybara through poltergeist. Development of phantomjs has stoppped so we should replace it with something maintained. People move to headless chromium or firefox. We should too...

**Comment by bear454** [comment]
[Travis](https://docs.travis-ci.com/user/sauce-connect/) does support [Sauce Labs](https://saucelabs.com/open-source/open-sauce), though...

**Comment by bear454** [comment]
I submitted an application to Sauce Labs for an "open sauce" account.

**Comment by hennevogel** [comment]
chrome, chromium -> https://www.youtube.com/watch?v=zZ3fjQa5Hls&feature=youtu.be&t=90

**Comment by bear454** [comment]
Well, not exactly.

Chrome uses a different _binary_ than Chromium - we'd have to have Travis run with `google-chrome`, but locally run with `chromium` or... ? I'm just saying... the difference in binary names needs to be handled.

**Comment by hennevogel** [comment]
Well locally you can also have google-chrome, or yes you handle this. But that are rather minor thing I would say.

**Comment by bear454** [comment]
Okay, I have capybara working locally with selenium webdriver and headless Chrome _and_ headless Firefox... just need to fix a bunch of newly failing tests...

Also got the green light from Sauce Labs - we're in Open Sauce! So I'll add that to Travis.

**Comment by bear454** [comment]
Grmbl; I can't get Sauce to work right, and I've exhausted my free test time. So instead of merging breakage, I'm just going to submit with headless chrome on Travis. :/
