### ISSUE TITLE
Track/Difficulty dropdown not visible at program/proposals/new page

### ISSUE THREAD

**Issue by nikkhils** [openSUSE/osem#2222]
**I'm submitting a ..**
- [*] Bug Report
- [ ] Feature Request

**Current behavior:**

I have added tracks to my conference. After that when user goes on submit proposal at "program/proposals/new", "track dropdown" and "difficulty dropdown" is not available. However later if we edit the proposal, it shows the track/difficulty dropdown.

**Expected correct behavior:**

The submit proposal link should show track/difficulty dropdown for selection when she goes to program/proposals/new for the first time.

**Steps to reproduce:**

**Other information:**

**Comment by nikkhils** [comment]
I figured I could add content from _proposal_form.html.haml into new.html.haml to get these track/difficulty dropdowns. But it's not documented.. can close this once I get an official confirmation regarding what I tried was ok enough. Thanks.

**Comment by hennevogel** [comment]
We purposefully avoid a too crowded submit form so people will more likely submit. Once they submitted we remind them to complete the stuff.
