### ISSUE TITLE
Email is still displayed on talk page even if Email public is unchecked

### ISSUE THREAD

**Issue by meonkeys** [openSUSE/osem#2270]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**

On https://osem.seagl.org/conferences/seagl2017/program/proposals/290 , my email is displayed, but on https://osem.seagl.org/accounts/edit "Email public" is unchecked.

**Expected correct behavior:**

If "Email public" is unchecked, email address is not displayed on the talk page.

**Comment by snpd25** [comment]
@Ana06 , I want to work on this issue, but the code [here](https://github.com/openSUSE/osem/blob/b68b7ca4006fff612e39e1b9df41c9bff90ec1f7/app/views/proposals/show.html.haml#L40) looks fine to me. Where do you think lies the bug?

**Comment by Ana06** [comment]
@snpd25 have you been able to reproduce the issue?

**Comment by snpd25** [comment]
@Ana06 sorry for replying late. I got in some trouble with setting up the development environment, will get back to this, once that's fixed.

**Comment by Ana06** [comment]
@snpd25 

> @Ana06 sorry for replying late. I got in some trouble with setting up the development environment, will get back to this, once that's fixed.

To set up the development environment check the [development section of the CONTRIBUTING guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md#development-environment) and if something there is not clear or you need help, just ask! :wink:

**Comment by snpd25** [comment]
Thanks @Ana06 , I have mentioned the issue [https://stackoverflow.com/questions/54956329/error-message-asking-for-bundle-install-even-when-i-have-run-bundle-install](here) , please see if you need any other detail.

**Comment by Ana06** [comment]
@snpd25

> Could not find active_model_serializers-0.10.9 in any of the sources

The version that is in the Gemfile.lock of the gem is 0.10.8, so it shouldn't be installed when running `bundle install`. Can you please provide more details of how you have set up docker and what are to exactly trying to execute?

**Comment by Ana06** [comment]
@snpd25

> Could not find active_model_serializers-0.10.9 in any of the sources

The version that is in the Gemfile.lock of the gem is 0.10.8, so it shouldn't be installed when running `bundle install`. Can you please provide more details of how you have set up docker and what are to exactly trying to execute?

**Comment by snpd25** [comment]
I have installed `docker-compose` and was trying to execute this command:
`docker-compose run --rm osem bundle exec rake db:bootstrap`

**Comment by Ana06** [comment]
@snpd25 have you also run the following line from the guide?

```
sed "s/13042/`id -u`/" docker-compose.override.yml.example > docker-compose.override.yml

**Comment by snpd25** [comment]
Yes @Ana06 , I had done that, but nothing changed.

**Comment by Ana06** [comment]
@snpd25 I think you may have updated the branch with master in the middle of the setup. Feel free to reach me in freenode IRC (Ana06 is my nickname) or to ask in the  #osem channel. I think it will be easier than writing it in Github. :wink:

**Comment by Ana06** [comment]
@meonkeys I can not reproduce the error. Are you the responsible of the instance where you get the bug? Does it have the current master code?

**Comment by meonkeys** [comment]
@Ana06 I think it's old code. I'll ask the folks on the SeaGL SRE team.

**Comment by Ana06** [comment]
It seems this was fixed in https://github.com/openSUSE/osem/commit/6fa709a4de497a52100d14b458a975a4fe7ca645 This should fix the problem in your instance. Closing as this is already fixed in master.
