### ISSUE TITLE
How to install this step by step in Docker PLEASE???

### ISSUE THREAD

**Issue by underworld111** [openSUSE/osem#2284]
**I'm submitting a ..**
Tutorial request for Docker deply / installation

Hi all, I have a synology server running and really want to deploy this OSEM on my server through Docker. I have already got the docker installed and running. But how do I install or deply OSEM in Docker??

Tried Heroku too.....no luck. Needs step by step instruction PLEASE. Thank you very much.

**Current behavior:**

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by differentreality** [comment]
https://github.com/openSUSE/osem/blob/master/INSTALL.md#deploy-with-docker
