### ISSUE TITLE
Not possible to add multiple speakers to event

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#2311]
Multiple is set to false in https://github.com/openSUSE/osem/blob/master/app/helpers/application_helper.rb#L124
https://github.com/openSUSE/osem/pull/2074

It breaks the functionality of having multiple users per event.

**Comment by snpd25** [comment]
@differentreality , can you provide more insight on what is needed to be done here?
Thanks.

**Comment by differentreality** [comment]
A talk can be given by multiple speakers. We need to allow the user to add multiple speakers in the proposal form.

**Comment by snpd25** [comment]
@differentreality ,Turning the multiple option true , looked fine to me. 
![image](https://user-images.githubusercontent.com/32434989/54193772-c29ddf00-44e0-11e9-9ae4-3b146d081884.png)
and after saving.
![image](https://user-images.githubusercontent.com/32434989/54193889-009b0300-44e1-11e9-9238-54513cb5ddb9.png)
What else is required?

**Comment by differentreality** [comment]
Sure looks like it! Please open a pull request so that we can see the proposed changes in the code.

**Comment by AndrewKvalheim** [comment]
Completed in #2425
