### ISSUE TITLE
How to change the email address associated with an account

### ISSUE THREAD

**Issue by monochromec** [openSUSE/osem#2313]
**I'm submitting a ..**
- [ ] Bug Report
- [ ] Feature Request

**Current behavior:**

As I did't see anyhting in the UI: How do I verify / change the email address of an account
after successful login?
 

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by differentreality** [comment]
From your account `/accounts/edit` - there is a link for `Edit account` in the user menu (top right corner).

![Screenshot from 2019-03-11 10-07-00](https://user-images.githubusercontent.com/4322737/54108756-791c9980-43e5-11e9-83ba-5229f30087f7.png)
