### ISSUE TITLE
Installation with Docker fails: the compose file is invalid without a build context specified

### ISSUE THREAD

**Issue by felipelovato** [openSUSE/osem#2316]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

When running **docker-compose run --rm osem bundle exec rake db:bootstrap** an error:
```
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
```

**Expected correct behavior:**

Install project for development using docker.

**Steps to reproduce:**

```
$ git clone https://github.com/openSUSE/osem.git
$ cd osem
$ sed "s/13042/`id -u`/" docker-compose.override.yml.example > docker-compose.override.yml
$ docker-compose run --rm osem bundle exec rake db:bootstrap
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
```

**Other information:**

I was able to workaround this by just adding a ```context: .``` in docker-compose.override.yml
```yml
version: '2'
services:
  web:
    build:
      context: .
      args:
        CONTAINER_USERID: 501
```

If you find that it will help, I can submit a PR updating the ```docker-compose.override.yml.example```

I found an issue that seems to be related: https://github.com/docker/libcompose/issues/502

My system info:
macOS Mojave 10.14.3
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01

**Comment by hennevogel** [comment]
The problem is more that the service names mismatch. web != osem
