### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by albarnaz** [openSUSE/osem#2321]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
When access https://osem.io/ got a SSL problem

![image](https://user-images.githubusercontent.com/20689519/52144534-bdc64f80-2645-11e9-9d57-ff02e63b5931.png)

![image](https://user-images.githubusercontent.com/20689519/52144579-dc2c4b00-2645-11e9-8b58-b67fdf1b024c.png)

**Comment by hennevogel** [comment]
github pages do not support ssl

**Comment by hennevogel** [comment]
Ups sorry that is not true anymore.

**Comment by hennevogel** [comment]
waiting for dns to prapagate

**Comment by hennevogel** [comment]
done. thanks for reminding us @albarnaz :bouquet:
