### ISSUE TITLE
Revision history is broken

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2334]
The [revision history link](https://events.opensuse.org/admin/revision_history) in the profile dropdown is broken:

![image](https://user-images.githubusercontent.com/16052290/53010850-30556e80-343f-11e9-8de7-d77487e4fcaf.png)

**Comment by rahul2240** [comment]
@Ana06 Can I work on it?

**Comment by Ana06** [comment]
@rahul2240 sure! :wink:

**Comment by AndrewKvalheim** [comment]
I’ve been unable to reproduce this. Is it specific to the openSUSE instance?

**Comment by hennevogel** [comment]
This should be fixed by https://github.com/openSUSE/osem/pull/3094
