### ISSUE TITLE
Clear indication of accept/reject event without email

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#234]
The option 'without' email should be obvious to the cfp team at all times.

The cfp team member that will do the event acceptances/rejections does not necessarily know or remember if there is an email template in the email settings. 
Clear indication of whether or not the submitter of the proposal will be notified about the CFP team's actions is so very important.

(As a side note, probably for a separate issue, the email templates should not be activated unless they have content.)

**Comment by ChrisBr** [comment]
@differentreality @hennevogel 
Ping

Currently it's this way implemented:

No Mail template generated:
- Accept Event

Mail template generated:
- Accept Event
- Accept Event (Without email)
