### ISSUE TITLE
Dates fields are plain text

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2347]
When creating a new conference in admin/conferences/new, the data fields are plain text instead of date picker:

![image](https://user-images.githubusercontent.com/16052290/53103794-835a1f00-352e-11e9-8fd4-83e7d08c2340.png)

**Comment by Ana06** [comment]
Related to https://github.com/openSUSE/osem/issues/2349

**Comment by Ana06** [comment]
It should be fixable similarly to https://github.com/openSUSE/osem/pull/2354

**Comment by rahul2240** [comment]
@Ana06 removing the pickTime from [osem-datepickers.js](https://github.com/openSUSE/osem/blob/master/app/assets/javascripts/osem-datepickers.js) worked for me. Should I create a PR for it?

**Comment by Ana06** [comment]
@rahul2240 

> removing the pickTime from [osem-datepickers.js](https://github.com/openSUSE/osem/blob/master/app/assets/javascripts/osem-datepickers.js) worked for me.

I also needed to get rid of it in https://github.com/openSUSE/osem/pull/2354 It seems it is not a valid attribute (maybe it was deprecated at some point :confused:)

> Should I create a PR for it?

Sure! :wink:  If you want to take a look if there are more broken datapickers, it would be appreciated :bouquet:

**Comment by rahul2240** [comment]
@Ana06 on it :+1:
