### ISSUE TITLE
Creating an event fails from admin panel

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2348]
If after creating a conference, I try to create an event from the admin panel I get `undefined method 'enable_registrations?' for nil:NilClass`.

This stop happening once a call for events is created (which shouldn't be needed for an admin)

**Comment by ehrenfeu** [comment]
> I try to create a conference

This should probably read "*an event*" rather than "*a conference*", right?

**Comment by Ana06** [comment]
@ehrenfeu 

> This should probably read "_an event_" rather than "_a conference_", right?

right :see_no_evil: Thanks!

**Comment by uebmaster** [comment]
i get the same, but for the comment of ehrenfeu i suppose that there is not problem, then how works "events"?

**Comment by Ana06** [comment]
@uebmaster 

> i get the same, but for the comment of ehrenfeu i suppose that there is not problem, then how works "events"?

I am not sure what you mean, can you please elaborate?

**Comment by uebmaster** [comment]
> @uebmaster
> 
> > i get the same, but for the comment of ehrenfeu i suppose that there is not problem, then how works "events"?
> 
> I am not sure what you mean, can you please elaborate?

Hola, ya veo que hablas español y como veras mi ingles no es muy bueno que digamos jeje.

A lo que me referia es de que yo también experimente la misma situación que tu, cree una conferencia de ejemplo y al tratar de agregar un evento me marco error.

Pero por lo que veo que te contesto ehrenfeu al parecer no es un error del sistema, pero no entendí muy bien la respuesta que te dio de:"This should probably read "an event" rather than "a conference", right?"

Por lo que entiendo significa que "eventos" funciona de otra forma.

Entonces esa es mi pregunta: ¿Cómo funciona la sección de eventos?, es decir, ¿Cuál es la manera correcta de usarlo?

Gracias de antemano.

**Comment by Ana06** [comment]
@uebmaster sorry, but we need to write English in the issues/PRs to allow that other people can follow the conversation and participate on it. You can ping me in freenode IRC or write me an email in Spanish if you have concrete problems, but in the issues/PRs is where we decide what we do and how. We have to give everybody the opportunity to be involved in the discussion. Just using other words or providing more explanations may be enough so that we understand us. If something is not clear, just say it and I/we'll try to clarify it.

@ehrenfeu just corrected a typo in my explanation, but I have already corrected. So the issue is just what the description says. In other words, admins can not create events without creating a call for papers before. Instead they get an exception when trying to do this.

**Comment by Ana06** [comment]
@snpd25 just for next time, it is a good practice to write in the issue that you will take care of it before working on it. Just to avoid that two people work at the same time on it. :wink:

**Comment by snpd25** [comment]
@Ana06 , will take care of it from now onwards!

**Comment by uebmaster** [comment]
> @uebmaster sorry, but we need to write English in the issues/PRs to allow that other people can follow the conversation and participate on it. You can ping me in freenode IRC or write me an email in Spanish if you have concrete problems, but in the issues/PRs is where we decide what we do and how. We have to give everybody the opportunity to be involved in the discussion. Just using other words or providing more explanations may be enough so that we understand us. If something is not clear, just say it and I/we'll try to clarify it.
> 
> @ehrenfeu just corrected a typo in my explanation, but I have already corrected. So the issue is just what the description says. In other words, admins can not create events without creating a call for papers before. Instead they get an exception when trying to do this.

ok, it is understood.
Thanks for the explanaition.
