### ISSUE TITLE
It is not possible to create an schedule

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2353]
According to @ddemaio, it is not possible to create an schedule. This is important for the conferences coming on.

**Comment by ddemaio** [comment]
Schedules can't be viewed anymore. When trying to view, it says "You are not authorized to access this page." The schedules I had previously made were erased. When I try to made a schedule, it is impossible to schedule anything after 1 p.m. because of the view, non-scrolling option and an error saying "not defined" when adding a new schedule and trying to schedule talks.

**Comment by Ana06** [comment]
That old schedules are not visible might be related with https://github.com/openSUSE/osem/issues/2330

**Comment by ddemaio** [comment]
![bugfrosem](https://user-images.githubusercontent.com/8996626/53161961-4d1ead00-35cb-11e9-9a00-8389ee08d7e8.png)
Here is the view. I have to shrink the view to 50 percent to move the talks to the correct position. I can put in one talk, then when I try to schedule the second talk, I get the undined error. Once I refresh it, I can put on more talk in the schedule, but will get the same error when I try to schedule a second talk.

**Comment by ddemaio** [comment]
![unscheduleosem](https://user-images.githubusercontent.com/8996626/53162310-1006ea80-35cc-11e9-9bcd-a902acffbfeb.png)
![moveosem](https://user-images.githubusercontent.com/8996626/53162317-139a7180-35cc-11e9-8af4-0149c61c643d.png)
Also, I can't move talks or unschedule talks as you can see from the screenshot above.

**Comment by hennevogel** [comment]
Obviously no one ever tried this feature in production with CSRF protection on...

**Comment by Ana06** [comment]
> @hennevogel added the Regression label 17 hours ago

The new `Regression` label need to be added to the wiki: https://github.com/openSUSE/osem/wiki/Labels-for-issues-and-PRs
