### ISSUE TITLE
Error on image uploads

### ISSUE THREAD

**Issue by uebmaster** [openSUSE/osem#2360]
**I'm submitting a ..**
- [ ] Bug Report

**Current behavior:**

When i try to atttach an image to an organization I get the next:
Errno::EACCES (Permission denied @ dir_s_mkdir - /osem/public/system/organizations):

I can create the organization but without image

**Expected correct behavior:**

I expect the creation of an organization with an image attached

**Steps to reproduce:**

Click on Organizations, fill the fileds, select a picture making click on the picture's button, click in create button.

**Other information:**

**Comment by Ana06** [comment]
Maybe related to https://github.com/openSUSE/osem/issues/2179

**Comment by uebmaster** [comment]
@Ana06 the answer of @ehrenfeu works for me, thanks.

How can i mark the issue like solved?

The true is that i don't know much about github xD

I will make click in "close and comment", i hope that's the way.

PD: Sorry for my bad english.
