### ISSUE TITLE
messge while running Bundle install - issue

### ISSUE THREAD

**Issue by georgooty** [openSUSE/osem#2377]
**I'm submitting a ..**
- [ 1] Bug Report

**Current behavior:**

Bundle complete! 115 Gemfile dependencies, 273 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from rails-assets-markdown:
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/evilstreak/markdown-js
**Expected correct behavior:**

What can I do for resolving the same
**Steps to reproduce:**

ruby version is 2.5.0
bundle install
**Other information:**

**Comment by hennevogel** [comment]
Those are just info messages. Nothing to worry about.
