### ISSUE TITLE
Unknown ruby interpreter version

### ISSUE THREAD

**Issue by georgooty** [openSUSE/osem#2392]
**I'm submitting a ..**
- [ 1] Bug Report
- [ 0] Feature Request

**Current behavior:**
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /osem_repo/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): ENV[OSEM_RUBY_VERSION]||2.5.0.

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by Ana06** [comment]
@georgooty I do not completely understand what the problem is, can you please elaborate?

**Comment by georgooty** [comment]
> @georgooty I do not completely understand what the problem is, can you please elaborate?

I installed ruby version 2.5.0 . and installed bundle version 1.17.1. then run bundle install.
I followed the below steps  to install osem, https://github.com/openSUSE/osem/blob/73c15e940458daf7da59ed855a987a4d2cc2123c/INSTALL.md

**Comment by Ana06** [comment]
@georgooty what is the error? what are you executing when the error happen?

**Comment by georgooty** [comment]
> @georgooty what is the error? what are you executing when the error happen?

I installed ruby version 2.5.0. Nothing do, just go to the folder, this message comes.. Please note that I didn't set any environment variable. Please let me ruby which version supporting by osem?

**Comment by Ana06** [comment]
@georgooty I am sorry, but I don't get when you get this error. Can you please try to use docker instead? It should work smoothy.

**Comment by hennevogel** [comment]
If RVM has problems with parsing ruby in Gemfiles you should report this to RVM, not here.
