### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by georgooty** [openSUSE/osem#2393]
**I'm submitting a ..**
- [1 ] Bug Report
- [0 ] Feature Request

**Current behavior:**

rake secret
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.

ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by Ana06** [comment]
@georgooty can you provide more details of what have you done before this error happens?

**Comment by georgooty** [comment]
I installed ruby version 2.5.0 . and installed bundle version 1.17.1. then run bundle install. 
I followed the below steps  to install osem, https://github.com/openSUSE/osem/blob/73c15e940458daf7da59ed855a987a4d2cc2123c/INSTALL.md
Please see the logs
----------------------
rake secret
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/uglifier-4.1.20/lib/uglifier.rb:5:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
/home/ec2-user/gk/osem_repo/config/application.rb:9:in `<top (required)>'
/home/ec2-user/gk/osem_repo/Rakefile:7:in `require'
/home/ec2-user/gk/osem_repo/Rakefile:7:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
/home/ec2-user/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

---------------------

**Comment by georgooty** [comment]
> @georgooty can you provide more details of what have you done before this error happens?

I installed ruby version 2.5.0 . and installed bundle version 1.17.1. then run bundle install. 
I followed the below steps  to install osem, https://github.com/openSUSE/osem/blob/73c15e940458daf7da59ed855a987a4d2cc2123c/INSTALL.md
Please see the logs
----------------------
rake secret
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/uglifier-4.1.20/lib/uglifier.rb:5:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
/home/ec2-user/gk/osem_repo/config/application.rb:9:in `<top (required)>'
/home/ec2-user/gk/osem_repo/Rakefile:7:in `require'
/home/ec2-user/gk/osem_repo/Rakefile:7:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/ec2-user/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
/home/ec2-user/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

---------------------

**Comment by Ana06** [comment]
@hennevogel is https://github.com/openSUSE/osem/blob/73c15e940458daf7da59ed855a987a4d2cc2123c/INSTALL.md up to date? I don't think it is. Should we drop this guide and encourage people to use docker instead?

@georgooty thanks for the issue. You should be able to set your development environment easily with docker following the steps in the [CONTRIBUTING guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md#development-environment)

**Comment by georgooty** [comment]
> @hennevogel is https://github.com/openSUSE/osem/blob/73c15e940458daf7da59ed855a987a4d2cc2123c/INSTALL.md up to date? I don't think it is. Should we drop this guide and encourage people to use docker instead?
> 
> @georgooty thanks for the issue. You should be able to set your development environment easily with docker following the steps in the [CONTRIBUTING guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md#development-environment)

I'm still facing other errors if I used Docker.
$ docker-compose run --rm osem bundle exec rake db:bootstrap
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by hennevogel** [comment]
This is the current version. 

https://github.com/openSUSE/osem/blob/master/INSTALL.md
