### ISSUE TITLE
Can't create questions if question type is nil

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#2396]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
![bu](https://user-images.githubusercontent.com/25618739/53878617-5f203700-4032-11e9-9404-bdfb2a7dae02.png)

**Steps to reproduce:**
1. Create conference
2. Questions
3. Create question

**Comment by Ana06** [comment]
Same https://github.com/openSUSE/osem/issues/2387 Can you please add this information in the original issue? I close this one.

**Comment by rahul2240** [comment]
@Ana06 this is related to questions#new and #2387 is related to questions#show, should I add this information to that issue?

**Comment by Ana06** [comment]
I think both issues can be fixed together. Please add the info to #2387 :wink:
