### ISSUE TITLE
Unable to edit "call for events" form in call for content. 

### ISSUE THREAD

**Issue by snpd25** [openSUSE/osem#2397]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
I am unable to edit the call for event form. The text field for "start date" and "end date" is not being edited. 

**Steps to reproduce:**
Create a new conference and try to create a call for event.

![screenshot from 2019-03-06 19-02-22](https://user-images.githubusercontent.com/32434989/53884830-71a26c80-4042-11e9-8d4c-73987b1d9b05.png)

**Comment by Ana06** [comment]
@snpd25 there is already an issue for this: https://github.com/openSUSE/osem/issues/2349
