### ISSUE TITLE
create a factory for organizer

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2398]
A factory for organizer to be able to have in our tests just:

```ruby
let(:organizer) { create(:organizer, resource: conference) }
```

instead of:

```ruby
let!(:organizer_role) { Role.find_by(name: 'organizer', resource: conference) }
let(:organizer) { create(:user, role_ids: organizer_role.id) }
```

Just similarly as how it is done with `admin`.

The current code needs to be adapted to use this factory.

**Comment by cyrillefr** [comment]
Hello, I would like to work on this one.

**Comment by Ana06** [comment]
go ahead @cyrillefr
