### ISSUE TITLE
Log out with ichain enabled doesn't work

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2399]
I clicked _Sign out_ as a normal user in events.opensuse.org

![image](https://user-images.githubusercontent.com/16052290/53944990-d7cdd480-40c0-11e9-85b7-33a8bcfa118e.png)

and I got the following error:

![image](https://user-images.githubusercontent.com/16052290/53944972-c97fb880-40c0-11e9-9a61-a69a30d91b4e.png)

And I was still logged in.

I tried again and it did work.... so not sure if this is a bug or some kind of problem with ichain in events.opensuse.org

**Comment by hennevogel** [comment]
Works for me. Still an issue?

**Comment by Ana06** [comment]
It happens once. For me it does work now. It was just after I created a new user... maybe related... Let close it and reopen if needed in the future.
