### ISSUE TITLE
Easier schedule date input

### ISSUE THREAD

**Issue by Dsxv** [openSUSE/osem#2411]
Hi! 
This is a :
- [x] Feature Request while creating the new conference
<hr>

**Current Behaviour**
When the admin creates a  new conference , has to manually input date in `(dd/mm/yy)` format 
![osem1current](https://user-images.githubusercontent.com/36789080/54082040-7f533d00-4335-11e9-8522-c9087b262361.gif)

<hr> 

**Proposed Behaviour**
What we can do is set the input type to date so that the admin can easily select a date from calander.
Or can enter manually if they want to. 
Something like 
![osem1updated](https://user-images.githubusercontent.com/36789080/54082065-eec92c80-4335-11e9-8d33-58fe74502c47.gif)
Thanks!

**Comment by Dsxv** [comment]
Ps :I'd also like to work on this! :smile:

**Comment by rahul2240** [comment]
Hi @Dsxv  :smile: ,
There is already a code for selecting date from calendar ([Check here](https://github.com/openSUSE/osem/blob/master/app/assets/javascripts/osem-datepickers.js)) but there is a bug in it right now.
Check this #2347 #2391

**Comment by Dsxv** [comment]
@rahul2240 I'm sorry! :sweat_smile: I did this hastily without looking up previous issues, by the way, are there any gitter channel for osem because I am new to this org and had some doubts in code base/website so I'd like to clarify them. 
Thanks!

**Comment by rahul2240** [comment]
You can use #osem channel on freenode IRC :smiley:

**Comment by Ana06** [comment]
Closing as there is already an issue for this (as @rahul2240 pointed out). @Dsxv apart from the #osem channel on freenode IRC, you can also ask directly in the issues/PR. :wink:
