### ISSUE TITLE
Error on creating a Survey with empty title.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#2412]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

![survey](https://user-images.githubusercontent.com/26951824/54084792-40d07900-435b-11e9-92cc-2d4936dd305e.png)

**Expected correct behavior:**
It should display a message with the error.

**Steps to reproduce:**

Try to create a survey without any title.

**Comment by differentreality** [comment]
Good catch! Thanks @rishabhptr

**Comment by snpd25** [comment]
@rishabhptr , @differentreality , why survey_params is passed while rendering new? [here](https://github.com/openSUSE/osem/blob/2a0552d6b29bf3ce1ed64b33da2b643667718479/app/controllers/admin/surveys_controller.rb#L13). Is it for rendering already filled up data? I removed it and changed the redirection path.
![image](https://user-images.githubusercontent.com/32434989/54196185-b4eb5800-44e6-11e9-8a9e-dd51599d9e51.png)
Is this fine?

**Comment by differentreality** [comment]
Params tell us the kind of survey we are creating. 
For instance, here we are defining that we are creating a new Survey for a conference
https://github.com/openSUSE/osem/blob/master/app/views/admin/surveys/index.html.haml#L6

**Comment by snpd25** [comment]
I changed the path of redirecting to `new_admin_conference_survey_path(@conference.short_title, survey: {  surveyable_type: 'Conference', surveyable_id: @conference.id })` and it generates the [same](https://github.com/openSUSE/osem/issues/2412#issuecomment-471963698) after submission. Is it okay?
