### ISSUE TITLE
Date-picker is not incorporated in creating Surveys

### ISSUE THREAD

**Issue by snpd25** [openSUSE/osem#2414]
**I'm submitting a ..**
- [ ] Bug Report
- [ ] Feature Request

In the surveys form the date-picker is not implemented. We can use #2354 here as well. 
It is in addition to #2347 .

Steps to reproduce:
Try to create a survey.

**Comment by Ana06** [comment]
I think that with one issue is enough. There are many datepicker broken. Let's keep https://github.com/openSUSE/osem/issues/2347 and close this. There is already a PR: https://github.com/openSUSE/osem/pull/2391
