### ISSUE TITLE
Error on submitting proposal when cfp is nil

### ISSUE THREAD

**Issue by rahul2240** [openSUSE/osem#2418]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
![bug](https://user-images.githubusercontent.com/25618739/54177543-966e6800-44b8-11e9-8273-c8df154d14ec.png)

**Expected correct behavior:**
Submit proposal button should not be present if cfp is nil

**Steps to reproduce:**
1.Create conference
2.Submit proposal

**Comment by Ana06** [comment]
Repeated issue: https://github.com/openSUSE/osem/issues/2348 

This is already fixed on master

**Comment by rahul2240** [comment]
@Ana06 what about ([proposals#new](https://github.com/openSUSE/osem/blob/master/app/views/proposals/new.html.haml#L62))

**Comment by Ana06** [comment]
@rahul2240 a user shouldn't be able to submit a proposal if there is no cfp
