### ISSUE TITLE
Discussion: Better proposal for the schedule design than the current carousel

### ISSUE THREAD

**Issue by cboltz** [openSUSE/osem#2421]
# Proposals for a design
### Pros

- It works for conferences with many rooms such as FOSDEM
- It is mobile friendly

### Cons

- You have to click multiple times to see the schedule of a single day
- The talks in the border are not clickable
- It is not possible to have smaller intervals (15 minutes)

### Pros

- It works for conferences with many rooms such as FOSDEM
- It is mobile friendly
- Scrolling is much easier than clicking and you don't have to wait for the animation
- All talks are clickable
- It is possible to have smaller intervals

### Cons

- Horizontal scroll may not be a wide concept and consequently not intuitive for users.

### Pros

- All talks are clickable
- It is possible to have smaller intervals
- You don't need to click many times to see the whole schedule

### Cons

- It doesn't work for conferences with many rooms such as FOSDEM
- It is not mobile friendly

## Other ideas? Please help! :pray: 

# Original bug submission from @cboltz 
**Current behavior:**

Since events.opensuse.org was updated to the latest OSEM, the schedule was "rotated" by 90 degrees. Now the rooms are rows and the columns are for the time. This causes two problems:

* It's annoying because you have to click multiple times to see the schedule of a single day

* The "scroll regions" on the left and right make it impossible to click on the talk displayed under them. For example, it's impossible to click / see the talk details of "What can you do with a self-hosted ..." scheduled at 11:45 on
https://events.opensuse.org/conferences/oSC19/schedule#2019-05-26

**Expected correct behavior:**

* all talks should be clickable (to go to the details page) - the "scroll overlay" should not break that
* have a view that shows the whole day on one page (switching back to having the rooms as columns is a possible solution, but I'm open for other ideas)

**Comment by bear454** [comment]
This isn't a bug; the 'carousel' was added as a feature ... years ago.

https://github.com/openSUSE/osem/pull/1030

**Comment by differentreality** [comment]
The bug is that you cannot click on some events because of the side arrows

**Comment by cboltz** [comment]
I disagree that the carousel is a feature, but hey, opinions differ ;-)

However, the fact that you can't click some events because of the side arrows clearly is a bug. Unfortunately I can't reopen this issue. Can you please do that, or should I file a new issue?

**Comment by bear454** [comment]
@cboltz ... I think I stopped reading at "It's annoying".

WRT to the two issues (which should be separate issues):

> * all talks should be clickable (to go to the details page) - the "scroll overlay" should not break that

This is only an issue on sessions that occupy only one timeslice; i'd consider that a corner case...  Does oSC really have 15-minute-long (short?) sessions? -.- Our shortest sessions at LFNW are 45-minutes on 15-minute slots, so 3 slots... never an issue.

> * have a view that shows the whole day on one page (switching back to having the rooms as columns is a possible solution, but I'm open for other ideas)

That's the "All events" tab at the top: https://events.opensuse.org/conferences/oSC19/schedule/events#2019-05-26

**Comment by cboltz** [comment]
> This is only an issue on sessions that occupy only one timeslice; i'd consider that a corner case... Does oSC really have 15-minute-long (short?) sessions? -.- Our shortest sessions at LFNW are 45-minutes on 15-minute slots, so 3 slots... never an issue.

Yes, we really have some 15 minute talks (slightly more than a lightning talk), and we managed to let them start at 11:45 - which is exactly where the scroll arrow is on https://events.opensuse.org/conferences/oSC19/schedule#2019-05-26 ;-)

> That's the "All events" tab at the top: https://events.opensuse.org/conferences/oSC19/schedule/events#2019-05-26

That's not exactly what I was looking for, but much better than the carousel :-)

**Comment by Ana06** [comment]
@cboltz this was my GSoC project 2 years ago. It was needed to rotate the schedule because of conferences like FOSDEM which have many rooms. We had several discussions and proposals both in GitHub and IRC at that point and we decided that his was the way to go. At the moment we can not revert this anymore. But I have to admit that after having used it for the conference I am not convinced with the carousel. Another idea that I had when this was implemented was to use horizontal scroll instead. We didn't move forwards with this because it was not a widely used concept. But maybe times have changed and we have to reconsider this and other possible solutions.

There is already an issue for the bug that @differentreality mentioned:

> The bug is that you cannot click on some events because of the side arrows

But I think it is worthwhile reopening this as a discussion of a better design, not as a bug. What do you think of using horizontal scroll? What other ideas could be better than the carousel?

@cboltz @bear454 @differentreality @hennevogel @ChrisBr @ddemaio (and anybody else) ideas?

**Comment by Ana06** [comment]
I have modified your original comment @cboltz to include a summary of the possible options. I hope that is fine. :smile:

**Comment by Ana06** [comment]
I have a proposal. Why about we try to come for the perfect solution for the schedule and in the meanwhile I give a try to the horizontal scroll so that we can deploy already while we find the perfect solution (in case the horizontal scroll is not perfect :stuck_out_tongue_winking_eye: )

**Comment by cboltz** [comment]
> What about we try to come up with the perfect solution for the schedule

Well, the perfect solution is to give everybody a 50 inch screen ;-) but I'm somewhat afraid that won't work in practise. (Any sponsors? ;-)

IMHO switching back to rooms as columns would be the best idea. Funnily, even FOSDEM does that (see https://fosdem.org/2019/schedule/day/saturday/), and they manage to squeeze all rooms into the screen ;-)

Horicontal scrolling sounds like a way to avoid overlap of the carousel controls with the talks, but I agree that it's not too intuitive - especially if there are many rooms and you have to scroll down to see the horicontal scrollbar. (To avoid that, make sure the horizontal scrollbar is always visible.)

There's another, easy to implement option which would improve things - instead of having a fixed width, use `width:100%` for the schedule to avoid the need for scrolling. The white areas in the left and right might look nice, but they waste pixels ;-)

**Comment by Ana06** [comment]
Related: https://github.com/openSUSE/osem/issues/1791

**Comment by hennevogel** [comment]
It's not related, it's a duplicate :-)

**Comment by Ana06** [comment]
@hennevogel 

> It's not related, it's a duplicate :-)

Well, when the other issue was open there were different conditions....

**Comment by hennevogel** [comment]
conditions?
