### ISSUE TITLE
DB Migration crashes

### ISSUE THREAD

**Issue by josegomezr** [openSUSE/osem#2422]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Cannot run osem on a Postgresql database. Because of incompatible type changes in migrations.

**Expected correct behavior:**
It should migrate flawlessly

**Steps to reproduce:**
1. Fresh clone from openSUSE/osem (master branch, ref `2a0552d`).
2. Install dependencies.
3. Setup db environment variables.
3. `$ bundle exec rails db:migrate`
4. a *very* explicit explosion db column type incompatibilities
```
#... ommited for brevity...#
== 20130712072609 AddAttendedToRegistrations: migrating =======================
-- add_column(:registrations, :attended, :boolean, {:default=>0})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DatatypeMismatch: ERROR:  column "attended" is of type boolean but default expression is of type integer
HINT:  You will need to rewrite or cast the expression.
: ALTER TABLE "registrations" ADD "attended" boolean DEFAULT 0
#... stacktrace ...#
```
**Other information:**
Tested with postgresql versions:
- 10.1
- 9.5

It also crashes with MySQL 5.1 for fields defined as uuid. 

In migration 
[20140623100942_create_visits][mysql-migration-1]
[20140623101032_create_ahoy_events][mysql-migration-2]

[mysql-migration-1]: https://github.com/openSUSE/osem/blob/2a0552d6b29bf3ce1ed64b33da2b643667718479/db/migrate/20140623100942_create_visits.rb#L6
[mysql-migration-2]: https://github.com/openSUSE/osem/blob/2a0552d6b29bf3ce1ed64b33da2b643667718479/db/migrate/20140623101032_create_ahoy_events.rb#L6

**Comment by hennevogel** [comment]
If you want to setup a new DB use `rake db:setup`, there is no use to do `db:migrate` on a new DB.
