### ISSUE TITLE
support Ruby 2.6

### ISSUE THREAD

**Issue by georgooty** [openSUSE/osem#2427]
It would be nice to support Ruby 2.6

**Comment by Ana06** [comment]
Sure  @georgooty! It would be great to update to Ruby 2.6. A PR is more than welcome :wink:

**Comment by alaxalves** [comment]
@Ana06 I'd like to start contributing to OSEM. Do you think this is a good issue to start?

**Comment by alaxalves** [comment]
Currently working on this...

**Comment by alaxalves** [comment]
Apparently latest opensuse/leap image doesn't have ruby 2.6 version. I'm facing:
![image](https://user-images.githubusercontent.com/19597045/54574826-95659b00-49d0-11e9-9dd0-584a1d96abe7.png)

**Comment by Ana06** [comment]
@alaxalves there is not package for ruby 2.6 in Leap. There is a 2.6 package in tumbleweed thought. Why do we need the leap package?

**Comment by AndrewKvalheim** [comment]
Resolved in 28caa143e8a4b4518c7d63b990260c57c5e58331
