### ISSUE TITLE
automatic emails

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/osem#2430]
I'm not sure what might be triggering this, but after logging in and making a few changes, there is something that triggers hydra.opensuse.org to send an email about the schedule. I've noticed this has happened twice. The first time it happened, the schedule wasn't viewable and I responded to all of emails I received. The schedule now works and I'm glad the email went out, but I didn't do anything to trigger the email other than change an option in the admin page, but the change I made did trigger an email to go out, which was not intended to sent. Probably a low priority bug.

**Comment by Ana06** [comment]
I think the first time it was me while debuging the bug, as I made the schedule public. Sorry for that, I should have told you.

The second one was when you made the schedule public and today it was sent again. What have you done exactly today? (to know what have triggered that)

**Comment by ddemaio** [comment]
@Ana06 under the program tab in admin, I edited it and clicked on the "Allow submitters to change their event after it is scheduled" button and then click the "update program". I guess this sounds like something that would want to send out an email with the updating of the program, so it's probably not a bug.

**Comment by Ana06** [comment]
@ddemaio 

> @Ana06  under the program tab in admin, I edited it and clicked on the "Allow  submitters to change their event after it is scheduled" button and then  click the "update program". I guess this sounds like something that  would want to send out an email with the updating of the program, so  it's probably not a bug.


But still is the same message, what is confusing for attendees, isn't it?
