### ISSUE TITLE
Event/track exports are broken.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#2432]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Exporting the events/tracks through the admin dashboard is landing to errors.
![pdf](https://user-images.githubusercontent.com/26951824/54423163-09384700-4736-11e9-895e-89257387beec.png)

**Steps to reproduce:**
Create new events or tracks through admin dashboard and click on export buttons to export all/confirmed events.

**Comment by rahul2240** [comment]
@Ana06 [layouts/application.haml](https://github.com/openSUSE/osem/blob/master/app/views/layouts/application.haml) should be application.html.haml right?

**Comment by snpd25** [comment]
@rishabhptr , @Ana06 , the gem used here for generating pdf is "prawn-rails" but I couldn't find the configuration file for it as mentioned here:
[https://github.com/cortiz/prawn-rails#default-configuration](https://github.com/cortiz/prawn-rails#default-configuration)

**Comment by rahul2240** [comment]
@snpd25, I think https://github.com/Whoops/prawn-rails this gem is used here according to the gemfile

**Comment by rishabhptr** [comment]
@snpd25 Yes, @rahul2240 is right  and regarding initialising, it can be done by overriding the Prawn::Document class just like [here](https://github.com/openSUSE/osem/blob/edc5a5b4aa7076b4adc888fc5d1400353b99754d/app/pdfs/ticket_pdf.rb#L6).

This version of gem is quite old, and because prawn-rails is now a separate gem as a dependency of prawn, this version is suspectible for problems. Though it's only for pdf export option.

**Comment by rahul2240** [comment]
@rishabhptr try changing prawn_rails with prawn-rails no need for any other gem.

**Comment by snpd25** [comment]
@rishabhptr , @Ana06 ,I found the same issue with "Registrations" as well. Should I open a different issue regarding that?

**Comment by rishabhptr** [comment]
@snpd25 Thanks for mentioning this, though that might require specifying the format in the controller but basically it would land to the same prawn error until the gem is updated.

**Comment by Ana06** [comment]
@rishabhptr @snpd25 @rahul2240 does any of you plan to send a PR? :hugs:

**Comment by rahul2240** [comment]
@Ana06 I will send the PR :smile:
