### ISSUE TITLE
User can buy tickets through splashpage even if registration is not open.

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#2433]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Currently if splash page is public and we have chosen to display tickets, then the default free tickets and/or any paid tickets are visible to the user even if registration have'nt started.
![Screenshot from 2019-03-15 15-24-39](https://user-images.githubusercontent.com/26951824/54423783-7a2c2e80-4737-11e9-871b-dc59a2ff6da5.png)
![Screenshot from 2019-03-15 15-25-23](https://user-images.githubusercontent.com/26951824/54423792-7d271f00-4737-11e9-8407-683dfea64fca.png)

User can get and download the ticket, only to land at an error that registration could'nt proceed.

**Expected correct behavior:**

I think if we want to showcase the tickets, we should disable clicking on them/ payment until registration starts. 

**Steps to reproduce:**
Create a new conference and make splashpage public with default selection( display tickets).

**Comment by ibrahimelbanna** [comment]
Can i take this issue ?

**Comment by rishabhptr** [comment]
@ibrahimelbanna Sorry for late reply, if you want to work on it feel free to send a PR. Let me know if you need more information on this.

**Comment by ibrahimelbanna** [comment]
@rishabhptr Thanks I will work on it and send pr

**Comment by AHaseebKhan11** [comment]
Hi I have made a pr for this issue https://github.com/openSUSE/osem/pull/2517
I wanted to use the link_to_if helper here but it doesn't work with do block in haml. I would have had to write some html markup for it so used a conditional statement.

**Comment by bear454** [comment]
I don't agree with the premise that tickets should only be available during the registration period. If you don't want tickets to show on the splashpage, uncheck the tickets option in the splashpage config.

**Comment by Ana06** [comment]
taking into account @bear454 comment, I am going to close this issue. It is true that there is an option to hide the tickets and people may be already using the feature this way.
