### ISSUE TITLE
Carousel elements in timetable beneath arrow overlays are neither clickable nor hoverable

### ISSUE THREAD

**Issue by clanig** [openSUSE/osem#2434]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
On the following page there are sliders on the right and left of the time table that prevent interaction with scheduled presentations
![events_osc_overlay_covering_presentations](https://user-images.githubusercontent.com/31621613/54433463-2cf68f80-472c-11e9-9e98-ec3feea33cda.jpg)

**Expected correct behavior:**
The visitor should be able to hover and click on every presentation element to obtain further information.

**Steps to reproduce:**
Visit https://events.opensuse.org/conferences/oSC19/schedule#2019-05-25 on a desktop computer.

**Other information:**
This bug report shall clarify the main point of the closed issue https://github.com/openSUSE/osem/issues/2421 in a more understandable way.

**Comment by Ana06** [comment]
Related to https://github.com/openSUSE/osem/issues/2421

**Comment by sncarnera** [comment]
![image](https://user-images.githubusercontent.com/28449015/54843763-d5f83980-4c9a-11e9-913c-493a7a9ff047.png)
To Fix this changed $carousel-control-width from 15% to 3% in _variables.scss

**Comment by Ana06** [comment]
@sncarnera thanks for the idea! :cupid: Do you plan to send a PR or should I do it?

**Comment by sncarnera** [comment]
@Ana06 please go ahead I've never done a PR

**Comment by Ana06** [comment]
@sncarnera I have sent [the PR](https://github.com/openSUSE/osem/pull/2462). I tried to add you as co-author but I would need a name and email for it to work properly. Btw, 3% didn't work properly for all screen sizes so I adapted it a bit. :smile: 

If at some point you want to make your first PR in OSEM and you need help, just let us know :wink:
