### ISSUE TITLE
export pdf, xml and csv not working properly

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/osem#2464]
As an admin, under the registrations tab, I am unable to export the data. All that comes up is a blank page and when downloading it, there is no data with a right click save. A screenshot is attached.
![exporterror](https://user-images.githubusercontent.com/8996626/55008527-67d8ad00-4fe1-11e9-98e7-c70243fd00eb.png)
 It is needed to send out daily emails to attendees.

**Comment by Ana06** [comment]
Related to https://github.com/openSUSE/osem/issues/2432

**Comment by differentreality** [comment]
Fixed in https://github.com/openSUSE/osem/pull/2471
