### ISSUE TITLE
Fix tests in rails-assets-bootstrap-select update

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2468]
@depfu[bot] opened a PR to update to rails-assets-bootstrap-select: 1.13.3 → 1.13.8: https://github.com/openSUSE/osem/pull/2477

but there are feature tests failing that need to be fix to merge the update: https://travis-ci.org/openSUSE/osem/jobs/508428537

In case of not having permissions to push to that PR, feel free to open a new one. :wink:

**Comment by kaunair** [comment]
I'd like to work on this issue :smile:

**Comment by AndrewKvalheim** [comment]
Updated to 1.13.10 in b76db5530275db35efcdd56e09f7830ec04f2d6c with passing tests
