### ISSUE TITLE
Should we drop piwik_analytics?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2480]
It seems that piwik  tracks things like:

- User IP address
- User ID (which identify the user)
- Approximate latitude and longitude of the user
- Main Language of the browser being used
- browser, operating system, device used (desktop, tablet, mobile, tv, cars, console, etc.), brand and model 

I wonder why do we need this information or track the users at all (any information). It doesn't seem something that we need and I would like to revert https://github.com/openSUSE/osem/pull/538, dropping the piwik tracking gems.

**Comment by ddemaio** [comment]
@Ana06 I agree. We don't really need this on events.o.o.. I think it would be fine to drop it.

**Comment by Ana06** [comment]
any other opinions? @differentreality @hennevogel @bear454 ^^

**Comment by hennevogel** [comment]
You can drop it for the opensuse installation but why would you drop that feature? Web analytics are a thing most people do.

**Comment by bear454** [comment]
Innocraft provides LFNW with a sponsored account; we, and our users, have been very happy to be off of Google Analytics, and onto something open source. So, no, I don't agree with dropping it.

**Comment by differentreality** [comment]
So do **not** drop? Can we close this?

**Comment by ddemaio** [comment]
I think @hennevogel and @bear454 make valid points, so don't drop it @differentreality
