### ISSUE TITLE
Registration fails with empty registration form

### ISSUE THREAD

**Issue by vinzv** [openSUSE/osem#2482]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
Being logged in and submitting https://events.opensuse.org/conferences/oSC19/register/new without ticking or filling any box I run into this error:

> The change you wanted was rejected.
> Maybe you tried to change something you didn't have access to.

**Comment by differentreality** [comment]
Couldn't find the error in the logs. @vinzv could you please reproduce?

**Comment by vinzv** [comment]
Thanks for having a look!

Registrations are tied to openSUSE infrastructure accounts. So I can't register again, unfortunately.
As long as no one else complains we're fine here, I guess. :)
Closing the issues for now.
