### ISSUE TITLE
Adding new conference is broke

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/osem#2496]
I need to add the openSUSE.Asia Summit for this year and give the organizers admin rights. The add conference button has disappeared.
![Screenshot from 2019-04-24 07-18-25](https://user-images.githubusercontent.com/8996626/56634264-a2297e80-6661-11e9-9984-9ebc8372fd98.png)
It was on the left drop-down bar, but it has disappeared. Now it is in the organizations section and there is an add conference button, which does not work. The following error appears saying I don't have authorization to add a conference.
![Screenshot from 2019-04-24 07-18-01](https://user-images.githubusercontent.com/8996626/56634364-00566180-6662-11e9-83f5-2a1cfbecdfa5.png)
@Ana06 @hennevogel could you please look at this so we can get the team started with the organization of this year's openSUSE.Asia Summit.

**Comment by Ana06** [comment]
@ddemaio I'll take a look :wink:

**Comment by Ana06** [comment]
I see the following in the menu that appear where my name is:

![image](https://user-images.githubusercontent.com/16052290/56804118-eb75fb80-6824-11e9-893d-8c0d7ff25f0e.png)


I do get to the new conference page, but sending the form return a 500. It may be related to https://github.com/openSUSE/osem/issues/2454

**Comment by Ana06** [comment]
This is a Roles related problem. I think running the following rake task will solve the problem: https://github.com/openSUSE/osem/blob/master/lib/tasks/roles.rake I need access to the server for that (I am on it).

@hennevogel I am not pretty sure how we should be handling this. But after https://github.com/openSUSE/osem/commit/b72e64b2385767f2b1634322ac2cf97c9a3a3638, not having run this task break the code in many places. At least we should document this somewhere.

**Comment by Ana06** [comment]
I finally manage to access the machine and the bug is fixed! (thanks @cboltz for the help :cupid:) As I expected, running the rake task fished the issue.

I leave this open until we discuss how to handle this as our instance may not be the only one affected.

**Comment by Ana06** [comment]
Btw Doug, the _Add conference_ button is in the organisation (you could have more than one organisation now).

**Comment by differentreality** [comment]
I'd expect whomever is admin on the OSEM instance to be able to handle this one way or the other.

In any case, the menu item is there for those with appropriate access, and it is my understanding that events.o.o proper functionality is now restored too, right? If so, can we close this?

I have also made @ddemaio an admin in events.o.o to solve the practical issues here.

**Comment by ddemaio** [comment]
Thank you @differentreality

**Comment by Ana06** [comment]
No, that the rake task need to be run still need to be documented for other instances that may want to update from version 1
