### ISSUE TITLE
Rendering of schedule.xml is broken

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#2497]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
https://events.opensuse.org/conferences/oSC19/schedule.xml returns a 500 server error.

**Expected correct behavior:**
https://events.opensuse.org/conferences/oSC19/schedule.xml should return a frab-compatible XML representation of the conference.

**Steps to reproduce:**

1. Open https://events.opensuse.org/conferences/oSC19/schedule.xml
2. A 500 Server error is returned.

**Comment by Ana06** [comment]
I'll take a look

**Comment by danimo** [comment]
Is this already deployed? I now get the same 500, but formatted as XML.

**Comment by Ana06** [comment]
@danimo It is deployed... it seems there are more problems in production. I'll try again... :mag:

**Comment by Ana06** [comment]
The log tells me we need to restart the server (`application.haml` is still rendered):

```
[a24608c7-4824-4f9a-b583-cafe297a6426] Processing by SchedulesController#show as XML
[a24608c7-4824-4f9a-b583-cafe297a6426]   Parameters: {"conference_id"=>"oSC19"}
[a24608c7-4824-4f9a-b583-cafe297a6426]   Rendering layouts/application.haml
[a24608c7-4824-4f9a-b583-cafe297a6426]   Rendering schedules/show.xml.haml within layouts/application
[a24608c7-4824-4f9a-b583-cafe297a6426]   Rendered schedules/show.xml.haml within layouts/application (390.3ms)
[a24608c7-4824-4f9a-b583-cafe297a6426]   Rendered layouts/application.haml (393.3ms)
[a24608c7-4824-4f9a-b583-cafe297a6426] Completed 500 Internal Server Error in 1107ms (ActiveRecord: 255.4ms)
```

@hennevogel how can I do that? :thinking:

**Comment by Ana06** [comment]
Server restarted. It is fixed now. :wink:

**Comment by danimo** [comment]
Thanks. Now, all that seems to be left is an issue while importing. It seems the timestamp format has changed:

```
14:0: ERROR: Element 'date': '2019-05-24 09:30 Berlin' is not a valid value of the atomic type 'dateTimeTZ'.
```

It should looke like this: ```2019-05-24T09:30:00+02:00```

From the XSD:

```
  <xs:simpleType name="dateTimeTZ">
    <xs:restriction base="xs:dateTime">
      <xs:pattern value=".+(Z|\+[0-9]{1,2}:[0-9]{2}|-[0-9]{1,2}:[0-9]{2})"/>
    </xs:restriction>
  </xs:simpleType>
```

(it also complains about the GUID field not satisfying the regex ```[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}``` (i.e. not being a true UUID) but I am not sure that was ever different. The validator and a link to the XSD is here: https://c3voc.de/schedulexml.


Can you fix or add a formatter in the XML template?

**Comment by Ana06** [comment]
I'll take a look :+1:

**Comment by Ana06** [comment]
@danimo I have added this info to a new issue: https://github.com/openSUSE/osem/issues/2510 (because this is not related to the first problem). I'll take a look :wink:
