### ISSUE TITLE
Error opening revision history on demo conference 500

### ISSUE THREAD

**Issue by eladeyal-intel** [openSUSE/osem#2506]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
When I open the "revision_history" in the OSEM demo website http://demo.osem.io/admin/revision_history I get Error 500

**Comment by Ana06** [comment]
Duplicated of https://github.com/openSUSE/osem/issues/2334

Please check the issues list before open a new one.
