### ISSUE TITLE
version demo

### ISSUE THREAD

**Issue by eladeyal-intel** [openSUSE/osem#2507]
which version of OSEM is deployed in http://demo.osem.io/admin/conferences/osemdemo ? I can't see any version number.

The only think I see is "This tool is free software, released under the MIT license. You can run, copy, distribute, study, change and improve it. The source code and the developers are on GitHub.". Maybe it should say the name of the tool and the version number.

**Comment by Ana06** [comment]
You can check the deployed version here: https://github.com/openSUSE/osem/deployments So, it is a current version.

The app looks exactly the same as if you would install it locally, so we can not add the version there. There is also no version number to mention as this is unreleased code. clicking on the link `Github` on the message takes you to the project where you can see the deployment and the project.
