### ISSUE TITLE
Dates format in xml is incorrect

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2510]
From @danimo in https://github.com/openSUSE/osem/issues/2497#issuecomment-487918981:

> It seems the timestamp format has changed:
> 
> ```
> 14:0: ERROR: Element 'date': '2019-05-24 09:30 Berlin' is not a valid value of the atomic type 'dateTimeTZ'.
> ```
> 
> It should looke like this: ```2019-05-24T09:30:00+02:00```
> 
> From the XSD:
> 
> ```
>   <xs:simpleType name="dateTimeTZ">
>     <xs:restriction base="xs:dateTime">
>       <xs:pattern value=".+(Z|\+[0-9]{1,2}:[0-9]{2}|-[0-9]{1,2}:[0-9]{2})"/>
>     </xs:restriction>
>   </xs:simpleType>
> ```
> 
> (it also complains about the GUID field not satisfying the regex ```[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}``` (i.e. not being a true UUID) but I am not sure that was ever different. The validator and a link to the XSD is here: https://c3voc.de/schedulexml.

**Comment by danimo** [comment]
Just an idea: If you want to create a test, and assuming osem has a mock for a complete conference schedule, the schedule.xml route could be checked against https://raw.githubusercontent.com/voc/schedule/master/validator/xsd/schedule.xml.xsd to avoid future breakage. If you want that as a new issue, that's fine.

**Comment by Ana06** [comment]
@danimo 

> If you want that as a new issue, that's fine.

It is a good idea, please open a new issue, so that we can fast fix the bug by now.

**Comment by danimo** [comment]
Done. If someone could reload the webserver, we can close this issue.

**Comment by Ana06** [comment]
@danimo I have deployed, please double check that the issue is fixed

**Comment by danimo** [comment]
Works like a charm, thanks!
