### ISSUE TITLE
Support talks without speaker

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2520]
For "talks" like lunch and party (in general any activity you want to add in the schedule but that doesn't have any speaker) it should be possible to have talks without speaker.

**Comment by snpd25** [comment]
@Ana06 , I wanna work on it, will making the speakers optional solve the issue or another option in the speaker list: "Not-particular" or "All present" will do?

**Comment by Ana06** [comment]
@snpd25 

>  I wanna work on it

cool! :wink: Go ahead!

> will making the speakers optional solve the issue or another option in the speaker list: "Not-particular" or "All present" will do?

I think internally we should just save no speaker, but when rendering it to the user it may be a good idea to show something, at least in the admin side. In the user side, I would say that when there is not speaker we should not render any picture or speaker field. But I would say those are details we can discuss in the PR. :smile: 

Take into account we don't want users to send talks for the call for paper without speaker. This should be only for the conference organizers/admins.

**Comment by snpd25** [comment]
Hey @Ana06 , sorry for getting back on it so late. I was just thinking if we can remove the validation
of speakers from the events model. 

> Take into account we don't want users to send talks for the call for paper without speaker. This should be only for the conference organizers/admins.

This will not be a problem as in the proposals controller the speaker is defined as the user who submits the proposal. And I could not find any other way where user defines the speaker. 
Once we get confirmed about what to show on the user side, I will make the final modifications and submit a PR :)

**Comment by Ana06** [comment]
@snpd25 

> I was just thinking if we can remove the validation of speakers from the events model

As we are planning to allow that there is no speaker, the validation has to be removed.

> Once we get confirmed about what to show on the user side, I will make the final modifications and submit a PR :)

IMO it would be enough with which I mentioned in my previos comment:

> I think internally we should just save no speaker, but when rendering it to the user it may be a good idea to show something, at least in the admin side. In the user side, I would say that when there is not speaker we should not render any picture or speaker field. But I would say those are details we can discuss in the PR

Is there something that is not clear or need to be further discussed? If not please go ahead with the PR :muscle:
