### ISSUE TITLE
Collecting additional information during submissions 

### ISSUE THREAD

**Issue by rishabhptr** [openSUSE/osem#2528]
As a part of the GSoC project. We want to collect additional details such a contact, social media, additional requests for.

- [ ]  Add social media links
- [ ]  Add contact fields 
- [ ]  Add a field for entering additional requirements.
- [ ]  Change the respective form and views.

For the Social media links, I have proposed to use the contact model which already exists for the social media links and create a polymorphic association with the track and booth models.
One query regarding this is should I leave the existing association with conference model as it is or change that too?

For contact fields I think we should add a website_url for tracks just like booths. Other options such as email / social _tag are covered in contact model.

**Comment by Ana06** [comment]
Where do you want to add this information? I guess you speak about the submission the tracks and booths, right?

> For the Social media links, I have proposed to use the contact model which already exists for the social media links and create a polymorphic association with the track and booth models.

This sounds good to me.

> One query regarding this is should I leave the existing association with conference model as it is or change that too?

What do you exactly mean?

> For contact fields I think we should add a website_url for tracks just like booths

:+1:

**Comment by rishabhptr** [comment]
> Where do you want to add this information? I guess you speak about the submission the tracks and booths, right?

Yeah, this is related to Tracks/Booths.

> One query regarding this is should I leave the existing association with conference model as it is or change that too?

What I mean to say is that using polymorphic association we would have ` contactable_type ` and ` contactable_id ` field for contact, so is it good practice to convert the `has_one` association between conference and contact to polymorphic association too.

**Comment by Ana06** [comment]
@rishabhptr what about you send a PR with a suggestion? It is much easier to discuss about code when seeing the code and we want to see the work you are doing :wink:

**Comment by rishabhptr** [comment]
@Ana06 Yes, you're right and sorry for not updating earlier. I have created a PR explaining my approach and the concerns that I am facing. Thanks!

**Comment by differentreality** [comment]
I am wondering if we want to allow people to submit custom things, in addition to the predefined fields, so that they can determine both the description as well as submit the equivalent value (eg. a link to project's repo).
Then the table can look like this:

ID | description | text
1  | Project license | X license
2  | Project repo | link-to-repo

**Comment by rishabhptr** [comment]
It's a nice idea and I don't think it would affect the contact/social-media field and the other fields that I have mentioned in the PR.

If this is a requirement we can definitely work on it and the discuss the approach here. I am assuming that we would need a different table to implement this.

**Comment by AndrewKvalheim** [comment]
Addressing a similar need: #3058

**Comment by hennevogel** [comment]
GSoC is long over :)
