### ISSUE TITLE
Feature tests are broken due to Chrome error

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#2540]
Since a few days we get the following error in the feature tests:

```
Selenium::WebDriver::Error::UnknownError:
  unknown error: Chrome failed to start: exited abnormally
     (unknown error: DevToolsActivePort file doesn't exist)
     (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

Check for example https://travis-ci.org/openSUSE/osem/jobs/544820037

It seems to be a credentials error:

> ERROR -- omniauth: (google) Authentication failure! invalid_credentials encountered.

This is an important issue as we can not merge new PR without ensuring the tests  are working.

@hennevogel do you know something about this?

**Comment by Ana06** [comment]
@hennevogel @differentreality @bear454 anybody has any idea how to solve this?

**Comment by hennevogel** [comment]
might be https://github.com/openSUSE/open-build-service/pull/7794

**Comment by Ana06** [comment]
@hennevogel 

> might be openSUSE/open-build-service#7794

I don't think it is the same one. In the one you send it is realated to W3C:

> unknown command: Cannot call non W3C standard command while in W3C mode

while in OSEM we have an authentication problem:

> ERROR -- omniauth: (google) Authentication failure! invalid_credentials encountered.

@hennevogel any idea where this problem is coming from?

**Comment by Ana06** [comment]
Fixed in https://github.com/openSUSE/osem/pull/2548
