### ISSUE TITLE
Generate html files including OSEM conference data

### ISSUE THREAD

**Issue by sbernhard** [openSUSE/osem#2565]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature Request

**Current behavior:**
It's not possible to generate HTML files containing conference data which can be integrated to a CMS like wordpress. Currently its not possible to show the views in the way you like it - you need to use the OSEM generated, static format.

**Expected correct behavior:**
It would be nice, to have something like a template engine which can be used to generate HTML files containing conference data. The HTML files can then be used to integrate them in a CMS like wordpress. Using a template engine it should be possible to reference a OSEM conference. Using this it should be possible:
- to create a nice HTML file showing the speakers of a conference (table view including the short title of the talk)
- user-defined conference schedule view

**Comment by hennevogel** [comment]
You can use our API to query most data we have for conferences. However you integrate this into your CMS is up to you I would guess.

**Comment by sbernhard** [comment]
Thanks @hennevogel.
