### ISSUE TITLE
Support for banner photos?

### ISSUE THREAD

**Issue by cycomachead** [openSUSE/osem#2626]
**I'm submitting a ..**
- [ ] Bug Report
- [X] Feature Request

It seems like there used to be a way to have a banner photo for a conference splash page. Is this still possible?

**Comment by differentreality** [comment]
No, I am afraid not. By default the conference color is used to create a bg with triangles
https://github.com/openSUSE/osem/blob/master/app/views/conferences/show.html.haml#L82
