### ISSUE TITLE
Cannot sign in for openSUSE virtual summit; Error 500

### ISSUE THREAD

**Issue by norwegianPancakes** [openSUSE/osem#2660]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

I can view the login screen and enter my credentials; I get Error 500 when logging in. The error persists until I delete my browser history. Afterwards, rinse and repeat; login to see the error again.

**Expected correct behavior:**

I assume that I need to use my SUSE account to log in. I should see some page that isn't an error. I am registering for a conference for the first time so I don't know exactly what to expect, other than an error.

**Steps to reproduce:**

Go to https://www.opensuse.org/. 
Click Conferences at the top right. Your browser will scroll to the bottom.
Click View Upcoming Conferences.
Wait a little bit for the page to load, then click Sign In at the top. Enter your SUSE credentials then login.
You should get the following error:
![Screenshot_20200410_132649](https://user-images.githubusercontent.com/63428680/79020933-0ffade80-7b2f-11ea-9723-077bffc4bc40.png)

**Other information:**

**Comment by hennevogel** [comment]
should be fixed now

**Comment by hennevogel** [comment]
On production [this column](https://github.com/openSUSE/osem/blob/master/db/schema.rb#L559) was not having a default value. Which made every new sign up crash.
