### ISSUE TITLE
Can't review proposals

### ISSUE THREAD

**Issue by brianharvey** [openSUSE/osem#2669]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
On a proposal page, near the bottom there's a place to give the proposal 1-5 stars and another place to make comments.  The comments are stored correctly, but the stars disappear after leaving that page.  There's no way to rate the proposal that sticks.

**Expected correct behavior:**
When I give a proposal some number of stars, that should be remembered.

**Steps to reproduce:**
Go to the Program>Events page, click on a proposal title, scroll down, try to record stars (with admin privileges).

**Other information:**

**Comment by differentreality** [comment]
Can't reproduce, ie my user with `is_admin: true` and no roles can successfully submit a star rating, and the star rating persist when I refresh the page. 
If this is still an issue for you, please provide us with 
* the commit you are at 
* the roles the user has
