### ISSUE TITLE
Registration/CFP Start Dates in the "Past"

### ISSUE THREAD

**Issue by cycomachead** [openSUSE/osem#2674]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
When you edit a registration or CFP, the start date changes to become the current date which is wrong. 

**Expected correct behavior:**
I should be able to set a start date in the past, and the front end shouldn't enforce a constraint here. There's nothing that _breaks_ when the start date has fewer restrictions and removing this one line fixes a usability annoyance.

https://github.com/openSUSE/osem/blob/9fd55d528ce394c8f524ae1864a63414fe5e0ebf/app/assets/javascripts/osem-datepickers.js#L65

**Steps to reproduce:**
1. make a cfp
2. wait a day
3. edit the CFP
4. Notice the start date changed.

this is for CFPs and conference registrations which use the same date picker. It's a bug in both cases. 

**Other information:**
The fix, in my view, is trivial and it's just to remove the front-end restriction. Is there any opposition to that?

**Comment by AndrewKvalheim** [comment]
Does #3093 address this?

**Comment by cycomachead** [comment]
Yes, that should. I just merged this into my fork recently. Thanks for following up. :)
