### ISSUE TITLE
UTC Time for scheduling talk

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/osem#2676]
I'm submitting a Feature Request. Since we moved to online events during the COVID-19 pandemic, it would make sense to have a UTC time option for scheduling a conference. Picking a similar time will not work since some conferences are during the daylight savings timeframe.

![Screenshot from 2020-06-03 11-06-11](https://user-images.githubusercontent.com/8996626/83618828-4da64180-a58b-11ea-82bd-6fdcddb6bf6e.png)

**Comment by AndrewKvalheim** [comment]
I see a UTC option now:

> <img src="https://user-images.githubusercontent.com/1844746/222943666-3f47832a-a73a-46ee-b090-02a512bf6252.png" width="410" alt="(GMT+00:00) UTC" />

However from what I understand it also existed at the time this issue was reported—

```console
$ docker run --rm ruby:2.5 sh -c "gem install --silent tzinfo-data:1.2020.1 nokogiri:1.12.5 activesupport:5.2.3 actionview:5.2.3; ruby -r active_support/all -r action_view/helpers -e 'include ActionView::Helpers' -e 'puts time_zone_options_for_select.lines.grep(/UTC/)'"
<option value="UTC">(GMT+00:00) UTC</option>
```

—so I’m not sure whether the problem has actually been addressed.

**Comment by ddemaio** [comment]
@AndrewKvalheim Yes, this is new, so looks like it was added.
