### ISSUE TITLE
Merge Registration Questions and Surveys?

### ISSUE THREAD

**Issue by cycomachead** [openSUSE/osem#2684]
**I'm submitting a ..**
- [ ] Bug Report
- [X] Feature Request

**Current behavior:**
Registration questions are their own functionality, and have only limited answer options.

**Expected correct behavior:**
I would like to build a survey that asks some short answer questions at registration.

**Steps to reproduce:**

**Other information:**
Done right it seems like this could give us flexibility without adding more code, since I would reuse some bits that exist, and ideally remove unneeded code.

**Comment by differentreality** [comment]
You are currently able to create a survey (from the admin area) with questions that will appear during registration to the conference. Is that not what you are looking for?

Survey is per-conference, and  you need to choose the during_registration option
![Screenshot from 2020-10-28 18-32-12](https://user-images.githubusercontent.com/4322737/97466697-11191f00-194c-11eb-85a2-e146f9221888.png)

Does that cover what you need? If not, please do provide details.

**Comment by cycomachead** [comment]
Thank you! I think this does work -- though it's a little confusing why there's 2 very similar features. If it's just a legacy thing, I do understand that. I am not sure if there was a specific reason to use one feature over the other?
