### ISSUE TITLE
Rails update breaks migration because of missing versions

### ISSUE THREAD

**Issue by bennettscience** [openSUSE/osem#2706]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
When doing a new database setup, `db:migrate` fails because old migrations are missing the Rails version the migration was created for.

**Expected correct behavior:**
The migration should succeed.

**Steps to reproduce:**
Starting with a clean download (no gems, no databases set up), install gems from the current lockfile.
Run` bundle exec rake db:create` to create databases.
Run `bundle exec rake db:migrate` to apply migrations to the database.

The rake task aborts with `Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for.`

**Other information:**
This change was introduced in Rails 5.

**Comment by bennettscience** [comment]
Just found #2422 which solved this.

**Comment by AndrewKvalheim** [comment]
See also #2665 for existing databases.
