### ISSUE TITLE
Organizations/Conferences Index Shows all conferences

### ISSUE THREAD

**Issue by cycomachead** [openSUSE/osem#2743]
**I'm submitting a ..**
- [X] Bug Report
- [ ] Feature Request

**Current behavior:**
IMO, this is a bug, but it seems somewhat intentional...
The routes /conferences/ and /organizations/:id/conferences should the same list of (all) conferences.

**Expected correct behavior:**
/conferences should show all conferences, /organizations/:id/conferences should filter on the org id.

**Steps to reproduce:**
* Have a conference in 2 different orgs.
* Go to each orgs conferences index page.

**Other information:**

**Comment by mkiroshdz** [comment]
@cycomachead @hennevogel Is this still an issue? 
If it is I would like to work on it please.

**Comment by hennevogel** [comment]
@mkiroshdz Hey Monica!  There is no need to ask me for "permission" to work on something. Just verify yourself if this is still an issue (in the development environment) and send a pull request if it is. Looking forward to it. If you need any help, let us know here 😃

**Comment by mkiroshdz** [comment]
@hennevogel @cycomachead I tried to reproduce this but seems to me like it's filtering org conferences correctly.

**Comment by cycomachead** [comment]
Sorry about that! I think I had something misconfigured. You're right -- I do think this works correctly.
