### ISSUE TITLE
Launch Conference Button to Venueless

### ISSUE THREAD

**Issue by cho2** [openSUSE/osem#2768]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature Request

**Current behavior:**
No button to go to Venueless (https://opensuse.venueless.events/) for oSVC21 attendee

**Expected correct behavior:**
There is a "Launch Conference" button for oSVC21 attendee to Venueless (https://opensuse.venueless.events/)

![screenshot-events opensuse org-2021 05 15-23_27_55](https://user-images.githubusercontent.com/6271071/118371124-4d088e80-b5d5-11eb-8c8e-e367bf9d86e3.png)

**Steps to reproduce:**
n/a

**Other information:**
Reference https://linux.conf.au/news/welcome-to-lca2021/ on "Logging On" section

**Comment by hennevogel** [comment]
If you want some patches to events.opensuse.org you should create a ticket for the openSUSE installation. Send mail to admin@opensuse.org
