### ISSUE TITLE
Wrong default OSEM_ROOT_CONFERENCE

### ISSUE THREAD

**Issue by eladeyal-intel** [openSUSE/osem#2908]
the "production setup" , following the instructions in `INSTALL.md` by default seems to redirect `/` to `/osc18`

So you setup the demo, navigate to `http://localhost:8080` and... get 404 :-(

I needed to edit `.env.production` to add `OSEM_ROOT_CONFERENCE=` in order to get to the nice welcome page (the one saying "first user to sign up is the admin".

With 2018 being behind us, I think the default should change to nil.

**Comment by hennevogel** [comment]
`.env.production` is yours and not part of the repo. In dotenv.example `OSEM_ROOT_CONFERENCE` is commented.
