### ISSUE TITLE
Cleanup proposal forms

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#2921]
There are currently the following views

- `app/views/proposal/new.html.haml` with a form to create a new `Event`
- `app/views/proposal/form.html.haml` with the edit view
- `app/views/proposal/edit.html.haml` with 3 lines of html of the edit view
- `app/views/proposal/_proposal_form.html.haml` with form to edit an `Event`

This should be cleaned up into `new`, `edit` view and a `form` partial

**Comment by mkiroshdz** [comment]
@hennevogel was this ticket taken care of?. I would like to work on it.
