### ISSUE TITLE
Missing templates for admin forms

### ISSUE THREAD

**Issue by AndrewKvalheim** [openSUSE/osem#2975]
**I'm submitting a ..**

- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

Some pages in the admin interface are broken with `ActionController::MissingExactTemplate`:

- [ ] Administration → Users → Edit (`Admin::UsersController#edit`)
- [ ] Manage conference → Events → Add Event (`Admin::EventsController#new`)

**Expected correct behavior:**

Show the appropriate form.

**Steps to reproduce:**

In a new instance, create a conference and navigate as above.

**Other information:**

Completing #2921 should help with this.

**Comment by hennevogel** [comment]
It's probably fallout of removing the general new/edit/form templates from `app/views/layouts`

**Comment by hennevogel** [comment]
Also point to some missing specs

**Comment by Liberatys** [comment]
@hennevogel I'd love to work on this ^^ Seems like a good first issue to get started 😉

**Comment by hennevogel** [comment]
@Liberatys knock yourself out 😃

**Comment by YTeyddie22** [comment]
Is this issue still open?

**Comment by hennevogel** [comment]
@YTeyddie22 sure is

**Comment by mkiroshdz** [comment]
@hennevogel I'm working on putting the views back but I'm not sure what fields the user form needs to have. Can you please provide me those?. Thanks

**Comment by AndrewKvalheim** [comment]
For reference here’s the former template resolution:

<pre>Started GET "/admin/users/1/edit"
Processing by Admin::UsersController#edit as HTML
  Rendering <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/layouts/application.html.haml">layouts/application.html.haml</a>
  Rendering <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/application/edit.html.haml">application/edit.html.haml</a> within layouts/application
  Rendered <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/admin/users/_form.html.haml">admin/users/_form.html.haml</a></pre>

<pre>Started GET "/admin/conferences/example/program/events/new"  
Processing by Admin::EventsController#new as HTML  
  Rendering <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/layouts/application.html.haml">layouts/application.html.haml</a>
  Rendering <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/application/new.html.haml">application/new.html.haml</a> within layouts/application
  Rendered <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/proposals/_proposal_form.html.haml">proposals/_proposal_form.html.haml</a>
  Rendered <a href="https://github.com/openSUSE/osem/blob/3bbbdb4aae9d4be9ce1bba35fc7586988261d5a9/app/views/admin/events/_form.html.haml">admin/events/_form.html.haml</a></pre>

**Comment by Amjt11** [comment]
Lol

**Comment by ams0** [comment]
I'd love to use this for [Kubernetes Community Days Amsterdam 2023](https://cloudnative.amsterdam) but currently hitting this bug too, I cannot add events to manually create the conference schedule. I deployed it on a VM using docker compose instructions.

**Comment by AndrewKvalheim** [comment]
While they’re not yet reviewed there are a few attempted solutions you could pull from in a pinch:

- #3073, which introduces undiscussed changes and has no tests
- #3092, which introduces undiscussed changes, has no tests, and ignores the existing pull request
- the following collection of commits, which restore and test the forms but haven’t been submitted back upstream:
    - [Add test of admin editing a user](https://github.com/AndrewKvalheim/osem/commit/2cb770aa6e2c7e884356e10961cf6b2dae0fbec8)
    - [Add test of conference organizer adding a proposal](https://github.com/AndrewKvalheim/osem/commit/4a66692b30c46af447f302a62e38fb5e375521c5)
    - [Restore views for Admin::EventsController#new and Admin::UsersController#edit](https://github.com/SeaGL/osem/commit/5224515e0267b109535bd36704a9f2c5bbab1312) (restoration process noted in commit message)
