### ISSUE TITLE
Refactor conferences_controller

### ISSUE THREAD

**Issue by carlosdanielpohlod** [openSUSE/osem#3036]
**I'm submitting a ..**
- [ ] Bug Report
- [ x ] Feature Request

**Current behavior:**

**Expected correct behavior:**

**Steps to reproduce:**

**Other information:**
Refactoration of conferences_controller.

**Comment by diwakar9274** [comment]
Hi if this issue is still open can you please let me know which confrences_controller you are talking about as there are multiple like inside admin, user or api.

**Comment by hennevogel** [comment]
No need to open issues if you want to refactor something :)
