### ISSUE TITLE
Error 500: Internal Server Error when adding this character to biography 🐘

### ISSUE THREAD

**Issue by AlicjaKucharczyk** [openSUSE/osem#3258]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**
Getting Error 500: Internal Server Error when adding this character to biography 🐘 in Edit your profile page

**Expected correct behavior:**
no error :)

**Steps to reproduce:**
go to Edit your profile and try to use 🐘 somewhere

**Other information:**

**Comment by AndrewKvalheim** [comment]
Sounds like #2686

**Comment by hennevogel** [comment]
duplicate of #2686
