### ISSUE TITLE
I cannot login into events.opensuse.org, so I cannot register for openSUSE conf 2024 nor submit talk proposals

### ISSUE THREAD

**Issue by binary-sequence** [openSUSE/osem#3264]
**I'm submitting a ..**
- [x] Bug Report

**Current behavior:**
- Trying non-existing account gives an expected error of "invalid account".
- Trying the existing account (same used for build.opensuse.org) the pages fails with error "too many redirects". After that any visit to events.opensuse.org fails with "too many redirects"
  - Happening on openSUSE Tumbleweed (Chrome and Firefox) and iOS with Safari.
  - Deleting the cookies allows me to visit the page again, but after logging in, I always get a "too many redirects".
- Logging in with the same account on build.opensuse.org works

**Expected correct behavior:**
After I log in into events.opensuse.org, I can register for openSUSE conf 2024 and submit talks proposals.

**Steps to reproduce:**
1. Visit events.opensuse.org
2. log in
3. page doesn't load anymore with "too many redirects error"

**Comment by hennevogel** [comment]
I'm sorry that I have to close this, but we are tracking issues in the source code in here. Github issues are ***not*** a way to request support from openSUSE.

For events.opensuse.org please contact admin@opensuse.org

Thank you for your consideration.
