### ISSUE TITLE
Ahoy error (ID constraint)

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#379]
@ChrisBr as we discussed a couple of times we continue having this error:
http://paste.opensuse.org/83963228

It just occured over 4 times while creating a new proposal or registering for a conference.

It also seems to be a problem with other people:
https://github.com/ankane/ahoy/issues/32

**Comment by meonkeys** [comment]
I'm seeing a bunch of errors like https://github.com/openSUSE/osem/issues/379#issuecomment-66979240 in my log/production.log file for https://osem.seagl.org/ . For example:

    Mysql2::Error: Duplicate entry '4' for key 'PRIMARY': INSERT INTO `visits` ...

(snipped). Also, for one other table:

    Mysql2::Error: Duplicate entry '9' for key 'PRIMARY': INSERT INTO `ahoy_events` ...

(also snipped)

I'm running OSEM from 124d275a09c3c2035a47ad394c64de72a3249a38

**Comment by differentreality** [comment]
https://github.com/ankane/ahoy/issues/32  is now closed and there are new versions of ahoy gem. Worth updating and re-checking if this issue is still valid?

**Comment by bear454** [comment]
Ahoy is a performance train wreck. IMO the campaigns feature isn't worth the trouble, but even if it is, I'm confident it can be handled much more performantly _without_ Ahoy. I'll extract my WIP changes out to a commit and link here. (I've removed Ahoy for LFNW branch).

**Comment by bear454** [comment]
Closed with #2205.
