### ISSUE TITLE
call for paper start date can't be in the past

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#411]
Yeah, why would you want to have the call for paper date be in the past... well, if you update the call for papers from, say, March to end of July to extend it into August and suddenly, you have to make it say that the CfP opened on August 1st! That is just not true and looks silly.
It shows up on
http://conference.owncloud.org/conference/OCC14

And I can't get it to the past ;-)

Not a huge deal, but not nice either.

**Comment by ChrisBr** [comment]
@differentreality Yep, it's fixed!

**Comment by jospoortvliet** [comment]
Thanks! Soon we'll start organizing the event for 2015 and I'm hoping there will be a release we can use from osem at some point ;-)
