### ISSUE TITLE
Refactor Conference: Program

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#417]
* has_one Program
 * has_many Rooms()
 * has_many Tracks()
 * has_many DifficultyLevels()
 * has_many Events()
 * has_many EventTypes()

**Comment by ChrisBr** [comment]
@hennevogel same here, refactoring is done?

**Comment by hennevogel** [comment]
Nope all of them are still somewhere else.

**Comment by differentreality** [comment]
Program to also include call_for_papers?

**Comment by hennevogel** [comment]
The call for papers stuff should be inside Program I think

**Comment by differentreality** [comment]
I am thinking this would also result in a change in routes, eg:
admin_conference_events_path -> admin_conference_program_events_path

**Comment by differentreality** [comment]
All done here?

**Comment by hennevogel** [comment]
Jawoll! :-)
