### ISSUE TITLE
Dashboard: Withdrawn Events

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#463]
At the top bar information there should be the following:
- sadly the event X, Y and Z where withdrawn

**Comment by chocoelho** [comment]
Since @hennevogel had it renamed, should it be on top bar or should it be on another section in dashboard?

**Comment by hennevogel** [comment]
How about you come up with a solution and present it? Then we can discuss it :-)

**Comment by chocoelho** [comment]
k, I'll do it

**Comment by chocoelho** [comment]
So, one more thing, what would be better: using id from events or title? Title would make it more readable than id, but it's not unique.

**Comment by agrim123** [comment]
@ChrisBr i m interested on working on this issue.
