### ISSUE TITLE
Make it possible to deal with very short or arbitrary length talks

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#481]
Hi osemers,

A nice challenge for you. We have 5 minute lightning talks with 1 minute time in between. That can't be scheduled as the scheduling works per 15 minutes ;-)

Figure out a solution!

Hugs,
Jos

**Comment by meonkeys** [comment]
We have 50 minute talk slots at SeaGL. We just crammed `50` into the database. :frog:

**Comment by ChrisBr** [comment]
@meonkeys be careful with that! The event length should be a multiple of 15, otherwise schedule will look messed up ...

**Comment by meonkeys** [comment]
Uff da! Good to know, thank you.

Cc: @shanet, @altsalt, @eximious

**Comment by jospoortvliet** [comment]
It continues to be a pita, I think. We do want 5 min lightning talks and yes, pre-scheduled of course -otherwise you have to schedule 10 min for each, as it costs 5 min to twiddle with the projector for each presenter...

A single 1 hour lightning track slot works but the scheduling tool can't deal with that very nicely: all the 5 min slots show up and pollute the list, making it very hard to schedule things.

**Comment by differentreality** [comment]
@aspiers this is now configurable through program, marked as **schedule interval** and it is expected to be a value of 5, 6, 10, 12, 15, 20, 30 or 60.

http://demo.osem.io/admin/conferences/osemdemo/program/edit
