### ISSUE TITLE
Feature Request -- Scheduling>show times for all rooms

### ISSUE THREAD

**Issue by ghost** [openSUSE/osem#512]
When scheduling, the first rooms entered have times listed in the left column.

With more than 4 rooms, additional rooms are shown further down the page, and time slots are not shown. This makes it difficult to drag-n-drop events onto the schedule.

Would it be possible to show the left column of time slots for each of the room groupings?
![times_in_firstrooms](https://cloud.githubusercontent.com/assets/8466850/4516761/81796ec6-4c07-11e4-9823-151fdb7351e2.png)

-----------------------------------------

![times_in_otherrooms1](https://cloud.githubusercontent.com/assets/8466850/4516764/8b181f2c-4c07-11e4-81ee-f1535944df65.png)

**Comment by hennevogel** [comment]
This simply happens when the amount of rooms is larger then the screen width. The whole page isn't responsive, but obviously it needs to be.

**Comment by differentreality** [comment]
Fixed in https://github.com/openSUSE/osem/pull/1094
