### ISSUE TITLE
dashboard status is minutes, not hours

### ISSUE THREAD

**Issue by ghost** [openSUSE/osem#519]
@ChrisBr @bear454 

Chris wrote of the categories at the top of the conference dashboard...
The Hours category sums up the length of each submitted talk. This is useful if you know that you have room / time for X hours program then you can compare it with this number to check if you have already enough submissions.

This is actually the number of _minutes_ (not hours). Nice statistic for measuring various conference areas!!

**Comment by differentreality** [comment]
When in hours, we run into the problem of accuracy, as it doesn't make much sense to show 3.2 hours but we should be able to see that it's more than 3 hours.

Any ideas?

![minutes](https://cloud.githubusercontent.com/assets/4322737/5592723/8b83a14a-91e7-11e4-9c3e-a216da3c78f3.png)

**Comment by kallecarlkde** [comment]
On 01/01/2015 08:54 AM, Stella Rouzi wrote:
> When in hours, we run into the problem of accuracy, as it doesn't make
> much sense to show 3.2 hours but we should be able to see that it's more
> than 3 hours.
>
> Any ideas?
>
> minutes
> <https://cloud.githubusercontent.com/assets/4322737/5592723/8b83a14a-91e7-11e4-9c3e-a216da3c78f3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openSUSE/osem/issues/519#issuecomment-68491437>.
>

showing "days, hours, minutes" helps convey the information; minutes 
gives it a sense of urgency despite the remaining duration. This format 
can stay in place from start to finish.

Each category needs to accommodate the range of expected numbers...
Days could be as much as triple digits as some CfP deadlines are 4 or 
more months in the future, and "hours" doesn't work for long lead times.
Hours - 24 to 0; minutes 60 to 0.
I think that people would understand ###d, ##h, ##m

There's also an issue of making the information fit in the dashboard 
appropriately...in a line or stacked?

As a conference organizer, I like the countdown to close information 
being available to potential participants.

Carl

**Comment by shayonj** [comment]
I can get going with this. From the above, I feel ```Day, Hour, Min ``` makes sense and can convey accurate information right away. So yes, a countdown in place.

Please correct me if wrong, or there is some other way(s) we can handle this.

**Comment by hennevogel** [comment]
Just hours, rounded please. This is about getting an overview of the state of your submissions not about total accuracy.

**Comment by ChrisBr** [comment]
@shayonj Please note that it's also necessary to change the unit of targets / goals to hours!
(https://github.com/openSUSE/osem/blob/master/app/models/target.rb#L12)
Migration etc..

@hennevogel

**Comment by raluka** [comment]
@ChrisBr : ready to be closed?

**Comment by ChrisBr** [comment]
See #611 
We need to transform targets to minutes, too!

```
@hennevogel But what we have to bear in mind: There is now a mismatch between tagets / goals and the dashboard! A target has the unit minutes and in the dashboard we now have hours. So we have to migrate the targets / goals also to hours, otherwise it's hard to compare the values ... What do you think, do we want to fix that in an additional PR?
@shayonj Can you fix that also?
@shayonj
shayonj commented on Mar 16

@ChrisBr sure, I can do.

I will wait for @hennevogel to get back on the new PR reply and then accordingly proceed :)
@hennevogel
Owner
hennevogel commented on Mar 16

@ChrisBr moving target to hours sounds like a plan
@ChrisBr
Collaborator
ChrisBr commented on Mar 16

@shayonj I will merge this PR! As described, we want to switch the targets unit also from minutes to hours, if you could do that, it would be awesome!
```

**Comment by hennevogel** [comment]
#611 is also merged...
