### ISSUE TITLE
package for osem

### ISSUE THREAD

**Issue by tampakrap** [openSUSE/osem#561]
For production people could benefit from a package of OSEM. The new ruby packaging scheme in openSUSE can read the dependencies from gemspec, thus first we would need a gem in rubygems.org. The generated RPM could optionally offer generic config examples for various web server deployments, and possibly run automatically the DB migrations in updates. Thus, the steps here are:
1. Create osem.gemspec with the production dependencies (based on the current Gemfile)
2. Leave only development/test deps in Gemfile, tell it to read the rest from gemspec
3. Decide what non-ruby files include/exclude from gemspec
4. Generate sample config files for webservers
5. Generate gemfile, test and upload to rubygems.org
6. Create the RPM with gem2rpm in OBS
7. Check if any additional optional or non-ruby dependencies are needed to be included in the spec file
8. Check if we can automatically run db migrations with the RPM
9. Check if we can create packages for more distros that are supported in OBS

**Comment by hennevogel** [comment]
deploying a rails app is more than installing a package...
