### ISSUE TITLE
Name attribute empty

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#577]
After ichain implementation, the 'name' attribute for user is no longer required.

This lets users get created without a value for 'name' attribute.

But we use name, for example recent registrations in admin/conference/index.
Being blank is ugly and withholds the necessary information for no good reason.

http://paste.opensuse.org/89076165

**Comment by differentreality** [comment]
I have concerns about that, I am not sure 'username' is what we are really after here.

Username does not really tell me who is the last person to register to the conference, in the essence that:
if you see that 'differentreality' registered to a conference, that gives you much *different information* than seeing that 'Stella Rouzi' registered to the conference, which is actually a very straight forward info! 
(assuming you don't know me that well so that you can immediately relate my nickname, which may well be my username, to my real name)

**Comment by ChrisBr** [comment]
@differentreality If you ask me, I wouldn't worry too much about it! If you think that this information is really necessary, the only way to fix it is to make name mandatory (and in the same breath I would recommend to split name in first and lastname). But as I said, I think a good and acceptable solution would be to use the username...
@hennevogel What do you think about it?

**Comment by hennevogel** [comment]
Web apps usually have one primary identifier: **either** username or email address. I don't know a single one which requires me to set a Given Name and Surname.

But that does not keep us from showing this **IF** it is available. We can also update it from the Access Manager data (like we do it with the email address).

**Comment by ChrisBr** [comment]
@hennevogel @differentreality Facebook for instance requires for instance a first and surname ;)

That's a good point, showing the full name if there is one otherwise the username!
The Access Manager is an option, but not all instances use it (eg Owncloud)! If they don't use it, the name is still empty!

**Comment by hennevogel** [comment]
@ChrisBr this would be in [user#for_ichain_username](https://github.com/openSUSE/osem/blob/master/app/models/user.rb#L73) so it wouldn't matter for installations with ichain disabled...

**Comment by ChrisBr** [comment]
@hennevogel Yes, I know! Just wanted to let you know that this opportunity doesn't exist if ichain isn't enabled!

**Comment by differentreality** [comment]
Same problem in registrations list. Really looks bad and if the email does not contain the name of the user it is even more difficult for the Info Desk people to find the user in that registration list.

**Comment by hennevogel** [comment]
Rather then requiring a full name I would suggest we think about the whole registering and paper submission workflow from the organizers perspective. I'm pretty sure that printed lists with names on them are not the non-plus-ultra solution here :-) (think self-printed tickets, QR codes and whatnot!)
