### ISSUE TITLE
About Log in

### ISSUE THREAD

**Issue by alexvenn** [openSUSE/osem#588]
Hello,
I tried to sign in to osem (https://events.opensuse.org/conference/oSC15) with my account that I have also used for oSC13 & oSC14 & Summit13 and I couldn't connect... 

Finally I found that my novell acount works fine but what happend with the other email that I have already used for registration? 

Only with Novell account now I can register???
And if I am a new user and I don't wan't to create a Novell account???

**Comment by ChrisBr** [comment]
@alexvenn Yes that's true, OSEM is now connected to the Novel iChain Proxy! If your username of the openSUSE/Novell account was the same as your OSEM username, than these two accounts are now connected! Did you get an exception when logging in with your (old) OSEM credentials?

And yes, you can only register with an Novell/openSUSE account to a conference! But that was our intention, we wanted to integrate OSEM in the openSUSE login infrastructure! You need also an Novel/openSUSE account for opensuse news, TSP etc.

**Comment by alexvenn** [comment]
I don't know what happened with my old account. Now it doesn't work!
I have only the Novell account now.

Ok I have Novell account. But I was thinking...
Next conference is in Haag, and I am a local people/student that I want to go to openSUSE conference...why I have to created a novell account and I don't have other options??? 
I want only to participate to this conference because is close to my home...
why I can't use only my email? 

This example is based on realy problem that we had on oSC14...
Local volunteers didn't want to regisrter to osem and give their email...

**Comment by ChrisBr** [comment]
@alexvenn I see! On the one hand we wanted to integrate OSEM in the openSUSE infrastructure and on the other hand I don't know if it's possible (and makes sense at all) to combine different login approaches...

Can you join #osem on freenode, than we can investigate what happened with your account ...

**Comment by hennevogel** [comment]
Merged his 2 accounts on the openSUSE instance...
