### ISSUE TITLE
Registrations PDF broken

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#589]
NoMethodError: undefined method `attending_social_events' for #<Registration:0x0000000597c9f8>

We have to remove the attending_social_events attribute from the prawn file

**Comment by shubhankardesh** [comment]
What is the cause of NoMethodError?

**Comment by shubhankardesh** [comment]
Suppose the attribute is removed, then what could be a substitute for 'attending_social_events'?

**Comment by differentreality** [comment]
We have introduced questions.
Organizers can create their own custom questions with stuff they want to ask to attendees.
These questions (if they exist) they appear in the registration page.

**Comment by shayonj** [comment]
I am planning on taking this up. I see that both ```attending_social_events``` and ```attending_with_partner``` are no longer the columns. 

So we would need to remove this from both - https://github.com/openSUSE/osem/blob/master/app/views/admin/registrations/index.pdf.prawn  and https://github.com/openSUSE/osem/blob/master/app/views/admin/registrations/index.xlsx.axlsx  , right?

**Comment by differentreality** [comment]
Yes that is correct.  We need to remove those attributes from everywhere, as they are no longer used.
Some work is already being done in https://github.com/openSUSE/osem/pull/601

**Comment by ChrisBr** [comment]
@differentreality I'll close this one because it's fixed in #645 right?
