### ISSUE TITLE
Abstract word counting does not seem to work

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/osem#590]
When entering abstract for talk on openSUSE conference 2015 the abstract words are not counted. Regardless of the content I see there "You have used 0 words. Abstracts must be between 0 and 250 words. "

The browser is chromium 40 and only extension is adblock, so no disabled scripting.

**Comment by v0dro** [comment]
I'll do this. Could you please assign me to it?

**Comment by hennevogel** [comment]
No need to. Just do it :neckbeard:

**Comment by v0dro** [comment]
I've zeroed the bug to [this line](https://github.com/openSUSE/osem/blob/master/app/assets/javascripts/osem.js#L169).

The funny thing is, when I copy paste the entire `$("#event_abstract").bind` function into the browser, the abstract count is updated properly! (exact same code)

Any idea why this should happen?

**Comment by v0dro** [comment]
It works now.

Please evaluate.

**Comment by differentreality** [comment]
Fixed in #678
