### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#591]
Provide the ability to add a code of conduct to a conference that is displayed on the splash page and can be hooked into the 'ticket sales' workflow.

**Comment by hennevogel** [comment]
Interesting read on how to integrate it into the ticket workflow: http://blog.thefrontiergroup.com.au/2015/05/using-cancan-to-implement-an-agree-to-terms-workflow/

**Comment by bear454** [comment]
How about registration workflow instead?
