### ISSUE TITLE
Find a way to replace plain html building in ApplicationHelper.format_comments

### ISSUE THREAD

**Issue by kalabiyau** [openSUSE/osem#600]
https://github.com/openSUSE/osem/blob/master/app/helpers/application_helper.rb#L150

Better way to do that is to introduce partial which should be rendered rather than plainly build html template by hand

**Comment by shayonj** [comment]
I will get going with this one :)

**Comment by hennevogel** [comment]
Great! Rock 'n' Roll @shayonj

**Comment by raluka** [comment]
@ChrisBr : ready to be closed?

**Comment by ChrisBr** [comment]
fixed with  #604
