### ISSUE TITLE
Additonal info questions on registration page

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#607]
Questions in registration form are rendered with partial "_questions.html.haml" which uses a loop for each question.
```ruby
- @conference.questions.each do |q|
  = f.inputs 'Additional Info' do
```
Now if there are more than one question then "addtional info" will be repeated more than once.

Additionally, Why do question types with id = 3 have their label set as false? Questions title are not showing up for multiple choice answers.. 

```ruby
 - if q.question_type.id == 3  # multiple choice
      = f.input :qanswers, :collection => q.qanswers, :as => :check_boxes, :input_html => { class: 'col-sm-2' }, :label => false,
                :member_label => Proc.new {|a| a.answer.title}
```

![screenshot from 2015-02-28 23 47 48](https://cloud.githubusercontent.com/assets/7680662/6429863/2a9a1cec-c013-11e4-9811-ef57fbd9df48.png)

**Comment by shayonj** [comment]
One way to handle this would be change

```
= f.inputs 'Additional Info' do
```
to 
```
= f.inputs q.title do
```
Mark label false in both the areas. And then just add a legend with some some sort of heading number for ```Additional Info``` before the loop. Something like
```
%legend
  %h2 Additional Info
```

This way you wont be running into margin issues for input items. Just a quick thought :)

**Comment by sonalkr132** [comment]
Wouldn't that violate belongs_to relationship of all the questions with "additional info"? https://github.com/justinfrench/formtastic#user-content-its-awesome-because
There isn't an actual relationship between them but that's how things were being done in rest of forms.

That would solve the margin issue but now one has to deal with underlined question titles.

**Comment by shayonj** [comment]
Never mind, I overlooked the association based setup there. Was definitely a quick thought :)

**Comment by differentreality** [comment]
Issue fixed.
