### ISSUE TITLE
Implement a listing for confirmed, but not yet scheduled talks

### ISSUE THREAD

**Issue by hcderaad** [openSUSE/osem#610]
Currently in OSEM events only become visible on the central event page (or schedule) when they are scheduled.
This is suboptimal because it means that scheduling needs to start at a very early time in the organization of the event and therefor will change a lot.
That is not very friendly to speakers (because they get a lot of date/time changes for their talks), and also inconvenient for attendees because changing talks often is confusing.

What would help is simply having a listing block (or specific page) with the titles of talks that have already been confirmed, but not necessarily have been scheduled.

Accepted talks are already world viewable for anyone having a direct link to the talk. So this feature should only implement a listing of these world viewable links (with the talk titles), and if possible a cropped version of the abstract.

**Comment by ChrisBr** [comment]
@hennevogel So you would suggest an extra page or tab on the schedule page?
Any other input on this one? Maybe I can look at it tonight!
@hcderaad

**Comment by hennevogel** [comment]
@ChrisBr I guess an extra tab (like All Events) on the schedule page would be the quickest solution. A simple datatable sounds feasible. Another dimension of this would be the Ability Events. So far confirmed-not-scheduled events are not visible to the public.

**Comment by ChrisBr** [comment]
Okay, I will have a look at it tonight!

**Comment by differentreality** [comment]
https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L116

**Comment by ChrisBr** [comment]
So how do we want to go: Show the event/talk if it is accepted (by the organizers) or confirmed (accepted and the speaker confirmed)?
@hennevogel @differentreality @hcderaad

**Comment by hcderaad** [comment]
@ChrisBr Thanks for picking this up!

Could we make that a configuration option?
Either implemented Event wide ("Publish Accepted talks to All Events page" and "Publish Confirmed talks to All Events Page") or per talk ("Publish this talk on the All Events page").

I can see use cases for both.

But for now, as far a I am concerned from the organization of oSC, I'd be very happy to have all Speaker confirmed talks published (since that is also an setting an admin can edit per talk).

**Comment by differentreality** [comment]
Accepted talk without the speaker's final confirmation does not mean much.
We should *not* make public unconfirmed talks.

**Comment by hennevogel** [comment]
@differentreality true that.  Regarding the work-flow I guess it can stay as it is. Either Call_for_paper.schedule_public is true and then confirmed talks show up or not...

**Comment by hcderaad** [comment]
@differentreality Well, if you host an uncon and have a lot of quickly entered talks you don't want to wait for the confirmation workflow since people will already be there, but an admin can already promote the status of a talk, so it's not that much of a functional issue. Perhaps I'm too fond of configuration options.

**Comment by differentreality** [comment]
@hcderaad if you have an uncon, you still need an organizer (someone with access to admin panel) to mark the submitted sessions as accepted. The organizer can also confirm the session immediately (you don't have to wait for the submitter to confirm it, which is the normal workflow).

**Comment by hcderaad** [comment]
@differentreality That's exactly what I meant, so indeed, at the moment I'd be very happy with just a very simple listing of all Speaker confirmed talks on a separate page.

**Comment by hennevogel** [comment]
Organizing unconferences in tools is like doing freestyle rap with a rhymebook in hand ;)

**Comment by hcderaad** [comment]
@hennevogel :-) Any updates on this?

**Comment by ChrisBr** [comment]
@hcderaad Please see PR https://github.com/openSUSE/osem/pull/612

There are still some issues but I think I fix it tonight...

**Comment by hcderaad** [comment]
@ChrisBr Looks very promising, many thanks for your efforts! As far as i'm concerned, a title for this could be Events (like its called in the admin interface), but program is fine as well. Regarding the schedule being visible, I'd recommend only displaying that when there are actual events/talks scheduled.
