### ISSUE TITLE
Switch checkbox does not work properly with datatabales

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#614]
Eg in events#index, the switch checkbox is only shown for the first page (first set of data), if you click next or show all, you do not see a switch checkbox for the rest of the records.

**Comment by differentreality** [comment]
Looks like when extra data is loaded, the js from osem-switch is no longer available (even though the class: 'switch-checkbox' is still there).

The event for datatables is
$('.datatable').on( 'draw.dt', function () { }

No we could add at this point the js code for the switch, but it would make more sense to reload osem-switch.js file, would it not?

**Comment by differentreality** [comment]
I don't see this happening any more

**Comment by hennevogel** [comment]
Then let's close this :-)
