### ISSUE TITLE
Public API url

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#616]
Anyone having seen code on github can figure this out. Only event organizers should be able to see this data?
![screenshot from 2015-03-13 23 23 19](https://cloud.githubusercontent.com/assets/7680662/6655114/6355b760-cb14-11e4-9301-825eeb5ded10.png)

**Comment by ChrisBr** [comment]
@sonalkr132 I think this is intentionally! Long time ago there was an Android app for OSEM which accessed the data via the API. You can also gather these information via the web interface. For instance

- https://events.opensuse.org/conference/osc15/proposal (tracks)
- https://events.opensuse.org/conference/osc15/schedule (rooms, speakers)

If you ask me, there are no security concerns. The only thing is that you can access the speakers and rooms before the schedule is public...
@hennevogel Do you think we should do anything regarding this issue?

**Comment by hennevogel** [comment]
Nope...
