### ISSUE TITLE
prefill your arrival time with dates of the conference

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#623]
If you are a good boy/girl and register well in advance for a event with OSEM, you get rewarded by having to scroll forward months and months until you get to the dates of the event ;-)

Most people won't arrive that far in advance so I suggest to open the date picker at least at the month of the event starting, perhaps even pre-select the event dates so people too lazy to fill this in don't get frustrated by it. Heck, make it non-mandatory?

**Comment by differentreality** [comment]
That's a good point.

Arrival/departure dates are not mandatory by the way. Could you double check?

**Comment by jospoortvliet** [comment]
ah, yes, that is not mandatory, I can get to the error page without entering it.

Also, wrong password, invalid email address etc gives proper warnings, so input validation works...

**Comment by differentreality** [comment]
So for this issue what is left is just fast-forward the calendar to conference dates, right?

**Comment by jospoortvliet** [comment]
@differentreality yeah, exactly. It's a minor thing...

**Comment by hennevogel** [comment]
Can be easily done in [app/assets/javascripts/osem-datepickers.js](https://github.com/openSUSE/osem/blob/master/app/assets/javascripts/osem-datepickers.js)

**Comment by jospoortvliet** [comment]
@hennevogel I suggest to make this a juniorjob then... ;-)

**Comment by eximious** [comment]
An alternative would be an option to tell the conference organizers, "I'm attending both days, attending just Friday, or just Saturday" tick box, or however many days your event spans. I think that would be more useful than the exact times for general attendees, even if that remianed an option for speakers to fill out. (Let me know if this would be better as a feature request.)

**Comment by jospoortvliet** [comment]
Yeah, just boxes that say what days you're there is easier, indeed...

**Comment by ChrisBr** [comment]
@eximious @jospoortvliet I like the idea too!

**Comment by differentreality** [comment]
As far as datepicker is concerned, using the option defaultDate sets the input box in that date on initilization (before the user actually selects anything from the calendar)

**Comment by jospoortvliet** [comment]
That would be a nice quick fix. In 3-4 months we'll update our instance and get ready for the next ownCloud Contributor Conference (this one was awesome!), I'm wondering if there is anything I should be aware off - you folks planning to do a release at some point?

**Comment by jospoortvliet** [comment]
actually we're looking at deploying registration for ownCloud conference 2016 already this year - was hoping to rekindle interest in this issue as it is quite a usability PITA...

**Comment by Shriyanshagro** [comment]
@eximious , good proposal . I have gone through the idea and vaguely get it. So @jospoortvliet  can you please elaborate the idea a bit more. I want to work on it.

**Comment by Shriyanshagro** [comment]
#911

**Comment by Shriyanshagro** [comment]
I tried , resolving this issue .
But got stuck at a point.
Is there any method through which I could get start_date of conference , without fetching it from url in form of Json.

**Comment by Shriyanshagro** [comment]
#919

**Comment by jospoortvliet** [comment]
Awesome. Yeah, just something like:

- [] day 1
- [] day 2

etc... that would cover it ;-)

**Comment by Shriyanshagro** [comment]
So than I guess , "users attending dates" would make more sense rather than "users arrival dates".. What say ?? On other side it would also help organizers to make count for each day.

**Comment by jospoortvliet** [comment]
Yeap, that wording is better.

**Comment by differentreality** [comment]
Closing due to https://github.com/openSUSE/osem/issues/1263
