### ISSUE TITLE
medium usability issue: no "forgot password" at signin option on conference registration

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#625]
Hi,

When registering for a conf, there's the 'sign in' option for those who already have an account. But unlike the sign in option on top of the screen, this one has no 'forgot password' or 'reset password' option. Would be nice to have ;-)

Probably a relatively simple thingy...

**Comment by jancborchardt** [comment]
Seconding that, this confused me a lot.

On a similar note: In the top right sign in dropdown, why is a click on »Need help?« needed to reveal the »Forgot your password« option? If it only reveals that one thing, might as well just show that already.

**Comment by hennevogel** [comment]
It reveals whatever is configured which can be one or a gazillion options...

**Comment by hennevogel** [comment]
Oh and as #639 is merged this is fixed. You fine ownCloud people should update your instance :-)

**Comment by jancborchardt** [comment]
Great stuff, thanks @differentreality for fixing! @jospoortvliet get to updating! :D

**Comment by jospoortvliet** [comment]
Unless there's a proper release which has had testing and can be upgraded (taking care of migrating database etc) too I'd rather keep our instance running as it is ;-)
