### ISSUE TITLE
Support social media card embedding

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#626]
An oembed-header, pointing to an [oembed](http://oembed.com)-file, significantly improves social media embedding. Since conference sites usually are advertized through social media, oembed would allow turning the card below a post that currently looks something like this:

![image](https://cloud.githubusercontent.com/assets/1315934/7063317/f85338ac-dea5-11e4-88c6-af0e6cf2cce8.png)

into this:

![image](https://cloud.githubusercontent.com/assets/1315934/7063351/3d276d4a-dea6-11e4-95cd-046d438cf0b3.png)

if somebody pastes the link into a social media site that supports oembed (FB, G+, etc). This mockup is based on embed.ly output.

/cc @jospoortvliet

**Comment by hennevogel** [comment]
I guess the key to this is [open graph](http://ogp.me/) meta data rather than oembed. oembed could still be used for videos on `Proposal#show`

**Comment by hennevogel** [comment]
Now tracked in #1177 and #1178
