### ISSUE TITLE
Event Registration

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#632]
There are two reasons submitter wants to require registration for his event:
1. They can only accommodate a limited amount of people because of limited resources (think Rasberry PI workshop and I have only N machines)
2. Knowing how many people will show up

Both are not handled in the current form. I can not limit the amount of registrations and I can't see how many people registered.

**Comment by differentreality** [comment]
Note: we can see how many people have registered in 
https://github.com/openSUSE/osem/pull/634/files#diff-8fb9d019430ee6b805c281047c1b7a2fR70
