### ISSUE TITLE
Variable does not exist

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#642]
https://github.com/openSUSE/osem/blob/master/app/controllers/admin/events_controller.rb#L183

**Comment by emercado1** [comment]
![screen shot 2015-04-28 at 8 49 37 pm](https://cloud.githubusercontent.com/assets/8637557/7383613/2846cad2-ede8-11e4-9028-e5f3a8cc1b69.png)

Would you possibly need to set a parameter for "error" when defining "update_state" function in line 179 (just as you did for notice, highlighted in the screenshot)?
