### ISSUE TITLE
Attendee export problem

### ISSUE THREAD

**Issue by hcderaad** [openSUSE/osem#645]
The attendee xls and pdf export for oSC 15 returns:

We're sorry, but something went wrong.

Which also means I can't provide you with more info to go on.

**Comment by differentreality** [comment]
That's ok erros get logged.

Duplicate: https://github.com/openSUSE/osem/issues/589

**Comment by hcderaad** [comment]
@differentreality Ok, thanks, any estimation on the resolving this? We really need this for the export of the sleepover bookers.

**Comment by differentreality** [comment]
Just be clear, do you want to export a list of registered people or a list of people that said 'yes' to the question about the sleepover?

**Comment by hcderaad** [comment]
@differentreality Both

**Comment by ChrisBr** [comment]
@differentreality dropping the missing fields should do the trick, shouldn't it?

**Comment by differentreality** [comment]
@ChrisBr yes for the pdf of registrations, but the questions that's a new feature.

I may have some time today to do some show action for questions.

**Comment by ChrisBr** [comment]
@differentreality Okay, great :+1:

**Comment by hcderaad** [comment]
If i could even only get a "flat" csv export (or even a mysql dump), I'd be very happy. No nice rendering/theming or anything needed.

**Comment by hennevogel** [comment]
deployed. everything, including answers to questions is working.
