### ISSUE TITLE
Wrong days remaining label when submitting a new proposal

### ISSUE THREAD

**Issue by koslibpro** [openSUSE/osem#649]
Hey,

When opened the proposals page for the conference via OSEM (https://events.opensuse.org/conference/osc15/proposal), it showed a subzero number of days remaining (in my case -2). It is suggested to fix this by just showing 0 days remaining in such case, or completely changing the sentence shown there.

Keep up the good work,
kostas

**Comment by ChrisBr** [comment]
@koslibpro Normally you shouldn't be able to access this page at all! Thanks for reporting!

**Comment by koslibpro** [comment]
oh then have also in mind that it was not a bookmark or something, i accessed it completely normally via the app flow

**Comment by ChrisBr** [comment]
@koslibpro From which page? On the root page and the conference page there are no links available anymore!

**Comment by koslibpro** [comment]
Noticed it now, i cannot see the link directly, so i have to assume that the link showed up in there after navigating a bit within the app. Trying now to reproduce it, I'll let you know.

**Comment by differentreality** [comment]
@ChrisBr  he is in proposal#index not proposal#new and I think the link on the top right user-menu stays either way (because you *need* to be able to see the list of your submitted proposals even after CFP is over. CfP will be over, afterwards your submission will be accepted.)

**Comment by ChrisBr** [comment]
@differentreality hm, yeah you're right! But obviously we hide the link to the proposal#index page...

**Comment by differentreality** [comment]
Fixed in #708
