### ISSUE TITLE
Change speaker on registered talk

### ISSUE THREAD

**Issue by hcderaad** [openSUSE/osem#651]
Currently it's impossible to change the speaker of a talk. It's very desirable to be able to do that, especially because as organizer I want to be able to enter talks for other people and keynote speakers don't generally register their own talks.

**Comment by hennevogel** [comment]
We don't have accounts without a login so if you want to create fake users, do so with "Sign Up".

**Comment by hcderaad** [comment]
Not working, these talks are already registered, we just need the speaker name.

**Comment by RobinEd** [comment]
We don't want the submitter account changed, just the speaker name. you can do this when you first register the talk, but can't edit it afterwards.
