### ISSUE TITLE
Add venue link error on dashboard

### ISSUE THREAD

**Issue by Doctor-Who** [openSUSE/osem#665]
When started a new event, on right windows on conference progress, links name "add venue" not working. See the screenshot : 

![capture du 2015-06-02 15 30 04](https://cloud.githubusercontent.com/assets/5890416/7937167/a2603418-093e-11e5-9329-3ba23cb283a0.png)

Fact : when a venue is add by main left menu, it works and then link in conference progress is working too after first completion

**Comment by differentreality** [comment]
Fixed in #674

**Comment by Doctor-Who** [comment]
Work fine, thanks !
