### ISSUE TITLE
use https: for all URLs in email

### ISSUE THREAD

**Issue by meonkeys** [openSUSE/osem#672]
Is there some way to use https: for all URLs sent in emails?

For example, can I set `action_mailer` defaults in `config/config.yml`? I think I want `protocol` set to `https`.

http://stackoverflow.com/a/5303353/156060

**Comment by meonkeys** [comment]
Ah, looks like I can just edit `osem/config/environments/production.rb` [like so](http://stackoverflow.com/a/5760867/156060)... is that kosher?

I see that file refers to `CONFIG`, so do we actually need a patch here so one can specify protocol for URLs included in emails?

**Comment by ChrisBr** [comment]
@meonkeys Yeah, such a "feature" would be preferable!
@hennevogel how do we do that on events.o.o? I guess we also use https?

**Comment by hennevogel** [comment]
No we don't, we use apache rewriting :-)

**Comment by raluka** [comment]
@ChrisBr : still open?

**Comment by bear454** [comment]
Use the `FORCE_SSL` environment variable.
