### ISSUE TITLE
Postgresql error

### ISSUE THREAD

**Issue by milovanderlinden** [openSUSE/osem#684]
When going to an event admin page [http://localhost:3000/admin/conference/testconference](http://localhost:3000/admin/conference/testconferenc), a pg error is thrown:

    PG::GroupingError: ERROR:  column "events.id" must appear in the GROUP BY clause or be used in an aggregate function
    LINE 1: SELECT "events".* FROM "events" WHERE "events"."conference_i...

To me this looks like a valid error as you cannot select * when using a group by in postgres.

**Comment by milovanderlinden** [comment]
Application trace:

app/models/conference.rb:837:in `calculate_program_minutes'
app/models/conference.rb:395:in `current_program_minutes'
app/models/conference.rb:404:in `current_program_hours'
app/controllers/admin/conference_controller.rb:107:in `show'

**Comment by milovanderlinden** [comment]
Some light on the issue [http://stackoverflow.com/questions/16418504/pgerror-in-group-by-clause](http://stackoverflow.com/questions/16418504/pgerror-in-group-by-clause)

**Comment by hennevogel** [comment]
We don't really support PostGre, I'm sure there are lots of other places where the APP goes wrong. Sorry :disappointed:

**Comment by milovanderlinden** [comment]
No worries. I will make postgresql supported in my fork as I need it for a heroku deploy of the app. Please let me know if you would like to add support for postgresql to your branch somewhere in the future.

**Comment by ChrisBr** [comment]
@milovanderlinden Great! Let us know how OSEM works for heroku! We planned a deploy to heroku feature some time ago but never finished it ... :(

**Comment by hennevogel** [comment]
@milovanderlinden awesome! :bouquet:

**Comment by milovanderlinden** [comment]
It works pretty well. I also discovered an issue with campaigns. Will fix that when I find some time later. Progress can be seen on my dev environment at http://young-woodland-2376.herokuapp.com/
