### ISSUE TITLE
Postalcode requires number

### ISSUE THREAD

**Issue by milovanderlinden** [openSUSE/osem#686]
But international postal codes are not always only numbers.

**Comment by ChrisBr** [comment]
Thanks for the hint! This is really ugly. We should never store a value like postalcode as an integer ...

https://github.com/openSUSE/osem/blob/master/db/schema.rb#L518

@skriesch How about this one? Aren't you a migration expert now? ;)

**Comment by differentreality** [comment]
Fixed in #713
