### ISSUE TITLE
Remove D3

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#694]
We still have D3 in our gemfile:
https://github.com/openSUSE/osem/blob/master/Gemfile#L79

I'm pretty sure that we don't use it anymore. We should double check that and then remove the gem!

**Comment by ZJaffee** [comment]
https://github.com/openSUSE/osem/pull/706
Opened a pull request to fix this

**Comment by AdiChat** [comment]
The d3_rails gem has been removed as it is not required. I have tested the application in local machine.

**Comment by chocoelho** [comment]
Shouldn't this be closed since it was already solved?

**Comment by ChrisBr** [comment]
yes, closing ...
