### ISSUE TITLE
Complete your todo list not working

### ISSUE THREAD

**Issue by bryanstein** [openSUSE/osem#698]
After someone submits a proposal in osem, their proposal page says "Complete your to do list". Osem is supposed to display a java popup that shows items that need to be filled out such as name, etc. 

The popup never shows and users in turn never fill out crucial details such as name that allows us to tell who they are and who submitted a session.

**Comment by ChrisBr** [comment]
@bryanstein works for me
http://paste.opensuse.org/view/raw/36859710

Do you have a public instance?

**Comment by ChrisBr** [comment]
Yes, I tested it and it doesn't work on @bryanstein instance! On events.o.o and on my dev machine it works perfectly fine... So I guess there's a configuration issue?

@differentreality @hennevogel

**Comment by hennevogel** [comment]
Yeah this sounds like a deployment issue. @bryanstein please provide more information

**Comment by ChrisBr** [comment]
@bryanstein ping!

**Comment by sonalkr132** [comment]
Can we close this? We don't have this issue on our master.

**Comment by pavanvd** [comment]
Seems like this issue still exists, but affects Safari and not Chrome.
