### ISSUE TITLE
html in program doesn't work on splash page

### ISSUE THREAD

**Issue by jospoortvliet** [openSUSE/osem#701]
Hi,

I love how you can use html in talk descriptions - that is much, much needed in our case. But it doesn't work on the splash page... See the screenshot.
![statistics july 27 2016](https://cloud.githubusercontent.com/assets/551757/8953188/03fdd2d2-35dd-11e5-82bf-718b20be97c3.png)

**Comment by ChrisBr** [comment]
@jospoortvliet can you try if markdown works? Would using markdown fix your issue?

**Comment by jospoortvliet** [comment]
@chrisBr thing is - you have to use html in the talk descriptions for it to show up properly on the individual talk pages ;-)

Example of the lightning talks part 1 working well there: https://conference.owncloud.org/conference/oCC2015/proposal/105

So if that page needs html and the program page markdown then it'll never look good on both ;-)

I strongly suggest to decide on ONE markup language used in all of OSEM - and I don't care if it's HTML or Markdown, they both do the job just fine. But be consistent or you get this kind of issues.

**Comment by hennevogel** [comment]
In general you are right but in this case proposal#show shouldn't use simple_format IMHO

**Comment by differentreality** [comment]
@Ana06 maybe you are also interested in this issue? :)

**Comment by Ana06** [comment]
@differentreality I think https://github.com/openSUSE/osem/pull/1127 fixes this issue, as now only markdown is supported.
