### ISSUE TITLE
Events/CFP Sort by Rating Misordered

### ISSUE THREAD

**Issue by altsalt** [openSUSE/osem#703]
When sorting by Rating, floating points are given less value than integers.

This is apparent when a 1.75 is ranked lower than a 1, or 2.33 is ranked lower than 2.

![osem_sort_issue](https://cloud.githubusercontent.com/assets/2441328/9101182/7b003f62-3b98-11e5-8850-a9dc891f0950.png)

**Comment by differentreality** [comment]
Fixed in #704
