### ISSUE TITLE
Cannot Run

### ISSUE THREAD

**Issue by fajar7xx** [openSUSE/osem#709]
Hy i have any problem with instalation this apps 
can you guide me 

im using XAMPP server and can't run it for the firstime 
it mean when i type localhost/osem it just give me a view about folder view not 
the apps 

can you help me how to solve it
thank you

**Comment by ChrisBr** [comment]
@fajar7xx still a problem?

We now have a vagrant environment for OSEM. Just clone the OSEM repository and ``vagrant up``. For more details please look at our README.md
