### ISSUE TITLE
Cannot open talks in separate tabs

### ISSUE THREAD

**Issue by muelli** [openSUSE/osem#71]
I am on an unreliable network and I want to preload data. When opening, i.e. https://conference.opensuse.org/osem/conference/osc14/schedule, I expected to be able to middle click the talks to load them in several tabs. That, however, does not work and I cannot preload the abstracts of the talks.

**Comment by differentreality** [comment]
With https://github.com/openSUSE/osem/pull/582 both CTRL+left click  and  middle click opens a new tab with the event for me.

**Comment by ChrisBr** [comment]
@differentreality What do you think, should we add a info text how to open the event in a seperate tab?

**Comment by differentreality** [comment]
@ChrisBr why are you suggesting this? You think some people might not be familiar with middle click or ctrl+click and we are still missing the right click -> 'open in new tab' dialog?

**Comment by ChrisBr** [comment]
@differentreality Exactly!
