### ISSUE TITLE
[FAQ] Demo site

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#714]
Hi,

Is there any hosted demo site to play around the features ?

Thanks.

**Comment by ChrisBr** [comment]
@kirantpatil Unfortunately not :(
But we're working on that ...

**Comment by kirantpatil** [comment]
Thanks a lot.
I am planning to use it for our Spiritual hosting event and planning to contribute as well.

**Comment by kirantpatil** [comment]
our site is up checkout "confoo.in"

**Comment by kirantpatil** [comment]
I am using unicorn and nginx on CentOS 7.

I will share the files here.
