### ISSUE TITLE
[production][proposal#show] NoMethodError: undefined method `color' for nil:NilClass

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#718]
proposal#show threw this 2 times
<pre>
NoMethodError: undefined method `color&#39; for nil:NilClass
</pre>
[https://events.opensuse.org/conference/osc13/proposal/124](https://events.opensuse.org/conference/osc13/proposal/124)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/5620db69764b230006000002)

**Comment by differentreality** [comment]
Track deleted while being used in event.

**Comment by Shriyanshagro** [comment]
@differentreality , can you please elaborate the bug , and when does it occur ??

**Comment by differentreality** [comment]
It seems I cannot recreate the same problem any more.
However, we are still letting organizers delete tracks that are already being used by proposals, without offering any notification whatsoever.

**Comment by hennevogel** [comment]
Notification how?

**Comment by differentreality** [comment]
@hennevogel I was thinking making the confirmation message more explicit "There are already X events that use this track", or even making a new table column showing how many events belong to that track.

On a different note, we might have some bad values left in our production. 
Check https://events.opensuse.org/conference/osc13/program/proposal/124

**Comment by hennevogel** [comment]
Sounds like a job for `dependent: :nullify`

**Comment by ChrisBr** [comment]
@hennevogel we already have ``dependent: nullify`` set on these models, however, we introduced it probably after we corrupted some objects ...

https://github.com/openSUSE/osem/commit/799fd0c3a43699fbd0ad97363bea2f7e46e6bef7
