### ISSUE TITLE
[production][unknown] ActionController::RoutingError: uninitialized constant Admin::StatsController

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#720]
unknown threw this 1 times
<pre>
ActionController::RoutingError: uninitialized constant Admin::StatsController
</pre>
[https://events.opensuse.org/admin/conference/osc14/stats](https://events.opensuse.org/admin/conference/osc14/stats)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/5620f0e1764b23000c00000a)

**Comment by differentreality** [comment]
Noticed that the route for stats is still there, and should be removed too.

**Comment by Shriyanshagro** [comment]
@differentreality , The link you have provided isn't available now. So is this issue still open , If yes, can you please elaborate it more.

**Comment by differentreality** [comment]
There isn't much to elaborate on really. There is a routing error about statscontroller. To debug the error:
- Check the routes: is there something relevant about stats?
- Check the controllers, is there a statscontroller?

**Comment by 4bic** [comment]
@differentreality @ChrisBr  , [this pr](https://github.com/openSUSE/osem/pull/897)  should clean up the routes

**Comment by differentreality** [comment]
Closed via https://github.com/openSUSE/osem/issues/720
