### ISSUE TITLE
Improvements in the flow of the forms

### ISSUE THREAD

**Issue by lalalalalazy** [openSUSE/osem#725]
The conference registration and event submission forms could be better integrated. Right now there are two separate forms for conference registration and submitting proposal. This could be better integrated by having a flow in which:
- if it's a not-logged-in user (new user) s/he's asked to provide username, email and password followed by, for submitting a proposal, a title, session type and an abstract **and** registration for the conference.
- if it's a logged-in user s/he's asked to provide, for submitting a proposal, username, email and password followed by, for the submission/event, a title, type and an abstract. If the user hasn't registered **then only** s/he's asked to register for the conference.

(in both cases. keeping *registration* part optional is an *option*)

Furthermore, the user is given an option to add *difficulty level* and *subtitle* only after the proposal has been submitted. I think this should be given directly in the first form.

**Comment by ChrisBr** [comment]
Is this still valid? Thought we implemented this during hackweek last year? @differentreality @hennevogel

**Comment by hennevogel** [comment]
We have

**Comment by sonalkr132** [comment]
>  The user is given an option to add difficulty level and subtitle only after the proposal has been submitted. I think this should be given directly in the first form.

We are still asking for tracks and subtitle after submission. If we are doing this on purpose to keep submission of proposal simple (at first), I think it would make more sense if we change submission process to widget kind of thing (which would step user through the process).

**Comment by hennevogel** [comment]
And why would we?

**Comment by sonalkr132** [comment]
> And why would we?

All the things we are asking users to add to proposal seems like to be all over the place.  User adds tracks and subtitle by editing the form after submission, there is a different tab to adding commercial, there is a button to schedule the proposal. I think it would be better if we can unify all this process. We also would be adding more stuff (for example: `speakers`). Users save the first draft (just with title and abstract) and then continue where they left off at any later point.

**Comment by hennevogel** [comment]
We're already doing this. If you want to make the Event#edit form more simple please go ahead or record an issue so we can discuss this. This has nothing to do with this issue though...
