### ISSUE TITLE
Public listing of submitted proposals

### ISSUE THREAD

**Issue by lalalalalazy** [openSUSE/osem#726]
Some of the conference organizers might want to have the list of submitted proposals to be public. There should be an option in admin to enable/disable this. Having an option of having a public list would allow potential submitters to see what other kind of content is already there. The obviously trashy proposals can always be rejected through admin.

**Comment by hennevogel** [comment]
Make your schedule public and it will show a list of all confirmed Events. Showing unconfirmed events makes no sense as you don't know if they will happen at all or not...
