### ISSUE TITLE
User meta data for admins

### ISSUE THREAD

**Issue by cherrymathew** [openSUSE/osem#730]
Some conferences require admins to micro-manage participant arrival/departure/facilitation.
The current "status" might be ill defined, and right now , we use a spreadsheet for https://www.hackbeach.in

I'm wondering if there's a way to include this info in a way that a list of users can be modified/filtered similar to a spreadsheet for this purpose.

an eg: row might look as follows:

User  | Sent welcome mail | Response recieved | Arrival Confirmed | Phone number
---------|-----------------------------|------------------------------|---------------------------|---------

etc.

Ideally the admin should be able to add / remove any of the columns above.

**Comment by differentreality** [comment]
Even though this specific example is better served with filling out the arrival details of the attendee (send emails to registered users without arrival info and ask them to fill them in. https://github.com/openSUSE/osem/issues/105) this sounds to me like a feature for customized TODO list for organizers.

**Comment by kirantpatil** [comment]
:+1:

**Comment by hennevogel** [comment]
We're not going to implement spreadsheets in osem sorry :-) There is the the feature to toggle the attendance.
