### ISSUE TITLE
Support FRAB XML output

### ISSUE THREAD

**Issue by danimo** [openSUSE/osem#733]
It would be nice if there was a way to export a conference to FRAB (http://frab.github.io/frab/) XML. The rationale is that a lot of conference recording tools developed by c3voc.de which are actively used consume FRAB output. This allows for same day publishing & streaming, e.g. https://github.com/voc/intro-outro-generator.

Examples can be found here:

http://programm.froscon.de/2015/schedule.xml
https://events.ccc.de/congress/2014/Fahrplan/schedule.xml

The XSD is located at https://raw.githubusercontent.com/voc/schedule/master/validator/xsd/schedule.xml.xsd

Online-validator (also accepts URLs): https://c3voc.de/schedulexml/

**Comment by ChrisBr** [comment]
@danimo nice idea! Maybe we can include that into #741

**Comment by jospoortvliet** [comment]
just out of curiosity, was this done? I saw in #741 "transferring" but not sure what that means...

**Comment by differentreality** [comment]
Nop, it was not done. Yet..

**Comment by differentreality** [comment]
@ChrisBr @hennevogel are you going to include this in Ana's GSOC project?

**Comment by hennevogel** [comment]
Nope. I'm not even convinced that this is a good feature in general

**Comment by afranke** [comment]
If it helps convincing you, note that many mobile conference apps consumes this format, which gives you schedule apps for your event for free.
