### ISSUE TITLE
payment gateway interface

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#735]
Hi,

Is there a payment gateway interface code integrated ?

Where should we include gateway interface for Ticket, Registraion ?

Thanks.

**Comment by differentreality** [comment]
No, payments are not possible through OSEM at this point.

Ticket option, when configured in admin panel, is made available in the registration page. But the payment of the ticket needs to take place outside of OSEM (eg. upon arrival at the conference)

**Comment by kirantpatil** [comment]
Thanks a lot.
