### ISSUE TITLE
mobile support

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#739]
Hi,

I could see https://github.com/openSUSE/osem-app for android.

It is not maintained for long time.

Is anyone using it with latest osem server ?

Is there any other alternative to it ?

Is there any roadmap for it by moving frontend to Ember.js or so?

Thanks,
Kiran.

**Comment by hennevogel** [comment]
> Is anyone using it with latest osem server?

Nope

> Is there any other alternative to it?

Except using the web frontend, no.

> Is there any roadmap for it by moving frontend to Ember.js or so?

We're already having a responsive frontend what would be need Ember for?

**Comment by kirantpatil** [comment]
Ember helps to maintain common code base for both Browser and Mobile app ie Hybrid app.

**Comment by ChrisBr** [comment]
@kirantpatil can we close this issues? As @hennevogel already mentioned, currently not on our roadmap...

**Comment by kirantpatil** [comment]
Yes Sir, I will close this issue.

**Comment by ChrisBr** [comment]
:+1: thanks @kirantpatil
