### ISSUE TITLE
bundle exec rake db:setup warnings

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#740]
Hi,

I am installing osem on fedora 23.

I saw warning messages during db:setup, are they ignorable or do I need to do any configuration ?

#### [kiran@ganapati-1gb-sgp1-01 osem]$ bundle exec rake db:setup
/home/kiran/.gem/ruby/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
warning: you are loading parser/ruby22 from /home/kiran/.gem/ruby/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.
[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.
/home/kiran/.gem/ruby/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: already initialized constant User::HABTM_Roles
/home/kiran/.gem/ruby/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_Roles was here
-- create_table("ahoy_events", {:force=>true})
   -> 0.0141s
-- add_index("ahoy_events", ["time"], {:name=>"index_ahoy_events_on_time"})
   -> 0.0067s
-- add_index("ahoy_events", ["user_id"], {:name=>"index_ahoy_events_on_user_id"})
   -> 0.0123s
-- add_index("ahoy_events", ["visit_id"], {:name=>"index_ahoy_events_on_visit_id"})
   -> 0.0163s
-- create_table("answers", {:force=>true})
   -> 0.0080s
-- create_table("call_for_papers", {:force=>true})
   -> 0.0166s
-- create_table("campaigns", {:force=>true})
   -> 0.0130s
-- create_table("comments", {:force=>true})
   -> 0.0083s
-- add_index("comments", ["commentable_id"], {:name=>"index_comments_on_commentable_id"})
   -> 0.0125s
-- add_index("comments", ["commentable_type"], {:name=>"index_comments_on_commentable_type"})
   -> 0.0085s
-- add_index("comments", ["user_id"], {:name=>"index_comments_on_user_id"})
   -> 0.0095s
-- create_table("commercials", {:force=>true})
   -> 0.0108s
-- create_table("conferences", {:force=>true})
   -> 0.0111s
-- create_table("conferences_questions", {:id=>false, :force=>true})
   -> 0.0099s
-- create_table("contacts", {:force=>true})
   -> 0.0139s
-- create_table("delayed_jobs", {:force=>true})
   -> 0.0104s
-- add_index("delayed_jobs", ["priority", "run_at"], {:name=>"delayed_jobs_priority"})
   -> 0.0087s
-- create_table("dietary_choices", {:force=>true})
   -> 0.0097s
-- create_table("difficulty_levels", {:force=>true})
   -> 0.0083s
-- create_table("email_settings", {:force=>true})
   -> 0.0188s
-- create_table("event_types", {:force=>true})
   -> 0.0101s
-- create_table("event_users", {:force=>true})
   -> 0.0142s
-- create_table("events", {:force=>true})
   -> 0.0113s
-- create_table("events_registrations", {:id=>false, :force=>true})
   -> 0.0066s
-- create_table("lodgings", {:force=>true})
   -> 0.0205s
-- create_table("openids", {:force=>true})
   -> 0.0083s
-- create_table("photos", {:force=>true})
   -> 0.0075s
-- create_table("qanswers", {:force=>true})
   -> 0.0076s
-- create_table("qanswers_registrations", {:id=>false, :force=>true})
   -> 0.0099s
-- create_table("question_types", {:force=>true})
   -> 0.0088s

Thanks.

**Comment by kirantpatil** [comment]
[kiran@ganapati-1gb-sgp1-01 osem]$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

**Comment by ChrisBr** [comment]
@differentreality any idea? You're our rolify expert ;)

**Comment by kirantpatil** [comment]
Also happening under ruby 2.2.0 as below.

[kiran@sammelana osem]$ ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
[kiran@sammelana osem]$ 
[kiran@sammelana osem]$ 
[kiran@sammelana osem]$ tail -f log/unicorn.stderr.log 
I, [2015-12-21T05:51:42.021708 #4137]  INFO -- : master complete
I, [2015-12-21T05:51:44.706573 #4189]  INFO -- : Refreshing Gem list
/home/kiran/osem/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: already initialized constant User::HABTM_Roles
/home/kiran/osem/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_Roles was here
I, [2015-12-21T05:51:50.801247 #4189]  INFO -- : unlinking existing socket=/home/kiran/osem/tmp/sockets/osem.socket
I, [2015-12-21T05:51:50.801543 #4189]  INFO -- : listening on addr=/home/kiran/osem/tmp/sockets/osem.socket fd=12
I, [2015-12-21T05:51:50.801940 #4189]  INFO -- : listening on addr=127.0.0.1:8080 fd=13
I, [2015-12-21T05:51:50.807013 #4189]  INFO -- : master process ready
I, [2015-12-21T05:51:50.820733 #4192]  INFO -- : worker=0 ready
I, [2015-12-21T05:51:50.827350 #4194]  INFO -- : worker=1 ready

**Comment by differentreality** [comment]
The warnings are not errors and do not interfere with the functionality.

It looks to be that db:setup ran successfully and that everything works. Is that not the case @kirantpatil ?

**Comment by kirantpatil** [comment]
Yes, things works but i haven't yet checked complete functionality, which
will be done in couple of days.

I will close this if nothing major comes up while testing.

**Comment by differentreality** [comment]
If you experience any other problems, please report them individually by opening new issues.

Same goes for any other questions! Thanks!

**Comment by kirantpatil** [comment]
Thanks, forgot to close the issue.
