### ISSUE TITLE
GSoC: Enhance visitor experience

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#741]
Continuing our discussion via mail I would like to start to write down our project ideas:

**Description:** The [Open Source Event Manager](http://osem.io) is an event management app tailored to Free Software Conferences, it is developed in the [Ruby on Rails](http://rubyonrails.org/) web framework. We have several ideas to enhance the visitor experience. First of all, the event schedule isn't mobile friendly and and there is no way to have several schedule proposals to compare before releasing it (see #18 & #587). Furthermore we would to gather feedback from the conference visitors (see #549) and improve our conference splash page (#400).

**Deliverable:** Reworked and mobile friendly schedule and splash page. Some way to gather user feedback

**Mentors:** @chrisbr @hennevogel @differentreality 

**Skills:** Ruby, Ruby on Rails, HTML, Java Script

**Skill Level:** Medium

 **Getting started:** Pick one of the [Junior](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) labeled issues and get in touch with the mentors.

**Github:** https://github.com/openSUSE/osem

**Comment by ChrisBr** [comment]
@hennevogel and @differentreality please review that we can soon submit our project ideas...

**Comment by kirantpatil** [comment]
:+1:

**Comment by ChrisBr** [comment]
@differentreality @hennevogel ping

**Comment by hennevogel** [comment]
Looks fine to me, transerfing! :+1:

**Comment by Shriyanshagro** [comment]
Hi there, I am willing to contribute to osem as My Gsoc'16 project.
Can somebody suggest me to where to start from.
I mean weather I should start fixing junior labeled issues or the one that are mentioned above , #733,#722
