### ISSUE TITLE
Implement ticket payment feature

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#742]
Continuing our discussion via mail I would like to start to write down our project ideas:

**Description:** The [Open Source Event Manager](http://osem.io) is an event management app tailored to Free Software Conferences, it is developed in the [Ruby on Rails](http://rubyonrails.org/) web framework. OSEM already has a feature to sell conference tickets. At the moment the user has to buy the ticket online and pay on arrival at the conference. We would like to have a way to purchase and pay online.

**Deliverable:** Workflow to support online payment of conference tickets.

**Mentors:** @chrisbr @hennevogel @differentreality 

**Skills:** Ruby, Ruby on Rails, HTML, Java Script

**Skill Level:** Medium

 **Getting started:** Pick one of the [Junior](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) labeled issues and get in touch with the mentors. Furthermore have a look at the [Paypal API](https://developer.paypal.com/).

**Github:** https://github.com/openSUSE/osem

**Comment by ChrisBr** [comment]
@hennevogel and @differentreality please review that we can soon submit our project ideas...

**Comment by kirantpatil** [comment]
great :+1:

**Comment by hennevogel** [comment]
@kirantpatil glad you like it but please refrain from those types of comments. They just make issues less readable. Thanks in advance!

**Comment by ChrisBr** [comment]
@differentreality @hennevogel ping

**Comment by hennevogel** [comment]
I'm fine with it

**Comment by grepwood** [comment]
So, what happened with OSEM supporting Paypal?

**Comment by differentreality** [comment]
@grepwood nothing happened with paypal actually - I think you are away of a related open issue, are you not? 
During the GSoC project it was decided that Stripe fits open source conferences better.

**Comment by grepwood** [comment]
@differentreality probably, I'm not sure. I'm very impressed with OSEM, but my client cannot afford to use Stripe. First, it's because they aren't based in a country supported by Stripe. Second, they are barely making ends meet to attract customers, so having card transactions would gut them. I understand that OSEM is intended for open source conferences, but as I see it, conventions that revolve around topics other than open source software could also greatly benefit from OSEM.
