### ISSUE TITLE
[FAQ] Email notification setup 

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#743]
Hi,

I have enabled google oAuth for single signon and it works.

So for I have made changes in secrets.yml and config.yml file.

How do I setup to send email notifications like to confirm the State of User ?
![screenshot from 2015-12-21 16-56-23](https://cloud.githubusercontent.com/assets/1178055/11929772/d84f4c6c-a803-11e5-8159-5e5e1f277b52.png)

**Comment by differentreality** [comment]
An email to confirm your account is sent automatically when the user account is created.

I don't think there is an option to send a manual reminder for this.

**Comment by kirantpatil** [comment]
Even though I am running delayed_job " 3774 pts/0    Sl     0:10 ruby /home/kiran/bin/rake jobs:work
",  I did not get any confirmation email.

**Comment by kirantpatil** [comment]
Sorry, the mail was in spam folder.

**Comment by ChrisBr** [comment]
Is it for development or production?

If it is for production: Please read the RoR mail faq (http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration).

For debugging I would go to ``/admin/conference/<shorttitle>/email`` and enable ``Send an email when the user registers for the conference?``! Than register for the conference and check if you get an email.

**Comment by kirantpatil** [comment]
It is for production.

I will follow your suggestion.

Thanks.
