### ISSUE TITLE
[FAQ] Delete Conference not found

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#744]
I do not find the "Delete Conference" link anywhere in the app.

Is this feature supported or not ?

**Comment by differentreality** [comment]
No, you cannot currently delete a conference.

**Comment by kirantpatil** [comment]
Ok, thanks.

**Comment by ChrisBr** [comment]
@differentreality is right!

But, if the conference date is passed, the conference is automatically hidden on the index page.

If you want to delete a conference because it was just for testing I recommend to use the rails console.

``
rails c
c = Conference.where(title: 'yourtitle')
c.destroy
``
