### ISSUE TITLE
Registration shows "... is free of charge"

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#745]
The registration shows "... is free of charge" and I don't see any where in configuration to change it as paid.

![screenshot from 2015-12-29 11-27-15](https://cloud.githubusercontent.com/assets/1178055/12030215/80140bea-ae21-11e5-8c9d-92f55278933f.png)

**Comment by ChrisBr** [comment]
It's hardcoded in app/views/conference/_registration.html.haml.
You're right, we should handle there if tickets are available ...
