### ISSUE TITLE
INSTALL.md demo doesn't work :(

### ISSUE THREAD

**Issue by Maijin** [openSUSE/osem#746]
Hello o/

osem looks awesome ! But Looks like the INSTALL is not working out of the box, I was expecting to try out the interface after doing the first steps + there is no demo website as mentionned here #714 .

It's not mentioned that you have to rename all the yaml.example stuff for example and even after I got : 

```
[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.
/usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: already initialized constant User::HABTM_Roles
/usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_Roles was here
```

+ this error when reaching 127.0.0.1:3000

```
Started GET "/" for 10.0.2.2 at 2016-01-01 23:25:22 +0100
Processing by ConferenceController#index as HTML
Completed 500 Internal Server Error in 26ms

ActiveRecord::StatementInvalid (Could not find table 'users'):
  app/models/ability.rb:17:in `initialize'
  app/controllers/application_controller.rb:42:in `new'
  app/controllers/application_controller.rb:42:in `current_ability'
```

**Comment by kirantpatil** [comment]
What steps did you follow ?

I think you missed migration step as below,
RAILS_ENV=production bundle exec rake db:migrate

**Comment by Maijin** [comment]
@kirantpatil simply copy/pasta what was in the in INSTALL.md and tried to use the .example nothing more.

**Comment by kirantpatil** [comment]
I haven't used the one mentioned in INSTALL.md which uses Vigrant.

Please find the below steps to configure manually.
1. cd osem/
2. gem install bundle
3. bundle install
4. cd config
5. cp config.yml.example config.yml
6.  cp database.yml.example database.yml
7.  cp secrets.yml.example secrets.yml
8. cd ..
9. RAILS_ENV=production bundle exec rake db:setup
10. RAILS_ENV=production rails s

**Comment by differentreality** [comment]
@Maijin are you still having problems?

Are you using vagrant? 
(What's the top entry you see when you run ``git log``)

**Comment by AdiChat** [comment]
On following the instructions given in INSTALL.md, I get an error in the command : vagrant exec rails server -b 0.0.0.0 . The error is "bash: rails: command not found" but rails is installed as I get the desired output for the command "rails -v". 
The top entry in git log is : 
commit bcacc7fd17e490f066f6f22055b0ce3068308c9b
Merge: 4e51e93 27e8016
Author: Henne Vogelsang <hvogel@opensuse.org>
Date:   Mon Feb 8 15:55:07 2016 +0100

    Merge pull request #765 from hennevogel/travis
    
    Travis: Enable IRC notification, disable addons

**Comment by hennevogel** [comment]
@AdiChat how did you install rails in the vagrant machine? What's the output of 

`vagrant exec rails -v`

**Comment by AdiChat** [comment]
@hennevogel This is the output of the command "vagrant exec rails -v" :
Vagrant 1.7.4 
I did not install rails inside the vagrant machine but it recognizes all ruby and rails commands. Rails is installed in my root directory.

**Comment by hennevogel** [comment]
Have you installed the exec plugin? What's the output of

`vagrant plugin list`

**Comment by AdiChat** [comment]
@hennevogel This is the output : 
vagrant-exec (0.5.2)
vagrant-reload (0.0.1)
I did install the 2 vagrant plugins.

**Comment by hennevogel** [comment]
I think you're not in the git checkout when you execute 

`vagrant exec rails -v`

you have to be in the osem directory you have cloned

**Comment by AdiChat** [comment]
I am in the osem deirectory when I execute the command. The osem directory is up-to-date with the origin-master branch.

**Comment by hennevogel** [comment]
No, please try

`vagrant exec "rails -v"`

**Comment by awasum** [comment]
The procedure outlined by @kirantpatil works well for both development and production setups. may u should stop using vagrant and just follow those steps.

**Comment by hennevogel** [comment]
Yes both setups work very well if you have the underlying system under control. Anyway, there has been no feedback on this since a month. Closing...
