### ISSUE TITLE
Tea Coffee lunch break time in schedule

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#747]
I would like to add the Tea, Coffee, Breakfast, lunch, Dinner break information in schedule.

I could add only tracks with event types which is in appropriate to add the break time.

May I know any other way to add the break time in the schedule ?

Thanks,
Kiran.

**Comment by kirantpatil** [comment]
Also forgot to mention Registration event.

They all(Registration, Tea/Coffee, Breakfast, Launch, Dinner) become global events across all tracks.

**Comment by kirantpatil** [comment]
All global events should not be part of CFP (Call For Papers).

**Comment by kirantpatil** [comment]
If this make sense, then each program will have global events and the time allotment of events should not clash with the global events.

**Comment by kirantpatil** [comment]
Idea site: https://opensource.com/business/16/1/10-tips-for-event-organizers

In addition to event sessions, all versions of the schedule should include information on whether meals are provided during breaks or whether attendees are on their own.

**Comment by cniedzwiedz** [comment]
Not sure if this is the appropriate way to indicate this, but I would also like this feature.  I can here to open a similar request.

**Comment by differentreality** [comment]
@cniedzwiedz you don't have to open another issue for this. Commenting here is fine. Even though at this point this issue is vague in terms of implementation. As a result, don't expect it to be implemented, before we come up with a plan on how to do it.

**Comment by Ana06** [comment]
@differentreality  we could have a new attribute in events that indicate if this event take place in all the rooms or not. Then it will be render in all the rooms and when schedule it, it could only be schedule if there are not more events at the same time in any room.

I think it is not that difficult, although it implies changes things in several places.

**Comment by bear454** [comment]
re: Issue #13.

**Comment by differentreality** [comment]
Closing this in favor of #13
