### ISSUE TITLE
UI discrepancy in schedule page

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#748]
I have created 2 events with 1 hr and 2 hr each and schedule page shows some discrepancy.

URL: http://confoo.in/conference/4th_way_workshop_2016/schedule

Screenshot:
![screenshot from 2016-01-11 12-17-31](https://cloud.githubusercontent.com/assets/1178055/12228177/b132162c-b85d-11e5-849c-2451c71cb4ba.png)

**Comment by differentreality** [comment]
@kirantpatil what's the discrepancy?

**Comment by kirantpatil** [comment]
1. 10.00 AM slot does not contain the horizontal line
2. At 11.00 AM slot the text and user image are not fitted in that slot.

**Comment by differentreality** [comment]
This is what I am seeing in your webpage:

![screenshot-confoo find your conference - chromium](https://cloud.githubusercontent.com/assets/4322737/12296120/55e6de80-ba0e-11e5-8dd2-fea132637640.png)

I thought that something might be wrong with your attachment. Can you double check the webpage and what you currently see on it?

**Comment by kirantpatil** [comment]
Sorry, I forgot mention that the screenshot is taken on Firefox 40.0 and on chrome no issues.

**Comment by kirantpatil** [comment]
I could not test since our site is down due to hack. I am closing this issue after seeing the @davidsf screenshot. Feel free to reopen if it is not fixed.

**Comment by davidsf** [comment]
Well, the fix it's not in master yet, so technically is not fixed :)

**Comment by kirantpatil** [comment]
Yes Sir, reopening the issue.
