### ISSUE TITLE
Add/Remove additional Speakers to the event

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#749]
I would like to add/remove additional speakers to the event and I should be able to add them as users and fill all the relevant details.

**Comment by Shriyanshagro** [comment]
Okay , I will implement this feature. Can somebody suggest me where should I add this option button , I guess under 'admin/conference/.../program/events' ??
Also , I suggest there should also be a add/remove additional **Proposal** to the event 
![osem](https://cloud.githubusercontent.com/assets/13868098/14156185/b296d3d6-f6e2-11e5-91a3-997dd0706995.png)

**Comment by hennevogel** [comment]
@Shriyanshagro please concentrate on issues labeled junior for now...

**Comment by differentreality** [comment]
Closing this as the feature of having multiple speakers per events has been implemented. Users need to sign up on their own though.

https://github.com/openSUSE/osem/pull/1278
