### ISSUE TITLE
[RFC] whiteboard or bulletin board support

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#753]
This idea came from https://opensource.com/business/16/1/10-tips-for-event-organizers link.

Technical conferences are a great place to find or change jobs, so make the job search easier for attendees. Simply by providing a whiteboard or bulletin board, you can offer extra value to your community of attendees and to event sponsors.

**Comment by hennevogel** [comment]
Then do that with some bulletin board software :-)
