### ISSUE TITLE
[ :star: Feature Request] Offline support

### ISSUE THREAD

**Issue by kirantpatil** [openSUSE/osem#754]
Offline support to save and open the conference details from browser and mobile phones.

I believe this is the must have feature.

**Comment by hennevogel** [comment]
You know stuff like [Instapaper](https://www.instapaper.com/) or [Pocket](https://getpocket.com/) right? We're not going to re-implement features that your browser brings in our app sorry...

**Comment by kirantpatil** [comment]
This is what I mean by https://github.com/wycats/rack-offline.
