### ISSUE TITLE
Configure language of events

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#760]
In some conference the events could be in various languages. It would be great that admins could configure the accepted languages in the backend and the user in the proposal selects the language of his event.

**Comment by Shriyanshagro** [comment]
Good Idea ..
I can work on it . Can someone guide me on it ??
@ChrisBr @differentreality

**Comment by hennevogel** [comment]
@Shriyanshagro If you want guidance come up with concrete questions please :-) What is it you need guidance for?

**Comment by Ana06** [comment]
I'll do it! :wink: 
Where should I put the languages configuration in the backend? I think that it can be another page inside the program section of the backend.
How should admins select the language? I think that a list of check-boxes would be easy to use, specially if a lot of languages want to be selected.

**Comment by hennevogel** [comment]
Yes `Program` sounds like the object to hold this info. I think for starters this can be a simple text field with comma separated value of ISO 639-1 language codes and a select for `Event`
