### ISSUE TITLE
Show contact information (email)

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#764]
If organizers have set a relevant email in the admin form, we should make that visible in conference#index and conference#show, so that visitors can actually find a way to email the conference team.

**Comment by chocoelho** [comment]
Should this email appear below conference title?

**Comment by chocoelho** [comment]
IMHO it's the best position, since it can handle long emails.

**Comment by chocoelho** [comment]
Something like this

![screencapture-localhost-3000-conference-1457353306605](https://cloud.githubusercontent.com/assets/3460435/13569299/067aed52-e446-11e5-8155-43dae8e0b309.png)

**Comment by chocoelho** [comment]
Better with mail_to

![screencapture-localhost-3000-conference-1457353387458](https://cloud.githubusercontent.com/assets/3460435/13569326/355db92e-e446-11e5-8be9-1d853de336e3.png)

**Comment by chocoelho** [comment]
And about conference#show, should contact through email be one of the last items along with social media contact?

**Comment by ChrisBr** [comment]
Not sure if I would display it on Conference#index, at least I don't like your proposed screenshot ... Showing it on Conference#show along with the social media links is fine for me!

**Comment by chocoelho** [comment]
Yeah, you're right. It makes more sense to display it only on show.

**Comment by chocoelho** [comment]
So it'll be better to show email along with social media and not another section, right?

**Comment by ChrisBr** [comment]
Yes, definitely

**Comment by chocoelho** [comment]
Ok, it'll look like this when every social media info is informed by organizers

![screencapture-localhost-3000-conference-testcon2016-1457354526785](https://cloud.githubusercontent.com/assets/3460435/13569810/ecb215f0-e448-11e5-8eb4-7ff7d4b07995.png)

**Comment by ChrisBr** [comment]
LGTM
