### ISSUE TITLE
First user in test is admin

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#799]
Steps to reproduce:
* Run following code (say spec/model/admin_spec.rb)
```Ruby

require 'spec_helper'

describe Registration do
  before do
    @user = create(:user)
  end

  it 'user is admin' do
    expect(@user.is_admin).to be_truthy
  end
end
```
* spring rspec spec/model/admin_spec.rb

Test passes! I think it is happening because of hack we do to set first user as admin.
Tests seem to be written with assumption that when we do `create(:user)` it is just a normal user (for example [this conference_registration spec](https://github.com/openSUSE/osem/blob/master/spec/features/conference_registration_spec.rb#L5))

**Comment by differentreality** [comment]
What about we create a user in `config.before(:suite)`?
Our application will always has a first user, and any user creation in the tests will always correspond to a simple user, and not an admin. @hennevogel ?

**Comment by sonalkr132** [comment]
I haven't given much time to find where exactly is the hack for this admin user setup, is it some migration file?

I think we can get around it by putting the hack in an `if` block which doesn't run when `ENV` is test.

**Comment by hennevogel** [comment]
This is a feature of the ap. If a test assumes something wrong, it's wrong. If the factory is wrong, it's wrong.
