### ISSUE TITLE
Add flash_type error

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#804]
In a lot of our controllers we use `flash[:error] = 'message'` and then we redirect.
In other places we just use `redirect_to root_path, notice: 'message'`
To have a common way, we should add the flash_type error (http://api.rubyonrails.org/classes/ActionController/Flash/ClassMethods.html#method-i-add_flash_types) and rewrite the controllers to use a common style.

**Comment by AdiChat** [comment]
@differentreality  So does that mean that we rewrite the two types of flash messages to the form 
[ redirect_to user_path(@user), warning: "Incomplete profile" ] after adding the flash_type error. So this involves modifying controllers and view. Is this the vision?

**Comment by differentreality** [comment]
Yes, but we want to add the flash_type of error, so when we do `add_flash_types :error`, then we obviously need to use **error** in our messages, not warning.

Which views would you modify with this change?

**Comment by chashmeetsingh** [comment]
@differentreality can I work on this?

**Comment by differentreality** [comment]
Anyone who wants to work on any issue can do so, by assigning himself/herself from the right side of this page where it says **Assignee**.

**Comment by AdiChat** [comment]
@differentreality  It seems views will not be affected by this change as the objective is to attain uniformity in code style.

**Comment by differentreality** [comment]
Closed via #858
