### ISSUE TITLE
[production][conference#index] ArgumentError: bad value for range

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#807]
conference#index threw this 0 times
<pre>
ArgumentError: bad value for range
</pre>
[https://events.opensuse.org/](https://events.opensuse.org/)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/56d5548ee384f70006000000)

**Comment by ChrisBr** [comment]
Hot fixed on events.o.o, reason was that last_sign_in_at was nil. We have to investigate why iChain set a nil value...

app/models/comment.rb
```
  scope :find_since_last_login, lambda { |user|
    last_sign_in_at = user.last_sign_in_at ? user.last_sign_in_at : Time.now
    where(created_at: (last_sign_in_at..Time.now)).order(created_at: :desc)
  }
```

**Comment by ChrisBr** [comment]
As discussed with @hennevogel, basically it's possible that user.last_sign_in_at is ``nil``, so we need to fix this issue!

**Comment by theaverageguy** [comment]
We can check for the value assigned to this. What should be the value if it is assigned nil by iChain?

**Comment by ChrisBr** [comment]
@theaverageguy if it's nil I would say we should assign Time.now. 
@hennevogel what do you think?

**Comment by hennevogel** [comment]
Make the code rubust against `nil` do not work around it :-)
