### ISSUE TITLE
Try out sexant

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#810]
`rake routes` is an important command, however because of limited terminal window length, all the lines gets smushed together.

![screenshot from 2016-03-02 06-53-12](https://cloud.githubusercontent.com/assets/7680662/13447702/8d726260-e043-11e5-86a6-7deed6fefc53.png)

I tried out [sexant](https://github.com/schneems/sextant) and I think it is really cool. 
![screenshot from 2016-03-02 06-57-04](https://cloud.githubusercontent.com/assets/7680662/13447774/135655b2-e044-11e5-8edb-6abe2079c353.png)

Let me know what do you guys think.

**Comment by chashmeetsingh** [comment]
@sonalkr132 I guess rake routes is better. Yes you have to increase the height and width to view the contents perfectly but this seams the best way :)

**Comment by ChrisBr** [comment]
:-1: 
You get the very same result when you try to access an invalid route, e.g. ```localhost:3000/foobar```
![routes](http://paste.opensuse.org/view/raw/54827930)

**Comment by ChrisBr** [comment]
Furthermore, have a look at the sextant [README](https://github.com/schneems/sextant#the-future), it's meanwhile merged into rails 4.
```http://localhost:3000/rails/info/routes```

**Comment by sonalkr132** [comment]
`http://localhost:3000/rails/info/routes` works :D Thats all I need. Sorry, I didn't read it all.
