### ISSUE TITLE
Ticket description is not working

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#811]
Steps to reproduce:
* Make a conference (say: goto)
* Go to new tickets page (url: http://localhost:3000/admin/conference/goto/tickets/new )
* Click in description text area, the markdown toolbar will appear and textarea goes out of focus.
* Keep clicking in it until the world doesn't make any sense :smile_cat: 
![screenshot from 2016-03-03 17-10-24](https://cloud.githubusercontent.com/assets/7680662/13493254/04036f08-e163-11e5-8f76-d929dc443b11.png)

Console says:
> Uncaught TypeError: this.$textarea.on(...).on(...).on is not a function

pointing to[ these lines](https://github.com/openSUSE/osem/blob/37697517df1a34a5d62773713307a93a0039d98a/vendor/assets/javascripts/bootstrap-markdown.js#L143-L147).

**Comment by arun1595** [comment]
[https://github.com/toopay/bootstrap-markdown/issues/215](url)

**Comment by rishabhs95** [comment]
this issue has been resolved in the pull request #839 . please review the request.

**Comment by sonalkr132** [comment]
closed by #849
