### ISSUE TITLE
Switch Vagrant base box

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#824]
We are currently using `webhippie/opensuse-13.2` as the base box for our vagrant file. We should switch to one of the *official* [openSUSE boxes](https://atlas.hashicorp.com/opensuse). I guess `opensuse/openSUSE-Tumbleweed-x86_64` is the best choice as we're only using the Vagrant box for development.

**Comment by chocoelho** [comment]
Tumbleweed would be good, but there's no such provider for it. I guess the best we can get right now is Leap.
