### ISSUE TITLE
Authorization of Registration#show

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#828]
As of now authorization of registration is:

``` Ruby
can :show, Registration do |registration|
     registration.new_record?
end
```

While going through show of registration, checking of `new_record?` doesn't seem to be right. I think more appropriate one would be something like:

``` Ruby
can :show, Registration user_id: user.id
```

**Comment by differentreality** [comment]
Please note that this code is happening in https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L49 where there is no user. So the suggested rewriting, cannot happen.
