### ISSUE TITLE
Allow confirmed speakers to register even after registration period is over

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#829]
Taken from [this comment](https://github.com/openSUSE/osem/pull/795#issuecomment-190727264).

> We should probably provision for confirmed speakers to be able to register even after the registration period (they will be there anyway).
> All that might collide with registration_limit, we should address it.
> @differentreality 

We need to be more explicit with authorization of registration, `new` and `create` actions should be allowed if user is confirmed speaker.

**Comment by AEtherC0r3** [comment]
I'm going to work on this.
About the registration_limit, do we want to take into account the speakers of new, unconfirmed and confirmed events in order not to exceed it or just bypass the registration_limit for speakers of confirmed events in case it has been reached or exceeded

**Comment by bear454** [comment]
This creates other problems, when call for papers _precedes_ registration.

How about we allow registration by speakers _anytime after registration starts_ ?

**Comment by namangupta01** [comment]
@bear454 Yes you are right! Confirmed speaker is allowed to register when registration period is set. Done in pr #1629
