### ISSUE TITLE
Document workflow on vagrant

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#830]
Currently [INSTALL.md](https://github.com/openSUSE/osem/blob/master/INSTALL.md) just documents the process of setting up your environment the very first time.
However, our workflow requires that contributors are upto date with master. They would need to migrate database, install gems etc. Unless someone goes and reads `bootstrap.sh` file, doing `vagrant up` may seem like magic to someone not so familiar with vagrant.
It would be best if we document other basic commands as well.

cc: @arun1595

**Comment by hennevogel** [comment]
There is no point in re-documenting standard rails practices...
