### ISSUE TITLE
email is not sent when event is accepted

### ISSUE THREAD

**Issue by davidsf** [openSUSE/osem#835]
I have configured an custom email when the event is accepted.

But when an event is accepted, the email isn't sent.

**Comment by ChrisBr** [comment]
I also have issues when registering to the conference, so there is definitely some problem with the emails ...

**Comment by ChrisBr** [comment]
Two "problems" I found so far:

1) (Obviously) You have to start the delayed job in development:
```rake jobs:work``` 
We need to document it somewhere
2) The ``from`` attribute comes from ``conference.contact.email``, it's possible that this is `nil` and raises an exception. We need to state somewhere that the contact email is mandatory when you want to send email.
