### ISSUE TITLE
Admin Users view datatable not scaling to screen sizes

### ISSUE THREAD

**Issue by rishabhs95** [openSUSE/osem#842]
to reproduce this issue, go to 'admin/users' on small screen sizes,

the datatable shows like this : 
<img width="652" alt="screen shot 2016-03-07 at 11 30 57 am" src="https://cloud.githubusercontent.com/assets/10002834/13561993/36e69528-e459-11e5-8b21-f087dd33639d.png">

**Comment by awasum** [comment]
change the div class containing table in `admin/user/index.html.haml` from `<div class="row"` to `<div class="table-responsive"`

**Comment by awasum** [comment]
https://github.com/awasum/osem
