### ISSUE TITLE
admin tickets view sidebar on small screens

### ISSUE THREAD

**Issue by rishabhs95** [openSUSE/osem#853]
admin's tickets view for conferences on small devices has sidebar uncollapsible
<img width="941" alt="screen shot 2016-03-09 at 10 14 33 pm" src="https://cloud.githubusercontent.com/assets/10002834/13642966/b16d39ea-e644-11e5-94a6-adac39e3093b.png">

**Comment by rishabhs95** [comment]
should i make the sidebar collapsible? because in this type of UI, user may get confused on small screens?

**Comment by rishabhs95** [comment]
please tell if it will be okay to do that, so as to fix that bug

**Comment by Katy310** [comment]
Any guidelines/ pointers for this issue?

**Comment by Ana06** [comment]
@Katy310 As you can see in the screenshot for devices with small screens the sidebar in the admins part of OSEM keeps up in the page while the content (which is the important part) goes down. It would be great if it was collapsible, so it could be hidden. This way the content would be up and it will look much better.
Is that explanation enough? If not please tell me what is exactly what is not clear so I can elaborate. :wink:

**Comment by rishabhs95** [comment]
Yeah @Katy310, you can try some predefined bootstrap properties like `collapsible`, etc. and test it on small screens so that it works well.

You can take a look at properties at https://getbootstrap.com/components/#navbar
