### ISSUE TITLE
Edit and schedule of proposal ends up in unauthorized access

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#859]
Steps to reproduce:
* Submit a proposal to a conference (say: goto)
* Visit the show page of proposal (link: http://localhost:3000/conference/goto/program/proposal/1)
* Click on edit or schedule button on top right.

The page will redirect to home and flash will say: "You are not authorized to access this page."

Link of edit button is `edit_admin_conference_program_event_path` when it should be `edit_conference_program_proposal_path`. Schedule is most likely getting denied access due to incorrect authorization setup.

**Comment by differentreality** [comment]
Good catch!
Look more closely to as why the schedule is not working.
