### ISSUE TITLE
Removing all users from a role removes the role

### ISSUE THREAD

**Issue by nishanthvijayan** [openSUSE/osem#864]
Removing all users  from a role (other that organizer) deletes the corresponding role as well.

**Comment by differentreality** [comment]
Damn you are right, my provision for that must have gotten lost on the way.
This is the regular behaviour of rolify, which however, we clearly do not want. Are you going to work on it @nishanthvijayan ?

**Comment by nishanthvijayan** [comment]
One way to fix this is by invoking [create_roles](https://github.com/openSUSE/osem/blob/master/app/models/conference.rb#L556) of conference from roles#index.
(For this create_roles should be made public)
Also since the deleted role is being recreated its ID will be incremented.This will cause the table to look kinda weird
![ID increment](https://cloud.githubusercontent.com/assets/7537349/13686890/27767972-e73e-11e5-8e74-d0cee6a301fa.png)
Is it necessary to display the ID field here?
Can I go ahead with this solution?
