### ISSUE TITLE
Bring back coverall webhook

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#869]
Did you guys remove it? Is something wrong on coverall side (travis is sending coverage info to coverall)? :frowning: Why is coverall not added as check on PRs anymore? I think it is useful information for knowing if proposed change needs (more) tests.

**Comment by differentreality** [comment]
I see it working now.

**Comment by sonalkr132** [comment]
Can we please turn off coverall comments on PR? It creates lot of noise (with information we can see at bottom of PR anyway). The owner of github repo can do this at url: https://coveralls.io/github/openSUSE/osem

![screenshot from 2016-03-31 12-15-22](https://cloud.githubusercontent.com/assets/7680662/14167742/135bbfe4-f73b-11e5-877b-db333d4a055a.png)

cc: @hennevogel

**Comment by sonalkr132** [comment]
I am talking this:
![screenshot from 2016-03-31 12-26-13](https://cloud.githubusercontent.com/assets/7680662/14167905/fc8c648e-f73b-11e5-9930-c4861daa230a.png)
___
![screenshot from 2016-03-31 12-26-29](https://cloud.githubusercontent.com/assets/7680662/14167906/fc95f9ea-f73b-11e5-8ac1-39c737609da4.png)

**Comment by differentreality** [comment]
It is however a nice indication that newer actions have been taken in this PR / tests have rerun, and % of coverage with any newly added code to the PR.

**Comment by sonalkr132** [comment]
> newer actions have been taken in this PR / tests have rerun

Yeah, thats a nice way to see it. I would still say that I hate coverall comments, also PR submitter is going to comment about the *update* regardless.

> % of coverage with any newly added code to the PR.

That will be there at the bottom with other status even after you have turned off comments.

**Comment by hennevogel** [comment]
Turned it off
