### ISSUE TITLE
ConferenceRegistrationsController#new: authorization when ichain is set and user in not signed in

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#871]
ConferenceRegistrations controller has [following branch](https://github.com/openSUSE/osem/blob/master/app/controllers/conference_registrations_controller.rb#L13-L16) in `new` actions:
```Ruby
if @conference.user_registered?(current_user)
   # do something
elsif CONFIG['authentication']['ichain']['enabled'] && !current_user
  redirect_to root_path, alert: 'You need to sign in or sign up before continuing.'
  return
end
```
elsif covers for case when ichain is enabled and user is not signed in.
However, if you go and look at [ability file](https://github.com/openSUSE/osem/blob/master/app/models/ability.rb#L48):
```Ruby
def not_signed_in
  # code omitted
  unless CONFIG['authentication']['ichain']['enabled']
    # code omitted
    can [:new, :create], Registration do |registration|
       registration.conference.registration_open? && registration.new_record?
    end
  end
end
```
Authorization rules for registration for not_signed_in user is defined in a block which will only when ichain is disabled. **#contradition**
ie: authorization rules are defined for `ichain = false` when in controller we have a branch which will run only when `ichain = true`. Since we have no rule for `ichain = true` branch, it will always end up in denied access.

cc: @hennevogel

**Comment by differentreality** [comment]
Right now authorization via ability.rb is working on events.opensuse.org
I think we should lose the if statement in the controller.

**Comment by hennevogel** [comment]
I don't see a contradiction. We allow Registration without login if ichain is diabled.

The duplicated (slightly different) if-chain is something that can be refactored yes....
