### ISSUE TITLE
incorrect number of tickets shown in admin tickets view

### ISSUE THREAD

**Issue by rishabhs95** [openSUSE/osem#877]
admin tickets view shows incorrect number of tickets purchased by users.

for example, two users buy different number of tickets:
<img width="342" alt="screen shot 2016-03-14 at 6 07 59 pm" src="https://cloud.githubusercontent.com/assets/10002834/13745695/79fabc38-ea15-11e5-93ca-971915a31429.png">
<img width="538" alt="screen shot 2016-03-14 at 6 08 23 pm" src="https://cloud.githubusercontent.com/assets/10002834/13745697/7b0664c4-ea15-11e5-979c-fead4a583863.png">

still admin gets the information that number of tickets sold = 2 (number of users who purchased the tickets)

<img width="881" alt="screen shot 2016-03-14 at 6 07 34 pm" src="https://cloud.githubusercontent.com/assets/10002834/13745700/7cf275f2-ea15-11e5-8b39-acd4c9de75bf.png">

shouldn't it show the total quantity of tickets sold for each ticket?

**Comment by rishabhs95** [comment]
working with this bug

**Comment by rishabhs95** [comment]
@ChrisBr the sold value in admin's ticket view for a conference should show the total number of tickets sold right? 
like in above example, it should've been : 
- 36 for 1$ ticket
- 28 for 10$ ticket
- 33 for 90$ ticket

**Comment by differentreality** [comment]
The table header says **sold**, but the value it shows is `= ticket.buyers.count`
Perhaps we should have column for `Sold` and another column for `Buyers`

**Comment by rishabhs95** [comment]
okay @differentreality ... i will do that  :)

**Comment by hennevogel** [comment]
Who cares how many Buyers there are?

**Comment by rishabhs95** [comment]
i think that the main thing is to display the correct number of total tickets bought... but we may display the number of buyers if it is required.
which would be better?

**Comment by hennevogel** [comment]
You can also display a squirrel eating a nut
 
![tumblr_n6ie66wsvo1rpe379o1_r1_500-1](https://cloud.githubusercontent.com/assets/514785/13846347/ac5a2bea-ec46-11e5-9759-56f1a6d21094.gif)

The question is **why** would you? ;-) This is an APP. Display data that is relevant for the people using it :-) In my opinion this is

Ticket | Price | Sold | Total Amount
------------ | ------------- | ------------- | -------------
Supporter | $15 | 10 | $150

**Comment by rishabhs95** [comment]
that's true @hennevogel... i will display the required info only :+1:
