### ISSUE TITLE
events#index datatable state not persistent

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#881]
You sort the datatable of events by `Type`, then change the `Track` of one of the `Events` with the dropdown. The subsequent reload of `events#index` sorts the table by `id` again.

The datatable should save the state.

**Comment by rishabhs95** [comment]
interested to work with this bug... @hennevogel

**Comment by hennevogel** [comment]
No need to ask. Just go ahead :-)

**Comment by rishabhs95** [comment]
okay :)

**Comment by differentreality** [comment]
Fixed in #882
