### ISSUE TITLE
leaflet: image assets are 404 NOT FOUND

### ISSUE THREAD

**Issue by bear454** [openSUSE/osem#883]
When you add a Lat & Long to a conference's venue, a map is shown (instead of the venue image - that's a different issue) using leaflet.js.

Leaflet expects some images, and I've verified they are present in the 'rails-assets-leaflet' gem.

ex: https://events.opensuse.org/assets/leaflet//marker-icon.png

**Comment by promulo** [comment]
hi @bear454 , I believe this was already fixed, at least I could not reproduce locally:


![image](https://cloud.githubusercontent.com/assets/450960/13956369/c8b8b06c-f048-11e5-9351-7d6457bfd996.png)

**Comment by bear454** [comment]
Okay, maybe it's just a configuration issue on https://events.opensuse.org

**Comment by hennevogel** [comment]
Yeah leaflet has real problems with asset digests...
