### ISSUE TITLE
db:migrate sets auto limit in db/schema.rb

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#902]
After running db:migrate, the db/schema.rb file seems to have set automatically
limit: 4 for integer fields and
limit: 255 for string fields

Relevant issue: 
https://github.com/rails/rails/issues/19001

This seems to have come from me around the time we updated rolify, even though the issue above does not seem to reference anything about rolify at this point.

Shall we investigate further?

**Comment by sonalkr132** [comment]
I think it could be environment specific. If I run: `rake db:drop db:create db:migrate`, it removes all the added limits you mentioned.

**Comment by hennevogel** [comment]
This is environment specific, especially if you run it against mysql...
