### ISSUE TITLE
Issues on hakiri

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#921]
[Cross-Site Scripting Warning](https://hakiri.io/github/openSUSE/osem/master/b367676d32e8e3a07951e4957f220d0699f9365d/warnings?name=Cross-Site+Scripting): Unescaped model attribute rendered inline in app/controllers/admin/commercials_controller.rb
```Ruby
render(text => Commercial.render_from_url(params[:url])[:html], {})
```

People seem to maintain list of `TRUSTED_OEMBED_PROVIDERS`[1][2] and ensure that requested embedded content is coming from trusted source. We can also use the general approach against XSS attacks and filter for script tag. However, do we really need either of those? Our embedded content fetch is only going to work for [providers we have registered](https://github.com/openSUSE/osem/blob/master/app/models/commercial.rb#L35-L42). So, it kinda already ensures that untrusted urls get rejected.

[1]https://github.com/sechat/joindiaspora/blob/62bb7dfab463db140280f9da2f4f330dc387ed06/app/models/o_embed_cache.rb#L36-L38
[2]https://github.com/BrakemanSecurityInc/oss_rails_apps/blob/eb6780ffc062ece9375f86ce2d34d0fc5e3c4ed0/diaspora-0.1.1.0/config/initializers/oembed.rb#L38

___
[Redirect Warning](https://hakiri.io/github/openSUSE/osem/master/b367676d32e8e3a07951e4957f220d0699f9365d/warnings?name=Redirect): Possible unprotected redirect in app/controllers/application_controller.rb
```Ruby
redirect_to(User.ichain_logout_url, ...)
```
Again, it is unlikely that an unintended redirect is possible here. `User.ichain_logout_url` comes from [here](https://github.com/openSUSE/osem/blob/37697517df1a34a5d62773713307a93a0039d98a/config/initializers/devise.rb#L248-L254):
```yml
  # You will always need to set this parameter.
  config.ichain_base_url = "https://events.opensuse.org"

  # Paths (relative to ichain_base_url) used by your proxy
  # config.ichain_login_path = "ICSLogin/"
  # config.ichain_registration_path = "ICSLogin/auth-up/"
  # config.ichain_logout_path = "cmd/ICSLogout/"
```
Only application administrator can set `ichain_logout_url` and there is nothing user related here. Probably, brakeman won't get confused if we used `config` variable instead of class method of user. However, thats not how [devise_ichain_authenticatable setup](https://github.com/openSUSE/devise_ichain_authenticatable/blob/74743478fd20f16e1c9a17bfa8bc4c5174414c39/README.md#installation-and-basic-setup) recommends it.

**Comment by ChrisBr** [comment]
Agreed! However, I also don't like to mark them as false positives ...
Anyway, will do it for now!

**Comment by ChrisBr** [comment]
Seems I don't have permissions to do it, @hennevogel can you mark the reports as false positives?

**Comment by sonalkr132** [comment]
Is using `config` variable directly instead of `User.ichain_logout_url` that bad of an idea? I am pretty sure brakeman is complaining only because it doesn't like class method of **User** . We can get around at least one of them with that.

**Comment by hennevogel** [comment]
Marked as false positive
