### ISSUE TITLE
Test for custom style

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#928]
It would be nice if we can break build for any custom style guide we follow. for ex:
```Ruby
# preffered
redirect_to path
# over
redirect_to(path)
```

I think we can write custom cop for it, however looking for a particular regex (`/redirect_to(/`) in `controller` folder files isn't as bad (or slow) as you might think. Check this: https://github.com/bundler/bundler/blob/master/spec/quality_spec.rb It has test for documentation quality, tab character instead of double space etc.
I would like to know opinion of others cause I would like to work on this.

Relevant confusion: [link](https://github.com/openSUSE/osem/pull/907#issuecomment-203497131).

**Comment by hennevogel** [comment]
This is not custom style. This is ruby style...

**Comment by sonalkr132** [comment]
> Omit parentheses around parameters for methods that are part of an internal DSL

Okay, it is not ruby style but internal DSL. What I proposed was that if we going to follow this (`redirect path` over `redirect(path)`) then we can automate the reviewing part with a simple test, so that we don't have to hassle human (`PR reviewer`) for such mundane review.
