### ISSUE TITLE
Exclude api and serializer from test coverage

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#937]
I think we should exclude files under `api` and `serializers`, we don't really use those and it is most likely that any user of OSEM is not going to need them either. A low test coverage may give wrong impression of our application. It will also help us(mostly me) focus our energy on more important things.
It will be just like a `rubocop_todo`. As of implementation part, we can add filter for file names or use [:nocov:](https://github.com/colszowka/simplecov/blob/master/features/skipping_code_blocks_manually.feature).

**Comment by hennevogel** [comment]
It's part of the app, some people use it for pulling stuff to other pages via javascript...
