### ISSUE TITLE
Adding commercials fails at InvalidAuthenticityToken

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#938]
I guess it has something to do with the loading of the Commercial from the url?

**Comment by sonalkr132** [comment]
Which provider and if possible which url? I was able to add links of youtube, flicker, vimeo and slideshare:
![screenshot from 2016-04-01 20-00-24](https://cloud.githubusercontent.com/assets/7680662/14210006/a63cf094-f844-11e5-8666-fd1973ffb6bc.png)

**Comment by hennevogel** [comment]
Any provider in production...

**Comment by mauromorales** [comment]
I'm getting this issue when trying to add a youtube video

**Comment by differentreality** [comment]
Invalid token issue does not only occur for commercials, but any form really.

**Comment by ChrisBr** [comment]
@hennevogel you fixed this for events.o.o right? Can we close it?
