### ISSUE TITLE
OSEM Logo

### ISSUE THREAD

**Issue by elioqoshi** [openSUSE/osem#948]
OSEM has no logo as of now, am I right? If that's the case, I'd love to work on one :)
I have done dozens of logos for Mozilla and other open source projects in the past, which you can find here:

http://elioqoshi.me/en/mozilla-logos/
https://dribbble.com/elioqoshi

**Comment by ChrisBr** [comment]
That would be awesome! 
@hennevogel we just discussed it last week ...

**Comment by hennevogel** [comment]
@elioqoshi OMG OMG OMG :-) I have a ton of ideas. Can we chat somewhere? :-)

**Comment by elioqoshi** [comment]
I just followed up via email :)
I'm on freenode as elioqoshi and Telegram with the same username. Would love to chat!

**Comment by ChrisBr** [comment]
@elioqoshi you can find us usually in #osem @ freenode!

**Comment by elioqoshi** [comment]
First proposal, what do you think?
![draft1](https://cloud.githubusercontent.com/assets/5436686/14365179/9db8a31a-fd0c-11e5-91d0-10aa44012dc2.jpg)

**Comment by elioqoshi** [comment]
Here a proposal with the full name. I must say branding wise, "OSEM" is not a good choice, so that didn't help much while designing.

![draft2](https://cloud.githubusercontent.com/assets/5436686/14365515/682ad2b6-fd0e-11e5-8671-b4a3b4648aa6.jpg)

**Comment by elioqoshi** [comment]
Getting closer...
![draft3](https://cloud.githubusercontent.com/assets/5436686/14365722/7cabbe16-fd0f-11e5-9cf0-263514ba1f2a.jpg)

**Comment by elioqoshi** [comment]
@hennevogel had a little chat with @ChrisBr , we can chat tomorrow if you like. I'm in the same timezone as you.

**Comment by hennevogel** [comment]
@elioqoshi that would be awesome as your proposals don't really go into the direction I was thinking about ;-)

**Comment by Raphseck** [comment]
@elioqoshi Elio asked for the following sketch of an opposum
![opposum](https://cloud.githubusercontent.com/assets/14264676/14439028/5ee574c4-ffff-11e5-87a7-392865bfbcf9.png)

**Comment by elioqoshi** [comment]
@Raphseck Thanks so much, I love where this is going! I modified your version myself, simplified it a bit, gave it a bit of colour and came up with this. Thoughts @hennevogel ?

![new_artboard 1-02](https://cloud.githubusercontent.com/assets/5436686/14442814/184dc7f4-003c-11e6-9312-ed081882ce4f.jpg)
![Uploading New-01.jpg…]()

**Comment by elioqoshi** [comment]
Modified strokes and further optimized

![new2_artboard 1-02](https://cloud.githubusercontent.com/assets/5436686/14443193/f5f076a0-003d-11e6-88bb-3769cb3beb1e.jpg)
![new2-01](https://cloud.githubusercontent.com/assets/5436686/14443192/f5f06606-003d-11e6-87fd-5f81da790bee.jpg)

**Comment by ChrisBr** [comment]
I love it :heart:

**Comment by elioqoshi** [comment]
Thanks @ChrisBr ! Here is a new version with the opossum's tail lying on the floor instead
![new3_artboard 1-02](https://cloud.githubusercontent.com/assets/5436686/14451412/3d1ce2ea-0087-11e6-81e2-e422bf43ac4a.jpg)
![Uploading New3-01.jpg…]()

**Comment by hennevogel** [comment]
@elioqoshi @Raphseck awesome possum! I'm digging it completely.

**Comment by Raphseck** [comment]
Thanks @ChrisBr ! I'm happy that you liked!
Great job @elioqoshi !!

**Comment by hennevogel** [comment]
So how will we continue? :-)

**Comment by sonalkr132** [comment]
Will we be changing our green theme?
![screenshot from 2016-04-12 17-52-45](https://cloud.githubusercontent.com/assets/7680662/14459820/d93ea12c-00d7-11e6-86b4-eeff0302f172.png)

**Comment by elioqoshi** [comment]
@hennevogel glad you like it!

This is definitely not fitting with the green. It should be some kind of gray.

**Comment by ChrisBr** [comment]
@hennevogel order some stickers and shirts hehe

**Comment by elioqoshi** [comment]
Final update (I hope) with some little fixes and a better tail. I also think this beige background colour works best for our theme

![new4_artboard 1-02](https://cloud.githubusercontent.com/assets/5436686/14488280/aba61764-0167-11e6-8189-3aba6904f399.jpg)
![new4_artboard 1-03](https://cloud.githubusercontent.com/assets/5436686/14488282/abd34cde-0167-11e6-951d-2781d8d78f76.jpg)
![new4-01](https://cloud.githubusercontent.com/assets/5436686/14488281/abd32254-0167-11e6-8eca-68ff3dc13539.jpg)

**Comment by elioqoshi** [comment]
Oh, and the font is of course Open Source too - Museo Slab

**Comment by hennevogel** [comment]
The green is green for no reason, we can change that :-)

@elioqoshi can you attach some open format of your work here (SVG?)

**Comment by elioqoshi** [comment]
Yeah, let me export this all correctly.

Btw, let's open a brandspace on www.brandisty.com for this

**Comment by elioqoshi** [comment]
@hennevogel I need access to Brandisty

**Comment by elioqoshi** [comment]
voila :)
https://brandisty.com/osem

Thanks @Raphseck for the great help!

**Comment by yofiesetiawan** [comment]
cute raphael!

**Comment by Raphseck** [comment]
@yofiesetiawan thanks!  : )

**Comment by Raphseck** [comment]
great work @elioqoshi !!! : )

**Comment by hellcp** [comment]
> voila :)
> https://brandisty.com/osem
> 
> Thanks @Raphseck for the great help!

Since brandisty closed 3ish years ago, do we have SVGs anywhere?

**Comment by elioqoshi** [comment]
> > voila :)
> > https://brandisty.com/osem
> > 
> > Thanks @Raphseck for the great help!
> 
> Since brandisty closed 3ish years ago, do we have SVGs anywhere?

Yep, here:

https://github.com/uracreative/works/tree/main/OSEM

**Comment by hellcp** [comment]
Thanks!
