### ISSUE TITLE
Move registration_limit check to ability file

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#955]
[Source of suggestion](https://github.com/openSUSE/osem/pull/795#discussion_r55738013)

We are checking for registration limit of conference in `new` action of [ConferenceRegistrationsController](https://github.com/openSUSE/osem/blob/master/app%2Fcontrollers%2Fconference_registrations_controller.rb#L26-L29):

```Ruby
def new
  # code ommited
  if @conference.registration_limit_exceeded?
      redirect_to root_path, error: "Sorry, registration limit exceeded for #{@conference.title}"
      return
    end
end
```
We should be handling this with authorization of the `new` action.

**Comment by Ana06** [comment]
I'll do it :wink:

**Comment by Ana06** [comment]
This issue can be closed :cactus:
