### ISSUE TITLE
Registration update by organizers

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#956]
Registration update section in **admin area** has following section:
![screenshot from 2016-04-13 09-00-44](https://cloud.githubusercontent.com/assets/7680662/14482107/b5e0e486-0156-11e6-97f1-9b534a31f649.png)

It breaks any attempt to update the registration with following error message in flash:
> An error prohibited the Registration for : User email can't be blank. User password can't be blank. User username has already been taken. User username can't be blank.

Why do organizers need to update user related info(Name, Nickname and Affiliation) anyway?

**Comment by differentreality** [comment]
I think having the option to change some basic user information should be given to people than cannot otherwise access user information (eg. Info Desk volunteers). Name and affiliation might be important to be fixed in case of typo or something for attendees like sponsors, keynote speakers.
