### ISSUE TITLE
Testing for_ichain_username of User model

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#961]
I am stuck over [this](https://github.com/openSUSE/osem/blob/master/app/models/user.rb#L85-L89) for quite a while:
```Ruby
def self.for_ichain_username(username, attributes)
  # something something code
  else
    begin
      user = create!(username: username, email: attributes[:email]) # <- line of interest
    rescue ActiveRecord::RecordNotUnique
      raise IChainRecordNotFound
    end
  end
end
```

How is `create!` working? events.o.o must be executing this line to sign in with ichain. However, If I write following test:
```Ruby
describe '.for_ichain_username' do
  context 'user is not found' do
    it 'creates user' do
      expect{User.for_ichain_username('johndoe', email: 'john@doe.com')}.to change { User.count }.by 1
    end
  end
end
```
It failes with:
> ActiveRecord::RecordInvalid:
       Validation failed: Password can't be blank

**Comment by hennevogel** [comment]
This is used inside the [devise_ichain_authenticatable](https://github.com/openSUSE/devise_ichain_authenticatable) plugin. I doubt it makes sense to test this outside of it...
