### ISSUE TITLE
Word limit on user biography

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#965]
User can update there biography with word count exceeding the limit cause we don't have relevant validation in place:
![screenshot from 2016-04-18 11-22-16](https://cloud.githubusercontent.com/assets/7680662/14594928/a3dd6416-0558-11e6-8858-523261a8457b.png)

![screenshot from 2016-04-18 11-29-05](https://cloud.githubusercontent.com/assets/7680662/14594965/f96d652a-0558-11e6-9eb1-dc206fdc5090.png)

**Comment by Ana06** [comment]
I'll do it! :smile:

**Comment by differentreality** [comment]
Upon visiting edit_user_path, before typing anything in the bio box, it says you have used 0 words (even if there is text as biography).

**Comment by Ana06** [comment]
This issue can be closed :wink:

**Comment by hennevogel** [comment]
Yes boss :-)
