### ISSUE TITLE
Custom Error Pages

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#972]
We are currently using the standard error pages. They don't really help the users to solve or report the problem. We should have some custom error pages at least for 
- [ ] 403 Forbidden
- [ ] 404 Not Found
- [ ] 500 Internal Server Error

These pages should explain what has gone wrong and how to mitigate this problem.

**Comment by coderhs** [comment]
Is there a draft of the issues one need to add to this page? @hennevogel I am interested to work on this.

**Comment by hennevogel** [comment]
@coderhs I don't understand your question. What exactly are you looking for? :-)

**Comment by FleetAdmiral** [comment]
Hey i'd like to take this up myself! Being a newbie it'd be great if i could get some assistance too! :D

**Comment by ChrisBr** [comment]
@FleetAdmiral sure! Just join #osem on freenode or answer in this PR if you need help!

**Comment by FleetAdmiral** [comment]
@ChrisBr Could you possible exemplify upon what i'm expected to do? Would a generic 404/403/500 error page for anyone who gets them be enough? Or do they need to be dynamically changed based on the page the user has arrived over there from?

**Comment by ChrisBr** [comment]
@FleetAdmiral no I think a generic page for each of them is enough!

Maybe you can bring our OSEM logo somehow into the pages:
https://camo.githubusercontent.com/a58785e43799dfbdb63f58fbda4336060eb98088/68747470733a2f2f63646e2e6272616e64697374792e636f6d2f696d673f69643d35373066366463333963393932623662363730303030306126666f726d61743d706e6726773d33303026683d3839

And e.g. link to the github repository / issues.

For reference, look what we do in the build service:
https://github.com/openSUSE/open-build-service/tree/master/src/api/public

**Comment by FleetAdmiral** [comment]
@ChrisBr Alright then , i'll start working on this today.

**Comment by FleetAdmiral** [comment]
@ChrisBr Btw , am i required to keep the  color scheme(green) the same , or am i allowed to make the color more , say , suited to an error , like red?

**Comment by mwgalloway** [comment]
@FleetAdmiral Are you still working on this? If not I would be happy to take this on.

**Comment by differentreality** [comment]
@mwgalloway the previous comment is very old, since the issue is not closed/solved, feel free to work on it!

**Comment by FleetAdmiral** [comment]
@mwgalloway Yea i've been caught up on something else, you can go ahead!

**Comment by mwgalloway** [comment]
I added a PR with the three requested error pages. I did not change how the app handles errors in any one.

**Comment by mwgalloway** [comment]
@hennevogel @differentreality I added a PR with the three requested error pages. I did not change how the app handles errors in any one.
