### ISSUE TITLE
Statistics on top of Events#index & Registrations#index

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#973]
In the admin interface both are basically 2 huge lists containing all submitted events and all registered people. We should show some statistics on top like:

![dashboard](https://cloud.githubusercontent.com/assets/514785/14912456/b973d790-0dfc-11e6-919b-baf99fae31f1.png)

For Events it could also include this (from the general dashboard)

![screenshot from 2016-04-29 11-23-47](https://cloud.githubusercontent.com/assets/514785/14912489/e8e32b48-0dfc-11e6-8254-8ab7a4e8a0e5.png)

**Comment by Ana06** [comment]
I'll do it. 
The statistic on the top are the same as the ones in the dashboard, aren't they?
The event types, difficulty levels and tracks should be also at the top?

**Comment by hennevogel** [comment]
For Registrations I would say those 3 are important:

* Number of overall registrations
* Registration attended vs. Registration not attended
* Distribution of affiliation (if that is possible)

For Events I would say those 3 are important:

* Confirmed vs. Unconfirmed Events
* Scheduled (start_time set) vs. Unscheduled events
* Track Distribution

**Comment by Ana06** [comment]
This issue can be closed :smile:
