### ISSUE TITLE
Venue Commercial->Picture->Icon degradation

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#974]
On the splash page the Venue should display an Commercial or Picture or Icon. Depending on what is there. Currently it shows a Commercial or nothing.

**Comment by hennevogel** [comment]
@Shriyanshagro can you look into this?

**Comment by Shriyanshagro** [comment]
Ok, I can solve this issue. But if commercial is not there, then which picture or icon should it display??
There must be an icon or picture available for the same.

**Comment by ChrisBr** [comment]
@Shriyanshagro what about 
http://fortawesome.github.io/Font-Awesome/icon/building-o/ or http://fortawesome.github.io/Font-Awesome/icon/university/ ?

**Comment by Shriyanshagro** [comment]
@ChrisBr,  that's actually very good idea,  
if we could somehow figure out the type of venue,like either it's a commercial building or any institute, then we can set a profile icon too..
What do you say @hennevogel ??

**Comment by differentreality** [comment]
Before we implemented commercial for venue we had a venue photo, the photo is still available, but we never show it.
So if there is a commercial, we show the commercial, if not we show the venue picture. If there is no commercial, and no picture, we just show a building image like suggested.

**Comment by hennevogel** [comment]
I've meant exactly what @differentreality said :-)

**Comment by arun1595** [comment]
@hennevogel I would like to work on this issue.

**Comment by arun1595** [comment]
I have added code to fallback to venue picture in case of the absence of commercial.
This is how the splach page looks when there's a venue commercial.

![conf-commercial](https://cloud.githubusercontent.com/assets/7039523/16204017/93a49d80-373a-11e6-8cdb-98c6d25c816d.png)

Case when there's not venue commercial, but a venue picture

![venue-picture](https://cloud.githubusercontent.com/assets/7039523/16204032/a0fe7fb4-373a-11e6-8856-840ee4477aa0.png)

When both commercial and picture are absent

![icon](https://cloud.githubusercontent.com/assets/7039523/16204026/9b751e7c-373a-11e6-8901-e49a5499f9e3.png)

**Comment by differentreality** [comment]
You should add those photos in your PR

**Comment by differentreality** [comment]
Would be nice to implement the code for venue#show in the admin panel

**Comment by arun1595** [comment]
Sure. I can try that. But I think a separate PR would be appropriate. What do you think?

**Comment by differentreality** [comment]
As you wish.
