### ISSUE TITLE
Blindvoting

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/osem#981]
We should introduce blind voting:

- You shouldn't be able to see the votes of the others
- You shouldn't be able to see the current mean
(- You shouldn't be able to see the author)

Otherwise your vote will be biased ...

**Comment by differentreality** [comment]
Duplicate of #702 
And I would personally like to see this. I hope I will eventually find time to implement it.

**Comment by hennevogel** [comment]
If it's a duplicate, close it :-)
