### ISSUE TITLE
Cannot confirm proposal

### ISSUE THREAD

**Issue by mauromorales** [openSUSE/osem#988]
Tried to confirm proposal 926 and got an error page.

**Comment by hennevogel** [comment]
After adding the youtube video?

**Comment by ChrisBr** [comment]
I'll have a look into it!

**Comment by mauromorales** [comment]
@hennevogel Nope without adding the video. This was at the page where the proposals are listed and there is a green confirm button. I clicked on this and got the error

**Comment by hennevogel** [comment]
This request (on `2016-05-04 20:58:47`) ran into Cross-Site Request Forgery protection because there was a CSRF problem with the commercial before. This is fixed now. @mauromorales you should be able to add commercials and confirm your event now.

**Comment by mauromorales** [comment]
@hennevogel yup working fine, thanks guys!
