### ISSUE TITLE
[production][conference_registrations#new] NoMethodError: undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/osem#991]
conference_registrations#new threw this 1 times
<pre>
NoMethodError: undefined method `&gt;&#39; for nil:NilClass
</pre>
[https://events.opensuse.org/conference/oSC16/register/new](https://events.opensuse.org/conference/oSC16/register/new)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/57308ae9f12576000c000003)

**Comment by hennevogel** [comment]
This happens because e.max_attendees is nil by default. hotfixed in production by removing this condition.

**Comment by differentreality** [comment]
It is cause because events already had require_registration set, before we introduced max_attendees. Now a user cannot set require_registration attribute without putting a value for max_attendees too.

I will send a task to fix this for the existing events with require_registration.

**Comment by hennevogel** [comment]
But whats wrong with an Event that requires registration but does not have a max_attendees limit set?

**Comment by differentreality** [comment]
Since we dropped 0 value for max_attendees, I haven't provisioned for this scenario, where registrations are limitless. 
Usually registration is required because there is a limit to the amount of people that can be accommodated.

**Comment by ChrisBr** [comment]
@differentreality is this still valid with #994 merged?

**Comment by differentreality** [comment]
@ChrisBr should be closed via #994
