### ISSUE TITLE
[production][users#edit] NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by differentreality** [openSUSE/osem#995]
users#edit threw this 0 times
<pre>
NoMethodError: undefined method `split&#39; for nil:NilClass
</pre>
[https://events.opensuse.org/users/11314/edit](https://events.opensuse.org/users/11314/edit)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620ca99dc71fa00b1000002/problems/5731add4806a92000c000000)

**Comment by hennevogel** [comment]
Meanwhile this is the most prominent exception...
